### ISSUE TITLE
All downloads get stuck on "preparing to download".

### ISSUE THREAD

**Issue by mindaboveall** [rogerfar/rdt-client#1]
They're added fine and I can see the updates as they're downloaded on Real-Debrids end, but they are never downloaded to my local machine and just stay on "preparing to download".

Let me know what troubleshooting information you need, if interested.

Thanks!

On a side note: startup.bat is missing from 1.1.

**Comment by rogerfar** [comment]
I have pushed 1.2 with some small bug fixes and the Startup.bat included.

When it's stuck on "preparing to download", what does the app.log file show, that file is in the installation directory? And the download folder in the settings dialog, are you sure you have access to write to that path?

**Comment by mindaboveall** [comment]
@rogerfar I think it may have been some sort of permissions issue. Updated to 1.2 and everything is working great, thank you!
