### ISSUE TITLE
Fail: Hoster Unavailable

### ISSUE THREAD

**Issue by handshake87** [rogerfar/rdt-client#10]
Everything was running fine then I get the following error in console. I have confirmed that API key matches

```
RdtClient.Service.Services.TaskRunner.DoWork() in C:\Projects\rdt-client\server\RdtClient.Service\Services\TaskRunner.cs:line 61
fail: RdtClient.Service.Services.TaskRunner[0]
      {
        "error": "hoster_unavailable",
        "error_code": 19
}
System.Exception: {
        "error": "hoster_unavailable",
        "error_code": 19
```

**Comment by rogerfar** [comment]
Does this happen all the time?

This error is normal, it's just RealDebrids poor API's that timeout or throw errors for no reason once in a while.

**Comment by handshake87** [comment]
I have about 88 files pending download now and it will not continue forward. New episodes are added and downloaded but it never takes the next step and download locally.

**Comment by handshake87** [comment]
I also have all my downloads just sitting at "Pending download" and never continues. If I press the red arrow on the others that say "Ready to download, press the download icon to start" It just switches to Pending download and never continues.

**Comment by rogerfar** [comment]
Can you try the new docker image or new version? This should have fixed some of those issues.
