### ISSUE TITLE
Feature Request: Delete torrent automatically after download

### ISSUE THREAD

**Issue by elmerohueso** [rogerfar/rdt-client#101]
To keep the UI clean, can you add an option to automatically delete torrents from the Client and Provider after a successful download?

**Comment by bastardsandcheats** [comment]
If you're using sonarr/radarr, they control rdt client and can be set to delete after download. 
If you're using something else, you can probably set that up to do the same using the API
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#delete-torrents

**Comment by rogerfar** [comment]
Both of these options already exist in RDT:
![image](https://user-images.githubusercontent.com/1142915/149352994-74499ab2-6d33-4670-878c-7cab3d9fccf0.png)
and:

https://github.com/rogerfar/rdt-client/blob/8d036847f3e9aa963dd9e680854835be7e964f8f/server/RdtClient.Web/Controllers/QBittorrentController.cs#L248

**Comment by elmerohueso** [comment]
Yes, they exist when manually adding a torrent, but I don't see them on the
Download Client page for torrents added automatically.
[image: image.png]

**Comment by rogerfar** [comment]
That's because the other side should take care of that. Both Sonarr and Radarr have the ability to delete torrents when completed.

**Comment by elmerohueso** [comment]
Since RDT presents as a qBitTorrent client, making it possible to use with
other download clients other than Radarr and Sonarr, would it be possible
to add that feature, though?

**Comment by screamjojo** [comment]
> 

I'm also very interested, or do you have a solution with a batch command ?
Thanks in advance
