### ISSUE TITLE
Can't access WebUI.

### ISSUE THREAD

**Issue by madieboyd** [rogerfar/rdt-client#103]
**What version are you using?**
2.0.5
**Wat OS are you running?**
Win10
**Are you using Docker or as a service?**
service
**Please attach a log file here with the log setting set to debug**
no log file

I downloaded the new version and changed the appsettings.json file and started the program with RdtClient.web.exe and I cannot access the webui. The docker container I was using would let me access the webui but would give a 'bad token' error when I would try to download something from sonarr or radarr.

**Comment by rogerfar** [comment]
That's not a lot of information. What does the console say when you start the app, or the event manager?

**Comment by madieboyd** [comment]
console doesn't say anything when i run it from cmd. The docker container just started working out of nowhere though and I haven't changed anything. Ill just stick to the docker container for now.
