### ISSUE TITLE
[low priority] webinterface login - iOS autofilled passwords don't work without user intervention

### ISSUE THREAD

**Issue by janitory** [rogerfar/rdt-client#104]
Low priority issue regarding the webinterface. This issue doesn't seem to be device-specific.

When accessing the web interface through iOS, Apple's autofill does fill the username and password fields, however the password does not get treated as a correct entry, even though the length of the hidden characters matches the vault's entry. If I copy the password from my vault and paste it manually, it however works. The username field doesn't cause that issue.

It seems like Apple's autofill service causes a conflict with fields that have bound values continuously updating:
https://developer.apple.com/forums/thread/659105

I noticed that adding and then removing a character to the password field after the autofill filled the password causes the string value to update and thus the AuthController will recognize the password.

**Comment by rogerfar** [comment]
This is fixed in .16 now.
