### ISSUE TITLE
Run external program on torrent completion

### ISSUE THREAD

**Issue by vegedb** [rogerfar/rdt-client#106]
Since this is emulating qbittorent, any chance this feature could be added? Or any workaround?

Example use case: 

1. download files to RAMdisk
2. use script/bat to **move** from RAMdisk > HDD/SSD after completion

![image](https://user-images.githubusercontent.com/72070424/150692064-36767104-f83b-4939-8f5b-1fd164a5ab10.png)

**Comment by rogerfar** [comment]
Duplicate of #95 , but this has now been added with (almost) the same parameters.
