### ISSUE TITLE
Sequential Downloading with RD

### ISSUE THREAD

**Issue by HashaRock** [rogerfar/rdt-client#111]
I have been trying to set up an automated system with RD for content requests with Overseer. However, when a movie is downloading I do not think it is sequential because it does not load into Plex mid-download. Is there a specific downloader to use or does RD's API not support it?

**Comment by rogerfar** [comment]
It would work if RealDebrid gives you an actual video file, sometimes they are rarred, then it wouldn't work.

The simple downloader downloads sequentially, so if that should theoretically work.

**Comment by HashaRock** [comment]
Understandable, it is just the movie file but I will use the simple downloader and see if it works! Thanks for the quick response!
