### ISSUE TITLE
Change password after initial setup

### ISSUE THREAD

**Issue by popophobia** [rogerfar/rdt-client#112]
Is there a way to change the password after the initial setup? When I click Account > Profile, nothing happens.

**What version are you using?**
2.0.5

**Wat OS are you running?**
Docker - Synology

**Are you using Docker or as a service?**
Docker

**Please attach a log file here with the log setting set to debug**
Nil

**Comment by rogerfar** [comment]
I added a profile page in 2.0.6 where you can change your username and/or password.
