### ISSUE TITLE
Add Readarr as download option

### ISSUE THREAD

**Issue by Stephan296** [rogerfar/rdt-client#117]
Add Readarr as option like radarr and sonarr

**Comment by rogerfar** [comment]
What issues are you running in right now that it doesn't work?

**Comment by Stephan296** [comment]
Because i see also the downloads from Radarr in my Readarr

**Comment by rogerfar** [comment]
Then you probably need to configure Readarr in a way to not do that. I'm not sure what RDT changes should be made to prevent that. Probably just use different categories for each system. These is no explicit Radarr or Sonarr support, there is just qBittorrent API's.

**Comment by Stephan296** [comment]
ok thx for your reaction!
