### ISSUE TITLE
Add API to monitor downloads

### ISSUE THREAD

**Issue by Stephan296** [rogerfar/rdt-client#118]
Could you make an API to monitor the download like in Homeassistant or something? I tried Qbittorrent component in Home assistant but it cant make connection.

**Comment by rogerfar** [comment]
It looks like the /api/v2/sync/maindata API endpoint will need to be implemented.

I'm open for PR's.

**Comment by rogerfar** [comment]
This endpoint was added in 2.0.11, I have tested it with my home assistant and it seem to work.
