### ISSUE TITLE
Docker: Persistent config storage, custom user:group for container and sonarr/radarr import deleting top level downloads folder?

### ISSUE THREAD

**Issue by timcoop3r** [rogerfar/rdt-client#12]
Thanks for creating this handy docker image. On the face of it is going to be really useful, however I have been setting it up today and have the following questions that if answered should get things working pretty well for me:

When using the docker image, which path inside the container needs to be pushed to a volume created for persistent storage of configuration? Currently without this specified the configuration does not persist beyond a recreation of the container?

The docker images I use for Sonarr/Radarr run under their own user/group. What is the recommended way to get this container to run as a custom user in the same way? I am no docker expert and have tried a few things but had permissions errors inside the container when trying to force it to run as another user? Without this Sonarr/Radarr are unable to import the downloaded files and end up in an infinite import loop as they don't have permissions to remove the download files after import.

Many Thanks

**Comment by rogerfar** [comment]
The docker path should be the path that you use in your docker file. So if you run with `-v /your/storage/path/:/data/downloads` then use `/data/downloads` as the path in RDT-Client. It will then download files to `/your/storage/path`. In windows that could be `D:/Downloads` for example.

For the permissions, I am not sure either. In the end this will be a user that will need to be able to read and write files in your download directory. You could create a separate user or group that has the correct permission to your download folder. This does mean that Sonarr and Radarr will need permissions to those files too.

**Comment by timcoop3r** [comment]
The download path is working. I was more referring to the config file that stores the API key. Either pushing this into a persistent docker volume or onto the file system of the host like the downloads?

Regards permissions, when I tried to set the user: UID:GID in docker-compose the services inside the container itself wouldn’t start due to permissions issues so presumably there is correlation between permissions inside and outside the two in some way?
Not sure if it’s related but even running everything as route radarr can’t finish an import. It now copies the files around correctly, deletes the original from the download location, but doesn’t complete the import from the queue and remove the file from the client? This could maybe be a radarr config issue though rather than permissions?

**Comment by rogerfar** [comment]
I see what you mean about the data path yeah, I should add that otherwise it will reset your database on each upgrade.

Can you set Radarr to debug logging and see what that says? If it deletes the file correctly it should have the right permissions. I do find that Radarr has more issues than Sonarr though.

**Comment by timcoop3r** [comment]
well, for now I have run everything as root as a workaround/test and that seems to have changed the problem. The import completes, but during the process both Radarr or Sonarr remove the root downloads folder completely? (which is its own kind of problem so feels like its off-topic for this one a bit now).

With the Sonarr logs on Debug, it looks like it thinks the download folder for an episode itself _is_ '/data/downloads' which would explain why its doing that. Looking at the API response for the downloads in the client at ip:6500/api/v2/torrents/info the save_path for all downloads are all "save_path":"/data/downloads/", is that expected?

I'm not really sure why else Sonarr/Radarr would think they need to remove the directory after the import? Either I have something set wrong, or Sonarr/Radarr are picking up something wrong somewhere? This may explain why the import didn't work with the wonky permissions if it was trying to delete this folder as well before? If I can fix this I can go back to trying to test as a non-root user.

**Comment by timcoop3r** [comment]
Further to this delete of root downloads folder issue, I think it may be related to relatively new versions of radarr/sonarr expecting 'content_path' returned in the qtorrent API response? (Found reference here https://github.com/qbittorrent/qBittorrent/issues/13389 to improvements made for QBT support)

Perhaps Radarr/Sonarr are making incorrect assumptions based on 'save_path'?

**Comment by rogerfar** [comment]
I have added the `content_path` on the torrent output, let's see if that fixes the issue!

**Comment by timcoop3r** [comment]
> I have added the `content_path` on the torrent output, let's see if that fixes the issue!

iirc the emulated QBT api version endpoint also needs to return >= 2.6.1 for Sonarr/Radarr to look for the content_path so this will need to be updated as well to try this out. Then I am happy to get testing! :)

**Comment by timcoop3r** [comment]
Further to this, the latest docker image now prevents imports into Radarr (not tested Sonarr yet). Import returns the following error and does not import:
_'No files found are eligible for import in <rdt-client Mapped path>'_ (where <rdt-client Mapped path> is the path configured in rdt-client)

I'm not sure content path is returning the right path being just the mapped root download location? From the QBT API docs:
_'content_path | string | Absolute path of torrent content (root path for multifile torrents, absolute file path for singlefile torrents)'_

Seems like this should return the specific directory thats created for the file download itself?

**Comment by timcoop3r** [comment]
Same issue when testing with Sonarr

**Comment by rogerfar** [comment]
Ah I see, I didn't read that right.

I changed it in a new docker release now. 

Are you using Sonarr 3 beta? I'm still on 2 probably that's why I'm not seeing those errors. I am on Radarr 3 though.

**Comment by timcoop3r** [comment]
yeah this is with Sonarr 'preview' 3.0.4.1060.

Will pull the new image and give it another go.

**Comment by timcoop3r** [comment]
I'm an idiot, I was using the native file path as the mapped path, and not the the docker volume path that radarr/sonarr actually see. I _think_ importing is working without removing the folder now but will double check :)

**Comment by rogerfar** [comment]
There is still something up with the paths. It looks like Radarr isn't setting the category when adding a torrent, so it doesn't create a subfolder. Which is odd, because Radarr forces you to have a category on your torrent client. I have to look into that a bit more. I compared the outputs from qBittorrent and RDTClient and they seem to be matching.

**Comment by timcoop3r** [comment]
Just done some more testing and Radarr is importing again, but back to nuking the root download folder. Would you mind bumping the string returned by the webapiVersion endpoint to 2.6.1, I'm not convinced that the content_path is used unless Sonarr/Radarr expect it to be there by checking the API version returned?

**Comment by rogerfar** [comment]
I updated the versions to the latest qBittorrent versions to see if that works.

What I noticed though is that the `torrents/categories` endpoint in a real qBittorrent doesn't specify the `savePath`, it's just empty. So I emptied that out, I think Radarr was tripping over that too.

Also, for some reason they have removed the ability to set a label when adding a torrent from Radarr, so unfortunately the splitting of downloads between different folders won't work anymore.

**Comment by timcoop3r** [comment]
That seems to have done the trick! Imports from sonarr/radaar seem to be working and root folder not getting removed.

**Comment by rogerfar** [comment]
I have found why it didn't set the category correctly on adding a torrent from Radarr too now, so that's fixed too.

**Comment by timcoop3r** [comment]
Just spotted the persistent storage, thanks for that one as well!

**Comment by rogerfar** [comment]
Sounds good, I'm going to close this issue to prevent it bleeding into other issues :) Thanks for helping test!
