### ISSUE TITLE
When uploading, even if the selected files are all videos, they will still be compressed into a compressed package. On real debrid, I get the download link of each video.

### ISSUE THREAD

**Issue by shanyan-wcx** [rogerfar/rdt-client#120]
**What version are you using?**
2.0.7
**Wat OS are you running?**
synology
**Are you using Docker or as a service?**
docker
**Please attach a log file here with the log setting set to debug**

**Comment by rogerfar** [comment]
I'm not sure what you mean exactly. This is how real-debrid works, when you select the files, after they are done there is a chance they will be added together in 1 zip package. This doesn't always happen and I'm not sure what the condition is when this occurs in real-debrid.

You could ask them, but I doubt you get a useful answer.
