### ISSUE TITLE
VPN 

### ISSUE THREAD

**Issue by f3rr311** [rogerfar/rdt-client#122]
Good Morning 

I am using this and I have to say its amazing but ran into an issue where I think my ISP is blocking real-debrid, I dont know if you can add openvpn service to this in any way or any other basic VPN. but it could help with some of these issue as others are reporting getting blocked.

**Comment by rogerfar** [comment]
What kind of errors are you getting? Is it contact the real-debrid API's or it failing with downloading?

Adding a VPN by default in the product isn't easy or a bit outside the scope, you could create a docker image that contains a VPN, there are a few examples that do that like:
https://github.com/haugene/docker-transmission-openvpn

**Comment by f3rr311** [comment]
failing on all downloads I also can not see real debrid without a VPN,
switched to alldebrid for now

Traceroute never reaches real either, just times out.

**Comment by rogerfar** [comment]
Interesting, what country/ISP if I may ask? It's possible that routing to RealDebrid is broken, their infrastructure isn't the greatest.

**Comment by f3rr311** [comment]
US and Spectrum

**Comment by rogerfar** [comment]
I'm going to close this issue as it's outside the scope of this project to add a VPN. If anyone ever wants to make a PR to the product or docker container that supports it, please 👍🏻
