### ISSUE TITLE
Access to the path '/Users/XXXXXXXX/Downloads/test.txt' is denied on MacOS

### ISSUE THREAD

**Issue by vivek2731** [rogerfar/rdt-client#128]
Files from real-debrid are downloading (=I know this because I lose storage space when I download). However, I can't find them. When I try to run the test for download permissions, I get the above error.

**Comment by vivek2731** [comment]
It looks like they're downloading to the /data/downloads folder of the Docker volume but NOT to my host's/local downloads folder on Mac. 

Why is this?

**Comment by rogerfar** [comment]
Please read the docker setup instructions and get familiar with how Docker handles volume mapping.

**Comment by vivek2731** [comment]
Not really sure where to go from that though

**Comment by rogerfar** [comment]
https://github.com/rogerfar/rdt-client/blob/master/README-DOCKER.md

**Comment by vivek2731** [comment]
I even have the mapped path on RDT-Client set to my local Downloads folder on Mac, but it's simply not mapping. I even gave Docker full Disk Access permissions on my Mac, but it's not really doing anything.
