### ISSUE TITLE
Readarr support

### ISSUE THREAD

**Issue by Gaisberg** [rogerfar/rdt-client#129]
Readarr categorizing not supported, could it be implemented?

**Comment by rogerfar** [comment]
What errors are you getting? Please follow the template when posting an issue.

**Comment by Gaisberg** [comment]
No errors, the only thing missing is readarr category is not being set to torrent resulting in it being showed on all *arr apps.

**Comment by rogerfar** [comment]
I would still need to see logs from RDT and readerr to see why it fails.

**Comment by rogerfar** [comment]
This should be fine now with a bug fix in the qBittorrent interface.
