### ISSUE TITLE
Docker: Downloads don't restart/resume after connectivity loss

### ISSUE THREAD

**Issue by timcoop3r** [rogerfar/rdt-client#13]
Don't want to dilute the existing thread I have (which already probably has too many issues in a single post) so opening a new one for this. Hopefully thats the best way to track separate topics/discussions.

I'm using the docker image with connectivity through another container running a VPN client. When the VPN drops and restarts, which is more likely than with native connectivity, and this happens during a download, the download stalls and does not restart or resume. Manual intervention is required to restart the rdt-client container to restart the download.

**Comment by rogerfar** [comment]
I added a simple retry mechanism which will restart the complete download if it fails, for 1 hour.

So if you get disconnected you need to re-connect within an hour so the download restarts itself.

**Comment by timcoop3r** [comment]
Not sure if it is related to this change, but with the latest docker build rdt-client is incorrectly reporting downloads as queued when they are actually actively downloading to the host. This is with max downloads set to 2, rather than the default of 10. I haven't tried with the default setting. to see if the behaviour is the same.

**Comment by timcoop3r** [comment]
Further on this one, I am not sure the unpacking status is correct either, and is reporting incorrectly to sonarr/raddar somehow? Initially it seems like Sonarr/Radarr might be on occasion starting to import before the unpack is complete? This returns an import error in Sonarr/Radaar, however the hardlinking carries on in some way as the unpack process takes place and you see the file slowly growing in size _inside_ the relevant series/movie path (but it has been 'removed' from the download path). 
If left alone the complete file does fully appear in the movie/series path but not in an imported state. Once the full file is present it can be imported manually and removed from the active downloads.

**Comment by rogerfar** [comment]
I double checked this and it looks to be good. It only sends the "pausedUP" state when the whole torrent is completed.

Does this happen on a manual import or automatic?

**Comment by timcoop3r** [comment]
This is all happening on automatic import. What seems to happen pretty consistently if there is more than one torrent added to rdt-client is that the downloading to host status is 'queued for download' when actually the file is being downloaded to the host. This status then eventually immediately transitions to unpacked (my file system is not fast enough for the unpack to happen that quickly :) ). I'm not yet sure if the unpack is mis-reported as complete, and this is actually happening when the unpack starts, or if the status doesn't change until is totally completed. (I'll run some more tests).

This failed import itself seems to be more intermittent, I've only seen it twice so far in all the testing. I need to try and catch this when the import is actually being attempted to understand if the file was actually still being unpacked or not, but currently I am making that assumption due to what I see on the file system and process usage.
It appears that the unpacking is in progress when the hardlink is attempted and that the unpack process can continue because of the way the hard-linking works on the filesystem the 'destination' on the file system file being unpacked to is now represented only as the media storage location due to the hardlink (as the download location pointer on the filesystem has been removed by the failed import).
While this 'phantom unpack' takes place I see significant CPU time on the 'dotnet' process as I would expect while the unpack is still happening, even though the GUI reports it complete.

**Comment by timcoop3r** [comment]
No, you can ignore most of the above, it's not actually the unpacking I don't think, as I am seeing weird issues with single file downloads.

Radarr example:
- rdt-client downloads 'file.mk4' to the file system whilst status is 'queued for download'.
- When the download completes the rdt-client status changes to 'Files Unpacked'
- At the same time the fully downloaded file on the filesystem resets to 0 size, and starts growing again. (this looks like its re-downloading based on the speed)
- Radarr sees 'file.mkv' and tries to import it and fails, but the hardlink is created.
- File continues to download to the filesystem but the path is reflected in the media storage location due to the hardlink.

**Comment by rogerfar** [comment]
Yeah there is definitly something up, the GUI doesn't show download progress, but radarr does, but I did see it pop and re-start the download, I will have to have a look at that asap.

**Comment by rogerfar** [comment]
I pushed a new image with fixes that won't keep downloading the same file over and over.

But I'm not 100% sure if the content_path / save_path thing is just right yet. It seems like that Radarr is trying to find files in `path/torrentname.mkv` instead of `path/torrentname/torrentname.mkv`, but I have to look into it a bit more.

**Comment by timcoop3r** [comment]
> I pushed a new image with fixes that won't keep downloading the same file over and over.
> 
> But I'm not 100% sure if the content_path / save_path thing is just right yet. It seems like that Radarr is trying to find files in `path/torrentname.mkv` instead of `path/torrentname/torrentname.mkv`, but I have to look into it a bit more.

Initial test can confirm no repeat downloads for the updated docker image. 

Regards content_path, checking trace level logging in my Radarr instance it is looking in the correct place and imports correctly?

Example log lines like:
`2021-1-15 09:57:02.3|Debug|DownloadedMovieImportService|Processing path: /data/downloads/radarr/torrentname`

and 

`2021-1-15 09:57:02.3|Debug|VideoFileInfoReader|Getting media info from /data/downloads/radarr/torrentname/torrentname.mkv`

**Comment by rogerfar** [comment]
Ok, maybe my testing wasn't painting a real picture. Sonarr and Radarr seem to work fine for me.

**Comment by timcoop3r** [comment]
Think this is still an issue restarting downloads. Connectivity dropped download overnight and the queue stalled. This is with the simple downloaded and 1 download stream. May not be a problem worth investigating if the aria2c downloader is still a likely future change, but seemed worth mentioning none the less.
