### ISSUE TITLE
Constant calls to real Debrid API causing block

### ISSUE THREAD

**Issue by m-ayub** [rogerfar/rdt-client#133]
**What version are you using?** 2.0.12

**Wat OS are you running?** Synology NAS

**Are you using Docker or as a service?** Docker

**Please attach a log file here with the log setting set to debug**

Has something changed in the latest version? I am seeing lots of calls to api.real-debrid.com every 10 seconds or so. Not sure if this used to happen previously but I think it's causing RD to ban my IP. 

I updated the client in the past week and I started getting blocked a couple of days later. 

When I turn off the RDTClient I can see the dns lookups to api.real-debrid.com stop.

**Comment by m-ayub** [comment]
When I turn off the RDTClient I can see the dns lookups to api.real-debrid.com stop.

**Comment by m-ayub** [comment]
[rdtclient_001 (1).log](https://github.com/rogerfar/rdt-client/files/8443402/rdtclient_001.1.log)

added a log file

**Comment by rogerfar** [comment]
This is normal behaviour, it checks every 10 seconds when you are downloading something. When you are not downloading anything it's doesn't check either.

I see this error come by often:
```
One or more errors occurred. (Cannot assign requested address (api.real-debrid.com:443))
```
It seems like you have some connectivity issues to real-debrid. Could it be your provider blocking or throtteling your connection? Maybe antivirus?

**Comment by m-ayub** [comment]
Those errors were when I blocked the calls from pihole just to get the logs. 

There was a download that seemed to be stuck. The Apostle. I deleted that. It seems to be okay now from what I can tell so far.
