### ISSUE TITLE
Feature Request: Adding a Watch folder

### ISSUE THREAD

**Issue by ianb445** [rogerfar/rdt-client#139]
Hi,

Great software and brilliant addition to the Media server family.

It would be great if a Watch folder capability could be added to check for a .torrent or a magnet URL text file and automatically import and process to RD. This would complement the existing qBittorrent type functionality whereby a folder is watched for torrent files and downloads automatically triggered.

Thanks in advance.

**Comment by rogerfar** [comment]
This has now been added. Let me know if you run into issues.

**Comment by ianb445** [comment]
Wil test and advise, thanks for picking it up!

 

Cheers
