### ISSUE TITLE
Docker: Sonarr/Radarr 'Configuration of label failed'

### ISSUE THREAD

**Issue by timcoop3r** [rogerfar/rdt-client#14]
Sonarr/Radarr return 'Configuration of label failed' errors when using the 'Category' option in the download client settings, at least when using the Docker image on Linux.

Radarr Version 3.0.1.4259
Sonarr Version 3.0.4.1042

Client will operate without this option set, however this can cause other downloads in rdt-client to be incorrectly detected inside Sonarr/Radarr as they are not looking for specific categories to identify their own active downloads.

**Comment by jdotdarko** [comment]
Just run two instances of rdt-client. One for Radarr and one for Sonarr with two different port/volume mapping for each of them. Then configure remote mapping for download clients on those services. The settings to change the container port (not to be confused with the host port which can be changed in docker arguments or docker-compose) is inside "/app/appsettings.json" in rdt-client. You can again map that specific file on the container in order for the config to persist. 

This is my current setup right now. A workaround for "categorization" which is important on any download clients. I hope this feature will be implemented in the future.

**Comment by timcoop3r** [comment]
> Just run two instances of rdt-client. One for Radarr and one for Sonarr with two different port/volume mapping for each of them. Then configure remote mapping for download clients on those services. The settings to change the container port (not to be confused with the host port which can be changed in docker arguments or docker-compose) is inside "/app/appsettings.json" in rdt-client. You can again map that specific file on the container in order for the config to persist.
> 
> This is my current setup right now. A workaround for "categorization" which is important on any download clients. I hope this feature will be implemented in the future.

This issue isn't causing as much pain as some of the other issues currently, but may actually still offer some benefits to have two instances (such as the root download folder being deleted on import problem will only impact Sonarr/radarr and not both) so may give that a try anyway. Thanks for the idea.

**Comment by jdotdarko** [comment]
> > Just run two instances of rdt-client. One for Radarr and one for Sonarr with two different port/volume mapping for each of them. Then configure remote mapping for download clients on those services. The settings to change the container port (not to be confused with the host port which can be changed in docker arguments or docker-compose) is inside "/app/appsettings.json" in rdt-client. You can again map that specific file on the container in order for the config to persist.
> > This is my current setup right now. A workaround for "categorization" which is important on any download clients. I hope this feature will be implemented in the future.
> 
> This issue isn't causing as much pain as some of the other issues currently, but may actually still offer some benefits to have two instances (such as the root download folder being deleted on import problem will only impact Sonarr/radarr and not both) so may give that a try anyway. Thanks for the idea.

You're welcome. I created another workaround to solve the root permission on the download folder by using a script that watches the said folder for any changes made and executes a command immediately that changes the permission back to my uid and docker gid on every files/folders recursively. This is to eliminate the import issue on Sonarr/Radarr after downloading. 

If the script interests you, you can refer to this post: https://unix.stackexchange.com/a/24030

**Comment by rogerfar** [comment]
I'm looking into this issue now but I'm not 100% sure what's happening.

My sonarr has the category "tv-sonarr" and my Radarr has the category "radarr" set.

The `Configuration of label failed` error I have never seen, does this happen every time?

If the download path is set to `C:\Downloads` and a label is passed in, do you expect the file to be downloaded to `C:\Downloads\tv-sonarr` (and `C:\Downloads\radar`)?

I kind of like that solution of just taking the category appended to the download path.

**Comment by timcoop3r** [comment]
Yeah I get this error every time, across a couple of different installations of radarr/sonarr (I had multiple instances of these for testing). I should probably add this is on Docker on a linux box so there may be something different happening there. Not sure if @jdotdarko is in a similar position?
I can try and dig into some debug somehow to see whats happening in the requests. Let me know what you need and I'll try and provide.

The way deluge behaved previously for me was the torrent just had a label applied. I presume that Sonarr/Radarr are just using this in some way to filter whats included in the response from the client? Everything still had a single download root location, e.g. '/data/downloads' rather than category based path. If you are writing torrent info to a DB backed in some way it probably just needs to have this label set in a similar way to return this back to filter the output?

The categories would probably help reduce the required processing if you have lots of downloads active outside of radarr/sonarr, but to me this is a smaller issue more of the fact its throwing an error when you setup rdt-client in the first instance, making you think something is wrong, rather than having a _huge_ impact to it actually working. 

(For me the bigger problem is the root download folder getting removed due to the issues with the qtorrest /files endpoint or Sonarr/Radarr QBT API updates :) )

**Comment by rogerfar** [comment]
I noticed that qBittorrent does not have the behaviour of moving downloads to its own paths, but transmission does. So I will keep the feature in just because it makes it easier to manage downloads.

I will have a look at the files endpoint, I'm not familiar with that yet.

**Comment by rogerfar** [comment]
I just looked at the torrents/files endpoint but that is implemented. I also don't see code why it would delete the root path. 

I will release a new docker container soon with a new download manager, can you try that one and see if it still throws that error?

**Comment by timcoop3r** [comment]
> I just looked at the torrents/files endpoint but that is implemented. I also don't see code why it would delete the root path.
> 
> I will release a new docker container soon with a new download manager, can you try that one and see if it still throws that error?

The files endpoint is present but throws and returns and exception when its queried, rather than whatever its actually supposed to return, at least on my docker install. I think this is preventing Sonarr/Radarr picking up the proper path of the specific download and it just falls back in some way to using the download root instead. Radarr/Sonarr imports the files and once the path is empty it removes it. This seems like more of a Sonarr/Radarr issue, but is probably only happening because the QBT API is essentially broken from their perspective.

Fundamentally the content_path and API version bump should bring rdt-client in line with the way Sonarr/Radarr v3 interact with recent QBT versions so the /files exception becomes a non-issue there. The exception may be more of an issue for Sonarr/Radarr v2 that don't have this implemented and still rely on it perhaps. Depends what version combinations you want to support I suppose. :)

**Comment by rogerfar** [comment]
`Configuration of label failed` is now fixed, I never received that error in Sonarr, but when I tried Radarr I was getting it.

Issue is that your torrent client needs to have a category set, so for now your download client has to have the "radarr" or "sonarr" category.

Can you try the latest docker container and see if that's fixed now?

**Comment by timcoop3r** [comment]
> `Configuration of label failed` is now fixed, I never received that error in Sonarr, but when I tried Radarr I was getting it.
> 
> Issue is that your torrent client needs to have a category set, so for now your download client has to have the "radarr" or "sonarr" category.
> 
> Can you try the latest docker container and see if that's fixed now?

Latest docker image has no more category errors adding the client in either Sonarr or Radarr

**Comment by timcoop3r** [comment]
Further to the above, I am seeing the following error in Radarr (v3) 'system status' since the category change:

_Remote download client rdtc places downloads in /{mapped_path}/radarr but this directory does not appear to exist. Likely missing or incorrect remote path mapping._ (where {mapped path is the mapped path set in rdt-client)

I have the category set to 'radarr' but can confirm the downloads are not being placed with /radarr appended to the download path. Likewise with Sonarr /sonarr is not appended to the download path with 'sonarr' set as the category, but no error is reported in Sonarr.

**Comment by rogerfar** [comment]
Does `/{mapped_path}/radarr` exist and does Sonarr have permissions to write in it?

**Comment by timcoop3r** [comment]
> Does `/{mapped_path}/radarr` exist and does Sonarr have permissions to write in it?
> 

No it does not. Let me create it and see what it does :)

**Comment by timcoop3r** [comment]
/{mapped_path}/radarr now exists but rdt-client is still writing downloads to the root download location rather than radarr/sonarr folders. This is with the latest available docker image.

**Comment by timcoop3r** [comment]
Can confirm this seems to be working as intended now in the latest docker image. I can see /sonarr /raddar paths being used on the host download root as per the categories set in Sonarr/Radarr. Sonarr/Radarr seem to be aware of the correct import locations.
