### ISSUE TITLE
Reappearing torrents

### ISSUE THREAD

**Issue by phirestalker** [rogerfar/rdt-client#142]
**What version are you using?**
2.0.12
**Wat OS are you running?**
Ubuntu 20.04
**Are you using Docker or as a service?**
docker
**Please attach a log file here with the log setting set to debug**
[rdtclient_027.log](https://github.com/rogerfar/rdt-client/files/8620929/rdtclient_027.log)

I have reappearing torrents. I downloaded one large torrent that turned out to be the wrong thing. Ever since then, related torrents seem to be adding themselves. There are duplicates multiple times.
I first tried to just delete all of my torrents from the app. Then, I edited the database and truncated the Downloads and Torrents tables while also clearing everything from real-debrid. Then I enabled the function to delete torrents when deleted from real-debrid, so I could easily delete whole pages. But they keep coming back after a few hours.

**Comment by rogerfar** [comment]
Can you try on the new version?

**Comment by phirestalker** [comment]
Yes, they reappeared.

**Comment by phirestalker** [comment]
Sorry, I thought I checked already. It was my tv show downloader.
