### ISSUE TITLE
v2.0.14 - Unexpected error upon finish downloading from Radarr/Sonarr

### ISSUE THREAD

**Issue by popophobia** [rogerfar/rdt-client#145]
Hi,

I'm running RDT v2.0.14 from docker (synology box)
On the latest version, both Radarr and Sonarr cannot import download from rdt (with and without category assigned).
Upon completion of download, the torrent is removed from rdt client, and the file is still available, however, sonarr and radarr report error code from rdt and cannot import the file automatically.

Everything works find on v2.0.12.

I think some recent changes may have resulted in this bug.

Thanks

**Comment by rogerfar** [comment]
Can you post logs on debug mode?

**Comment by rogerfar** [comment]
I just tested it and it worked, but I realized this settings might not work properly:

![image](https://user-images.githubusercontent.com/1142915/168479577-c1421d49-4afe-4fec-92df-9997dc1338d2.png)

You will want this setting under the `Provider` tab to be `No Action` by default.

**Comment by popophobia** [comment]
> I just tested it and it worked, but I realized this settings might not work properly:
> 
> ![image](https://user-images.githubusercontent.com/1142915/168479577-c1421d49-4afe-4fec-92df-9997dc1338d2.png)
> 
> You will want this setting under the `Provider` tab to be `No Action` by default.
> 
> Edit: sorry I meant the qBittorent tab, I will push a version with those settings removed now.

You're right. It's this setting that throw things off.
I always thought the removal upon completion is handled by Sonarr/Radarr.
