### ISSUE TITLE
Dont complete download in LXC container Proxmox

### ISSUE THREAD

**Issue by Stephan296** [rogerfar/rdt-client#154]
He doesn't complete downloads when i use this container in an LXC container in Proxmox.
I can't found anything in the logfile about the error. How can i provide you some information?
Container start with downloading but stops at some time and starts over and over. But don't finish the jobs.
I tried it with multiple files, when i copy the url and download it with for example google chrome it works without any problem.

only thing that i can found in the log file is: [WRN] Microsoft.EntityFrameworkCore.Query: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.

**Comment by rogerfar** [comment]
Please post a debug log.

**Comment by Stephan296** [comment]
https://file.io/wArPbi84ds0N

about 22:12:18 the problem starts

**Comment by rogerfar** [comment]
The issue looks to be here:
`
2022-06-12 22:13:42.241 +02:00 [DBG] RdtClient.Service.Services.TorrentRunner: Download reported an error: The operation was canceled. for download FBI.S02E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv 0% (ba5b99dd-b36d-41c5-8a55-813adfd0ec22) for torrent FBI.S02.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] (3SB3E2GJJPMNO - downloaded 100%) (c60df530-8338-454b-9280-581fffcfa482)
`
I have seen this happen when trying to process are large amount of torrents at the same time where the system becomes laggy and the http connection breaks.

How much resources do you have allocated to the container? You could try using the Aria2 downloader, that why it's disconnected from the process,

**Comment by Stephan296** [comment]
I have now upgraded the lxc container from 4 gb to 6gb RAM and from 4 cores to 6 cores.

**Comment by Stephan296** [comment]
Unfortunately it doesn't solve the problem. I have tried multiple Aria downloaders but i dont fix the problem

**Comment by rogerfar** [comment]
What errors are you getting in Aria2?

**Comment by rogerfar** [comment]
The simple downloader is fairly heavy on resources, multi part is a bit better because it flushes to disk properly.

I will investigate a bit to see if the simple downloader can be a bit leaner.
