### ISSUE TITLE
Settings to report as error if real debrid doesn't have it

### ISSUE THREAD

**Issue by dewdrinker19** [rogerfar/rdt-client#155]
Hello, great tool. Simply amazing!  Does anybody know how to set up properly so that if a file hasn't been downloaded by real-debrid it tells radar it is an error and to move on to the next torrent?  I sometimes get stuck at "Torrent downloading (0% - 0 B/s)" because the file has not been downloaded by real-debrid and with no seeds it will not finish.  Thanks.

**Comment by rogerfar** [comment]
That is a great suggestion. I was thinking to make an indexer that kinda does the same thing. 

In Prowlarr, you can add a generic Torznab indexer, we could simulate the behaviour like we do for qBittorrent in the client.

Would something like that work?

**Comment by dewdrinker19** [comment]
Are you saying you are thinking you could make a custom indexer where you could search for "x" and it would only return results of torrents that are cached on real-debrid and ready to download via the rdt-client?

If so, that would be insanely incredible.

**Comment by rogerfar** [comment]
That first option should already work by setting this setting:

![image](https://user-images.githubusercontent.com/1142915/173403363-e8e296b7-2475-4877-a3d5-ad103cc3c644.png)

If you set this to 10, the torrent has 10 minute to complete, if not, it will get marked as error. If the torrent is complete on RealDebrid, then this time doesn't matter anymore.

**Comment by dewdrinker19** [comment]
Oh wow! I am not sure how I missed that. Incredible! Thank you.
