### ISSUE TITLE
Install rdt-client without root

### ISSUE THREAD

**Issue by phiivas** [rogerfar/rdt-client#158]
Is there any way to install rdt-client without root. I am subscribed to ultra.cc seedbox, but I do not have root access there and accordingly installation of docker containers is impossible?

**Comment by phiivas** [comment]
I wrote to the support of ultra, they refused to install a docker container, which is not officially supported by them, nor do they allow me to install it myself via SSH access, because there is no root. Therefore I decided to write to you. 

However, with apps that allows python installations everything works great. For example, piejanssens/premiumizer was installed and started successfully with this script:

$ git clone https://github.com/piejanssens/premiumizer.git premiumizer
$ cd premiumizer
$ pip install -r requirements.txt
$ python premiumizer/premiumizer.py

The Python version on the server is:
Python 3.8.13

Is there a way to install this app via Python script or some other option that does not require root?

Thanks

**Comment by rogerfar** [comment]
RDT, like Radarr and Sonarr runs on .NET 6. If you can get those working on there, then this one should work on there too. As those have a much larger community check if you can find anything about that.

Check if .NET is installed by running `dotnet --list-runtimes`

**Comment by phiivas** [comment]
This is what I found in the discord group of ultra. What script should I execute to install and run RDT?

**Installing a second instance of *Arrs**
Install Lidarr | Radarr | Readarr | Prowlarr | 

Whisparr:
`bash <(wget -qO- https://raw.githubusercontent.com/ultraseedbox/UltraSeedbox-Scripts/master/dotNetArrs/dotNetArrs-install.sh)`

Install Sonarr
`bash <(wget -qO- https://raw.githubusercontent.com/ultraseedbox/UltraSeedbox-Scripts/master/Sonarr/sonarrv3-install.sh)`

Install Bazarr
`bash <(wget -qO- https://raw.githubusercontent.com/ultraseedbox/UltraSeedbox-Scripts/master/Bazarr/bazarr-install.sh)`

**Comment by phiivas** [comment]
Ok, I successfully installed dotnet on the server. Now when I type `dotnet --list-runtimes` in shell, I get this:

```
Microsoft.AspNetCore.App 6.0.6 [/home24/phivas/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.6 [/home24/phivas/.dotnet/shared/Microsoft.NETCore.App]
```

I unzipped RealDebridClient.zip v2.0.17 on the server, then I changed the paths and the port in `appsettings.json`

```
{
  "Logging": {
    "File": {
      "Path": "/home/phivas/.apps/RealDebridClient/db/data/rdtclient.log",
      "FileSizeLimitBytes": 5242880,
      "MaxRollingFiles": 5
    }
  },
  "Database": {
    "Path": "/home/phivas/.apps/RealDebridClient/db/data/rdtclient.db"
  },
  "Port": "13801"
}
```
then in the RealDebridClient directory I wrote this command:

`dotnet run RdtClient.Web.dll`

I got this:

`Couldn't find a project to run. Ensure a project exists in /home24/phivas/.apps/RealDebridClient, or pass the path to the project using --project.`

and this:

`dotnet RdtClient.Web.dll`

and got this:

`Failed to create CoreCLR, HRESULT: 0x8007000E`

Where am I wrong? I apologize, but I'm still not familiar with how to deal with dotnet and your app.

Thanks for your help

**Comment by rogerfar** [comment]
`0x8007000E` means out of memory. How much memory does the instance have?

**Comment by phiivas** [comment]
Me

"I installed .dotnet:

dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.6 [/home24/phivas/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.6 [/home24/phivas/.dotnet/shared/Microsoft.NETCore.App]

and trying to run an .dotnet app, but I get a message that there isn't enough RAM.

dotnet RdtClient.Web.dll
Failed to create CoreCLR, HRESULT: 0x8007000E
This error code means "out of memory".

How many GB is the RAM in my slot?"




Ultra.cc

"RAM is shared across users and processes, so it is not really possible to tell how much is allocated to single user/application. The 1-click installers have access to the RAM necessary for a consistent user experience, 3rd party installed apps are more restrictive.

Please note the following that may be of use in the future:
You are more than welcome to install the application/software in your userspace/home directory by using your shell access, providing it does not abuse server resources. We will not be able to provide any official support for installing the 3rd party application/software.

Real-debrid block known hosting providers, so your app would probably never work even without the RAM challenges.

You may find that the 1-click installed app: JDownloader2 fits some of your requirements."
