### ISSUE TITLE
WebUI not opening

### ISSUE THREAD

**Issue by Ditto6995** [rogerfar/rdt-client#159]
Hey, I've downloaded the newest version of rdt client (2.0.17) onto my host, and AspNet Core Runtime 6. I tried different config combinations and cannot for the life of me get the webUI to open. I'm not too well versed in command line or Docker so I tried to install it as a Windows service. When I run the application, a cmd window opens and closes and then nothing shows up when I try to open the webUI. I have the appsettings file config'd to `"C:\\RdtClient\\db\\rdtclient.log"` & `"C:\\RdtClient\\db\\rdtclient.db"` respectively, and my Port: `"6500"` 

If anyone can help me to automate a pretty easy way to get media, that would be helpful. Thank you.

**Comment by rogerfar** [comment]
If you execute the application in cmd or Windows terminal it wilm show you the output without closing right away.

**Comment by Ditto6995** [comment]
Alright, I was able to get it to load the WebUI and am now just configuring to my specs. Thanks for the program and everything.
