### ISSUE TITLE
"The task was cancelled."

### ISSUE THREAD

**Issue by Sekihotai** [rogerfar/rdt-client#162]
**What version are you using?**
Latest
**Wat OS are you running?**
Synology DSM 7.0-41890
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/9032277/rdtclient.log)

Basically, the download from Real-Debrid fails every single retry and says that the "task was cancelled" even though I never cancelled it.  I tried increasing the timeout (as you can see in the log) but it didn't help. It was working earlier today so I'm not really sure what's wrong. I tried remaking the container and restarting the container but it didn't help. The API Key is correct, and my subscription has not run out.

**Comment by rogerfar** [comment]
I do see this error:
```
2022-07-02 01:00:55.064 +00:00 [WRN] Microsoft.AspNetCore.Server.Kestrel: As of ""2022-07-02T01:00:46.2529006+00:00"", the heartbeat has been running for ""00:00:05.2633409"" which is longer than ""00:00:01"". This could be caused by thread pool starvation.
```
Downloading through the simple downloader is a fairly CPU intensive process unfortunately, it could be that it's maxing out memory or CPU on your host causing it to lock up.

You could try setting the download speed lower, but probably you're better off setting up Aria2c to download files.
