### ISSUE TITLE
[Question] Is use with multiple sonarr and radarr instances possible?

### ISSUE THREAD

**Issue by h3rb1n4t0r** [rogerfar/rdt-client#163]
background: i am using 6 sonarr and 6 radarr instances for different languages and quality levels. thus, all *arr instances are mapped to different paths since i store all media separately to have different libraries in plex. qbittorrent is able to serve all the 12 different instances.

question: is it possible to use rdt-client the same way? i ask, since i see only one option for "mapped path" in the UI

**Comment by rogerfar** [comment]
There is only 1 mapped path, but it's usually not even needed. 

I have seen people using multiple instances, so that should work, as long as you make sure your categories are properly separated.

**Comment by h3rb1n4t0r** [comment]
I was able to link all 12 instances just fine. Thank you sir for this awesome client!
