### ISSUE TITLE
Simple Downloader Speed Limit

### ISSUE THREAD

**Issue by MGM03** [rogerfar/rdt-client#164]
**What version are you using?**
2.0.17
**What OS are you running?**
Linux (TrueNAS Scale)
**Are you using Docker or as a service?**
Docker

When using the "Simple Downloader" setting it to 50MB/s results in around 10MB/s of actual download speed, however if I set it to 250MB/s (Which considering I have Gigabit internet that is not possible) it will download at 50MB/s, I initially presumed it was Mbps but mislabelled however that would be a factor of 8 not 5.

When using the Multi-Part Downloader the 50MB/s limit is respected and is reached.

**Comment by rogerfar** [comment]
That's interesting, the Multi-Part and simple downloader both use the same throttling algorithm. I tested it on Windows and it seems fine, could be that in linux it behaves differently.

**Comment by MGM03** [comment]
I thought some proof to these claims may help.
The first is a current download with the download "speed" present.
The second is my settings.
The third is the network inbound in Mbps (Taken through Netdata)
[https://imgur.com/a/Dg5JLzb](url)

**Comment by MGM03** [comment]
Below I have also attached a screenshot of the statistics from the server to show further information of the system and its usage when running RDT-Client.
[https://imgur.com/a/keDwsJF](url)
As you can see there is a download speed of 389.6Mbps which is 48.7MBps (evidently inconsistent with RDTs settings

**Comment by mynvnow** [comment]
I had the same issue for a while now. Didn't bother to report as it doesn't break stuff and I use it in docker.

**Comment by rogerfar** [comment]
If you use the multi-part downloader, does it give the same issue?

**Comment by MGM03** [comment]
I do not have the same issue with the multi part downloader

**Comment by rogerfar** [comment]
I have removed the internal downloader completely and replaced it with https://github.com/bezzad/Downloader

So far I'm having good results and the download speed seems to be more accurate.

**Comment by MGM03** [comment]
The new internal downloader solved all of my issues
