### ISSUE TITLE
Synology NAS Compatible?

### ISSUE THREAD

**Issue by cremonies** [rogerfar/rdt-client#165]
Just wondering if this can be ran on a NAS with Docker.

**Comment by rogerfar** [comment]
Yes that should be fine.

**Comment by cremonies** [comment]
could you tell me if this looks right?
version: "3.8"
services:
    rdtclient:
    image: rogerfar/rdtclient:latest
    container_name: rdtclient
    environment:
      - PUID=1030
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /volume1/data/torrents:/data/downloads
      - /volume1/Docker/rdt-client/:/data/db
    ports:
      - 6500:6500
    network_mode: synobridge
    restart: unless-stopped
    	logging:
            driver: json-file
            options:
                max-size: 10m
