### ISSUE TITLE
I'm on the rdt-client latest version service version on windows 10 enterprise downloading stuff by using a torrent file works fine but trying to use it with radarr to download a movie i get this error 

### ISSUE THREAD

**Issue by Pickymarker** [rogerfar/rdt-client#168]
I'm on the rdt-client latest version service version on windows 10 enterprise downloading stuff by using a torrent file works fine but trying to use it with radarr to download a movie i get this error 
![image](https://user-images.githubusercontent.com/74084396/180240374-d9fb5979-edac-4c46-8795-56057dbd7b00.png)

![image](https://user-images.githubusercontent.com/74084396/180240526-94defe4a-295a-4730-8f83-17a0d349d842.png)

![image](https://user-images.githubusercontent.com/74084396/180240583-85133543-3ca4-47c1-a3ee-65adc35df466.png)

![image](https://user-images.githubusercontent.com/74084396/180240651-c109f5b2-428b-4bca-b599-ca0f4bff714d.png)

![image](https://user-images.githubusercontent.com/74084396/180240719-ca992ca5-c4d0-4142-b6d8-3f79d91246aa.png)

![image](https://user-images.githubusercontent.com/74084396/180240801-d631bc6e-cb1a-4828-bd49-8000bbf0f069.png)

![image](https://user-images.githubusercontent.com/74084396/180240958-ed365c6e-e681-4c16-a44e-3a7c8a55d595.png)
 
that's all the screenshots i think you will need to help and here's the log 

[rdtclient.log](https://github.com/rogerfar/rdt-client/files/9160258/rdtclient.log)

**Comment by rogerfar** [comment]
Unfortunately infringing files aren't handled very proper at this time, I will add better handling for it in the next version.

**Comment by rogerfar** [comment]
I had a look at this again, because it's an infringing file it will report it as an error to sonarr/radarr. They will handle this error, blacklist the torrent and try another one.
