### ISSUE TITLE
Feature Request - Only proceed with Download if X GB space left on disk

### ISSUE THREAD

**Issue by h3rb1n4t0r** [rogerfar/rdt-client#169]
Hi. A feature which stops downloads at a given remaining space limit would help to have disks not overrun. Could something like this be implemented? Sabnzbd has a similar option in settings.

**Comment by h3rb1n4t0r** [comment]
I just saw this was raised a year ago with issue #61

**Comment by h3rb1n4t0r** [comment]
I raise a feature bounty worth 20 USD 💵 😄

**Comment by rogerfar** [comment]
I'll close this because of the duplicate of #61.
