### ISSUE TITLE
Loose connection on my raspberrypi when the container "rdtclient" start

### ISSUE THREAD

**Issue by Maedhros-dev** [rogerfar/rdt-client#171]
I'm new on Docker so I don't understand everything about it
**What version are you using?**
the latest (installed today) v2.0.17
**Wat OS are you running?**
I'm on raspbian 11 Bullseye (v11.4) on a raspberry pi 4

**Are you using Docker or as a service?**
I use Docker and I have followed the instruction from the readme
**Please attach a log file here with the log setting set to debug**
[logs.txt](https://github.com/rogerfar/rdt-client/files/9295437/logs.txt)

When I start the container "rdtclient" after several seconds I have no connection anymore on my raspberrypi

**Comment by rogerfar** [comment]
There is nothing in the logs that indicate anything unusual. Did you check your system or docker logs?

**Comment by Maedhros-dev** [comment]
I'm really new and I don't really know if something is wrong with the logs, I've looked and I don't see any errors but I think the problem might be with my settings (which are the default ones)

**Comment by Maedhros-dev** [comment]
I reinstalled all (my os and everyting else) and now It seems to work
