### ISSUE TITLE
please explain the following settings

### ISSUE THREAD

**Issue by cremonies** [rogerfar/rdt-client#173]
1. Provider>"Automatically import and process torrents added to provider"
Does this download the files manually added to the provider to the download/mapped path listed under 'download client' settings?

2. Provider>"Automatically delete downloads removed from provider"
Does this delete the file in Download/Mapped path right after the download is complete?

3. "Finish Action"
what happens to the file when "Remove Torrent From Client and Provider" is selected?
will this also delete the downloaded file if "Automatically delete downloads removed from provider" is selected?

4. "Only download available files on debrid provider"
If this is not selected, does debrid download the files and then the client downloads from debrid?
Why is it listed under 'provider' and 'GUI defaults'?

**Comment by rogerfar** [comment]
1. It imports the torrents that are in RealDebrid or AllDebrid, so technically, yes, it will download those files.
2. No, it only removes the torrent itself from RDT-Client.
3. No, it only removes it from RealDebrid or AllDebrid.
4. When checked it only downloads the files that are available on RealDebrids or AllDebrids servers. If it's unchecked, it will attempt to download all files in the torrent, this usually means that RealDebrid or AllDebrid will re-download the complete torrent to fetch those missing files.

**Comment by kristobal62** [comment]
Thank you for your reply. After several hours of testing I finally found the right path.
Everything works great.
Thanks for this app.
