### ISSUE TITLE
Bug: WR permission test 

### ISSUE THREAD

**Issue by ianb445** [rogerfar/rdt-client#174]
Currently running 20.0.17 
Ubuntu 22.04
Running under docker.

I recently changed formatted storage from vfat to ext4 which resulted in folder ownership permissions, ownership was changed from the specified user to root, however the Download Permissions Test did not detect an issue until an actual file was downloaded and RDTC could not create the folder and write the file.

The folders are created by the respective *arr apps (sonarr, lidarr etc) running on another machine and accessing the same mounted folder via sshfs. Owership for the folders needed to be set via chmod, after which everything worked well.

1. It would be great if the tests could test both folder creation as well as file creation. 
2. In the error reporting, check to see what permissions are blocking a download.

Thanks

Ian

**Comment by rogerfar** [comment]
Unfortunately it's not that simple as Radarr and Sonarr make their own directories, the permission test only tests the root.
