### ISSUE TITLE
Not Following rule - Only download available files on debrid provider

### ISSUE THREAD

**Issue by cremonies** [rogerfar/rdt-client#175]
**What version are you using?**
2.0.17
**Wat OS are you running?**
linux/synology
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**
I do not see an option for this.

Files added though sonarr are downloading torrent when file is not already cached on RD.
It should be returning as failed or something?

**Comment by rogerfar** [comment]
This is by design, if they are not available then it will simply download the full torrent.

**Comment by cremonies** [comment]
> This is by design, if they are not available then it will simply download the full torrent.

Then what does the checkbox change?

**Comment by rogerfar** [comment]
Let's say you download a movie and it has 2 files:
- Movie.m4a
- Subs.en.srt

Often what happens is that only the file `Movie.m4a` gets cached on the RealDebrid servers. If you enable the checkbox, it only downloads this file, and skips the `Subs.en.srt` file.

If no files are available then it will attempt to download the full torrent to the RD cache servers.

**Comment by cremonies** [comment]
Oh that makes sense. Thanks.
