### ISSUE TITLE
Windows Service install instructions are not clear.

### ISSUE THREAD

**Issue by pickinanameainteasy** [rogerfar/rdt-client#176]
**What version are you using?**
v.2.0.17 (latest)

**What OS are you running?**
Windows 10

**Are you using Docker or as a service?**
Service

I have followed the instructions under the run as a service section. First I installed the necessary .NET runtime linked in step 1. Then I extracted the latest zip file to C:/Program Files/rtd-client. 

I then opened appsettings.json and set LogLevel path to C:\\Program Files\\rdt-client\\client.log and set Database path to C:\\Program Files\\rdt-client\\rdtclient.db, both of these directories are empty as I assume running the software will generate the necessary files. I have made sure to escape the backslashes.

I then had to search thru the Program Files directory and found a script called service-install.bat and I ran that which did create firewall rules and a Service for RealDebridClient however this was never mentioned in the readme. Even after installing the service, the site at localhost:6500 is unavailable.

Opening up services and attempting to manually start the service results in the following error:

`Windows could not start the RealDebridClient service on Local Computer.

Error 1053: The service did not respond to the start or control request in a timely fashion.`

The windows installation instructions feel incomplete and I am unable to use the program because of this.

**Comment by rogerfar** [comment]
Did you the install the .NET6 runtime? Otherwise check your event logs.

**Comment by pickinanameainteasy** [comment]
Looks like I installed the SDK 6.0.400. It says it ASP.NET Core Runtime 6.0.8 is included.

**Comment by rogerfar** [comment]
What does the event viewer log?

**Comment by pickinanameainteasy** [comment]
Where are the event logs located?

**Comment by pickinanameainteasy** [comment]
I have uninstalled the sdk and installed only the .NET6 runtime. I removed the service and then installed it again, but still when I press start on the service I get the same 1053 error. No logs are created in the logs directory I created so I can't check the event logs.

**Comment by rogerfar** [comment]
Right click start menu -> Event Viewer.

**Comment by pickinanameainteasy** [comment]
I have 
![runtime error](https://user-images.githubusercontent.com/86267611/187754793-7513e28a-313b-407a-b170-4913c8441af7.JPG)
Assuming this has something to do with it

**Comment by pickinanameainteasy** [comment]
More detail:

`Log Name:      Application
Source:        .NET Runtime
Date:          8/31/2022 1:38:15 PM
Event ID:      1023
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      John-HP
Description:
Description: A .NET application failed.
Application: RdtClient.Web.exe
Path: C:\Program Files\rdt-client\RdtClient.Web.exe
Message: A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Program Files\rdt-client\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=6.0.5


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-08-31T18:38:15.2445559Z" />
    <EventRecordID>59018</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>John-HP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Description: A .NET application failed.
Application: RdtClient.Web.exe
Path: C:\Program Files\rdt-client\RdtClient.Web.exe
Message: A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Program Files\rdt-client\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&amp;arch=x64&amp;rid=win10-x64&amp;apphost_version=6.0.5

</Data>
  </EventData>
</Event>`

**Comment by pickinanameainteasy** [comment]
I notice it says to install dotnet at C:\Program Files\dotnet
but it installed it at C:\Program Files (x86)\dotnet

**Comment by rogerfar** [comment]
What do you get if you do in the command line: `dotnet --list-runtimes`?

**Comment by pickinanameainteasy** [comment]
i get:
'dotnet' is not recognized as an internal or external command, operable program or batch file.

**Comment by rogerfar** [comment]
Then it seems you haven't install the runtime no. Did you use this link:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.8-windows-x64-installer

**Comment by pickinanameainteasy** [comment]
I had installed ASP.NET runtime. I uninstalled it and then installed the one you linked. Now I get this error:

`Log Name:      Application
Source:        .NET Runtime
Date:          8/31/2022 2:09:05 PM
Event ID:      1023
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ******-HP
Description:
Description: A .NET application failed.
Application: RdtClient.Web.exe
Path: C:\Program Files\rdt-client\RdtClient.Web.exe
Message: You must install or update .NET to run this application.

App: C:\Program Files\rdt-client\RdtClient.Web.exe
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '6.0.0' (x64)
.NET location: C:\Program Files\dotnet\

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-08-31T19:09:05.1959235Z" />
    <EventRecordID>59066</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>******-HP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Description: A .NET application failed.
Application: RdtClient.Web.exe
Path: C:\Program Files\rdt-client\RdtClient.Web.exe
Message: You must install or update .NET to run this application.

App: C:\Program Files\rdt-client\RdtClient.Web.exe
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '6.0.0' (x64)
.NET location: C:\Program Files\dotnet\

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&amp;framework_version=6.0.0&amp;arch=x64&amp;rid=win10-x64

</Data>
  </EventData>
</Event>`

**Comment by pickinanameainteasy** [comment]
However typing dotnet --list-runtimes yields:

`Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]`

**Comment by pickinanameainteasy** [comment]
Do I need both? Because I had ASP.NET installed earlier and that's when I got the first error.

**Comment by rogerfar** [comment]
No only the latter, there is no harm having them both installed though.

**Comment by pickinanameainteasy** [comment]
Ok, I installed the ASP.NET Hosting Bundle (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.8-windows-hosting-bundle-installer) and now it works! Thanks for your help
