### ISSUE TITLE
Error auto unpacking

### ISSUE THREAD

**Issue by Wolnos** [rogerfar/rdt-client#18]
Hi thanks for making this project first of all. So I am experiencing a problem when the client tries to auto unpack a torrent. It works fine if I manually chose unpack after the download. Error: An unexpected error occurred preparing download https://sea1.download.real-debrid.com/d/scrubbed/The.Simpsons.S31E22.1080p.WEB.H264-ALiGN%5BTGx%5D.rar for torrent The.Simpsons.S31E22.1080p.WEB.H264-ALiGN[TGx]: File /plex/downloads/The.Simpsons.S31E22.1080p.WEB.H264-ALiGN[TGx]/The.Simpsons.S31E22.1080p.WEB.H264-ALiGN%5BTGx%5D.rar could not be extracted because it is missing. Watching the directory during the download its fine until it is fully downloaded then the file gets removed and it starts to redownload but the torrent is set to error in the web interface. Is this a problem with my docker mappings?

**Comment by rogerfar** [comment]
I think there is an issue where it re-downloads the file immediately after it completes. I will have a look tonight and push a fix!

**Comment by Wolnos** [comment]
> I think there is an issue where it re-downloads the file immediately after it completes. I will have a look tonight and push a fix!

Wow thanks for the quick response!

**Comment by Wolnos** [comment]
The fix you pushed worked perfectly thanks.

**Comment by rogerfar** [comment]
I'm actually just now pushing another fix you will want to grab.
