### ISSUE TITLE
Unable to download to non-local folders.

### ISSUE THREAD

**Issue by JacobSHayes** [rogerfar/rdt-client#180]
**What version are you using?**
v2.0.17

**What OS are you running?**
Raspbian GNU/Linux 10

**Are you using Docker or as a service?**
As a service

**Please attach a log file here with the log setting set to debug**

I can't seem to get RDCTs downloaders to work with my NAS which the Pi is connected to.
The error I get is 
Could not test your download path
Access to the path '/mnt/8tb/torrents/test.txt' is denied.

> Sep 15 19:56:44 octopi RdtClient[330]: [19:56:44 ERR] An unhandled exception has occurred while executing the request.
> Sep 15 19:56:44 octopi RdtClient[330]: System.UnauthorizedAccessException: Access to the path '/mnt/8tb/torrents/test.txt' is denied.
> Sep 15 19:56:44 octopi RdtClient[330]:  ---> System.IO.IOException: Permission denied
> Sep 15 19:56:44 octopi RdtClient[330]:    --- End of inner exception stack trace ---
> Sep 15 19:56:44 octopi RdtClient[330]:    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
> Sep 15 19:56:44 octopi RdtClient[330]:    at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
> Sep 15 19:56:44 octopi RdtClient[330]:    at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
> Sep 15 19:56:44 octopi RdtClient[330]:    at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
> Sep 15 19:56:44 octopi RdtClient[330]:    at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
> Sep 15 19:56:44 octopi RdtClient[330]:    at System.IO.StreamWriter.Dispose(Boolean disposing)
> Sep 15 19:56:44 octopi RdtClient[330]:    at System.IO.TextWriter.Dispose()
> Sep 15 19:56:44 octopi RdtClient[330]:    at System.IO.File.InternalWriteAllTextAsync(StreamWriter sw, String contents, CancellationToken cancellationToken)
> Sep 15 19:56:44 octopi RdtClient[330]:    at RdtClient.Web.Controllers.SettingsController.TestPath(SettingsControllerTestPathRequest request) in C:\Projects\rdt-client\server\RdtClient.Web\C
> Sep 15 19:56:44 octopi RdtClient[330]:    at lambda_method256(Closure , Object )
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecu
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTa
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Tas
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task las
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, Authorizati
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
> Sep 15 19:56:44 octopi RdtClient[330]:    at Program.<>c.<<<Main>$>b__0_12>d.MoveNext() in C:\Projects\rdt-client\server\RdtClient.Web\Program.cs:line 159
> Sep 15 19:56:44 octopi RdtClient[330]: --- End of stack trace from previous location ---
> Sep 15 19:56:44 octopi RdtClient[330]:    at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in C:\Projects\rdt-client\server\RdtClient.Service\Middleware\Author
> Sep 15 19:56:44 octopi RdtClient[330]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Ta

**Comment by rogerfar** [comment]
Fix your permissions.
