### ISSUE TITLE
Error in Download

### ISSUE THREAD

**Issue by rudnypc** [rogerfar/rdt-client#182]
Sometimes I receive 0 bytes:
![image](https://user-images.githubusercontent.com/50679581/191240273-4c8ec4fb-11ef-43ae-b359-65d48da75d3e.png)

But the Unrestricted Link works

I try to retry and I got
![image](https://user-images.githubusercontent.com/50679581/191240442-192d41df-8ad1-4372-8a11-41b4a709630a.png)
and the unrestricted link is blank now

**Comment by rogerfar** [comment]
Please provide a debug log.

**Comment by rogerfar** [comment]
I don't think you posted the right logs, those are not from rdt-client.

**Comment by rudnypc** [comment]
I did again
[idle.out2.zip](https://github.com/rogerfar/rdt-client/files/9611000/idle.out2.zip)

**Comment by rogerfar** [comment]
There's 117 torrents in RDT, which one is causing issues specifically?

**Comment by rudnypc** [comment]
I would like to understand the Dogs.in.Space.S02.1080p.NF.WEB-DL.x265.10bit.HDR.DDP5.1-SMURF[rartv]:
![image](https://user-images.githubusercontent.com/50679581/191359012-d24ab846-2e27-4534-8bf6-5951a426760e.png)

Downloaded:
![image](https://user-images.githubusercontent.com/50679581/191359048-35a9aea6-0e19-47ac-ab3c-9ff54618ac17.png)

**Comment by rogerfar** [comment]
That looks like a corrupt torrent on the Real-Debrid side. Doesn't happen very often, but their services aren't very reliably put together.

**Comment by rudnypc** [comment]
Yes, I can try once again in rdt, after that it gave an error..
> That looks like a corrupt torrent on the Real-Debrid side. Doesn't happen very often, but their services aren't very reliably put together.
> 
> If you unrestrict the torrent again through the Real-Debrid interface, does it unlock all files?

**Comment by rudnypc** [comment]
I will close, maybe it's a realdebrid problem
