### ISSUE TITLE
Queued for downloading

### ISSUE THREAD

**Issue by rudnypc** [rogerfar/rdt-client#184]
**What version are you using?**
2.0.17
**Wat OS are you running?**
Ubuntu 20
**Are you using Docker or as a service?**
No
**Please attach a log file here with the log setting set to debug**
A lot of queued for downloading, how to start this?

[idle.out2.log](https://github.com/rogerfar/rdt-client/files/9666497/idle.out2.log)

![image](https://user-images.githubusercontent.com/50679581/192817649-0e59202c-02e2-4a5f-8632-62924a84d830.png)

**Comment by rogerfar** [comment]
Is this still an issue? Looking at the log it seems to download files just fine.
