### ISSUE TITLE
External program to download

### ISSUE THREAD

**Issue by rudnypc** [rogerfar/rdt-client#185]
**What version are you using?**
2.0.17
**Wat OS are you running?**
Ubuntu 20
**Are you using Docker or as a service?**
No
**Please attach a log file here with the log setting set to debug**
I would like to use another tools to download, like a rclone.

Can you create a External in this box?
![image](https://user-images.githubusercontent.com/50679581/192818996-d2f15166-fa96-48de-aa96-18ea4a73f8d4.png)

And create a new box like this:
![image](https://user-images.githubusercontent.com/50679581/192819083-12bbb505-2e42-4a85-938b-1d8d8a9c3dbc.png)

But to pass the decoded URL to another program, like a rclone, curl, wget....

I would like to download directly to my drive.

**Comment by rogerfar** [comment]
This isn't a good idea because there is no way to monitor the actual download. You can use Aria2c on an external computer to use it as a downloader.
