### ISSUE TITLE
Changes of owners and folder deletion

### ISSUE THREAD

**Issue by ianb445** [rogerfar/rdt-client#187]
Hi,

I am running RDT client on an Ubuntu 22.04 (Raspberry PI), mounting an external EXT4 filesystem to which the downloaded files are written. The ext4 folder is in turn mounted via an sshfs share from another machine running *arr containers.

The issue I encounter is the volumes created by RDTclient sometimes disappear (are deleted) or the ownership of files and folders are changed from the UID/GID to root:root.

I created the docker container with the full paths required and on initial create everything is created correctly e.g. -v /home/media/rdtclient/sonarr/: /home/media/rdtclient/sonarr  and so on for the others.

Yet occasionally the volumes are deleted, which prevents the *arr containers from seeing those volumes and on other occasions the ownership is set to root:root.

I use watchtower to update the images, so am unsure if this is not partially responsible for odd permissions when the rdtclient is updated, nothing like this happens on updates of other containers/images.

I have not been able to find references in the logs to the volumes being deleted, so not sure what process is responsible for this.

**Comment by rogerfar** [comment]
Have you been able to figure this out? RDT doesn't delete any folders, but are you sure you aren't sharing folders with other instances? You really should download into a dedicated folder, then have *arr read from those folders, which should happen automatically because the API returns the paths.
