### ISSUE TITLE
Request: Finish Action -> Remove Torrent From Client

### ISSUE THREAD

**Issue by sflix** [rogerfar/rdt-client#189]
Hello,
Could it be possible to add the option "Remove Torrent From Client" in "Finish Action".

**Comment by rogerfar** [comment]
You just want to remove it from the client, but leave it in Real Debrid? What is the use case here?

**Comment by rogerfar** [comment]
I added this in the next version.

**Comment by sflix** [comment]
I have problems with my *arrs, they get stuck on an orange icon., unless I remove from client.
Thank you for adding this.

**Comment by rogerfar** [comment]
I'm not sure what you mean? Did you set the setting to Remove from Client?
