### ISSUE TITLE
Unrar not decompressing when more than 1 level

### ISSUE THREAD

**Issue by schardosin** [rogerfar/rdt-client#19]
Hi,
thank you for this project, amazing idea.

When you download a torrent which the files are compressed more than once, then it decompresses the first time in the Temp folder and stop there.

For example:
File compressed.rar has inside the files compressedXYZ.rar and compressedXYZ.r01.

The tool decompresses the files compressedXYZ.rar and compressedXYZ.r01 inside the Temp folder, but doesn't continue decompressing the rar files that now are inside the Temp folder.

**Comment by rogerfar** [comment]
Would you know a (legal) torrent that has multiple levels of rarred contents? So I can test with.

**Comment by rogerfar** [comment]
Closing this issue as it's a very rare occurrence but hard to test. If you think this is still necessary please provide a demo torrent.
