### ISSUE TITLE
Do not generate new debrid link

### ISSUE THREAD

**Issue by Alldebrid** [rogerfar/rdt-client#192]
Hello,

It's alldebrid.com, we have a lot of same link generation from your app which impact our service. Could you please cache a download link and reuse it ?

Best regards.

**Comment by Alldebrid** [comment]
Hi,

Once you get a download link (from /link/unlock) you can cache it and keep using it for 24h. 
We are seeing lots a generated link but none downloaded as a whole, we did not check your source code but maybe you're using some sort of multithreading and generating download link for the same uptobox link multiple times ?

**Comment by rogerfar** [comment]
So we do multithread download an unlocked file, but it shouldn't unlock the same link multiple times.

My AllDebrid account expired, so let me renew and check in the next few days if I can see something going on.

**Comment by rogerfar** [comment]
@Alldebrid 
I had a quick look through the source, but I don't think anything odd is happening.

The workflow is:
- Upload Magnet or torrent File (magnet/upload)
- Store the ID of the magnet
- Periodically check if the magnet is finished 
- When download is done, unrestrict link (link/unlock)
- Store the result link
- Download the file with the unrestricted link

Only when a download fails it will attempt to re-unlock the link, then retry the download. Is there any caching on your end when unlocking a link? 

We re-unlock the link before a download retry each time simply because RealDebrid's API isn't very reliable and often needs re-unrestricting.

**Comment by cavedog8** [comment]
Hello

So I think i found the reason why Alldebrid is complaining.

I run rdtclient with docker compose. For some reason downloads are failing mid download on the single downloader. When this happens depending on what retry count is set the client will queue the download again but not from the unrestricted link but from the uptobox link meaning the downloaded will re-unrestrict the link, try to download and if it fails or stops then requeue the uptobox link to re-unrestrict and retry the download.

I'm not sure what is causing this failed download but I will look at the log and provide once I get some info.

![Screenshot 2022-11-18 123731](https://user-images.githubusercontent.com/64382634/202687453-3693627d-9f7e-436f-81fa-ee74308b6f06.png)

**Comment by cavedog8** [comment]
These with the red crosses already failed 3/5 times and have been requeued for unrestriction again and redownload attempt.

**Comment by rogerfar** [comment]
Do you have some logs or insights to why the downloads are failing? I can add an option to cache the unrestricted links, but I'm worried for corrupt unrestricted links.

**Comment by cavedog8** [comment]
The logs don't indicate anything at all, but I have seen the same issue in jdownloader.  In the middle of a download, it would just stop downloading and say starting download again and sometimes even add a timer for 20m to retry.

With jdownloader the download resumes so I assume even if it re-unrestrict the down it resumes where the simple downloader in rdtclient doesn't resume, it restarts from the beginning and the loop continues until the retry count has been reached.

I don't have the same issue with real debrid same client, same files same settings.

Something from Alldebrid side is stopping files mid download and the get re-queued for download from the start.

**Comment by rogerfar** [comment]
If this is still an issue then feel free to open this issue again.
