### ISSUE TITLE
Alldebrid Unable to deserialize AllDebrid API response to DownloadLink

### ISSUE THREAD

**Issue by famaTV** [rogerfar/rdt-client#193]
**What version are you using?**
2.0.18
**Wat OS are you running?**
Ubuntu 
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**
[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/9893212/_rdtclient_logs.txt)

In reference to issue # 123 (you can check history), I still have a problem of not able to download using Alldebrid. However, when I tried this Docker Alldebrid-watcher, I was able to download without any issues.

https://github.com/vlacour97/alldebrid-watcher 

Your software is way more superior than the above. Could you kindly look into how he has done it and try to amend your Alldebrid implementation. Hopefully, it's a minor change for you.

Many thanks for such a great software.

**Comment by rogerfar** [comment]
I think you're going to need to setup a VPN or proxy:
Sorry, the requested page is violating the regulations of
Ministry of Media.

**Comment by famaTV** [comment]
Why the other software works but not yours?

VPN is not working with Alldebrid. Alldebrid are very restrictive with VPN.

Can you check the implementation of this https://github.com/vlacour97/alldebrid-watcher? It's working for me without any issues.

**Comment by rogerfar** [comment]
You can enable VPN support here:

![image](https://user-images.githubusercontent.com/1142915/198909778-9749ee2c-a720-4cdc-ac0f-7c3c66a2b8f6.png)

On your account page on Real Debrid.

**Comment by rogerfar** [comment]
I noticed that I'm using the HTTP address for the AllDebrid API instead of HTTPS, I will change that.

**Comment by famaTV** [comment]
I contacted Alldebrid several times and filled out the VPN form, no luck of enabling it for my VPN provider. I really hope you get this fixed by enabling the HTTPS. Let me know once released a new version to test. Truly appreciate all your great work!

**Comment by rogerfar** [comment]
Can you try 2.0.19? I changed the link to use HTTPS.

**Comment by famaTV** [comment]
Hello friend

THANK YOU SO MUCH!

It's now working without any issues. Truly appreciate all your great and amazing commitment to continuous improvements.
