### ISSUE TITLE
how do you fix this error on windows 10 

### ISSUE THREAD

**Issue by Pickymarker** [rogerfar/rdt-client#194]
how do you fix this error on windows 10 
![image](https://user-images.githubusercontent.com/74084396/198858940-df7cebf7-30d2-48bf-b1f6-17caf4d16811.png)

**Comment by rogerfar** [comment]
It seems to be a DNS issue. Do you get this each time? Do you have a proxy or pihole running that blocks connections to Github? Anyway, the error is harmless because it's the update checker, it won't prevent anything else from stopping.
