### ISSUE TITLE
AllDebrid detects the use of a server and prohibits access

### ISSUE THREAD

**Issue by bannert1337** [rogerfar/rdt-client#196]
**What version are you using?**
Version 2.0.19
**What OS are you running?**
Debian 11
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**
Error retrying torrent: Unable to deserialize AllDebrid API response to MagnetUploadResponse. Response was: { "status": "error", "error": { "code": "NO_SERVER", "message": "Servers are not allowed to use this feature. Visit https:\/\/alldebrid.com\/vpn if you're using a VPN." } }

**Expected behaviour**
The torrent download should be done via the AllDebrid service, which will provide the download link afterwards.

**Comment by rogerfar** [comment]
Are you using a hosted server? Because that might cause it: https://help.alldebrid.com/en/faq/dedicated-servers

**Comment by bannert1337** [comment]
Yeah, I'm using a Cloud VPS from Hetzner. Well, that would explain it. Thank you!
