### ISSUE TITLE
sonarr shows incorrect qbittorrent status

### ISSUE THREAD

**Issue by maxdamage2122** [rogerfar/rdt-client#198]
**What version are you using?**
2.0.19
**What OS are you running?**
ubuntu 22.04
**Are you using Docker or as a service?**
docker
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/10114021/rdtclient.log)

RDTC does not seem to be reporting the correct status over to sonarr. The attached log says it marked the torrent as complete but as you can see in the image below sonarr immediately says qbittorrent is reporting as error and never changes. Sometimes sonarr will show the status as downloading but it never changes either.

![image](https://user-images.githubusercontent.com/198148/204558460-dc51ecba-b114-47e6-9dd0-f14ee19ceccf.png)

**Comment by rogerfar** [comment]
Most likely your mapping isn't correctly setup. How does your setting look like?

**Comment by maxdamage2122** [comment]
Can you please clarify what mapping and settings you are looking for?

**Comment by rogerfar** [comment]
In Sonarr:

![image](https://user-images.githubusercontent.com/1142915/205081257-952cb86d-dd20-49d8-9d2c-61b7d8687bd1.png)


And RDT Client:

![image](https://user-images.githubusercontent.com/1142915/205081361-3ebc50cb-073d-49c9-96e7-79e8ef5b167a.png)

**Comment by rogerfar** [comment]
I'm going to close this issue, if it's still not working let me know.
