### ISSUE TITLE
sonarr Unable to connect to qBittorrent

### ISSUE THREAD

**Issue by Nightreaper77** [rogerfar/rdt-client#199]
I can't get my sonarr to connect to rdt-client. Both are hosted in docker with the same network

What version are you using?
2.0.19

Wat OS are you running?
DSM 7.1.1

Are you using Docker or as a service?
Docker

Please attach a log file here with the log setting set to debug
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/10118771/rdtclient.log)
![image](https://user-images.githubusercontent.com/4968917/204690716-da984fd1-caf0-49ea-8ce4-4ed4e0f9b22d.png)

**Comment by rogerfar** [comment]
Check your Sonarr logs, it will tell you the actual error. Either username/password wrong or a firewall port not open perhaps?

**Comment by Nightreaper77** [comment]
Yeah, now I feel like a dummy. I had my firewall set up to only allow connections to port 6500 if the source IP was local. Issue is resolved, thank you!
