### ISSUE TITLE
Can't access application

### ISSUE THREAD

**Issue by besthitman7** [rogerfar/rdt-client#2]
Followed the install instructions but after executing startup.bat or serviceinstall.bat I can't access the app.

![image](https://user-images.githubusercontent.com/20758621/97712497-cec41f00-1abe-11eb-9f98-6c1456dc1594.png)

In the app folder, i don't have an app.log or any other log file.

The app port is allowed in the firewall.

Let me know what troubleshooting information you need, if interested.

Thanks!

**Comment by rogerfar** [comment]
Can you confirm the service is running in the Services list?

**Comment by besthitman7** [comment]
Thank you for the quick answer, what is the service name i should be looking for?

**Comment by rogerfar** [comment]
It should be called `RealDebridClient`.

If it's not running run `startup.bat` and see if that gives any errors.

**Comment by besthitman7** [comment]
I think I found the first problem, indeed the service wasn't running.

It turns out, I'm performing the install on a Windows 7 server and the syntax of the sc create is a little bit different than on Windows 10, there needs to be a space after the options equal sign:

sc create RealDebridClient binPath= "%installpath%RdtClient.Web.exe" start= auto

But the problem persists even after this correction, when I try to start the service I get this error:

![image](https://user-images.githubusercontent.com/20758621/97719529-78a7a980-1ac7-11eb-83d8-2df7afe4b8ad.png)
error 1053 service did not respond in a timely fashion

After a quick internet search, I tried to increase the ServicesPipeTimeout registry key but it didn't help.

I also tried on an up to date windows 10 machine with the same result.

**Comment by rogerfar** [comment]
Probably the service is throwing an exception.

Can you run this on the command line while you are in the extracted ZIP directory:
`dotnet RdtClient.Web.dll`

If you get an error that `dotnet` is not found, try installing the .NET Core runtimes:
https://dotnet.microsoft.com/download/dotnet-core/current/runtime

**Comment by besthitman7** [comment]
It works!

I didn't have dotnet frameworks installed, after installing them I can now access the app

Thanks!

**Comment by besthitman7** [comment]
Do you have any plans for new features? like maybe having the app watch a folder and download .torrent files it finds in it automatically?

**Comment by rogerfar** [comment]
Unfortunately I'm not using it anymore as much as I found the torrentboxes on RD unreliable, lots of errors or hangs. Try it out for a bit and see if you're seeing the same issues, if not I can have a look at adding more features.
