### ISSUE TITLE
Feature Request: HTTP Proxy Support

### ISSUE THREAD

**Issue by timcoop3r** [rogerfar/rdt-client#20]
Really appreciate all the time you've put into this so far, but going to throw this request out there none-the-less. :)

I currently use rdt-client in combination with a VPN service which also runs in a container. To achieve this currently the VPN and rdt-client share the VPN container network stack. This has the negative affect of rdt-client needing to be restarted when the VPN container restarts. 
With HTTP proxy support, rdt-client could run on its own network namespace, use the VPN or other network gateway by way of an HTTP proxy (this is my setup for Radaar/Sonaar etc.). 
This would also allow rdc-client container to keep running when the VPN container is restarted and could even allow rdt-client to run on a separate host on the network with the VPN endpoint on a seperate device running a web proxy that may not be the default gateway. 
Fundamentally just allows more flexibility with setup and deployment if this is a possibility?

**Comment by rogerfar** [comment]
I think this falls outside the scope of the application, at least I wouldn't know how to configure Kestral to use a proxy.

This should be possible through Docker config I would think right?

**Comment by timcoop3r** [comment]
I actually had no idea that could be done against the container through Docker!

I have pushed the proxy config to the container this way and can confirm that is working, thanks!

**Comment by asdproton** [comment]
@timcoop3r Can you please share how exactly you pushed this? I am trying the same thing but keep failing. Currently I am using HTTP_PROXY as ENV variable but the client still downloads directly and is ignoring the proxy.

**Comment by timcoop3r** [comment]
> @timcoop3r Can you please share how exactly you pushed this? I am trying the same thing but keep failing. Currently I am using HTTP_PROXY as ENV variable but the client still downloads directly and is ignoring the proxy.

Which downloader are you using? This only worked with the simple downloader for me and the multi-part downloader did not use the proxy. The API requests used the proxy in both setups.

I defined http_proxy and https_proxy as environment in docker-compose. Using an environment file for the compose project didn’t seem to work for me.

**Comment by asdproton** [comment]
@timcoop3r  I am/was using the multipart downloader. maybe that was the issue. Will reconfigure.

**Comment by rogerfar** [comment]
That is odd actually, I wonder why that downloaders would bypass the proxy. @timcoop3r can you share a bit on your setup? What docker container is the other VPN service? And what is the HTTP_PROXY config?

**Comment by timcoop3r** [comment]
@rogerfar Here is an example docker-compose I just switched to for 'proxy mode'. This works with the simple downloader, and you can see the API requests and simple downloader requests in the tinyproxy logs. If you switch to multipart downloader, you only see the API requests:

```yaml
version: '2.1'
services:
  vpn:
    container_name: vpn
    image: bubuntux/nordvpn:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    environment:
      - CONNECT=uk -g p2p
      - TZ=Europe/London
      - USER=username
      - PASS=password
      - TECHNOLOGY=NordLynx
      - NETWORK=x.x.x.x/24  # LAN Range
    devices:
      - /dev/net/tun
    network_mode: bridge
    ports:
      - "8888:8888" # tinyproxy listen port
    ulimits:
      memlock:
        soft: -1
        hard: -1
  tinyproxy:
    container_name: tinyproxy
    image: vimagick/tinyproxy
    restart: unless-stopped
    depends_on:
      - vpn
    network_mode: "service:vpn" #Binds this container to the VPN container network, the ports are exposed in that parent
  rdtc:
    container_name: rdtc
    image: rogerfar/rdtclient
    restart: unless-stopped
    environment:
      TZ: Europe/London
      http_proxy: http://x.x.x.x:8888 #Host IP:port for proxy, in this case, the other container on the same host
      https_proxy: http://x.x.x.x:8888 #Host IP:port for proxy
    volumes:
      - /data/media/downloads:/data/downloads
      - /opt/docker/vpn/rdtc:/data/db
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - "6500:6500"
    network_mode: bridge
 ```
 
 The VPN container applies iptables firewall rules to block all network access except for the VPN tunnel. the NETWORK env variable adds an exception for the LAN networks so you can access the tinyproy ports or other ports that may be attached to the container network. This tops traffic leaking when the VPN is down.
 
 Example tinyproxy log with a test download:
 
 ```
 INFO      Feb 08 15:22:07 [1]: Starting main loop. Accepting connections.
CONNECT   Feb 08 15:28:18 [10]: Connect (file descriptor 9): 172.17.0.1 [172.17.0.1]
CONNECT   Feb 08 15:28:18 [10]: Request (file descriptor 9): CONNECT api.real-debrid.com:443 HTTP/1.1
INFO      Feb 08 15:28:18 [10]: No upstream proxy for api.real-debrid.com
INFO      Feb 08 15:28:18 [10]: opensock: opening connection to api.real-debrid.com:443
INFO      Feb 08 15:28:18 [10]: opensock: getaddrinfo returned for api.real-debrid.com:443
CONNECT   Feb 08 15:28:18 [10]: Established connection to host "api.real-debrid.com" using file descriptor 10.
INFO      Feb 08 15:28:18 [10]: Not sending client headers to remote machine
INFO      Feb 08 15:28:23 [10]: Closed connection between local client (fd:9) and remote client (fd:10)
CONNECT   Feb 08 15:28:27 [14]: Connect (file descriptor 9): 172.17.0.1 [172.17.0.1]
CONNECT   Feb 08 15:28:27 [14]: Request (file descriptor 9): CONNECT 34.download.real-debrid.com:443 HTTP/1.1
INFO      Feb 08 15:28:27 [14]: No upstream proxy for 34.download.real-debrid.com
INFO      Feb 08 15:28:27 [14]: opensock: opening connection to 34.download.real-debrid.com:443
INFO      Feb 08 15:28:27 [14]: opensock: getaddrinfo returned for 34.download.real-debrid.com:443
CONNECT   Feb 08 15:28:27 [14]: Established connection to host "34.download.real-debrid.com" using file descriptor 10.
INFO      Feb 08 15:28:27 [14]: Not sending client headers to remote machine
INFO      Feb 08 15:28:27 [14]: Closed connection between local client (fd:9) and remote client (fd:10)
CONNECT   Feb 08 15:28:27 [10]: Connect (file descriptor 9): 172.17.0.1 [172.17.0.1]
CONNECT   Feb 08 15:28:27 [10]: Request (file descriptor 9): CONNECT 34.download.real-debrid.com:443 HTTP/1.1
INFO      Feb 08 15:28:27 [10]: No upstream proxy for 34.download.real-debrid.com
INFO      Feb 08 15:28:27 [10]: opensock: opening connection to 34.download.real-debrid.com:443
INFO      Feb 08 15:28:27 [10]: opensock: getaddrinfo returned for 34.download.real-debrid.com:443
CONNECT   Feb 08 15:28:27 [10]: Established connection to host "34.download.real-debrid.com" using file descriptor 10.
INFO      Feb 08 15:28:27 [10]: Not sending client headers to remote machine
```

**Comment by rogerfar** [comment]
@timcoop3r can you try the new proxy setting for the multi downloader?

**Comment by timcoop3r** [comment]
@rogerfar Can't see it hitting the web proxy but also can't see much in the logs to see why it's failing.

**Comment by rogerfar** [comment]
For now I'm going to close this, if anyone still wants to tinker with it, by my guest :)
