### ISSUE TITLE
I'm having trouble updating rdt-client on Docker

### ISSUE THREAD

**Issue by Bulletbling** [rogerfar/rdt-client#201]
Hello, I noticed my rdt-client was out of date on Docker so I used the pull command, which I presume updates it. However, it now gives me a second image, rather than updating the current one:

![image](https://user-images.githubusercontent.com/46613939/208729072-819c6d66-e60a-4b3f-b4e4-6b23766b3cfa.png)

When I run the new image, it has a random container that appears, rather than what it normally looks like here:

![image](https://user-images.githubusercontent.com/46613939/208728211-597d70b1-e08f-4c37-856e-e42d7ab5493d.png)

The random container that gets made doesn't say rdt-client anywhere and the three dots/settings button doesn't give an option to "open with browser". I barely figured out how to get this thing running and was hoping such an update would be simple, but there are no instructions on updating and I'm certainly not an expert on this, although I am with computers in general. Here's what it looks like when I run this new image:

![image](https://user-images.githubusercontent.com/46613939/208729292-7f34e965-5dbd-48c9-8ebd-df6f6c7f36b3.png)

Any advice on getting this updated?

**Comment by themegaphoenix** [comment]
It seems that you are running a `docker compose`. If so, just go where your docker compose file is and run the following commands:

`docker compose stop`
`docker compose pull`
`docker compose up -d`

This will update the images.

**Comment by Bulletbling** [comment]
> It seems that you are running a `docker compose`. If so, just go where your docker compose file is and run the following commands:
> 
> `docker compose stop` `docker compose pull` `docker compose up -d`
> 
> This will update the images.

This info is certainly appreciated. 

Since it's been awhile, would I simply open an elevated command prompt and CD to this location and then run these commands, or is it somewhere else? I apologize for my lack of knowledge with this software. It's very confusing to me, which is weird because I'm a computer guy myself.

**Comment by deepdivered** [comment]
I am also have trouble with pulling from docker hub. It seems it's out of date and does not have the latest build. 2.0.19 is the newest version and it looks like on got your at 2.0.21 or higher now.

https://hub.docker.com/r/rogerfar/rdtclient/tags

**Comment by ikrowni** [comment]
Same problem for me as well. Im also getting this on my synology NAS

`ERROR: manifest for rogerfar/rdtclient:latest not found: manifest unknown: manifest unknown`

**Comment by rogerfar** [comment]
2.0.25 is now published. If you still experience the same issues, please keep it central in https://github.com/rogerfar/rdt-client/issues/214.
