### ISSUE TITLE
Maximum restructuring depth reached

### ISSUE THREAD

**Issue by Muneer91** [rogerfar/rdt-client#202]
**What version are you using?**
2.0.19
**Wat OS are you running?**
Raspbian - 11 bullseye
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**
[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/10395652/_rdtclient_logs.txt)

Errors with various torrents. Requires reboot of rdtclient or raspberry pi to stop but then reoccurs after a short while

Client status shows torrent finished, waiting for download links but real debrid shows complete.

**Comment by Muneer91** [comment]
Debug level logs here

**Comment by rogerfar** [comment]
I removed a possible culprit in the next version, if you still see this happen let me know.
