### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by dyl4n20** [rogerfar/rdt-client#204]
**What version are you using?**
latest version
**Wat OS are you running?**
windows 10
**Are you using Docker or as a service?**
service
**Please attach a log file here with the log setting set to debug**
im not sure how to do this.

Hello, I am trying to run on windows and when clicking the .exe it closes immediately, and I cannot get the webpage to load. 
what am I doing wrong here?

my appsettings.json lloks like this

---
{
  "Logging": {
    "File": {
      "Path": "C:\\rdtclient\\db\\rdtclient.log",
      "FileSizeLimitBytes": 5242880,
      "MaxRollingFiles": 5
    }
  },
  "Database": {
    "Path": "C:\\rdtclient\\log\\rdtclient.db"
  },
  "Port": "6500"

---

**Comment by themegaphoenix** [comment]
What is in the log file?

**Comment by redvegas** [comment]
> What is in the log file?

Where can I find the log?
I tried installing on a different windows 10 laptop I have and same issue.

**Comment by dyl4n20** [comment]
i have solved the issue. i mustve not had the correct .net installed i installed the hosting bundles one and it worked right away becore i had only chosose x64

**Comment by rogerfar** [comment]
Just curious did you use this instruction from the readme?

```
Make sure you have the ASP.NET Core Runtime 6 installed: https://dotnet.microsoft.com/download/dotnet/6.0
```
Did installing only the runtime not work? The hosting bundle is design if you want to use IIS, so you shouldn't need it.

**Comment by redvegas** [comment]
> Just curious did you use this instruction from the readme?
> 
> ```
> Make sure you have the ASP.NET Core Runtime 6 installed: https://dotnet.microsoft.com/download/dotnet/6.0
> ```
> 
> Did installing only the runtime not work? The hosting bundle is design if you want to use IIS, so you shouldn't need it.

Yeah when I installed just the x64 on two windows PC it did not work, after installing the hosting bundle I had it working immediately. Not sure what could be happening here, I’m just glad I’ve got it working. 
Just want to say great work amazing project! Now that I’ve got it working it does an amazing job and it’s exactly what I was looking for! Thank you for your release.

**Comment by rushtothesun** [comment]
@rogerfar 
I also had to download the hosting bundle to get rdt-client to work. You should include this in the readme.
