### ISSUE TITLE
RdtClient stopped working (can't seem to connect to real-debrid)

### ISSUE THREAD

**Issue by bennewman91** [rogerfar/rdt-client#205]
**What version are you using?**
2.0.18 and 2.0.19 (same behavior)
**Wat OS are you running?**
Ubuntu 22.10 Linux 5.19.0-29-generic x86-64
**Are you using Docker or as a service?**
docker
**Please attach a log file here with the log setting set to debug**
[rdtclient-debug-log.txt](https://github.com/rogerfar/rdt-client/files/10699849/rdtclient-debug-log.txt)
Log represents starting rdt-client, opening UI, logging in, waiting about 30 seconds, then clicking add torrent, specifying a torrent file, then waiting for it to stop spinning and indicate error (A task was cancelled).

Background:
I have been running rdt-client docker container on this machine without any issues for some time.  My real-debrid premium expired and I made one change in my environment and rdt-client stopped working (obviously with the expired premium, it would be expected to not work).  I reactivated premium.  No joy.  The info in the upper left indicating a premium account never appears.

The thing that changed in my environment, is that I change the firewall/gateway software (from untangle to opnsense).  While most of the environment remains the same (from a network topology perspective), this change allowed me to move the VPN connection (NordVPN) from the host machine to the firewall/gateway.

No other software on the system is having any issues (Plex server, etc.)

Here are things I have tried to try to pinpoint the problem:
1) Installed hyperbunny77's RealDebridManager in docker on same machine.  It connects to real-debrid without issue.  Able to specify torrent. I could see the torrent and download file available on Read-Debrid site.  (it didn't download though the software indicated that it had submitted it to aria, but I didn't spend any time trying to resolve that).

2) Started an AllDebrid trial.  Changed rdt-client settings to use AllDebrid, and that worked (insofar as it was able to connect, show premium status, and issue torrents to download.  Some torrents did download, but while all were found, many failed to download automatically.  Never used AllDebrid before, so not sure what was happening here...  I was able to manually download the files directly).  But clearly rdt-client was able to communicate with and issue commands to AllDebrid.

3) I've completely wiped out containers and images and reinstalled 2.0.18 and 2.0.19 multiple times all with the same behavior.

Any clue?

**Comment by rogerfar** [comment]
It seems that RealDebrid is returning some sort of error but is not bubbling up properly, but because the left top doesn't show your username, I think it might be a firewall issue that is blocking traffic to Real Debrid.

It's odd that it doesn't block traffic to AllDebrid though.

**Comment by bennewman91** [comment]
I immediately suspected the firewall,  but i tried realdebridmanager and it
is working...  same machine.

**Comment by rogerfar** [comment]
Did you manage to find out something more? The last line of the log is suspicious: 
```
2023-02-09 11:14:57.033 -06:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
```
This indicates that the services is actually being shutdown. Are you running docker?

**Comment by bennewman91** [comment]
Hi Roger,

Sorry for not responding sooner.   I have been traveling a lot recently.
 I left it for several days,  and when I returned it just started working.
 Nothing had changed.   It has not been used extensively,  but it is
working.   Chalk it up to bad state somewhere in the system.   I am one
version behind currently because that is just where it was when I last left
it,  and I have been reluctant to change anything,  but when I get some
time I'll update to latest version.  I'm sure it will just be working.
 Sorry for the fire drill.

Ben

**Comment by rogerfar** [comment]
Alright thanks for following up, if it happens again feel free to reach out again!
