### ISSUE TITLE
Update on linux

### ISSUE THREAD

**Issue by OptimusGREEN** [rogerfar/rdt-client#206]
**What version are you using?**
2.0.17

**Wat OS are you running?**
linux

**Are you using Docker or as a service?**
service

**Please attach a log file here with the log setting set to debug**
na

Hi, how do i update this on linux without wiping out my settings/db?

thanks.

**Comment by rogerfar** [comment]
As long as you backup or don't overwrite your rdtclient.db file all your settings and torrents will be persisted.

**Comment by OptimusGREEN** [comment]
Ok thanks, every thing else from the zip should be copied over?

**Comment by rogerfar** [comment]
Yes, the rest can be copied over.
