### ISSUE TITLE
Download via aria2

### ISSUE THREAD

**Issue by mareczek82** [rogerfar/rdt-client#207]
**What version are you using?**
2.0.19

**Wat OS are you running?**
Ubuntu 22
**Are you using Docker or as a service?**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/10833866/rdtclient.log)

yes
**Please attach a log file here with the log setting set to debug**
attached log

Hi,
its my second try to use RDT-C. 
I have same issue: simple downloader crashes during download and when i try use aria2 i have error 18 
In settings after aria test i have :Found Aria2 client version 1.36.0 

Both apps are in separate docker but with shared network. 
I made test when using local (LAN) IP and after setting same docker network with docker IP with same result: error 18. 
When I copy link from RDT-C manually to aria it downloads it without any problems. 

Sorry if something is unclear, i'm very bad ad IT and english is my second language.

**Comment by rogerfar** [comment]
The error in the log is `Error 1: Unauthorized`. Make sure the Aria2c password is the same in the config file and in the RDT settings page.
