### ISSUE TITLE
Download Speed Throttled

### ISSUE THREAD

**Issue by ddpruel** [rogerfar/rdt-client#209]
I have 1.5Gbit internet, and can download at high speeds directly from the real debrid website. For some reason when I use rdt-client my max speed will be somewhere around 8MB/sec, cumulative between all current downloads. This occurs both with the multi downloader as well as aria2c. 

From what I can tell I don't have a bandwidth limit set (max parallel connections of 8, download speed set to 0 / unlimited).

On a side note this is an incredible tool! Appreciate all your work on this project.

**Comment by rogerfar** [comment]
Unfortunately I have the same issue, using Aria2c, and pretty much always capped at 8MB/s. Even when using 2 downloads it would just half the speed.

You can try and see if AllDebrid makes a difference, but I think it's a RealDebrid limitation: https://real-debrid.com/speedtest gives me only 8-9MB/s too.

**Comment by ddpruel** [comment]
Thanks for getting back! Very weird, that speed test link gives me 40MB/s single and 140MB/s multi. 
I'll give Alldebrid a try.

**Comment by rogerfar** [comment]
I released a new version that now uses a new downloader. I did some testing with it because I was also using Aria2c. It seems quite a bit faster, I can now download with a good 30MB/s / 300Mbit.

**Comment by timcoop3r** [comment]
Fwiw, I have had no issues using aria2c to get 35MB/sec from RealDebrid.

I can get this with the new internal downloaded as well but at the cost of 3.5x increase in CPU usage.

Aria2c is still by far the fastest and most efficient way to download with rdt-client but the new downloaded is a nice simplicity win.

These results are from a Nanopi R5S running dietpi. rdt-client is in docker and aria2c is running on the base system outside of docker (inside docker the CPU overhead for aria2c is massive and does impact speeds so I do not recommend that either)

**Comment by ddpruel** [comment]
On the new version I'm getting close to 50MB/sec with the internal downloader, but still limited to 8 with Aria2c. Luckily CPU usage is less of a problem since I'm using my desktop.

**Comment by rogerfar** [comment]
I swapped the internal downloader again for an updated version of the original internal downloader, the other one is just not very reliable. I'm getting good speeds and low memory/cpu usage, but that's on Windows, curious if it holds up in Docker / linux.

**Comment by ctriaan** [comment]
> I swapped the internal downloader again for an updated version of the original internal downloader, the other one is just not very reliable. I'm getting good speeds and low memory/cpu usage, but that's on Windows, curious if it holds up in Docker / linux.

I can confirm that I'm also getting really good performance with 2.0.26 using docker-compose on Ubuntu Server.

**Comment by timcoop3r** [comment]
Running on my quad-core Arm A55 machine (Nanopi R5S) inside docker, speeds are still pretty terrible. 4MB/s and maxing out 3 threads/cores. (vs 35MB/sec on a single core with Aria2c running outside of docker).

I’ll have an x86 machine to test with in a few days to compare there also but this is still similar to when I was running x86 before. 35MB/s is the limit of my broadband though for now and is the bottleneck for the aria2 setup.

**Comment by gaston-arg** [comment]
I was getting my usual max speed connection on Real Debrid Client at 50mb/s, but now I'm getting around 10mb/s. I tried just in case with my qBittorrent client on my server, and it's working fine around 49 or 55mb/s.

Using the latest version by the way 2.0.26 via Docker.

**Comment by Bulletbling** [comment]
I used to get 18MBps before, but now I am getting 747Bps after the latest update. I found that there is a docker problem, at least on Windows 11, that after around version 4.9, my download speeds were cut from 40MBps to just 18MBps, but this latest update has made the speed test perform very poorly. So not only is Docker causing a download speed issue after v4.9'ish, but this seems to have made the problem much worse for me at least.

**Comment by timcoop3r** [comment]
Just an update from my earlier ARM A55 based comparison, I am now back on x86. i3-7130U.

I can now max out my 300Mbit connection (35MB/sec) on both Aria2c outside docker, as well as the internal downloader inside docker container. However, the internal downloader runs at 10-11x the CPU usage of aria2c. 5% CPU vs 58% CPU.

I personally would still strongly recommend for best performance that people use the aria2c option on the base system outside of a docker container as the download client

**Comment by richard-lee-863** [comment]
Currently getting the following from RealDebrid speed test:
600Mbps / 74MB/s
My max should be aprox 900Mbps, so that makes sense. 

However download speed is very poor in RDT-Client using internal downloader.
About 2MB/s overall on a good day. 
Have tried various implementations of 
 - Maximum Parallel Downloads
 - Download Speed
 - Parallel connections per download

Will try get an Aria2 docker image going next, but am curious to know what people think the best options for Internal Downloader are.

**Comment by gaston-arg** [comment]
I "solved" the speed issue by using version 2.0.19
No problems at all with that one.

Cheers

**Comment by timcoop3r** [comment]
> Currently getting the following from RealDebrid speed test: 600Mbps / 74MB/s My max should be aprox 900Mbps, so that makes sense.
> 
> However download speed is very poor in RDT-Client using internal downloader on v2.0.30 as a Docker container. About 2MB/s overall on a good day. Have tried various implementations of
> 
> * Maximum Parallel Downloads
> * Download Speed
> * Parallel connections per download
> 
> Will try get an Aria2 docker image going next, but am curious to know what people think the best options for Internal Downloader are.

I would personally consider the internal downloader a convenience rather than something optimal

If you care about best performance use aria2 on the base system and not inside a container. Especially on low power systems like RPI or other ARM based platforms

**Comment by richard-lee-863** [comment]
Wow version 2.0.19 is significantly better, getting 220Mbps across 4 downloads now. Thanks!
I have started looking at Aria2 after all this reading, but the download for windows didn't seem to install so parked it for a bit. Happy with the convenient option if i can get reasonable speeds from it.

**Comment by richard-lee-863** [comment]
Playing around with Aria2 now, will see how it goes when utilized on base system for comparison. 
It does seem to peak higher, saw > 550Mbps at some stage. But it is less consistent than the simple downloader (at version 2.0.19).
Will try have another go at it tomorrow with latest version of rdt-client and Aria2.

**Comment by digitalbarrito** [comment]
> I "solved" the speed issue by using version 2.0.19 No problems at all with that one.
> 
> Cheers



> Wow version 2.0.19 is significantly better, getting 220Mbps across 4 downloads now. Thanks! I have started looking at Aria2 after all this reading, but the download for windows didn't seem to install so parked it for a bit. Happy with the convenient option if i can get reasonable speeds from it.

Okay, WOW! Holy hot diggity dang, downgraded my setup to v2.0.19, using the simple downloader option, am now able to get a maximum of around 96MB/s up from around 35MB/s on versions past v2.0.19. This is on my Pi CM4 running in a docker-like environment with an almost 1Gig connection, so I call this a _**win**_

**Comment by rogerfar** [comment]
Lets keep this central in this topic: https://github.com/rogerfar/rdt-client/issues/296
