### ISSUE TITLE
Feature Request: Reverse Proxy Support

### ISSUE THREAD

**Issue by timcoop3r** [rogerfar/rdt-client#21]
I have radarr/sonarr etc running behind an nginx reverse proxy to simplify TLS configuration and urls for accessing the apps running on various custom ports.

As best as I can tell rdt-client currently doesn't support this as when configured in the same way just returns a blank page?

Example nginx code block:
    location /rdt-client/ {
       proxy_pass               http://x.x.x.x:6500;
       proxy_http_version       1.1;
       proxy_set_header         Host                    $host;
       proxy_set_header         Upgrade                 $http_upgrade;
       proxy_set_header         Connection              $http_connection;
       proxy_set_header         X-Real-IP               $remote_addr;
       proxy_set_header         X-Forwarded-For         $proxy_add_x_forwarded_for;
    }

**Comment by rogerfar** [comment]
This should be possible, I have a reverse proxy, but through IIS setup:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Let's Encrypt" enabled="true" stopProcessing="true">
                    <match url="(.well-known/acme-challenge/*)" />
                    <action type="None" />
                </rule>
				<rule name="Redirect to HTTPS" enabled="true" patternSyntax="Wildcard" stopProcessing="true">
					<match url="*" ignoreCase="true" negate="false" />
					<conditions logicalGrouping="MatchAny" trackAllCaptures="false">
						<add input="{HTTPS}" ignoreCase="true" matchType="Pattern" negate="false" pattern="OFF" />
					</conditions>
					<action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" appendQueryString="false" redirectType="Permanent" />
				</rule>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://192.168.10.2:6500/{R:0}" />
                    <serverVariables>
                        <set name="HTTP_SEC_WEBSOCKET_EXTENSIONS" value="" />
                    </serverVariables>
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

**Comment by timcoop3r** [comment]
Ah, I think the issue is when not using the base url of '/'. 

e.g. http://www.example.com/ works, but http://www.example.com/rdt-client/ does not. 

There maybe be a way to fix this in the reverse proxy re-write now I know whats going on. I think I am just used to the *arr apps having the 'base url' option that can be set for where the application listens to support a reverse proxy with this type of config when requests hit the server with /whatever appended onto the http request.

I'll investigate if there is a way to re-write the proxied request to solve this.

**Comment by taschmidt** [comment]
@Oorweeg did you ever get this working?

UPDATE: I think I got it working:
```
    redir /rdtclient /rdtclient/
    handle_path /rdtclient/* {
		replace "<base href=\"/\">" "<base href=\"/rdtclient/\">" {
			match {
				header Content-Type text/html*
			}
		}
        reverse_proxy rdtclient:6500 {
            header_up Accept-Encoding identity
            header_up X-Forwarded-Prefix /rdtclient
        }
    }
```

**Comment by Oorweeg** [comment]
@taschmidt I have this working with the following Caddy config

```
example.com {
    redir /rdtc /rdtc/
    
    handle_path /rdtc/* {
        reverse_proxy localhost:6500
    }
}

```

and docker compose just have the BASE_PATH environment variable. 

```BASE_PATH: /rdtc/```

In my case I am also using ```network_mode: host``` but I expect that shouldn't make any difference in your case and I probably have that out of laziness more than any specific other reason 😆

**Comment by taschmidt** [comment]
Ahh, I didn't know about the `BASE_PATH` variable! Is that documented somewhere?

Thanks @Oorweeg !

**Comment by Oorweeg** [comment]
Had to hunt for it in the docs, finally found it mentioned here: https://github.com/rogerfar/rdt-client#running-within-a-folder
