### ISSUE TITLE
Simple downloader in v2.0.19 was significantly faster with realdebrid than the new internal downlaoder

### ISSUE THREAD

**Issue by privatize0965** [rogerfar/rdt-client#216]
With the old simple downloader I'd get about 1GB/s in download speed and sometimes, depending on rdb servers I guess, even 1,5GB/s.

With ne new internal downloader I'm only getting 500MB/s at a max. No matter how many parallel connections and chunks are set.

I tried to reacreate the simple downoaders behavior by setting chunks and connection both to 1, but that didn't help at all.
Also tried many different combinations, but as I said, download speed are never going anywhere over 500MB/s with this. Same thing for Aria2c. That's why I've always used simple downloader. It just worked the best.

Is there anything I'm missing? How exactly did the simple downloader work that made speeds differ so much?

This is also not just bad timing or currently struggling servers. Downgrading to v2.0.19 and simple downloader immediately gets me those speeds again.

**What version are you using?**
v2.0.22 

**Wat OS are you running?**
Ubuntu 22.04.2 LTS

**Comment by rogerfar** [comment]
If you put Parallel connections and Parallel chunks to 0, then it should behave as the old downloader. Straight do disk.

I made a small test app here, you will need the .NET6 runtime to run it:
[net6.0.zip](https://github.com/rogerfar/rdt-client/files/10951286/net6.0.zip)

You can change the appsettings.json to mess with the settings and DownloadList.json to add or change download paths.

If I run it with the default settings (no parallel) it gives me about 35MB/s which is also the max on my internet connection.

**Comment by privatize0965** [comment]
I have to run this on the Linux terminal. So No gui. Would you be able to provide a version of this without windows specific functions that also works in a  console?
 
```
System.NotSupportedException: Task bar progress only works on Windows
	at ShellProgressBar.ProgressBarOptions.set_EnableTaskBarProgress(Boolean value)
	at Downloader.Sample.Program.Initial() in C:\Users\Roger\Downloads\Downloader-master\src\Samples\Downloader.Sample\Program.cs:line 55
	at Downloader.Sample.Program.Main() in C:\Users\Roger\Downloads\Downloader-master\src\Samples\Downloader.Sample\Program.cs:line 36
END
```

**Comment by jagvirdehal** [comment]
@privatize0965 you could access the web portal with an SSH tunnel in PuTTY. Just create a local tunnel with port 6500 and you should be able to access it

**Comment by privatize0965** [comment]
> @privatize0965 you could access the web portal with an SSH tunnel in PuTTY. Just create a local tunnel with port 6500 and you should be able to access it

I was talking about the testing tool @rogerfar has posted in the reply above, not rdt-client itself.
There is no webinterface. It's just a small commandline utility, which uses a feature that is window only, so I can't run that to test the different settings, which is the whole purpose of the tool. I don't have a windows desktop, which wouldn't be useful anyway for my testing purposes, but much less do I have a windows server.

**Comment by privatize0965** [comment]
So I just tried settings parallel connections and chunks to 0. With those settings, I'm getting ~150MB/s  only. 
I'm getting about 3x that, by settings it to 4/4, but thats still far from the speed I'm getting with the old simple downloader, wich still downloads with over 1GB/s. Just tried both versions again.

**Comment by rogerfar** [comment]
I made a new test app, the other one was from the Downloader itself, this one has both the new Downloader and the old one.
[Downloadtest.zip](https://github.com/rogerfar/rdt-client/files/10952653/Downloadtest.zip)

There might be 1 explanation, the old downloader from 2.0.19 and before wasn't very well reporting speeds back, as the throttle part wasn't working either very well, there could very well be a calculation/display error.

**Comment by privatize0965** [comment]
Thanks. I'll test this when I find some time and give you some feedback.

**Comment by ddpruel** [comment]
I just downgraded to 2.0.19 and tried the simple downloader for the first time. I also find that I am getting speeds far higher than any other method.

**Comment by rogerfar** [comment]
@privatize0965 thanks for testing that. I think it might be an issue of Downloader using still the old obsolete and deprecated `WebClient` instead of `HttpClient`. I will do some research and see if there is a better downloader out there.

**Comment by rogerfar** [comment]
I have created a new downloader from scratch that should be a lot better than the current options, supports bandwidth throttling and multiple threads too.

I create an update to the test app, if anyone wants to test out the 3 different downloaders that would be appreciated.
[DownloadTest.zip](https://github.com/rogerfar/rdt-client/files/11035427/DownloadTest.zip)

**Comment by sylvaindd** [comment]
> I have created a new downloader from scratch that should be a lot better than the current options, supports bandwidth throttling and multiple threads too.
> 
> I create an update to the test app, if anyone wants to test out the 3 different downloaders that would be appreciated. [DownloadTest.zip](https://github.com/rogerfar/rdt-client/files/11035427/DownloadTest.zip)

Hi, could you please publish the version on Docker Hub with a custom tag so we can test ?
I just tried 2.0.26 too, i get 5-50Mpbs, with 2.0.19 I get 500-1000Mbps

**Comment by ctriaan** [comment]
2.0.26 works perfectly for me, maxing out my 200Mbps line.

Also, the whole process is really fast - unpacking, uploading into Sonarr, etc.

**Comment by ddpruel** [comment]
I'm unfortunately still experiencing significantly slower speeds than 2.0.19. 
80MB/s on the old version vs 3MB/s on the latest, even when playing with parallel download settings.

**Comment by ctriaan** [comment]
@ddpruel , my settings below.
General
Maximum parallel downloads 3
Maximum unpack processes 3

Download client
Download speed (in MB/s) (only used for the Internal Downloader) 0
Parallel connections per download (only used for the Internal Downloader) 0

I noticed that, when I tried 3 Parallel connections per download, the speed shown was 1/3 of the real download speed reported by my router.

**Comment by sylvaindd** [comment]
I think last release fixed it for me.
I'd even say it's now faster than in 2.0.19.

Note that it's now in MB/s (I had it in Mbps in .19), it averages around 80-90MB/s which is what I'd expect.

Thanks !
