### ISSUE TITLE
Hardlink with Sonarr on Unraid?

### ISSUE THREAD

**Issue by BlackMamba248** [rogerfar/rdt-client#220]
New to unaid and linux in general so its been a crazy few days trying to learn it and troubleshoot during setup. I apologize if my experience below is incorrect or doesn't make sense for trying to get rdt-client to setup with sonarr and maintain hardlinks.

I have been trying the last few days to get rdt-client to work on unraid with sonarr but facing issues with permissions for the created folder containing the file and the file itself. This lead to errors from sonarr about not being able to access the path and import/rename it. Manually assigning the folder/file the nobody user permission after it finished downloading eventually triggers the import to work but the file in the download location is automatically deleted after it is in the intended destination folder.

I was wondering if this is the intended outcome when rdt-client is working fully with correct permissions? I was curious because I have hardlinks setup for qbittorent right now and I was thinking that rdt-client should be able to produce files that can be hardlink. However, I thought that the folder/file would remain also in the original downloads location and eventually have to be deleted after hardlink allowed atomic move to happen?

**Comment by rogerfar** [comment]
Similar issue to https://github.com/rogerfar/rdt-client/issues/214, should be fixed in 2.0.23
