### ISSUE TITLE
Error during powershell update script in windows.

### ISSUE THREAD

**Issue by xsleepejelly** [rogerfar/rdt-client#222]
When running the powershell update script, it gives this move error.

"Move-Item: Cannot create a file when that file already exists."

**Comment by rogerfar** [comment]
Could be a failed update at one point perhaps. In the output it should tell you a temp path it uses, delete that path and try again.

**Comment by xsleepejelly** [comment]
Tried that and it did not work. Found this stackoverflow when googling the error.

https://stackoverflow.com/questions/43547874/move-item-causes-file-already-exists-error-despite-folder-having-been-deleted

I was able to run the update script successfully if I ended the windows service, deleting all the folder contents except the script and appsettings.json file.
