### ISSUE TITLE
v2.0.24 won't start

### ISSUE THREAD

**Issue by MagmaMDK** [rogerfar/rdt-client#226]
Edit: sorry duplicate topic with https://github.com/rogerfar/rdt-client/issues/225#issue-1627983581

I have updated from version 2.0.22 to 2.0.24
Running on Docker (with Synology DSM7).

RDT container fail to start ( no log on rdt side)

Here is the docker log:

s6-rc-compile: fatal: cyclic service dependency reached from legacy-services and involving legacy-services

**Comment by themegaphoenix** [comment]
same issue

**Comment by Micsters** [comment]
They are aware of the issue and working on it. Best to follow Issue #214

**Comment by MagmaMDK** [comment]
samr issue as https://github.com/rogerfar/rdt-client/issues/214
