### ISSUE TITLE
s6-rc-compile: fatal: cyclic service dependency reached from legacy-services and involving legacy-services

### ISSUE THREAD

**Issue by KINGLIFER** [rogerfar/rdt-client#227]
**What version are you using?**
latest

**Wat OS are you running?**
DSM

**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**

If there is a fix I would like to know where to go and what to do. I saw someone say reset permissions and I did that for the docker folder and still nothing.

**Comment by Micsters** [comment]
Please close this and see Issue #214

**Comment by KINGLIFER** [comment]
Can you reach out to me because that fix (re downloading or permissions) is not working for me. If I overlooked something I do apologize.

**Comment by Micsters** [comment]
@KINGLIFER Email me and Ill try to help ya out -- mjk770 at gmail
