### ISSUE TITLE
Docker: There is not enough space on the disk '/'

### ISSUE THREAD

**Issue by timcoop3r** [rogerfar/rdt-client#23]
When using the multi-part downloader I get the error 'There is not enough space on the disk '/'. Despite having the temp storage path set to the same external volume as the main download location.

This seems to have started when switching to the simple downloader and back again.

**Comment by rogerfar** [comment]
Is this with any download or only very large ones?

**Comment by timcoop3r** [comment]
This was with any download. In the end restarting the container resolved it. I haven't tried switching back and forth again that much to try and break it again since, but seems worst case a restart can resolve. :)

**Comment by rogerfar** [comment]
Ok let me know if you can reliably reproduce it, on the top of my head I can't think of a way why this would report low disk space.
