### ISSUE TITLE
no 2.0.25 docker file

### ISSUE THREAD

**Issue by pbranly** [rogerfar/rdt-client#230]
Hi 
I cant find the docker file for version 2.0.25
phil

**Comment by Muneer91** [comment]
Same, latest tag doesn't exist on hub.docker.com last version is 2.0.19

**Comment by techionltd** [comment]
same here, can't deploy with or without :latest tag. Reverted back to 2.0.20

**Comment by rogerfar** [comment]
2.0.25 is now published. If you still experience the same issues, please keep it central in #214.
