### ISSUE TITLE
Something broke after 2.0.25 update

### ISSUE THREAD

**Issue by ikrowni** [rogerfar/rdt-client#234]
**What version are you using?**
2.0.19 to 2.0.25
**Wat OS are you running?**
Docker on Synology NAS
**Are you using Docker or as a service?**
no
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/11047651/rdtclient.log)
[radarr.txt](https://github.com/rogerfar/rdt-client/files/11047660/radarr.txt)

Updated from 2.0.19 to 2.0.25 and now Radarr and Sonarr both give me the error "failed to connect to qBitorrent, check your settings"
When I check my settings in the download section of Radarr and Sonarr I click test and I get the green checkmark as if everything is fine. Thanks for taking a look into it.

**Comment by ctriaan** [comment]
@ikrowni same here, but it's not an rdt-client problem.

It looks like the Real-Debrid api SSL certificate expired. 

Lots of people are complaining on reddit.
