### ISSUE TITLE
2.0.25 breaks support for arm 32 bits (armhf)

### ISSUE THREAD

**Issue by Edouard-chin** [rogerfar/rdt-client#235]
Hello, thanks again for this great tool ❤️ .

I'm using this application on a Raspberry Pi 4 with the vanilla Raspberry PI os (32 bits).
Everything worked fine with RdtClient up to version 2.0.19.

I tried to upgrade to version 2.0.25 but the docker container can't start. This is the error

```
rdtclient       | Setting permissions
rdtclient       | Changing to /app folder
rdtclient       | Starting rtdclient
rdtclient       | Failed to load /app/libhostpolicy.so, error: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /app/libhostpolicy.so)
```

I saw this error was reported in https://github.com/rogerfar/rdt-client/issues/47 , but running the container in privileged mode (as re commended) didn't resolve the issue.

----

I'm seeing that RdtClient [switched from ubuntu to alpine](https://github.com/rogerfar/rdt-client/compare/v2.0.19...v2.0.25#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R48), but it seems dotnet isn't supported on armhf architecture https://pkgs.org/download/aspnetcore-runtime-6.0

Just wanted to know if this is an oversight or you stopped supporting arm 32 bits, just like [linuxserver did for its sonarr container](https://info.linuxserver.io/issues/2022-08-02-sonarr/)?

**Comment by rogerfar** [comment]
Honestly, I'm not sure. We're still building the same as before so I think it should still work, is it because we switched distro's or because it's .NET 6 that doesn't support it?

**Comment by Edouard-chin** [comment]
It's because we switched distro. The offical .net docs mention that it's up to the distro maintainers to support or not specific versions of .net (in that case alpine doesn't support .net 6.0 on arhmf).

If you are ok with that we should maybe tweak the dockerfile so that it doesn't try to pull an incompatible image.

**Comment by Edouard-chin** [comment]
Saw your comming in https://github.com/rogerfar/rdt-client/commit/4bea2f444f10a3624710e2bb98dcb0a181c735fb which addresses this issue. Ty!

**Comment by rogerfar** [comment]
Forgive my ignorance, but is it possible to run the pi on a 64bit OS nowadays?

**Comment by Edouard-chin** [comment]
Yep absolutely!
