### ISSUE TITLE
Request: build for Termux/Android using mono

### ISSUE THREAD

**Issue by aexarchos** [rogerfar/rdt-client#236]
https://www.mono-project.com/docs/about-mono/dotnet-integration/

https://github.com/Jackett/Jackett/releases/download/v0.20.3671/Jackett.Binaries.Mono.tar.gz

Jackett does that, for example, so now I can run it in using "tmux" via "mono --debug JacketConsole.exe" without having to use proot-distro to run dotnet... Cannot run dotnet outside of proot in Termux, but mono works fine, so building for Mono would be really cool 😊 thanks in advance.

Obviously I am not rooted, else things would be much easier ;)

PS: inside proot debian, and by installing dotnet 6.0 via the automated shell script from MS's site this works perfectly as a mock qbitttorrent web interface... I use it in conjunction with Jackett with an app called nzb360 on my phone.

**Comment by rogerfar** [comment]
Honestly, I doubt this would ever get any traction. If you want to make a PR then feel free, but I can't see the use case.
