### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by vavenCV** [rogerfar/rdt-client#237]
**What version are you using?**
2.0.25.0
**Wat OS are you running?**
docker on ubuntu 22.04 through Portainer

**Are you using Docker or as a service?**
docker

**Please attach a log file here with the log setting set to debug**
There is no real bug

The problem I currently have is that the rdtclient keeps using all my RAM and eventually crashes my computer. I had to limit the RAM usage using docker-compose version 3.x feature "limitations" but the containers would eat all 8Gb of RAM I let him use and just crashed with `[09:04:53 ERR] Unexpected error occurred in ProviderUpdater: Exception of type 'System.OutOfMemoryException' was thrown.`. 

This behaviour was not happening when I only had 4 Gb of RAM, now that i have 16Gb It keeps happening. So much so that I can't use the container.

One last thing, the container seems to store the whole downloaded files in RAM (the RAM usage is growing as the file is downloading).

**Comment by rogerfar** [comment]
The internal downloader that I used was still download to ram, even though it's not supposed to. It's just not very reliable. I swapped it for a newer one I wrote myself, that does write directly to disk and should be a lot better.

**Comment by profucius** [comment]
![RDT high ram usage](https://user-images.githubusercontent.com/18254607/229222040-f3cd5c42-da3e-42a2-b2ed-dba4a396bcc8.png)

I'm not sure this is only downloading, as I am seeing it spike while Extracting files from archives after download. 

@rogerfar Are you suggesting that we do not use "Internal Downloader" under Download Client, and rather use Aria2? If that is the case, a mention of warning on the settings page would be nice for anyone struggling with this issue.
