### ISSUE TITLE
Can't download anymore from alldebrid

### ISSUE THREAD

**Issue by athenard** [rogerfar/rdt-client#239]
Hi there ! 
Thank you for your great work.
I'm having an issue with 2.0.25, I can't download files anymore.

It stays on Torrent finished, waiting for download links
Then, deletes itself. 
Here are the corresponding logs : 
![image](https://user-images.githubusercontent.com/73397196/228670668-5bee2431-c7f1-40d9-9843-cd0a83092c14.png)
Thanks !

**Comment by rogerfar** [comment]
Please post full debug logs, this screenshot doesn't show any relevant info.

**Comment by Aris-Eng** [comment]
Same here, not sure if it is provider specific.
rdt-client v2.0.30 on Docker, through vpn(gluetun), was working fine for a few months. After latest update it keeps timing out for bigger files, but downloads files in the kB size range.
I haven't reverted to an older version to see if it fixes it, nor do I know how to create debug logs.

**Comment by Ace-Nanter** [comment]
Hey there. As I mentioned in issue #262, I had quite the same issue, and what I did was to put a very high timeout (in my case I had to go up to 30s) for the download client. So far I don't have issues anymore with alldebrid.

I hope it will help you too guys!
