### ISSUE TITLE
Download speed limit

### ISSUE THREAD

**Issue by MGM03** [rogerfar/rdt-client#241]
**What version are you using?**
The issue is in v2.0.26, I reverted to v2.0.25 to fix the issue

**What OS are you running?**
OpenMediaVault (Debian)

**Are you using Docker or as a service?**
Docker

The issue with 2.0.26 is that the limiting does not take place. 
In v2.0.25 I can place a limit of 70MBps and it will run just above 73.2
In contrast in v2.0.26, the limit I set had zero effect and it was running at 900mbps (112.5MBps)

Thanks for all of your work, great bit of kit.

**Comment by rogerfar** [comment]
How do you have your downloader settings setup, what are the `Maximum parallel downloads` and `Parallel connections per download` set to?

At the moment each download has its own speed limit, so if you have `Maximum parallel downloads` set to 2, and `Download speed` set to 10MB/s, it will essentially limit your speed to 20MB/s.

**Comment by MGM03** [comment]
I have always run Maximum parallel downloads 1 
With parallel connections per download set to 0 (to disable)
I will try upgrading again just to test and see if for whatever reason these settings changed when it updated

**Comment by MGM03** [comment]
Yes. having upgraded again to v2.0.26 the issue shows itself again
I have included some screenshots of the settings panel in case its a fault on my end 
![1](https://user-images.githubusercontent.com/108984525/229863721-d3b31795-70d5-4a82-8447-7825693c3454.png)
![2](https://user-images.githubusercontent.com/108984525/229863726-621cc308-4c26-4b5a-9f28-6b0cb6cddcf6.png)
![3](https://user-images.githubusercontent.com/108984525/229863730-f90175d7-0400-4aa7-96b6-652bb575ccb0.png)

**Comment by rogerfar** [comment]
Can you check if 2.0.27 is reporting a better speed?

**Comment by MGM03** [comment]
Interestingly pulling the image with tag 2.0.27 and the latest both result in 2.0.26 being used (this is after deleting all the older images) which has the issue. I will try again in a little while to see if this issue revolves

**Comment by MGM03** [comment]
Having upgraded to v2.0.29 the issue is still present.
The network usage is confirmed within dashdot as using in excess of 900Mbps (112.5MBps) when the limit is set to 70MBps using settings identical to those shown in the previous screenshots.


P.S I apologize for the attached screenshots looking odd 
![1](https://user-images.githubusercontent.com/108984525/230795629-e99b4ac7-a04a-443d-b13e-8992763f01ca.png)
![2](https://user-images.githubusercontent.com/108984525/230795632-e9f4b3c0-d89e-4599-9ac3-af964a3288bd.png)

**Comment by rogerfar** [comment]
Can you try again in 2.0.30?

**Comment by MGM03** [comment]
2.0.30 fixed the issue,
Thanks for all the work!
