### ISSUE TITLE
Cannot start linux service - Failed executing DbCommand

### ISSUE THREAD

**Issue by OBXMan** [rogerfar/rdt-client#243]
I am attempting to install the application as a service in an Ubuntu LXC container running Linux 22.04
I think I successfully installed the ubuntu package for .net, though I confess I'm not sure how to check that.
Using the instructions, I unzipped the package to /opt/rdtc
The appsettings.json file reads as follows:
{
  "Logging": {
    "File": {
      "Path": "/opt/rdtc/rdtclient.log",
      "FileSizeLimitBytes": 5242880,
      "MaxRollingFiles": 5
    }
  },
  "Database": {
    "Path": "/opt/rdtc/rdtclient.db"
  },
  "Port": "6500"
}

When i input dotnet RdtClient.Web.dll the application appears to start fine (no errors reported) and I can access at IP:6500.  Appears to work fine though I did not test any downloads.

My /etc/systemd/system/rdtc.service file reads as follows:

[Unit]
Description=RdtClient Service

[Service]

WorkingDirectory=/opt/rdtc
ExecStart=/usr/bin/dotnet RdtClient.Web.dll
SyslogIdentifier=RdtClient
User=media

[Install]
WantedBy=multi-user.target

The only things I changed from the sample in the instructions was to add my path in the working directory and a user name.

When I start the service and check status I get the following output:
root@aar2:/opt/rdtc# systemctl status rdtc
* rdtc.service - RdtClient Service
     Loaded: loaded (/etc/systemd/system/rdtc.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2023-04-17 00:40:44 UTC; 7s ago
    Process: 4466 ExecStart=/usr/bin/dotnet RdtClient.Web.dll (code=exited, status=0/SUCCESS)
   Main PID: 4466 (code=exited, status=0/SUCCESS)
        CPU: 2.185s

Apr 17 00:40:43 aar2 RdtClient[4466]:    at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
Apr 17 00:40:43 aar2 RdtClient[4466]: [00:40:43 WRN] Starting host on version 2.0.30.0
Apr 17 00:40:44 aar2 RdtClient[4466]: [00:40:44 ERR] Failed executing DbCommand (17ms) [Parameters=[], CommandType='Text', CommandTimeout='30>
Apr 17 00:40:44 aar2 RdtClient[4466]: SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';
Apr 17 00:40:44 aar2 RdtClient[4466]: [00:40:44 ERR] BackgroundService failed
Apr 17 00:40:44 aar2 RdtClient[4466]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
Apr 17 00:40:44 aar2 RdtClient[4466]:    at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken>
Apr 17 00:40:44 aar2 RdtClient[4466]:    at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService bac>
Apr 17 00:40:44 aar2 systemd[1]: rdtc.service: Deactivated successfully.
Apr 17 00:40:44 aar2 systemd[1]: rdtc.service: Consumed 2.185s CPU time.
lines 1-17/17 (END)

Appears this has something to do with the database but I'm not smart enough to understand what is or is not happening.

Thank you.

**Comment by rogerfar** [comment]
Does the database have the correct permissions? Can the service write to the data path?
