### ISSUE TITLE
Speed seems throttled or limited some how after the last updates

### ISSUE THREAD

**Issue by gaston-arg** [rogerfar/rdt-client#244]
Hi there,

I seem to have an issue with RDT Client and download speeds after the last updates. Don't know exactly after which release I started having this issue, but there's definitely something going on with the speed at this point. I even had a speed upgrade from my ISP to 1gbit, but that didn't change anything, as I expected.

This happens both with qBittorrent or Aria as downloader.

When performing a speed test through the RDT Client interface for my Real Debrid account I get the following:

Download speed 19.02 MB/s

However, when running a "speedtest-cli --simple" command via the terminal, I get this:

Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Grupo MásMóvil (Madrid) [0.88 km]: 12.223 ms
Testing download speed....
Download: 98.78 Mbyte/s 

There's a considerable difference, and no matter what I do it seems to be throttled around 15 o 20 MB/s.

Any clues on what could I do?
I'm running RDT Client via Docker on a Raspberry Pi 4 server.

Thanks!

**Comment by gaston-arg** [comment]
When using latest version:
![RDT1](https://user-images.githubusercontent.com/24280746/233075924-d05fdad6-49c5-4ca4-8b0e-6638b02d553f.png)

When using for example 2.0.19:
![RDT2](https://user-images.githubusercontent.com/24280746/233075955-6df3f2ba-2f3a-415f-be6d-00949e445eb6.png)

**Comment by rogerfar** [comment]
What speed does speedtest.net give you?

**Comment by gaston-arg** [comment]
Hi Roger, speedtest.net gives me a 95-98 MB/s, in line with what RDT Client gives (on version 2.0.19)

**Comment by Dervichter** [comment]
> Hi Roger, speedtest.net gives me a 95-98 MB/s, in line with what RDT Client gives (on version 2.0.19)

Do you find a solution? Same problem here :(

**Comment by gaston-arg** [comment]
Hi, the only fix is to use version 2.0.19

**Comment by ray-holmium** [comment]
I believe this issue may be related to rdtclient's display of the speed test, rather than the speed itself. I also get an rdtclient speed test result of approx 20.3 MB/s but my actual downloads in aria2 are saturating my connection at approx 100 MB/s.

**Comment by rogerfar** [comment]
Let's keep it central in this https://github.com/rogerfar/rdt-client/issues/296
