### ISSUE TITLE
The SPA default page middleware could not return the default page '/index.html

### ISSUE THREAD

**Issue by zanmera** [rogerfar/rdt-client#245]
**What version are you using?**
2.0.30
**Wat OS are you running?**
windows 10
**Are you using Docker or as a service?**
no

Getting the following error after clicking the .exe and going to http://127.0.0.1:6500/
[15:42:56 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

**Comment by rogerfar** [comment]
Did you install it as a service? Not sure if just doubleclick the exe is enough.
