### ISSUE TITLE
No download from realdebrid

### ISSUE THREAD

**Issue by ZOKOB** [rogerfar/rdt-client#246]
**Version 2.0.30**

**docker**

**Are you using Docker or as a service?** yes

Hello, since I passed my RDT in Version 2.0.30 I can no longer download it remains blocked at 8% then its DL 500,000 KB disappears and then it deletes the torent.

Do you know why ?

I enclose my logs in PJ

Wishing you a pleasant day
Sincerely Remy
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/11298399/rdtclient.log)

**Comment by rogerfar** [comment]
Please enable debug logging.

**Comment by ZOKOB** [comment]
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/11299225/rdtclient.log)

**Comment by rogerfar** [comment]
I don't see anything in the log, the only thing I see is you're trying to paste a http link in the magnet field, try uploading it instead.

**Comment by ZOKOB** [comment]
I just deleted the container and I just recreated it it does exactly the same in the debug logs I see nothing :(


`Setting permissions

[custom-init] No custom files found, skipping...

Setting permissions

chown: changing ownership of '/data/downloads/[ OxTorrent.com ] Central.Intelligence.2016.MULTI.VFF.BluRay.1080.x265.HEVC.DTS-HDMA-STARLIGHTER.mkv/[ OxTorrent.com ] Central.Intelligence.2016.MULTI.VFF.BluRay.1080.x265.HEVC.DTS-HDMA-STARLIGHTER.mkv': Operation not permitted

chown: chown: changing ownership of '/data/downloads/[ OxTorrent.com ] Central.Intelligence.2016.MULTI.VFF.BluRay.1080.x265.HEVC.DTS-HDMA-STARLIGHTER.mkv'changing ownership of '/data/downloads/[ OxTorrent.com ] Central.Intelligence.2016.MULTI.VFF.BluRay.1080.x265.HEVC.DTS-HDMA-STARLIGHTER.mkv/[ OxTorrent.com ] Central.Intelligence.2016.MULTI.VFF.BluRay.1080.x265.HEVC.DTS-HDMA-STARLIGHTER.mkv': Operation not permitted

: Operation not permitted

chown: changing ownership of '/data/downloads': Operation not permitted

chown: changing ownership of '/data/downloads/[ OxTorrent.com ] Central.Intelligence.2016.MULTI.VFF.BluRay.1080.x265.HEVC.DTS-HDMA-STARLIGHTER.mkv': Operation not permitted

Changing to /app folder

chown: changing ownership of '/data/downloads': Operation not permitted

Starting rtdclient

s6-rc: warning: unable to start service init-rdt-client: command exited 1

[07:39:10 WRN] Using an in-memory repository. Keys will not be persisted to storage.

[07:39:10 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.

[07:39:10 WRN] No XML encryptor configured. Key {7be2ff23-c6ac-4a33-b42f-d19a3d71d514} may be persisted to storage in unencrypted form.

[07:39:10 WRN] Starting host on version 2.0.30.0

[07:40:14 WRN] The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.

[07:40:14 WRN] 402: /Api/Authentication/IsLoggedIn`

**Comment by mastervash** [comment]
I am having the same issue. Running in docker. Radarr seems to add the torrent fine, but from there the status just remains stuck at ``Torrent waiting for file selection`` If I login to RD and manually select which files to grab, the status updates to `` Torrent finished, waiting for download links`` but once again it stays stuck. 

Here are some of the error logs I pulled from Portainer. 
[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/11301628/_rdtclient_logs.txt)

**Comment by rogerfar** [comment]
Your sqlite DB is corrupt. Try deleting your DB and set it up again.

**Comment by rogerfar** [comment]
And @ZOKOB you have a permission issue, as shown in the logs.
