### ISSUE TITLE
Feature Request: Pause Button

### ISSUE THREAD

**Issue by domoclick** [rogerfar/rdt-client#250]
is possible to add a download pause button?

**Comment by OverStyleFR** [comment]
I agree this feature

**Comment by kungfoolfighting** [comment]
I might spend some time to implement this. Where would you want that button to appear?
But even if I implement this, there is no guarantee, that it will become available. I have had a pull request open for quite a while without any response. I don't know if pull requests will get accepted at all.

**Comment by rogerfar** [comment]
@kungfoolfighting you put in a pr 3 days ago. Please understand I have a full time job and currently enjoying a holiday.

If you feel this is a useful feature then by all means make a proper pr.

In the meantime just use aria2c and it has all the functionality built in.

**Comment by kungfoolfighting** [comment]
Ah sorry, you must have misunderstood, I was not complaining. You just never know with public git repos. My PR was created on the 19th, so 6 days ago. But even if it had been a month ago, it's all good. People gotta work and this is vacation season, so don't worry about it.

**Comment by rogerfar** [comment]
Because of all the troubles we have with the downloader, I don't think this will ever be implemented unless someone wants to take it on.
