### ISSUE TITLE
Question: donation button?

### ISSUE THREAD

**Issue by BlueBull010** [rogerfar/rdt-client#251]
Hi there

Sorry for filing this as a bug report but it was the only type of report available. I have a simple question: do you have any mechanism set up for donations? Reason I ask is because I make extensive use of your application, it works well and it is the only one of its kind that is still being actively developed as far as I can tell. I would like to express my gratitude. It would just be a small amount, as much as I can spare. I feel like you should set up some form of donation support, like paypal, the "buy me a coffee" thing, or even github donation support. This so people can do more than say "thanks" and so you feel (even) more appreciated, which you deserve for your work

In any case, thank you very much for developing this, it is awesome, your efforts are hugely appreciated and your application has been put together masterfully

Cheers

Tom

**Comment by rogerfar** [comment]
Unfortunately I have a full time job, plus a family and some more side stuff on the go, so I want to keep this an open source project for whoever wants to use it, but I can't afford to become the powerhouses that Sonarr and Radarr are.

At this point I'm at almost 10 years of referrals on Real-Debrid, basically a lifetime supply, which I'm more than happy with.

**Comment by BlueBull010** [comment]
That is admirably altruistic. Okay, I understand. Please do know that your work is greatly appreciated. So much so that people would gladly donate to say thanks if it were possible. Your software is an indispensable part of my media setup and has been for years

Cheers and be well

Tom
