### ISSUE TITLE
permission problem

### ISSUE THREAD

**Issue by Sparklingx** [rogerfar/rdt-client#254]
setup as docker . and setup aria2c but permission problem is killing me cant test dir permission nor the speed test via aria2c

**Comment by cavedog8** [comment]
If you are running the docker image as root but what the permission changed add this.

    environment:
      - PUID=1001
      - PGID=1001

Get the id of the user that is accessing the content. Usually 1000 or 1001 unless you are using it on a system with a lot of users then you can get the user id by typing id

**Comment by Sparklingx** [comment]
I solved my problem the other ay when you do aria2 as baremetal but rdtclient as docker  their code is not well enough to path different paths in host and container so I mounted the same folder in both container and host LOL  now its all good.
