### ISSUE TITLE
rdt-client is causing Real-Debrid to block/blacklist on SOME links

### ISSUE THREAD

**Issue by vegedb** [rogerfar/rdt-client#255]
Seems like Real-Debrid is blocking rdt-client.
# RDT
![image](https://github.com/rogerfar/rdt-client/assets/72070424/bb555d91-4801-497b-b0ad-13971a747967)

# Copy link from real debrid website

![Clipboard Image (1) (Medium)](https://github.com/rogerfar/rdt-client/assets/72070424/ce5f03e4-66df-4e34-b7ee-a61c3358c943)

# WGET (Link from website)

![image](https://github.com/rogerfar/rdt-client/assets/72070424/bb66188a-2393-496b-80b2-01cbfccabac5)

# Other Info

1. No VPN used.
2. Same machine generating the link
3. Not all torrents are affected but its **repeatable** with the same problematic torrent

# Steps to Reproduce

1. [RDT] Click on "Add New Torrent" on rdt and paste magnet
2. [RDT] "Waiting for download" STUCK
3. Use browser, visit official RD website and download the same link
4. 503 OR 403 error as seen in screenshots
5. As I can see this torrent is blacklisted for 20-30 minutes> (adding new to website yields same problem), After the ban is lifted, download can continue from the website
6. Repeat STEP 1>5 to reproduce same problem

Perhaps masking rdt with "Default Browser Agent" when downloading might help?

Edit:
When downloading directly from real-debrid website, there's a split second where it accesses https://app.real-debrid.com
Perhaps this is the check that real-debrid uses?

![image](https://github.com/rogerfar/rdt-client/assets/72070424/8f6175a3-a749-4d3a-9e5b-7980ba453a26)

**Comment by rogerfar** [comment]
We're using the official API so it would be weird if they start blocking it. 

If it's the same torrent that's also broken on their website I would contact support first.

**Comment by vegedb** [comment]
@rogerfar 
> We're using the official API so it would be weird if they start blocking it.
> 
> If it's the same torrent that's also broken on their website I would contact support first.

Its not blocking if I add it manually to the website,
![image](https://github.com/rogerfar/rdt-client/assets/72070424/cbcbf233-b2b5-4797-af8d-ebc5b103c90f)


Weird, maybe this is a one off, I'll close it for now. If anyone else experiences this again, you might wanna open it.

**Comment by cavedog8** [comment]
I'm experiencing the same issue.

If I flip between direct a cloudflare it helps but not long then it stops working again.

wget also give me 403: service unavailable

![image](https://github.com/rogerfar/rdt-client/assets/64382634/5a6359eb-22e7-45cd-9448-d8683be3f6c5)

**Comment by cavedog8** [comment]
Link to the original issue oppened.

https://github.com/rogerfar/rdt-client/issues/255
