### ISSUE TITLE
rdt-client is causing Real-Debrid to block/blacklist on SOME links

### ISSUE THREAD

**Issue by cavedog8** [rogerfar/rdt-client#258]
I'm experiencing the same issue.

If I flip between direct a cloudflare it helps but not long then it stops working again.

wget also give me 403: service unavailable

![image](https://github.com/rogerfar/rdt-client/assets/64382634/5a6359eb-22e7-45cd-9448-d8683be3f6c5)

_Originally posted by @cavedog8 in https://github.com/rogerfar/rdt-client/issues/255#issuecomment-1545583004_

**Comment by cavedog8** [comment]
Same issue when rolling back to previous versions and downloaders.

I think it's either RD that are having issues or they are now blocking servers or some 3rd party downloaders.

![image](https://github.com/rogerfar/rdt-client/assets/64382634/309f161a-8f42-4c89-b909-077eede916bd)

**Comment by rogerfar** [comment]
You might have to contact their support, so far I haven't seen this issue. How many are you downloading at the same time with how many threads?

**Comment by cavedog8** [comment]
> You might have to contact their support, so far I haven't seen this issue. How many are you downloading at the same time with how many threads?

Single thread 2 downloads at a time. I have 2 accounts also so this account is used exclusively with rdtclient. I tried using on my other account and the same happened on it.

I disabled rdtclient for a while now and see if things get sorted but maybe rdtclient doesn't like the amount of traffic or something but direct works fine.

**Comment by cavedog8** [comment]
> You might have to contact their support, so far I haven't seen this issue. How many are you downloading at the same time with how many threads?

Looks like I found the issue... Looks like they no longer accept connections for these big dedicated server providers like OVH, Online.net, Hetzner etc...  I need a plan B or move to another host. Thanks.

root@PAR-487514:~# curl -4 https://real-debrid.com/vpn | grep blocked
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28532    0  <div class="error-box"><strong>Your ISP or VPN provider IP address is currently blocked on our website, please contact the support</strong></div>

Commands are 
Ipv4
curl -4 https://real-debrid.com/vpn | grep blocked

ipv6
curl -6 https://real-debrid.com/vpn | grep blocked

**Comment by rogerfar** [comment]
Ok yeah that's interesting, because it states in their TOS:
```
The User certifies that he will not use a dedicated server, VPS or any cloud service on our service other than by using his Remote Traffic
```
https://real-debrid.com/terms

Remote traffic would make it quite prohibitively expensive.

**Comment by cavedog8** [comment]
They were quite lenient on it but I think they might be clamping down on it now because it's always been working for ages.
