### ISSUE TITLE
No auto pause on low disk space

### ISSUE THREAD

**Issue by Sparklingx** [rogerfar/rdt-client#261]
**What version are you using?**
latest
**Wat OS are you running?**
ubuntu 22.04
**Are you using Docker or as a service?**
Docker
And im using Aria2 as downloader 

There is no auto pause on low disk space .... lets say i want to make it auto pause when disk space is less than 10GB.  Thats why often my disk is full and client is showing  diskallocation error because of low disk space 

![image](https://github.com/rogerfar/rdt-client/assets/85538352/708ef2e2-ac51-4a32-ae7f-78d9d37cf36e)

**Comment by rogerfar** [comment]
At this point I'm not implementing pausing and resuming features.
