### ISSUE TITLE
rdtclient - downloads failed with errors

### ISSUE THREAD

**Issue by mrizvi66** [rogerfar/rdt-client#262]
I'm getting a download error. everything was working fine until May 24 2023 then it just starting giving me these errors. 

**What version are you using?**
v2.0.30

**Wat OS are you running?**
Win11

**Are you using Docker or as a service?**
as a windows service

**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/11575503/rdtclient.log)
[rdtclient_001.log](https://github.com/rogerfar/rdt-client/files/11575504/rdtclient_001.log)
[rdtclient_002.log](https://github.com/rogerfar/rdt-client/files/11575505/rdtclient_002.log)
![rtdclient-download-error](https://github.com/rogerfar/rdt-client/assets/11949810/8e421006-a7ec-428b-a6ab-0307cf62483e)

**Comment by rogerfar** [comment]
The logs indicate that everything is downloading OK, what does the RDT UI say?

**Comment by mrizvi66** [comment]
that the operation has timed out.
![Screenshot 2023-05-26 092620](https://github.com/rogerfar/rdt-client/assets/11949810/5105f5a4-4fa8-4786-abec-4f91db044efb)

**Comment by Ace-Nanter** [comment]
Hi. I am having the same issue on a major part of my downloads for a while now (maybe a month or two). Here are more informations I gathered:
- I am using an AllDebrid subscription, and it seems to store downloaded torrents through UpToBox. I read UpToBox was being targeted by anti-piracy laws in my country (France), so maybe it's being blocked sometimes?
- Attached are some logs I gathered: it seems to loop a few times, then fails with a timeout.

[failed_download.log](https://github.com/rogerfar/rdt-client/files/11587032/failed_download.log)

Let me know if you need me to provide more logs or information, I am desperate for a solution!

**Comment by Ace-Nanter** [comment]
I finally made it working. As I was using rdtclient with docker, reinstalling didn't help. What I did to solve the issue was to set up download timeout to a ridiculously high value such as 30 seconds. So far, since I have done that, my downloads are taking longer but succeeds.
AllDebrid are probably having issues scaling correctly their API.
