### ISSUE TITLE
High CPU Usage on service mode

### ISSUE THREAD

**Issue by theoPARENTIT** [rogerfar/rdt-client#264]
**What version are you using?**
V2.0.30

**What OS are you running?**
Ubuntu on Proxmox hypervisor

**Are you using Docker or as a service?**
Service

**Please attach a log file here with the log setting set to debug**
![image](https://github.com/rogerfar/rdt-client/assets/91315765/285968a7-e706-411f-8517-e12cb2861f9f)

Hello everyone, I came here to maybe find a solution, I see that rdtc uses a big amount of CPU resources, creating CPU iowait even on idle, no download in progress, does it happen to some of you ? And do we have a solution for this ?

**Comment by theoPARENTIT** [comment]
Another information, when the service is stopped, everything go flat on charts :/ 

![image](https://github.com/rogerfar/rdt-client/assets/91315765/3217fbfc-e7e4-46c9-9295-d86a27aa90cf)

**Comment by rogerfar** [comment]
Do you have folder watch on? Can't do much without debug logs.

**Comment by rogerfar** [comment]
Let me know if this is still an issue.
