### ISSUE TITLE
RDT client don't download file

### ISSUE THREAD

**Issue by Dervichter** [rogerfar/rdt-client#266]
What version are you using? 2.0.30 and 2.0.19

Wat OS are you running? Windows 11

Are you using Docker or as a service? Docker!

My download fails all the time, I'm on version 2.0.19 because otherwise my download speed drops drastically (from 320MB/s to 30MB/s). I tested in version 2.0.30 but I have exactly the same problem. Whether it's with Sonarr or Radarr it only downloads a few percentages of the file and it ends up failing.
I can't finish downloads anymore (and before that I couldn't download files of several Go, only small series).

I'm too bad to configure Aria2c, is there someone to help me? Thx!

[Log file rdtclient.txt](https://github.com/rogerfar/rdt-client/files/11665482/Log.file.rdtclient.txt)

**Comment by Dervichter** [comment]
I tried again today.
He managed to download a few series except Rings of Power and 2 movies Every thing every where all at once and Interstellar.
It's always the same, it downloads (very slowly, 30MB/s whereas with 2.0.19 it was 300MB/s) and after a few percent it starts again at 0...
I need help please I would like to fix this it's the last thing to do to get everything working.

[Log file rdtclient 07-06-23 .txt](https://github.com/rogerfar/rdt-client/files/11676329/Log.file.rdtclient.07-06-23.txt)

**Comment by rogerfar** [comment]
Log says
```
2023-06-07 12:50:25 [10:50:25 DBG] All downloads complete, marking torrent as complete for torrent The.Lord.of.the.Rings.the.Rings.of.Power.S01.MULTi.WEBRip.2160p.DV.x265.DA.5.1-chrisj72 (UT6WSWVPOSOIQ - downloaded 100%) (148c2ed4-a09f-4e29-b2b6-acbdc7207525)
```

Which one failed?

**Comment by Dervichter** [comment]
at 10:50:25

My log isn't complete because i start many downloads but before that:
Same error with interstellar (download at 30MB/s for 74,48GB and failed many times before rdtclient tell me downloads failed with errors in torrent management)
Same error with movie Every thing every where all at once (download at 30MB/s for 81,9GB)
I don't know why but my downloads start and restart to 0% after few seconds for big files.

I try with small files like Animes and it's work (always at 30MB/s max...) but with many restart
I try with UHD TV show and movies and it's fail

**Comment by Dervichter** [comment]
[log file.txt](https://github.com/rogerfar/rdt-client/files/11677563/log.file.txt)

**Comment by Dervichter** [comment]
I try with a file (4,55GB) => no fail but always 30MB/s (my connection on my computer: 1600MB/s) it's a pain for big files.

I try with another file (74,48GB) => already 3 fails with "unable to read data from the transport connection" in log file restart download at 0%

Impossible to download big files because my download restart always with "unable to read data...." and stop after many fails.

**Comment by rogerfar** [comment]
> my connection on my computer: 1600MB/s

This is would like to see! 

What is your `Connection Timeout (only used for the Internal Downloader)` setting set as?

**Comment by Dervichter** [comment]
Connection Timeout: 500000

74,48GB file fail at:
13:47:48
13:55:56
13:59:19

Log File:
[new log file.txt](https://github.com/rogerfar/rdt-client/files/11677898/new.log.file.txt)

**Comment by rogerfar** [comment]
What happens if you take one of those links straight from the logs and try to download it in something with wget, or just plain try to download it in the browser?

**Comment by Dervichter** [comment]
If i try this link it download with IDM at max speed (but my download in rdtclient restart at 0%)

![Screenshot_9](https://github.com/rogerfar/rdt-client/assets/75535259/6c60eab3-2047-4427-983b-c6cb37af66b4)

**Comment by Dervichter** [comment]
Always at the same point...

**Comment by rogerfar** [comment]
It keeps reporting `Unable to read data from the transport connection`, maybe increase the `Connection Timeout` to 60 seconds and keep `Parallel connections per download` on 1 to see if that improves it.

**Comment by Dervichter** [comment]
Don't know why but my problem is still here

[log file.txt](https://github.com/rogerfar/rdt-client/files/11715424/log.file.txt)

**Comment by karl0ss** [comment]
I get the problem sometimes, I find if I restart the rdtc service it starts working again.

**Comment by rogerfar** [comment]
I put a few fixes in the internal downloader because I'm seeing the same issue consistently with the same downloads.

But, only in Docker. I can't reproduce it local or in Windows. There must be something going on with .NET on dockers networking.

**Comment by rogerfar** [comment]
Can you try again with the latest release? I updated the internal downloader to a different one which should be more reliable.

**Comment by rogerfar** [comment]
If it's still an issue please file a new issue with new logs.
