### ISSUE TITLE
Add Transmission 

### ISSUE THREAD

**Issue by gumballwat** [rogerfar/rdt-client#268]
Hello,
can you add Transmission to the download client list (as a remote GUI transmission)? 
Thank you

**Comment by rogerfar** [comment]
I am not sure what you're asking for. What is your use case?

**Comment by gumballwat** [comment]
Good evening and thank you for taking the time to reply:
I'd like to be able to use the transmission software instead of aria2c, for example.

Transmission already has an interface for remote communication: called transmission remote gui

**Comment by rogerfar** [comment]
Transmission is a torrentclient, Aria2c is a file downloader, not the same thing. Or am I not understanding?

**Comment by gumballwat** [comment]
Ah yes, you understood very well. You understood better than me that I was saying an aberration.
Sorry for the waste of time.
