### ISSUE TITLE
Specify network interface | Linux

### ISSUE THREAD

**Issue by ClaraCrazy** [rogerfar/rdt-client#270]
Hey there. Are there any plans of allowing us to use a specific network interface for downloading? Would be nice to not have to deal with overly complicated iptables stuff etc. to ensure our privacy.

Maybe you already know of a simple solution for this, or theres a setting and I am just blind, who knows. LMK!

**Comment by rogerfar** [comment]
Honestly, your probably easier off using a docker or LXC container which gives a lot more flexibility with choosing the correct interfaces. For now I'll accept PR's because I have no clue if it's even possible with .NET.
