### ISSUE TITLE
[Feature request] Option to fail a job if it's not cached in cloud after a certain time

### ISSUE THREAD

**Issue by nihilist77** [rogerfar/rdt-client#272]
There are times when a job is sent to cloud but the provider can't finish the download. It can be for various reasons and out of control from clients point of view. So if there is an option to fail a job if it's not cached in cloud after a certain period of time, then the indexer can try a different magnet or torrent.

**Comment by rogerfar** [comment]
This setting should do what you want:

![image](https://github.com/rogerfar/rdt-client/assets/1142915/4277e4ce-a7a6-4519-9213-af26b7d31e77)

**Comment by nihilist77** [comment]
Ah, got it!
