### ISSUE TITLE
Request: Add an "Add Torrent" button to the top of the page

### ISSUE THREAD

**Issue by rushtothesun** [rogerfar/rdt-client#273]
![3 (2)](https://github.com/rogerfar/rdt-client/assets/20650932/4574349f-8a79-4d75-b2dd-0f4e5874b006)

Could this button be moved to the top of the page, or an option for it, so that you don't have to constantly scroll down every time you add a new torrent?

**Comment by rogerfar** [comment]
This is in the next version.
