### ISSUE TITLE
Feature Request: Save torrent files to history

### ISSUE THREAD

**Issue by jack-mil** [rogerfar/rdt-client#274]
qBittorrent has a feature where .torrent or .magnet files can be saved to a directory as a backup and archive of all your downloads. Right now, I am achieving this by using a watch folder and a "torrent blackhole" client type in *arr. But this method has many drawbacks compared to using the full qbittorrent API protocol. 
This feature would add a setting in General or in the qbittorrent settings tab where a directory could be set (e.g. /history) to save all .torrent or .magnet links sent over the API.
This would be useful as a record of which torrents have been used, as well as allowing the future possibility or redownloading/seeding using a true torrent client.

How difficult would this feature be to implement? I am not experienced in dotnet/C# development, but I have done a good amount of other programming and would be willing to give it a shot in the future

**Comment by rogerfar** [comment]
I added a new setting under General: Copy added torrent files. This will copy torrent and magnet files to this directory.
