### ISSUE TITLE
Write permission folder problem (Docker / Nas Synology)

### ISSUE THREAD

**Issue by JPnux** [rogerfar/rdt-client#275]
**What version are you using?**
Docker rogerfar/rdtclient:latest
2.0.32

**Wat OS are you running?**
NAS SYNOLOGY DSM 7

**Are you using Docker or as a service?**
DOCKER

Problem :
When I go in "Settings" and "SpeedTests" and  "Test download path permissions" I have this error :

```
Could not test your download path
Access to the path '/data/downloads/test.txt' is denied. 
```
I already added PUID and PGID in environment variables.

Volumes : 
![image](https://github.com/rogerfar/rdt-client/assets/47024223/969b8fd5-ab8e-422c-89a3-5d6f5304813e)

`

2023/07/02 18:29:30 | stdout | Starting rtdclient
-- | -- | --
2023/07/02 18:29:30 | stdout | Changing to /app folder
2023/07/02 18:29:30 | stdout | [ls.io-init] done.
2023/07/02 18:29:30 | stdout | Setting permissions
2023/07/02 18:29:30 | stdout | [custom-init] No custom files found, skipping...
2023/07/02 18:29:30 | stdout | Setting permissions
2023/07/02 18:29:30 | stdout |  
2023/07/02 18:29:30 | stdout | ───────────────────────────────────────
2023/07/02 18:29:30 | stdout | User GID:    100
2023/07/02 18:29:30 | stdout | User UID:    1026
2023/07/02 18:29:30 | stdout |  
2023/07/02 18:29:30 | stdout | ───────────────────────────────────────
2023/07/02 18:29:30 | stdout | GID/UID
2023/07/02 18:29:30 | stdout | ───────────────────────────────────────
2023/07/02 18:29:30 | stdout |  
2023/07/02 18:29:30 | stdout | https://www.linuxserver.io/donate/
2023/07/02 18:29:30 | stdout | To support LSIO projects visit:
2023/07/02 18:29:30 | stdout |  
2023/07/02 18:29:30 | stdout | ───────────────────────────────────────
2023/07/02 18:29:30 | stdout | Based on images from linuxserver.io
2023/07/02 18:29:30 | stdout |  
2023/07/02 18:29:30 | stdout | \|_____\|_____\|_\|_____\|____/
2023/07/02 18:29:30 | stdout | \| __ -\|  \|  \| \|  \|__\|  \|  \|
2023/07/02 18:29:30 | stdout | \| __  \|  \|  \| \|  \|  \|    \
2023/07/02 18:29:30 | stdout | _____ __ __ _ __    ____
2023/07/02 18:29:30 | stdout | \|_____\|_____\|_____\| \|_\| \|_____\|_\|_\|_\|
2023/07/02 18:29:30 | stdout | \|   --\|  \|  \|__   \| \| \| \|  \|  \| \| \| \|
2023/07/02 18:29:30 | stdout | \|     \|  \|  \|   __\|_   _\|     \|     \|
2023/07/02 18:29:30 | stdout | _____ __ __ _____ _____ _____ _____
2023/07/02 18:29:30 | stdout | ───────────────────────────────────────
2023/07/02 18:29:30 | stdout | usermod: no changes
2023/07/02 18:29:30 | stdout | [migrations] no migrations found
2023/07/02 18:29:30 | stdout | [migrations] started

`

**Comment by DaisyF8** [comment]
May help : set "umask=0002" in docker, so group users have rw.

**Comment by rogerfar** [comment]
This seems to be a permission issue.
