### ISSUE TITLE
rdtclient on proxmox LXC

### ISSUE THREAD

**Issue by crawlingcity** [rogerfar/rdt-client#277]
Hey there,

I've been using rdtclient for a while now and lately I moved everything to lxc  regarding my *arr apps, so I thought, why not rdtclient as well?

So I contributed here to add this to the scripts (https://github.com/tteck/Proxmox/pull/1595) and if you want, your README can include this to show it's possible to have this in a lxc - up to you how you want to proceed from here.

Just letting you know!

**Comment by rogerfar** [comment]
Appreciate it! If you don't mind, could you add a small section in the readme here with a link to that? Not too familiar with proxmox just yet.
