### ISSUE TITLE
[Feature request] Button for finished torrent to change Post-donwload-action from "Don't download" to "Download".

### ISSUE THREAD

**Issue by DaisyF8** [rogerfar/rdt-client#278]
For a finished torrent that was added with "Post torrent download action : don't download" ---> have a button in tab General (or have the option in Change Settings) to change your mind and still download the torrent locally. For when you change your mind after having the torrent present in debrid-cloud and want to download it to your machine.

**Comment by rogerfar** [comment]
This is added in the next version.

**Comment by DaisyF8** [comment]
Thank you so much :)
