### ISSUE TITLE
Download speed limit for Simple Downloader

### ISSUE THREAD

**Issue by Vorenu5** [rogerfar/rdt-client#28]
This client has been working great since I was able integrate it into my system. The one thing preventing me from using it fulltime is I'm not able to control the speed of downloading when using the Simple Downloader. It would be great to see this feature implemented. Thanks for such an easy to use and functional client.

**Comment by timcoop3r** [comment]
What stopping using the multi-part downloader with 1 stream to enable a speed limit?

**Comment by Vorenu5** [comment]
I would prefer not to use the multi-part downloader for two reasons:
1) The length of time it takes to reconstruct larger files from the downloaded chunks
2) File permission issues with the unchangeable temp directory being used prevents the ability to download larger files (false "not enough space on disk" messages)

**Comment by timcoop3r** [comment]
>1. The length of time it takes to reconstruct larger files from the downloaded chunks (even with 1 chunk, it copies the file to the destination download folder instead of moving it, which takes the same amount of time as the default 8 chunks)

Fair enough. fwiw I also only use the simple downloader as I have been having issues with corruption in video files using the multi-part.

> 2. File permission issues with the unchangeable temp directory being used prevents the ability to download larger files (false "not enough space on disk" messages)

You can change the path of the temp files, there is a setting for this?

**Comment by Vorenu5** [comment]
The chunks being downloaded do go into the temp directory I have set in the settings, however I still receive "not enough space on disk" error messages on larger file downloads. So my best guess is that the multi-downloader is checking another unchangeable temp directory prior to sending the chunks to the temp directory specified in the settings. (This could be an issue with how I am running the service in linux using dotnet)

**Comment by timcoop3r** [comment]
Are you using docker? Have you configured the volumes correctly for the temp location? If no this could also explain the slow move speed if it is trying to move/hardlink and can't so is doing a copy instead?

Make sure your temp location and download location are on the same root volume to enable proper moves/hardlinks.

e.g from docker-compose have a single volume:

```yaml:
volumes:
      - /data/media/downloads:/data/downloads
```

Then have your 'temp' location in the settings as /data/downloads/temp

Broken example would be something like the following:

```yaml:
volumes:
      - /data/downloads:/downloads
      - /data/temp/:/temp
```

This would make the container see it as two mount points so you can not do a move/hardlink correctly and it would have to do a slow copy.

**Comment by Vorenu5** [comment]
I am not using docker, I am using dotnet. So there is no volume configuration. My temp and download locations are both on the same storage device with multiple TB free.

**Comment by timcoop3r** [comment]
> I am not using docker, I am using dotnet. So there is no volume configuration. My temp and download locations are both on the same storage device with multiple TB free.

Sounds like one for @rogerfar? I don’t see this behaviour with large files (20-40GB) with the multipart downloader when running in dotnet on Linux in the docker container.

**Comment by Vorenu5** [comment]
Using the Simple Downloader works as expected for me and I only hoped to have the ability to limit the download speed when using that particular downloader if it was easy enough to implement for @rogerfar. I did not intend this feature request to evolve into attempting to troubleshoot my obviously unorthodox setup. I'm already in the process of making backups of critical configurations so that I can start my entire build from scratch likely utilizing dockstarter.

**Comment by timcoop3r** [comment]
Just trying to help you get something working with a speed limit in the meantime :)

**Comment by rogerfar** [comment]
@Vorenu5 you can change the temp folder in the Temp Path setting:

![image](https://user-images.githubusercontent.com/1142915/107724751-d9877600-6ca1-11eb-8d06-ce602d04542a.png)

I can have a look putting a limiter in the simple downloader, it's not a high priority as the multi downloader has it built in.

I am playing with the idea of merging the 2 together in a new library, as the multi downloader is still using some old .NET stuff, which causes some of the performance issues.

**Comment by Vorenu5** [comment]
I appreciate you taking the time to to see if its feasible to implement. I have the Temp Path set already in that setting pictured and was still receiving the not enough space on disk error. I have been testing the client with the multi downloader in a docker container and the final downloaded file is owned by root which is preventing sonarr/radarr from being able to move it.

**Comment by timcoop3r** [comment]
> I appreciate you taking the time to to see if its feasible to implement. I have the Temp Path set already in that setting pictured and was still receiving the not enough space on disk error. I have been testing the client with the multi downloader in a docker container and the final downloaded file is owned by root which is preventing sonarr/radarr from being able to move it.

There is a workaround for this by setting the user when you run the container. With 'docker run' command this would be something like '--user uid:gid' where uid and gid are the user and group id of the sonarr/radarr user. e.g. '--user 1003:1003'.

You can also do this in docker-compose with 'user: 1003:1003' in your service definition. I believe @rogerfar may also be working on some other improvements/changes with regards to this and the permissions when using docker.

You can find the uid and gid of your relevant user by looking inside the /etc/passwd file for the line containing your relevant username.

**Comment by Vorenu5** [comment]
That did the trick. Thanks for the help :)

**Comment by Vorenu5** [comment]
Unfortunately I have the same issues with large files throwing the not enough disk space error. My download path and temp download path are the same and it works without issue using the simple downloader.

**Comment by rogerfar** [comment]
That is an odd one, I'm suspecting a bug in .NET core in the file space check system. As a workaround you can try increasing the disk space of the actual docker container, tricking it in thinking it's larger.

**Comment by timcoop3r** [comment]
If docker is using the overlay2 storage driver (is the default on linux anyway) it should see the container filesystem as the full size of the drive its running on. With other storage drivers this is not always the case. e.g. I think the devicemapper storage driver on Linux makes the container think its only got a 10GB drive which could be an issue?

**Comment by Vorenu5** [comment]
`Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true`

That is likely not the issue

**Comment by rogerfar** [comment]
I found a bug in the multi downloader library. It resolves the temp path `/data/temp` to `/` then checks the disk space available. This results in an unpredictable outcome. 

I raised the issue there.

**Comment by Vorenu5** [comment]
I'm glad to know I'm not completely crazy with what I was experiencing with the temp path. I went ahead and symlinked my docker path to my media drive and now I'm able to download the larger files using the multi downloader without error. Will be interesting to see if this solves the issue of copying from chunks instead of moving them like intended.

**Comment by Vorenu5** [comment]
So even with the path for docker and downloads being on the same media drive, the multi downloader still copies the file from the chunk(s) instead of just moving it. This causes needless wasted time and cpu/disk resources and is the primary reason I would prefer to only use the simple downloader. Its very understandable that adding a speed limit to the single downloader isn't a top priority. But if given a choice, I would much prefer to have this feature than not have it.

**Comment by rogerfar** [comment]
The copying is something I still need to address, but the disk full error should be resolved now in 1.5.6.

**Comment by Vorenu5** [comment]
Thanks for a quick update regarding the temp path issue. I'll update the docker image soon to check it out.

**Comment by rogerfar** [comment]
It's been overdue, but when using the Simple downloader you can now set a download speed limit in MB/s.
