### ISSUE TITLE
Failed to load /app/libhostpolicy.so

### ISSUE THREAD

**Issue by odyssey46** [rogerfar/rdt-client#282]
**What version are you using?**
v2.0.32
**Wat OS are you running?**
Raspbian OS 11 (Linux, Raspberry Pi)
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**
No log file exists; issue occurs during setup

After running the `docker run` command from the readme, the image is downloaded and setup begins. Soon, I receive the following terminal outputs which repeat until I kill it with Ctrl+C:
`Setting permissions
Changing to /app folder
Starting rtdclient
Failed to load /app/libhostpolicy.so, error: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /app/libhostpolicy.so)
An error occurred while loading required library libhostpolicy.so from [/app/]`

**Comment by rogerfar** [comment]
Is this 64bit Raspbian?

**Comment by odyssey46** [comment]
I believe it was 32 bit. I apologize, I should have followed up on this because I have since retired the Raspberry Pi and replaced it with an x86 system on which rdt-client is working perfectly.
