### ISSUE TITLE
Soulseek integration

### ISSUE THREAD

**Issue by KINGLIFER** [rogerfar/rdt-client#284]
I apologize AND I know this urks many.
I would like to create the same software as rdt-client but utilizing the soulseek protocol. or add soulseek to rdt-client. This is extremely important since sometimes an item will be on soulseek while it would not be on other platforms. I am willing to discuss this further if possible.
Unfortunately I can not communicate by any other means.

**Comment by kungfoolfighting** [comment]
Adding this feature here would be very welcome, I would definitely use it.

**Comment by rogerfar** [comment]
I'm not sure what you mean by soulseek, it seems to me that this is some sort of torrent client? RDT is designed only to work with debrid clients. Why can't you add it straight to soulseek, why does it have to go through RDT?

**Comment by KINGLIFER** [comment]
I am sorry you are looking at it backwards and that is my fault. The key is the Arrs... where soulseek is not connected to. As you know RDT is a web interface to manage torrents on Real-Debrid, AllDebrid or Premiumize. I am asking to add Soulseek. The difference is Soulseek (esp when it comes to music) has more niche titles. Put it this way if you ask if you should put it... I am positive you would not get someone saying no. They _might_ say something like it is old or perhaps no one uses it. That is because they simply have not used it recently.

**Comment by rogerfar** [comment]
I don't think this makes sense in the sense of adding it to RDT. RDT only works with torrent files while soulseek works with plain text searches. This seems to me more of an integration for Jackett or Prowlarr.

**Comment by KINGLIFER** [comment]
sigh. Thanks.
