### ISSUE TITLE
[Feature Request] Allow post download script to send `success` download state for *arrs

### ISSUE THREAD

**Issue by pettytreebroker** [rogerfar/rdt-client#285]
I have RDT set to not download any files to my host, and instead run a post download script to create a symlink in the download folder to the file in the mounted debrid webdav folder. The problem is, Radarr reports `Download warning: qBittorrent is reporting an error` from RDT (which makes sense bc the file is never downloaded), so it never imports the symlink.

**Comment by BlakeB415** [comment]
I had this issue as well.

I fixed it by removing ``torrent.Downloads.Count == 0 || ``
from this line https://github.com/rogerfar/rdt-client/blob/master/server/RdtClient.Service/Services/QBittorrent.cs#L299C40-L299C40

**Comment by pettytreebroker** [comment]
Thanks @BlakeB415 that worked, but now Radarr won't import the symlink because it can't determine if it's a sample. Wouldn't happen to have a solution for that too?

**Comment by bequbed** [comment]
Hi guys, I am getting the same error on Sonarr. How can I fix it ?
