### ISSUE TITLE
Large data usage through continuous websocket updates

### ISSUE THREAD

**Issue by jack-mil** [rogerfar/rdt-client#286]
**What version are you using?**
2.0.32
**What OS are you running?**
Debian 12
**Are you using Docker or as a service?**
Docker

I run Nginx Proxy Manager and route all my docker services through subdomains. Looking at the proxy logs, I noticed a surprisingly large amount of data transfer from my rdt-client endpoint. (14GB in 2 weeks time). I dug into and noticed the continous websocket updates when the page is loaded in a browser. I am guessing this system is for download progress updates. Depending on how many downloads are added to the client, this must be the cause of such a large data transfer.

![image](https://github.com/rogerfar/rdt-client/assets/62065280/173937aa-1858-4080-9f07-bced0677c05c)
![image](https://github.com/rogerfar/rdt-client/assets/62065280/c94ce0fe-c569-4749-a895-2983e810da26)

Maybe this is a necessary design decision and there is no way to avoid this, which would be fine. 
I could do several things to avoid this problem personally, like disable websocket support in NPM, remove finished downloads, avoid loading the webpage for long periods, etc...

Just wanted to bring this up in case it *wasnt* known about, and perhaps there is a solution to avoid sending as much data in the websocket replies.
One thing that came to mind is only send updates for downloads in progress, and ignore "completed" downloads. (The above screenshots is only 18 finished/completed downloads where no updates are needed, and each reply is 430kB

**Comment by rogerfar** [comment]
How often do you have the interface open in the browser? It's possible yes that it uses that much data, but the websockets only transmit data when you have the browser open.

**Comment by jack-mil** [comment]
I figured that was the case, and it's probably not a big deal. The main reason I noticed it was leaving the web page loaded on mobile while monitoring downloads over mobile data. Was just a little surprising because I was not expecting large data transfers for this tool
