### ISSUE TITLE
[Feature request] Two folders / Move downloads to a directory option

### ISSUE THREAD

**Issue by f3rr311** [rogerfar/rdt-client#287]
Have the downloader move files from download folder to a completed folder, this should be setabale as a path in the docker file

This would keep it in line with other download systems that use two separate folders to compartmentalize

**Comment by f3rr311** [comment]
Also wondering if you have ever thought about submitting to the unraid app listing ?

**Comment by rogerfar** [comment]
This could be solved with a custom post-download script, not the main focus of this app.
