### ISSUE TITLE
Torrents with Double Quotes always fail

### ISSUE THREAD

**Issue by seanbenton** [rogerfar/rdt-client#288]
**What version are you using?**
2.0.32
**Wat OS are you running?**
Windows 11
**Are you using Docker or as a service?**
Windows Service
**Please attach a log file here with the log setting set to debug**
Using Premiumize any torrent which loads containing double quotes "" always fails as shown. These files download with no problem in a web browser or using Jdownloader.
![image](https://github.com/rogerfar/rdt-client/assets/141379973/f47068e4-fe59-4495-b731-aeb3d6a64908)
Based on the error message this appears to be related to an invalid directory destination resulting from the double quotes.
![image](https://github.com/rogerfar/rdt-client/assets/141379973/32ac59a2-f5fd-41f4-acb9-6fa389a71ed8)

**Comment by rogerfar** [comment]
This seems to be a file path issue as Windows doesn't allow " in the file path.

This is fixed in the next version.
