### ISSUE TITLE
Can't add torrents, but speedtest is successful and directory permissions are fine

### ISSUE THREAD

**Issue by Shadowex3** [rogerfar/rdt-client#289]
**What version are you using?**
2.0.32

**Wat OS are you running?**
Ubuntu 22.04.2

**Are you using Docker or as a service?**
service with an unprivileged LXC also running prowlarr and qbittorrent

**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/12306011/rdtclient.log)

It's odd that I test successfully, if it slower speeds than I'd expect for gigabit fiber, but every attempt to add a torrent results in failure.

**Comment by Shadowex3** [comment]
I think this may be the same issue as #205 . What's confusing is the speedtest download works fine. If this was a firewall/connection issue you'd expect that to fail as well since it also relies on a connection to realdebrid.

**Comment by rogerfar** [comment]
Try increasing the timeouts in the settings.

**Comment by Shadowex3** [comment]
No dice unfortunately. I don't think that's the issue though, I can reach the REST API via curl in the terminal and the speedtest benchmark works fine. Both of those indicate my computer (and rdtc in particular) is capable of reaching realdebrid just fine and even interacting with my specific account.

It seems most likely for the breakdown to be somewhere inside rdtc with the mechanism that puts together an API call.

**Comment by rogerfar** [comment]
@Shadowex3 is this still occurring? If so, do you perhaps have a longer log?

**Comment by Shadowex3** [comment]
Nope, it's randomly working now for manual torrents. Just like the other error it seems to come and go on its own. Also for logs what I attached further up is everything from a single attempted torrent, anything "longer" would just be multiple attempts and the same lines repeated over and over.

**Comment by Shadowex3** [comment]
@rogerfar And the issue is back again. It seems like a signal to me whether it's busted or not is if I can see the version warning and also current premium status in the top bars. If I can't see those then something is wrong.

The thing is _nothing has changed_ and as before the download speed test still works perfectly, so rdtc can provably connect to real-debrid.

[rdtclient.log](https://github.com/rogerfar/rdt-client/files/12563948/rdtclient.log)

**Comment by rogerfar** [comment]
I added some extra error logging, can you try the new version and see if it still happens?

**Comment by Shadowex3** [comment]
I've updated, we'll see what happens. This error comes and goes without any apparent reason or pattern.

**Comment by Shadowex3** [comment]
So it worked at first, then had a brief period of not working, and is now "working" again... but with a different problem. Downloads will simply hiccup and repeat endlessly. They show as "Downloading file 1/1" with the percentage and speed but at some point the download progress resets. After a couple tries "1/1 downloads failed with errors". There is a file produced at the download location but it's never a complete one, it's like the download keeps randomly deciding to restart itself at some point during the process.

And then it gets weirder: There's no log file in the /rdtc/data/db/ folder anymore. I've tried stopping and restarting the service, rebooting the LXC, nothing.
