### ISSUE TITLE
Anyway to move from temp to the good folder automatically

### ISSUE THREAD

**Issue by billouetaudrey** [rogerfar/rdt-client#293]
Hello, sorry for my noob question

When I use sonarr, it display the good folder like /mnt/3T/Medias/Show/Blabla

But when download with rdt, it use folder set on the settings like /mnt/temp/

Any way to move file from /mnt/temp/ to /mnt/3T/Medias/Show/Blabla/

Thanks

**Comment by jeffjohnson11** [comment]
In sonarr settings -> download clients -> remote path mappings, create a new mapping that maps /mnt/temp to /mnt/3T/Medias

**Comment by billouetaudrey** [comment]
Hey,

seem not working, file stay on tv-sonarr folder

Host 192.168.1.48
Remote Path /mnt/virtual/Medias/tv-sonarr/
Local Path /mnt/virtual/Medias/Séries/

Any idea ? thanks

**Comment by rogerfar** [comment]
@billouetaudrey This seems to be a Sonarr issue.
