### ISSUE TITLE
Symbolic linking (symlinks)

### ISSUE THREAD

**Issue by JonnySiHI** [rogerfar/rdt-client#299]
Any plans for streaming from debrid services?

**Comment by JReming85** [comment]
You know most of them have webdav, ftp, etc.  

You could mount it using rclone and stream that way

**Comment by rogerfar** [comment]
I'm open for suggestions or PR's on how to solve this.

**Comment by pettytreebroker** [comment]
What I did was hack together a `SymlinkDownloader` that takes a mount path, searches it for the file to download, and creates a symlink to the file in the download directory.

PR here: https://github.com/rogerfar/rdt-client/pull/304 (First time writing .NET, so would not consider this at all production ready.)

**Comment by dreulavelle** [comment]
Could check out plex_debrid. It mounts rd through a forked and edited version of their rclone_rd. He's been working on artificial sorting (symlinking) as well and has a working one up on a branch. It's beta but seems to be working. 

Others have also gotten Filebot to work as well.

**Comment by dreulavelle** [comment]
Curious if theres been any development on this?

**Comment by rogerfar** [comment]
I have merged the Symlink downloader in the next version, if you can test it and let me know.

Also if you are still running into the occasional `Torrent finished, waiting for download links` please post a debug log, then I can see where it hangs on.

**Comment by JonnySiHI** [comment]
This is the error i get from sonarr using symlink downloader in real debrid client

`System.IO.FileNotFoundException: Could not find file "/downloads/tv-sonarr/Evolution.Earth.S01E01.mkv/Evolution.Earth.S01E01.mkv"
File name: '/downloads/tv-sonarr/Evolution.Earth.S01E01.mkv/Evolution.Earth.S01E01.mkv'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <d636f104d58046fd9b195699bcb1a744>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess)
  at NzbDrone.Common.Disk.DiskProviderBase.OpenReadStream (System.String path) [0x0001b] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:415 
  at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo (System.String filename) [0x0006e] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:59`

**Comment by Gaisberg** [comment]
Hi, first of all thanks alot @rogerfar for rdt-client and @pettytreebroker for creating the first implementation of symlink downloader. I started enhancing it as it felt pretty slow with seasons as it processed one download per torrent every cycle. I created an implementation for parallel processing [here](https://github.com/Gaisberg/rdt-client/tree/symlink_downloader_concurrency). Could you review the changes and see if this is viable? Im struggling to handle cases where the downloader where remoteId == null aka no file was found. Whats the best way to continue retry symlink.download() next cycle?

**Comment by JonnySiHI** [comment]
> You know most of them have webdav, ftp, etc.
> 
> You could mount it using rclone and stream that way

I was thinking maybe if it would be possible for RDTClient to mount the directories, then symlink those files into a chosen folder so that other programs can rename the files.

**Comment by JonnySiHI** [comment]
> > You know most of them have webdav, ftp, etc.
> > You could mount it using rclone and stream that way
> 
> I was thinking maybe if it would be possible for RDTClient to mount debrid, then symlink those files into a chosen folder so that other programs can rename the files.

Would this be possible?

**Comment by KINGLIFER** [comment]
patiently waiting for a tutorial.

**Comment by smoofus** [comment]
Would love a tutorial as well.  I've tried every combination I can think of with the download path and mapped path but radarr continues to show a qBittorrent error in the queue and never post processes the symlink.  I've set my rclone_rd mount path to the root of the mount '/storage/media/debrid' and set the radarr download client category to 'movies' since that is the subfolder rclone_rd has for movies.  I've tried setting the download path to the same directory as the rclone_rd mount but no luck... everything downloads but radarr does not get the message that it completed.  Has anybody gotten this to work? What the heck am I missing?

**Comment by Rodmodrtf** [comment]
first of thanks to all involved with this and the symlink downloader, loving it, is there any way to modify it to not wait for download links and just monitor/search for the file in /mnt/rd, some of the torrents gets stuck on waiting for download links and the file is already available in /mnt/rd and for this setup we don't need the download link.

**Comment by Pukabyte** [comment]
@smoofus the download path for the symlinks has to be seperate from the rclone debrid mount. Setup a directory for the symlinks eg: /mnt/symlinks and then create the category names inside that. it will create the symlink and place it in this directory for the arrs to pick up, rename and place into your plex library directory

**Comment by rogerfar** [comment]
If anyone could write a piece up for the readme, that would be greatly appreciated!
