### ISSUE TITLE
{Feature Request] Adjust password security options without having to rebuild

### ISSUE THREAD

**Issue by JReming85** [rogerfar/rdt-client#301]
Would love to be able to edit the password security settings without having to rebuild the project with adjusted settings.

**Comment by rogerfar** [comment]
Can you be more specific about what you are trying to accomplish here?

**Comment by JReming85** [comment]
Specifically expose these settings to be user adjustable.
https://github.com/rogerfar/rdt-client/blob/0a36a3fd204d168f84fbbebe4180a7b82d4c5bf0/server/RdtClient.Web/Program.cs#L81

```
builder.Services.AddIdentity<IdentityUser, IdentityRole>(options =>
       {
           options.User.RequireUniqueEmail = false;
           options.Password.RequiredLength = 10;
           options.Password.RequireUppercase = false;
           options.Password.RequireLowercase = false;
           options.Password.RequireNonAlphanumeric = false;
           options.Password.RequiredUniqueChars = 5;
       })
```

**Comment by rogerfar** [comment]
You mean they are too strict or not strict enough? What do you rebuild it with?

**Comment by rogerfar** [comment]
I'll lower it in the next version.
