### ISSUE TITLE
Docker failing : Getting error Filename too long

### ISSUE THREAD

**Issue by mk2134226** [rogerfar/rdt-client#303]
Getting this error

[14:29:02 ERR] BackgroundService failed
rdtclient    | System.Threading.Tasks.TaskCanceledException: A task was canceled.
rdtclient    |    at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
rdtclient    |    at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
rdtclient    | Setting permissions
rdtclient    | chown: changing ownership of '/data/downloads/radarr/Fantastic Beasts The Secrets of Dumbledore (2022) (2160p HMAX WEBRIP SDR x265 HEVC 10bit DDP5.1 Hindi + English) [ZiroMB]/Fantastic Beasts The Secrets of Dumbledore (2022) (2160p HMAX WEBRIP SDR x265 HEVC 10bit DDP5.1 Hindi + English) [ZiroMB].mkv': Filename too long

**Comment by rogerfar** [comment]
What OS?
