### ISSUE TITLE
Help with Run external program on torrent completion

### ISSUE THREAD

**Issue by subexx** [rogerfar/rdt-client#305]
I have installed rdt-client in Synology NAS. I want to run a curl command after download is finished. I can't enter the whole command in the run program session. so i created a script. How should i enter it in the settings.

I have tried the below but nothing happens.
/volume1/Videos/Watch/post-process.sh
watch/post-process.sh

**Comment by rogerfar** [comment]
Please post a screenshot of your settings.

**Comment by rogerfar** [comment]
If it's still an issue please file a new issue with new logs.
