### ISSUE TITLE
"FIles unpacked" error

### ISSUE THREAD

**Issue by ManvirDehal** [rogerfar/rdt-client#307]
I have installed version 2.0.37 in docker on ubuntu 22.04 with RealDebrid as the provider. Whenever I download this torrent (linked below) I get a "Files unpacked" status. I let it sit overnight but nothing has changed. In Sonarr, it says it is still downloading so I can't import it yet. 

TORRENT LINK: https://1337x.to/torrent/3243849/South-Park-1997-Season-15-S15-Extras-1080p-BluRay-x265-HEVC-10bit-AAC-5-1-RCVR-QxR/

Unfortunately, I don't know how to get the logs from RDTClient.

**Comment by rogerfar** [comment]
That sounds an error on the RealDebrid side as it's not an error on RDT client. Please follow the bug template when reporting issues.
