### ISSUE TITLE
Select wanted files

### ISSUE THREAD

**Issue by answer35** [rogerfar/rdt-client#310]
**What version are you using?**
2.0.37
**Wat OS are you running?**
Debian
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
Alldebrid
**Please attach a log file here with the log setting set to debug**

Would it be possible to add feature so we can disable files that are not needed to download. For example when you download a torrent which contains many files but you already have few of them so you can disable the download for those only and download the rest of the files ?

**Comment by rogerfar** [comment]
Unfortunately the AllDebrid API doesn't allow this functionality, that's why it's not available.

Only Real-Debrid has this.
