### ISSUE TITLE
s6-rc-compile Error on New Install

### ISSUE THREAD

**Issue by dreulavelle** [rogerfar/rdt-client#313]
**What version are you using?**
Latest

**What OS are you running?**
Alpine

*uname -a:*
`Linux web 6.2.16-12-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-12 (2023-09-04T13:21Z) x86_64 Linux`

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Real-Debrid

**Please attach a log file here with the log setting set to debug**
After setting up the Docker Compose and running it.. 

```
s6-rc-compile: fatal: unable to read /etc/s6-overlay/s6-rc.d/init-addusser/type: No such file or directory
```

**Comment by MervinJMinky** [comment]
Same issue since docker update.

**Comment by Muneer91** [comment]
Same issue here. Tried removing config and starting fresh, same issue

**Comment by quorn23** [comment]
Reverting back to [2.0.37](https://github.com/users/rogerfar/packages/container/rdtclient/124764597?tag=2.0.37) and it starts up fine, looks related to this commit https://github.com/rogerfar/rdt-client/commit/5c3d35701914d4f3440fa47f779a6796c9e80149

**Comment by danielandastro** [comment]
Same issue, reverting fixed it

**Comment by BlueBull010** [comment]
Same issue here. I thought it was because I was running it on unraid, since I just installed it yesterday. Apparently not. I'll try reverting as the other comments say, thanks!

**Comment by rogerfar** [comment]
Try 2.0.39

**Comment by quorn23** [comment]
```
09/21/2023 3:57:34 PM
Starting rtdclient
09/21/2023 3:57:34 PM
[15:57:34 WRN] Using an in-memory repository. Keys will not be persisted to storage.
09/21/2023 3:57:34 PM
[15:57:34 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
09/21/2023 3:57:34 PM
[15:57:34 WRN] No XML encryptor configured. Key {affb4bde9-e338-43a4-b346-654de0a932} may be persisted to storage in unencrypted form.
09/21/2023 3:57:34 PM
[15:57:34 WRN] Starting host on version 2.0.39.0```

Looks good. Starts up and seems to work.
Small fyi - Account - Version still says .37

**Comment by BlueBull010** [comment]
Confirmed, 2.0.39 fixes it. Don't know if you have changed anything more in the mean time but in my case (docker container on unraid) the version info does say 2.0.39 correctly
