### ISSUE TITLE
Symlinks downloader

### ISSUE THREAD

**Issue by laster13** [rogerfar/rdt-client#315]
Thank you for the latest RTD version which allows you to create symlinks between the local folder and the rclone remote, it works very well.
is it possible after decompressing the rar files to transfer to the rclone folder while keeping a symlink locally

**Comment by Guiro28** [comment]
An option to exclude .rar searches from the cache would be really perfect. My setup only works with cache and Rclone_rd.

Overseerr > *arr > rdtclient > rclone_rd > Plex

Plex read files directly from cache and an option to not extract archives locally would be perfect.

**Comment by laster13** [comment]
https://discord.com/channels/1021692389368283158/1146586109665607810/1155238278828671057
it's work
