### ISSUE TITLE
Unable to find ID for magnet

### ISSUE THREAD

**Issue by BetyOops** [rogerfar/rdt-client#318]
**What version are you using?** 
2.0.39

**Are you using Docker or as a service?**
Docker on Synology

**Which debrid provider are you using?**
Alldebrid

**Please attach a log file here with the log setting set to debug**
**Log on Sonarr:**

Couldn't add report to download queue. Sex.Education.S04.MULTI.VFF.1080p.10bit.WEBRip.6CH.x265.HEVC-FERVEX: Failed to connect to qBittorrent, check your settings.

HTTP Error - Res: [POST] http://192.168.2.149:6500/api/v2/torrents/add: 500.InternalServerError (28 bytes)
Unable to find ID for magnet

**Log on Docker:**

[_rogerfar-rdtclient1_logs.txt](https://github.com/rogerfar/rdt-client/files/12723761/_rogerfar-rdtclient1_logs.txt)

Thank you

**Comment by rogerfar** [comment]
What is the magnet?

**Comment by BetyOops** [comment]
No magnet, rdt download threw Sonarr or Radarr. 

I use ygg or torrent911.

I can direct download manually .torrent file but with sonarr i have actually this error on multiple torrent.

**Comment by rogerfar** [comment]
Does this still happen with the latest versions?

**Comment by BetyOops** [comment]
Hi,

It s ok since a few version. I have another problem (but it s just "cosmetic"): the percentage download is ok but speed stay at 0.00kb/sec.
