### ISSUE TITLE
Feature Request: Delete Download Within Certain Time

### ISSUE THREAD

**Issue by ManvirDehal** [rogerfar/rdt-client#322]
I see that there is already a feature to remove downloads or if they fail, but would it be possible to remove downloads within a certain time regardless of if they're finished or not?

This would be extremely useful for me as some downloads hang with "Files Unpacked" or "Getting Download Links" as their status and they are not removed with the current remove download option. 

Thank you for all the amazing work you've put into this project

**Comment by rogerfar** [comment]
I believe that is the `Torrent maximum lifetime` setting.

**Comment by ManvirDehal** [comment]
But this setting doesn't affect finished torrents that are stuck with "Files Unpacked" or "Getting Download Links"

**Comment by rogerfar** [comment]
Those shouldn't be stuck anyway, do you have logs when they are stuck in that state?

**Comment by rogerfar** [comment]
If it's still an issue please file a new issue with new logs.
