### ISSUE TITLE
New Alldebrid api ?

### ISSUE THREAD

**Issue by TEALC82** [rogerfar/rdt-client#324]
**What version are you using?**
2.0.39
**Wat OS are you running?**
Debian 12
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
Alldebrid
**Please attach a log file here with the log setting set to debug**
https://pastebin.com/Uyehag57

`Unable to deserialize AllDebrid API response to MagnetUploadResponse. Response was: { "status": "error", "error": { "code": "MAINTENANCE", "message": "Alldebrid is under maintenance, please retry later" } }`

**Comment by rogerfar** [comment]
Not much we can do about that, maybe a status message on the index page would be handy.
