### ISSUE TITLE
Sub folders from premiumize.me are being flattened when downloading.

### ISSUE THREAD

**Issue by kungfoolfighting** [rogerfar/rdt-client#325]
I looked at the code of your fix for the premiumize.me subfolder issue https://github.com/rogerfar/rdt-client/issues/281.
This new implementation will flatten the folder hierarchy.
If you download a music album with 2 CDs where the individual CDs are in the CD1 and CD2 subfolder, you will now download everything to the root folder of the download and the tracks of both CDs will be interleaved.
The PR that I opened (https://github.com/rogerfar/rdt-client/pull/283) adds target download folders to the downloads to solve this issue. This of course makes the code a little more complicated, but I think this change is necessary. Other than that, your fix is similar to mine, but adds a lot more debugging logs, that I don't have.
Could you please add this functionality as well? Currently this is preventing me from updating to your upstream version from my fork, because I think this is necessary to fix.

**Comment by rogerfar** [comment]
Could you send a test torrent through pastebin?

**Comment by rogerfar** [comment]
If it's still an issue please file a new issue and provide logs.
