### ISSUE TITLE
Downloads fail to download

### ISSUE THREAD

**Issue by reddit-reaper** [rogerfar/rdt-client#329]
**What version are you using?**
2.0.40

**Wat OS are you running?**
Windows

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Real-Debrid

**Please attach a log file here with the log setting set to debug**
[rdtclient_007.log](https://github.com/rogerfar/rdt-client/files/12865251/rdtclient_007.log)

Issue im having is that every download sits at 0b/s and then just does a loop of re-downloads. I saw the same pattern in premiumizerr app as well until i moved to using jdownloader2 as the downloader and it was much better but not really an option for RD in this scenario.

Any ideas?

**Comment by rogerfar** [comment]
Can you try with the latest version and see if it happens again?

**Comment by reddit-reaper** [comment]
Sorry completely missed this. I'll have to setup my test environment again but yes I'll let you know

**Comment by rogerfar** [comment]
If it's still an issue please open a new issue with new logs.
