### ISSUE TITLE
dotnet RdtClient.Web.dll wont work with .NET 7

### ISSUE THREAD

**Issue by Tyoryn** [rogerfar/rdt-client#330]
Most recent version I think.  Installed 10/07

Debian

As a Service

Real-Debrid

~/rdtc# dotnet RdtClient.Web.dll
You must install or update .NET to run this application.

App: /root/rdtc/RdtClient.Web.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.11 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=debian.12-x64

Not sure how to proceed with the install.  Did I install the wrong .Net? Is this the same as the issue with 2.0.20?

**Comment by rogerfar** [comment]
You have to install .NET 6.

**Comment by Tyoryn** [comment]
I thought so but can't seem to find a package to install it. I Tried last night to follow Microsoft's instructions and just change the 7 to a 6 and seemed to work but version check still says 7

**Comment by Tyoryn** [comment]
Was able to install 6 with snap and now all good.  Thanks for clearing up that it needed to be exactly 6 and that 7 isn't backwards compatible.
