### ISSUE TITLE
Multiple Files in torrent staying in download path

### ISSUE THREAD

**Issue by Tyoryn** [rogerfar/rdt-client#332]
**What version are you using?**
Current

**What OS are you running?**
Debian 12

**Are you using Docker or as a service?**
as a service

**Which debrid provider are you using?**
Real-Debrid

I just finished getting my whole setup working and tested it by downloading a movie but the torrent fed to rdt-client had multiple files in it.   Some shorts, some behind the scenes, stuff like that.  When everything was done only the main movie file moved from the download path to the storage path, which was great.  The problem is the remaining files stayed behind taking up space.  Someone on reddit told me the "remove completed" check box in the download client settings should be removing these but I have that option enabled.

Also totally separate side note, is there a way to have downloads paused or to pause passing new download requests from a set time until another set time?  Everyone I spoke to about that says that's usually an option with most download clients but none of them were familiar with rdt-client or debrid at all.

**Comment by rogerfar** [comment]
If you have the setting `Finished action` set when adding a new torrent to `Remove torrent from Client` it will delete the files.

If not, please post a log.
