### ISSUE TITLE
External program not running

### ISSUE THREAD

**Issue by tobyworks** [rogerfar/rdt-client#334]
**What version are you using?**
Latest
**Wat OS are you running?**
Windows
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
RD
**Please attach a log file here with the log setting set to debug**

Whatever i try to do i cannot get the external program to run after download is finished.

<img width="1399" alt="image" src="https://github.com/rogerfar/rdt-client/assets/2817395/586db6dd-dc64-476c-9f22-b4f9d2c109d9">

Running the script with bin/sh while connected to the docker container is no problem at all

<img width="817" alt="image" src="https://github.com/rogerfar/rdt-client/assets/2817395/7ce5b477-b748-41f5-96da-d3a952b0e2e7">

I verify if the script has ran by checking if there's a new random files created with a random number. but whatever i tried it does not get created

**Comment by screamjojo** [comment]
Your external program arguments isn't correct.

![image](https://github.com/rogerfar/rdt-client/assets/71469935/6867c0c3-5794-4713-b32c-7f36017d128c)
