### ISSUE TITLE
I can't download the file using either ALLDEBRID or REALDEBRID.

### ISSUE THREAD

**Issue by Walkerman59** [rogerfar/rdt-client#337]
**What version are you using?**
version 2.0.40.0
**Wat OS are you running?**
WINDOWS 11
**Are you using Docker or as a service?**
YES
**Which debrid provider are you using?**
ALLDEBRID
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/13047378/rdtclient.log)
error  : 
 2023-10-19 21:15:01.101 +01:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: Unable to read data from the transport connection: Connection reset by peer

**Comment by ikrowni** [comment]
Ever figure this out. Im struggling with helping a friend get this setup on his windows computer but hes running into pretty much the same issue

**Comment by Walkerman59** [comment]
I haven't found any solution for the moment; I have simply used ARIA2C as a workaround for now.

**Comment by rogerfar** [comment]
Please try the new version it uses a new internal downloader, should fix it.
