### ISSUE TITLE
Premiumize.me: Torrents in state seeding don't get downloaded

### ISSUE THREAD

**Issue by Turmoil1112** [rogerfar/rdt-client#338]
**What version are you using?**
rdt-client 2.0.40
**Wat OS are you running?**
TrueNAS
**Are you using Docker or as a service?**
Truecharts container
**Which debrid provider are you using?**
premiumize.me
**Please attach a log file here with the log setting set to debug**
will do so if neccessary

With premiumize.me it can happen that a torrent is instantly in state *seeding*. This happens when somebody else (our yourself) already transfered the same torrent as you and it is still cached on their servers. rdt-client will map this state to TorrentStatus.Uploading
https://github.com/rogerfar/rdt-client/blob/ee0a631cd99534c19bf2904da0541d3e576fd2a0/server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs#L203
It seems that this state will keep it from starting a download.
https://github.com/rogerfar/rdt-client/blob/ee0a631cd99534c19bf2904da0541d3e576fd2a0/server/RdtClient.Service/Services/TorrentRunner.cs#L496-L498C18

An example response for api/transfer/list looks as followed

    {
        "status": "success",
    	"transfers": [
    		{
    			"id": "AOzE[redacted]]n8VUseOQ",
    			"name": "Torrent Name",
    			"message": "Seeding at ratio 0.27 of 2.00 - 2 day(s), 20 hour(s) left",
    			"status": "seeding",
    			"progress": null,
    			"folder_id": "vIF0[redacted]]zkkYmzg",
    			"file_id": null,
    			"other_cloud_id": null,
    			"src": "https:\/\/www.premiumize.me\/api\/job\/src?id=AOzE[redacted]]n8VUseOQ"
    		}
    	]
    }

This torrent has (at least for the current user) never been in state *finished* so it stays as *Torrent uploading* in the web interface.
It seems a quick and dirty fix would be to change the mapping of *seeding* to *TorrentStatus.Finished* in [PremiumizeTorrentClient.cs](https://github.com/rogerfar/rdt-client/blob/ee0a631cd99534c19bf2904da0541d3e576fd2a0/server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs#L203).

**Comment by rogerfar** [comment]
Makes sense, fixed in the next version.
