### ISSUE TITLE
[Feat Idea] Jackett proxy to prioritise already cached torrents

### ISSUE THREAD

**Issue by Cucumberrbob** [rogerfar/rdt-client#339]
Been loving using this stack so far. Great job!

One thing that happens frequently that I haven't experienced with other debrid/plex solutions is uncached torrents being requested. 
This stack is fairly new to me, so it would be good to get others' thoughts on this idea, hence the issue:
Jackett could be put behind a proxy which modifies the number of peers returned from the indexer if the torrent is cached via the debrid provider. This should encourage radarr/sonarr to grab cached releases first.
Is this out of scope for this project? I can see both ways - it's almost a necessary piece but it lives on the opposite side of radarr/sonarr.
Have I missed a simpler solution?

**Comment by timcoop3r** [comment]
Feels a bit out of scope and complete to me to be honest? That should be a function of Jacket's or Prowlarr (I use this over Jackett now as its integrates with Radarr/Sonarr really nicely) if they wanted a feature like that?

On a similar topic though, are you using Trash Guides to set your custom formats (Doesn't sound like it if you are reliant of the number of seeders)? This generally scores the release you actually want to grab higher anyway, and 99.99% of the time these are the ones that are already cached. I'd say it's essential for any Radarr/Sonarr setup. 
I'd also heavily advise using Recyclarr as well to keep this in sync with updates to the guides. It's effort to setup but well worth it and would probably solve the problem you are having.

**Comment by Cucumberrbob** [comment]
Thanks for the recyclarr tip - I think that will solve my issues in a much simpler way.
Was some good practice for me learning rust though so it wasn't all in vain. 
I'll close this issue, and update this comment with my source code in a little bit in case anyone else wants this.
