### ISSUE TITLE
Feature request: Integrate with nzbtomedia

### ISSUE THREAD

**Issue by phirestalker** [rogerfar/rdt-client#34]
First of all, thanks for a nice piece of software. I was lucky to find this because I was planning to develop something very similar. You saved me lots of time.

Please consider integrating with https://github.com/clinton-hall/nzbToMedia

They have a script for torrents. Integration with this would allow rdt-client to notify SB, Radarr, Headphones, etc. when the download is complete or if it failed.

**Comment by rogerfar** [comment]
I'm not 100% sure what this would do exactly. It's not using NZB at all and when a torrent is finished it will inform Radarr/Sonarr that it's completed.

**Comment by phirestalker** [comment]
So, basically, the script gets called when an NZB or torrent is finished downloading by the downloader. Then, in my case, SickChill will post process the show that was just downloaded. 
Yes, I see that radarr works beautifully. I was hoping to have this work with SickChill, which is able to scan the directory periodically.  The problem with this method is that it has no way of knowing that the torrent failed and that it needs to grab a new one.
The script is only called NZBtoMedia because NZBs were all it was designed for when it was first created. Now, it is able to handle torrents as well.

**Comment by rogerfar** [comment]
@phirestalker are you still using nzbToMedia? I had a quick look through the API here:
https://github.com/clinton-hall/nzbToMedia/blob/9d64c2f47869584ebf3ca269632e1f03a461f99e/libs/common/qbittorrent/client.py

and it seems that only the sync metadata was missing, now that's implemented it might work.

**Comment by phirestalker** [comment]
I haven't touched Sickrage in about a year. I now get all my shows streaming.
