### ISSUE TITLE
Torrents Stuck in Various States

### ISSUE THREAD

**Issue by thaynes43** [rogerfar/rdt-client#340]
**What version are you using?**

2.0.40

**Wat OS are you running?**

unRAID

**Are you using Docker or as a service?**

Docker

**Which debrid provider are you using?**

RealDebrid

**Please attach a log file here with the log setting set to debug**

Logs were changed to debug and issue was reproduced but the Info logs are at the top.

<img width="206" alt="image" src="https://github.com/rogerfar/rdt-client/assets/4860853/eecd6c46-c7c5-4792-9d70-e82fd87e5466">

[rdtclient_004.log](https://github.com/rogerfar/rdt-client/files/13177320/rdtclient_004.log)

Hey Arnold, Doug, and Rugrats as well as a few other things that show up in the logs did not download cleanly or import into sonarr/radarr. Some were hung on "files unpacked". Others downloaded completely but Sonarr would complain that no files were present in the directory. The files were present while it was downloading, I checked that, but they were gone when sonarr tried to copy them over. I also experienced a massive amount of downloads that just reported they were in an error state, I think this was due to all the timeouts in the logs. 

This exception also popped up a lot, not sure what impact it has:

```
2023-10-26 08:35:10.808 -04:00 [ERR] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
RDNET.RealDebridException: infringing_file
```

I should also note that when I tried the links provided in rdt-client in RealDebrid I was able to stream the content fine so it seems to have cached it. 

Let me know if the logs provide enough information or if I should try and configure things to make it easy to reproduce this issue. Things don't always to to rdt-client but these shows seemed to heavily prefer torrents.

**Comment by thaynes43** [comment]
New round of things are stuck:
<img width="84" alt="image" src="https://github.com/rogerfar/rdt-client/assets/4860853/8311f2ba-4d83-4133-81c2-24c96c3c6853">
I'm not sure what Files Unpacked means.

**Comment by rogerfar** [comment]
`RDNET.RealDebridException: infringing_file` means that the file was removed from RealDebrid and you can't download it.

For the last error please open a separate issue with a full log.
