### ISSUE TITLE
Option to add all files of a torrent/magnet as individual downloads

### ISSUE THREAD

**Issue by mrkrauz123** [rogerfar/rdt-client#342]
I am currently running version 2.0.40 on docker and I am trying to find a way to add all files of a torrent/magnet as individual downloads. I am trying to do this because currently if I add a torrent to rdtclient through e.g. sonarr it needs to download the whole torrent file, so for example all 10 episode files in order for sonarr to see the download as completed and import the files. A common scenario would be : I add a torrent of a series to rdtclient through sonarr. Sonarr recognizes this and sees that the torrent is currently downloading. Rdtclient will start downloading the 10 files. Let's assume the first file is finished and rdtclient moves on to file 2 and is currently at 10%. Now if I look in sonarr in the "Activity" tab it says that all 10 files for this torrent have been downloaded up to 10% even though the first file has already finished and the other 8 files haven't been downloaded at all. The way it works right now requires all of the 10 files to be downloaded in order for rdtclient to report back to sonarr as "Finished" and only then can sonarr import the files even though it could have started with the first file 10 minutes ago when it was done with it. It would be easiest if the rdt client could add every single file as their own downloads and report back the download progress individually so that sonarr could import while the rest of the files are being downloaded.

I hope it is alright that I posted this issue as a blank issue because this is not a bug report and I wasn't sure to ask this otherwise.

**Comment by rogerfar** [comment]
Unfortunately this would be more suited as a request to Sonarr as this is just taking commands from Sonarr.
