### ISSUE TITLE
Premiumize hangs on "Torrent finished, waiting for download links"

### ISSUE THREAD

**Issue by hieronymu** [rogerfar/rdt-client#344]
**What version are you using?**
2.0.4.0
**Wat OS are you running?**
Synology | DSM 7.2
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
Premiumize
**Please attach a log file here with the log setting set to debug**
I do not see anything interesting in there.
[_rogerfar-rdtclient1_logs.txt](https://github.com/rogerfar/rdt-client/files/13223886/_rogerfar-rdtclient1_logs.txt)

This was working fine until a few weeks ago. Not sure if there was a change on the rdt end or the premiumize end. Everything is working fine until the download stage, when torrents hang in either of two states:
- Torrent finished, waiting for download links
- Queued to download

**Comment by Varming73** [comment]
I have the same problem but with Real Debrid

**Comment by Varming73** [comment]
I have now tested with both 2.0.49 and 2.0.40 in docker on Unraid. Same result: Torrent finished, waiting for download links
Maybe 2/3 of my downloads works flawless but the rest are stuck with this status.

I've also tried to change the CDN (out of desperation) but that didn't change anything.

**Comment by Cucumberrbob** [comment]
> This crap just started for me once I upgraded to the newest version. This needs to be looked at ASAP. I am using real debrid as well.

The tone of this message is quite entitled. You appear to have made an account to post this comment which is next to useless. Rogerfar clearly tells you proper logs are needed, but all the information you give is your debrid provider.  You didn’t take any steps to help get this issue resolved, or share what things you tried.

Rogerfar gives up time for free to maintain this project.  We should be a tad more grateful.

FWIW, if I start rclone after (dockerised) rdt-client, I get similar behaviour with torrents stuck as above.

**Comment by Varming73** [comment]
Fully agree. Are you able to provide logs? I would prefer not to have to upgrade just to reproduce the error

**Comment by kingkunta88** [comment]
I'm having the same issue. tried to rollback to 2.0.46 (didn't do it fresh though) and same thing. Here's some log. I'm running it in a docker container on unraid. 
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/13596870/rdtclient.log)

**Comment by rogerfar** [comment]
@kingkunta88 Your logs are full of errors, like:
```
RdtClient.Service.Services.Downloaders.SymlinkDownloader: Error creating symbolic link from /realdebrid/movies/Olympique Marseille - Olympique Lyonnais 06.12.2023.mkv/Olympique Marseille - Olympique Lyonnais 06.12.2023.mkv to /data/downloads/sports/Olympique Marseille - Olympique Lyonnais 06.12.2023.mkv/Olympique Marseille - Olympique Lyonnais 06.12.2023.mkv: Could not find a part of the path '/data/downloads/sports/Olympique Marseille - Olympique Lyonnais 06.12.2023.mkv/Olympique Marseille - Olympique Lyonnais 06.12.2023.mkv'.
```

**Comment by hieronymu** [comment]
I found an interesting error when I retry downloads marked as `Queued to download`

```
21:36:13 DBG] Retry download ddf01bdc-89a4-46b8-a65b-6f37617691b3
[21:36:13 DBG] Retrying Download for download https://[path-and-filename].mp4. Completed: -2147483648%, avg speed: 0bytes/s (ddf01bdc-89a4-46b8-a65b-6f37617691b3) for torrent [torrent name] - finished 100%) (8a7a9b03-e4a9-43f4-b561-724eb55da0f8)
```

Specifically: `Completed: -2147483648%`

**Comment by rogerfar** [comment]
Please try with the latest version, is it still an issue?

**Comment by Varming73** [comment]
I've switched to pukabyte/rdtclient:latest and have had no problems since then. It's based on an old version of RDT

**Comment by balor55** [comment]
Just updated to 2.0.53 and the "Torrent finished, waiting for download links" issue persists using real-debrid and docker using the symlink downloader. 
Log: [rdtclient.log](https://github.com/rogerfar/rdt-client/files/13847379/rdtclient.1.log)

**Comment by pcassar383** [comment]
I have the same issue in Windows- "Torrent finished, waiting for download links" on every torrent.  Restarting the service causes all of the torrents to switch to finished and everything moves on perfectly.  Any new torrents get the "Torrent finished, waiting for download links" message.

**Comment by rogerfar** [comment]
I added some logging, but most points to that the mount doesn't contain the file, and thus cannot complete the symlink process.

Not sure what the expected result is here, how long does it take for the file to show up on your mount? Should there be a certain that it will fail, or should it fail right away?

**Comment by pcassar383** [comment]
[log.txt](https://github.com/rogerfar/rdt-client/files/13865120/log.txt)

I've attached the part of my log (I am using Real Debrid) from when it happens, then a restart of the app, then it moving on as expected.

Thanks for any help!

**Comment by balor55** [comment]
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/13865829/rdtclient2.log)

Updated to 2.0.54 and grabbed another log. This file was visible on the mount almost immediately (rclone mount of real-debrid) after download to provider and while rdt client was showing "waiting for download links". Then after awhile  I pushed the Retry Torrent and it completed normally. My current work around is to have the container restart on a schedule to clear up any lingering stalled files. Seems to only be the symlink downloader but I didn't test the internal for very long.

 I didn't notice anything obviously different in the log but I'm not sure what I'm looking for, so hopefully it is useful!

Thanks for looking into this! If there is anything I could try or report on to help narrow this down just ask.

**Comment by rogerfar** [comment]
I think that this is the issue:
```
2024-01-08 19:29:41.899 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Starting symlink resolving of https://sea2.download.real-debrid.com/d/HVXELDZV6BCWG22/Movie.Title.mkv, writing to path: /data/downloads/radarr/Movie.Title/Movie.Title.mkv
2024-01-08 19:29:41.899 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Searching /mount/torrents for Movie.Title.mkv
2024-01-08 19:29:42.862 +00:00 [INF] RdtClient.Service.Services.Downloaders.SymlinkDownloader: File Movie.Title.mkv not found on /mount/torrents!
```

I think I need to change that process to be on a timer and check periodically if the file is copied over properly.

**Comment by rogerfar** [comment]
Is this still an issue in the latest version? It should keep checking for the file.

**Comment by rogerfar** [comment]
If it's still an issue feel free to open a new issue.
