### ISSUE TITLE
Not Downloading to PC?

### ISSUE THREAD

**Issue by GitHubQueenn** [rogerfar/rdt-client#345]
Using Windows 10. Using Jackett, Sonarr, & this client. I have it all setup correctly and RDTClient is automatically grabbing links and putting them on my Real-Debrid account, but then how do I get them to download to my PC once that happens? On RDTClient, it shows download status as "Finished" but the files are nowhere on my actual PC. Not using Docker. I have my mapped path set to "D:/" if that matters and using internal downloader (edit: ok, weird, I guess you can't use slashes on here because I have a slash after "D:" but GitHub keeps taking it out).

**Comment by rogerfar** [comment]
Review your settings, you don't need Download Mapping, just set your download path.
