### ISSUE TITLE
Am I Able to Choose My Download Source for Anime?

### ISSUE THREAD

**Issue by BelaBoxGitHub** [rogerfar/rdt-client#346]
So, I have Jackett, Sonarr, & RDTClient setup with Real-Debrid. It seems RDTClient downloads the shows I want, but from random sources (users) instead of the people I usually get certain shows from. Is it possible to tell the program only to download from certain users on Nyaa?

**Comment by cremonies** [comment]
Yeah. You do all that stuff in sonarr. This is just a downloader.

**Comment by rogerfar** [comment]
No you will have to manage this all in the processes before RDT-Client.
