### ISSUE TITLE
Feature request: option to only import links from provider

### ISSUE THREAD

**Issue by cremonies** [rogerfar/rdt-client#347]
Under provider settings, you only have the option to automatically import and process Torrence added to provider. I would like the option to only import and not automatically start downloading them to my host.

**Comment by rogerfar** [comment]
Fixed in the next version.

**Comment by cremonies** [comment]
I'm sorry, I don't quite know if I'm applying the settings correctly or if I communicated it wrong.
Should settings under provider "Automatically import and process torrents added to provide" be turned on or off?

Add link to debrid provider.
Expected result:
File appears in rdt client without downloading to host.
User can then manually start download to host.

Actual result:
File is downloaded to host.


![Screenshot_20240119-152110](https://github.com/rogerfar/rdt-client/assets/108636173/326991f5-31bb-4a5b-9850-d130cde1d598)
