### ISSUE TITLE
Feature Request: Schedule Download. 

### ISSUE THREAD

**Issue by letunglam** [rogerfar/rdt-client#35]
I would like to download movie at night so my family will not complain about how slow our internet is. I know there is speed limit but it would be great if we also have Schedule Download feature.

**Comment by jctennis** [comment]
I second this. A Scheduler would be to adjust the speed limit or restrict downloads at specified times would be amazing!

**Comment by philamp** [comment]
I totally second this, and there would also be 

- a button to manually trigger the download (with or without scheduling set)
- and so the status would be different between: 
  - a "finished ready to be downloaded item" 
  - and a "fully locally downloaded item"

**Comment by philamp** [comment]
@jctennis / @letunglam : this is achevable with this : https://github.com/rogerfar/rdt-client/issues/185 (implemented) and a bash file and a cron

**Comment by jack-mil** [comment]
This would be a great featuring mirroring some of the capabilities of qBittorrent itself!

**Comment by rogerfar** [comment]
At the moment I don't think this will make it in, it's probably better to use the aria2c downloader as it has that functionality built in.
