### ISSUE TITLE
Getting issue with Docker on Apple Silicon M1 : qemu-x86_64: Could not open '/lib/ld-musl-x86_64.so.1': No such file or directory

### ISSUE THREAD

**Issue by vnguyen42** [rogerfar/rdt-client#355]
**What version are you using?**
v2.0.46

**Wat OS are you running?**
Mac OS Monterey - Apple Silicon M1

**Are you using Docker or as a service?**
Docker

I was trying to update the docker image to the latest version, building works fine, however when running the image, I got the following error in the Docker logs : 

2023-11-18 05:12:14 rdtclient  | Setting permissions
2023-11-18 05:12:14 rdtclient  | Changing to /app folder
2023-11-18 05:12:14 rdtclient  | Starting rtdclient
2023-11-18 05:12:14 rdtclient  | qemu-x86_64: Could not open '/lib/ld-musl-x86_64.so.1': No such file or directory

I tried adding --platform linux/arm64 as some people suggested on StackOverflow to solve the issue but it didn't worked.

**Comment by maxexcloo** [comment]
Same issue for me, did you find a fix?

**Comment by vnguyen42** [comment]
> Same issue for me, did you find a fix?

Non I ended up installing the .NET version outsider of Docker and it Works fine

**Comment by rogerfar** [comment]
Can you try with the latest docker?
