### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by Tyoryn** [rogerfar/rdt-client#356]
**What version are you using?**
2.0.40

**Wat OS are you running?**
debian

**Are you using Docker or as a service?**
service

**Which debrid provider are you using?**
real-debrid

Got a banner that says new version v2.0.46 was found.  I looked all over settings and the readme and have no clue how to update to the new version... am I just dumb?

**Comment by profucius** [comment]
Dev is often MIA so I'll answer your question. You have two options: 1) run the "Update.ps1" file in the directory you installed this software, or 2) Open Services.msc and stop RealDebridClient service. Then Download the zip file in the Releases section of this github, extract it to where you installed the software (before!! make a backup of your AppSettings.json file in the software install directory). Then copy your AppSettings.json back and overwrite. Now start the service again or reboot your machine. Should be working as expected.

**Comment by Tyoryn** [comment]
Finally got around to doing this and now rdt-client won't load at all.  It just comes up a blank white screen or not at all.  I first tried the .PS1 update and then the 2nd method and no luck.  Only thing I can think of is I ran apt upgrade after installing powershell and maybe that updated .NET to the wrong version.

**Comment by profucius** [comment]
You may need to download .NET8 and install it manually. The dev made it mandatory in a recent version. Same thing happened to me but it got fixed after I installed net 8 sdk.

**Comment by Tyoryn** [comment]
Well that explains it I think.  Had to jump through a million hoops to get .NET 6 a few months ago since 8 wasn't working and now it needs 8 lol.  I'll see if that fixes it tonight and if so close the issue.  Thanks

**Comment by profucius** [comment]
Yeah I'm not happy with the dev pushing changes like this directly into production. You can see this happening in the releases changelogs, he adds something then rolls it back next version, then adds something and rolls it back again. It's a bit amateur, there should be a beta version for testing features before it's rolled to everyone.

The very least I would expect the dev to do would be to add a section of text to all release changelogs, to mention any major changes. Such as ".NET8 is now required as of X version" and this text would appear at the bottom of every changelog for ~3 months, to ensure nobody loses track and then wonders why their install broke.

Moral of the story, we must read every changelog between current and new, before updating this particular software. But it is free, so I suppose can't complain too much.

**Comment by rogerfar** [comment]
@profucius Sorry that it's not up to your standard. It's a project that I hosted here and had no intention of it growing into something. I have a full time job, a family and lots of other things to do. This project is far on the bottom of my list of priorities.

The changelog says that it's upgraded to .NET 8, the amount of tickets that are just shot in here without ANY sort if self investigating is seriously demoralizing, everyone just wants to use, but not put in the effort.

**Comment by profucius** [comment]
@rogerfar Did not mean to offend you, I do appreciate your development in this software. With that said, I think some of the issues that popup could be mitigated with more clear communication, such as the rolling major changes added to every release for a certain amount of time (e.g. .NET8 required) because things like that do get swept under the rug with rapid releases. It's also not obvious to a lot of people that it's required. 

You could alternatively place a header on the Readme about this with a timestamp/version-stamp of the required change. Anyway I can't speak to the other issues you face with complainers, but please don't get disheartened. A lot of us lurkers like the software and don't speak up often. Cheers.

**Comment by Tyoryn** [comment]
@rogerfar Sorry, didn't mean to start any drama.  I'm really new to GitHub (only really started using it for this actually). Honestly took me ages to even find the .zip files, and didn't even know there was a change log to check.  I started asking questions here because the *arr reddit groups can be pretty hostile about your project and Debrid.  I really appreciate your work since with my setup a VPN isn't really an option so without you I'd have 0 download automation. Thank you for all your work, it is greatly appreciated.
