### ISSUE TITLE
Height of individual rows changes frequently when progress is made in torrents list

### ISSUE THREAD

**Issue by belidzs** [rogerfar/rdt-client#358]
**What version are you using?**
2.0.46

**Wat OS are you running?**
Container on k3s on linux

**Are you using Docker or as a service?**
Container

**Which debrid provider are you using?**
RD

**Please attach a log file here with the log setting set to debug**

I'm using Firefox 119.0.1.

When I have an item in the torrents list which is in one of the downloading phases, the length of the text in the `Status` column constantly changes (ex: `Downloading file 1/10 (83.68% - 4.83 MB/s) `).

Due to the varying length of this message, the text sometimes fits in one line, but sometimes it has to break into two. When it changes from state to another, the whole row has to expand into two lines, or go back into one which makes the table look a little "jittery".

**Comment by rogerfar** [comment]
I would rather keep it fluid so it's easier to work with on mobile and responsive layouts, if you have a suggestion to make it better let me know.
