### ISSUE TITLE
Docker update

### ISSUE THREAD

**Issue by phirestalker** [rogerfar/rdt-client#36]
I am using docker-compose and pulling from rogerfar/rdtclient in the compose file. It is stuck on version 1.6.0.
What must I do to upgrade to 1.6.4?

**Comment by rogerfar** [comment]
Where does it show 1.6.0? If it is in the interface try doing a hard refresh `CTRL+F5`.

**Comment by phirestalker** [comment]
Yes in the interface and hard refresh does not work. I ran docker-compose up -d which should pull the updated image, but it says up to date.
Is there a way to check the image version to verify it has the latest image?

**Comment by rogerfar** [comment]
Run `docker images ls`, it shows the version there.

**Comment by phirestalker** [comment]
that command shoes nothing, but if I leave off ls it shows:
rogerfar/rdtclient              latest              df41df311e90        8 days ago          262MB

**Comment by rogerfar** [comment]
Are you pulling with `docker pull rogerfar/rdtclient:latest`? The latest image ID is `f1c8b79c3b5f`.

**Comment by phirestalker** [comment]
I didn't have the latest tag in the docker-compose.yml file. I put it in and did a dcoker-compose up -d which some instructions say will pull the latest image. It doesn't seem to work.
I did do the docker pull command that you posted and that worked. Thanks
Is docker-compose up -d supposed to pull an updated image if I have rogerfar/rdtclient:latest?

**Comment by rogerfar** [comment]
No it doesn't do that by itself, you have to manually pull in the latest image.

**Comment by phirestalker** [comment]
It is on the right one now.
