### ISSUE TITLE
RdtClient has a memory leak on Windows

### ISSUE THREAD

**Issue by khooniatma** [rogerfar/rdt-client#360]
**What version are you using?**
v2.0.46

**Wat OS are you running?**
Windows 10

**Are you using Docker or as a service?**
Service

**Which debrid provider are you using?**
Real Debrid

**Please attach a log file here with the log setting set to debug**

There seems to be a clear memory leak on Windows. The memory utilization of `RdtClient.Web.exe` keeps on linearly increasing as it downloads the file. At one point the overall memory consumption becomes equal to the total amount of physical memory in the machine, at which point `RdtClient` crashes. 

For cases where the download finishes before the maximum physical memory is reached, the occupied memory is never released back. Restarting the client instantly releasing the memory back to the system. There is nothing in the debug logs which point to a memory leak. This is based on observing the memory statistics of the system.

**Comment by larsgrah** [comment]
I can confirm the same on Linux/Docker

**Comment by Kwesty4658** [comment]
I am also experiencing memory leaks on Linux, specifically as a docker container on unraid.

**Comment by larsgrah** [comment]
After reverting to v2.0.40 the memory leak stopped, it seems to be a recent release that caused it

**Comment by rogerfar** [comment]
Try the latest version, should be good now.

**Comment by adiberk** [comment]
Seeing this issue latest docker image
