### ISSUE TITLE
[Feature] EasyNews support

### ISSUE THREAD

**Issue by GrabbenD** [rogerfar/rdt-client#361]
EasyNews is a service similar to Real-Debrid, AllDebrid and Premiumize, it allows you to search/access cached files.
However, this one is designed particularly for Usenet content (and you even [stream](https://www.reddit.com/r/StremioAddons/comments/13oyjjt/new_addon_easynews/) the files live with Stremio or Kodi+Fen).

Would love to hear what you guys think about adding support for this 🙂

**Comment by rogerfar** [comment]
If anyone wants to write a provider they can make a PR.
