### ISSUE TITLE
watch folder in docker

### ISSUE THREAD

**Issue by tjengbudi** [rogerfar/rdt-client#362]
hello how to describe setting to add watch folder ?
where is the default location?
so i can map it

**Comment by rogerfar** [comment]
There is so little effort in your question it doesn't make any sense.

**Comment by tjengbudi** [comment]
@rogerfar 

hello sorry for short statement from me.
i already map my localdrive/watch:/data/watch in my docker-compose
after that i put in setting watch path "/data/watch"

save and trying add some .torrent into localdrive/watch, but nothing happen. i wonder that the /data/watch is not created. but i checked from portainer container console. and i found that /data/watch is automatically create and linked.

so.. i do not know what make me cannot set the watch path. it might have default value so i asked for that. 

or i have set the watch path in wrong way?

**Comment by tjengbudi** [comment]
@rogerfar 
the permission change to 755 to works. i used 664 before.
thanks
