### ISSUE TITLE
I have been getting corrupted files since 2.0.46

### ISSUE THREAD

**Issue by rjdailey** [rogerfar/rdt-client#363]
**What version are you using?**
2.0.49

**Wat OS are you running?**
Linux

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Real-Debrid

**Please attach a log file here with the log setting set to debug**

Speeds keep dropping down to 0 while downloading and I end up with glitches in my video files. I downgraded to 2.0.40 and it is working fine.

**Comment by MtnDewster** [comment]
I can also confirm this has been an issue for me. I thought it was Jellyfin transcoding errors, but after viewing the downloaded file in VLC it also appears there. These artifacts do not appear in the RD Player from the RealDebrid website.

**Comment by theRoundGreek** [comment]
same here. if i re-download the file directly from real-debrid they're ok

**Comment by rogerfar** [comment]
Are you using the internal downloader? I updated the downloader to a new version so it should be fixed now.
