### ISSUE TITLE
Feature request : save torrent file 

### ISSUE THREAD

**Issue by Merrick28** [rogerfar/rdt-client#364]
**What version are you using?**

Docker version 2.0.49

**Wat OS are you running?**

Linux - Ubuntu 22.04

**Are you using Docker or as a service?**

Docker

**Which debrid provider are you using?**

Real Debrid

----------

Hello I'd like to save the torrent file that is pushed to rdt, in order to download/seed the selected torrent from another seedbox (to avoid H/R and keep some ratio). Do you think it's possible ?

**Comment by rogerfar** [comment]
I added a new setting under General: `Copy added torrent files`. This will copy torrent and magnet files to this directory.
