### ISSUE TITLE
Updated to 2.0.49.0 and now I can't download anything, fails to connect to RealDebrid

### ISSUE THREAD

**Issue by pickinanameainteasy** [rogerfar/rdt-client#366]
**What version are you using?**
2.0.49.0

**Wat OS are you running?**
Windows 10

**Are you using Docker or as a service?**
Service

**Which debrid provider are you using?**
Real Debird

**Please attach a log file here with the log setting set to debug**
[rdt-log.txt](https://github.com/rogerfar/rdt-client/files/13536961/rdt-log.txt)

I updated to 2.0.49.0 from 2.0.45.0 and now authentication seems to be broken. Normally upon updating all my settings are saved but I kept getting an error on the Move-Item line in the Update.ps1 file. It kept saying it can't move a file where one already exists or something like that. 

I have refreshed the apitoken 3 times and can confirm it is correct. In sonarr i do a test and it says it works, I attempt to do a download speed test and it never finishes it doesn't show results while the results and permissions test complete correctly. The logs say that it is downloading the test file but then it cancels it with no results.

I normally just go to Services and stop the RealDebridClient service and start it again tif anything goes wrong, but now if i go there it has Stop greyed out as if it isn't running. And when I try to start it it shows this error.

`Windows could not start the RealDebirdClient service on Local Computer

Error 1053: The service did not respond to the start or control request in a timely fashion`

I deleted the application from my machine and deleted the service, rebooted the machine, redownloaded the zip, and extracted, updated appsettings.json, ran the service-install.bat, which completed, then started the service. Configured everything thru web ui, can confirm real debrid api key is correct and being used successfully with stremio app but now when attempt to call the /api/torrents from this app it just gives me the failed to connect to real debrid error. Dont know what could be persisting between installs but if there are any other settings in different locations please advise, it doesnt make since to me that a botched update would break the app even after reinstalls

**Comment by cubbieblue16** [comment]
The newest version has been a freaking disaster. I cannot download anything either. It keeps saying it's waiting for download links.

**Comment by pickinanameainteasy** [comment]
Hmm, here i was thinking i broke something. Gonna try to downgrade and see if it works

**Comment by rogerfar** [comment]
@pickinanameainteasy If you would read your logs:
```2023-12-02T17:35:12.7726357Z Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.UnauthorizedAccessException: Access to the path 'C:\Users\me\Documents\logs\rdt-client' is denied.```

**Comment by pickinanameainteasy** [comment]
> @pickinanameainteasy If you would read your logs: `2023-12-02T17:35:12.7726357Z Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.UnauthorizedAccessException: Access to the path 'C:\Users\me\Documents\logs\rdt-client' is denied.`

As you can see even without that error and downgrading i am still unable to connect and i dont know why: 
[rdt-log.txt](https://github.com/rogerfar/rdt-client/files/13538052/rdt-log.txt)

**Comment by pickinanameainteasy** [comment]
@rogerfar ok, i set the timeout to 30 and now i dont see that error anymore but now when i select a magnet in sonarr it sends a POST request to rdt-client which is recorded in rdt logs but the magnet never appears in rdt-client and never gets downloaded.

No logs showing a failure either but in sonarr it shows red cloud icon as if the download failed.

Any advice?

[rdt-log-3.txt](https://github.com/rogerfar/rdt-client/files/13548218/rdt-log-3.txt)
![Screenshot_20231204-093300](https://github.com/rogerfar/rdt-client/assets/86267611/cfbfc4da-8d2d-4af1-9704-102d4b1409fd)

**Comment by rogerfar** [comment]
Did you restart the service after you changed the settings? The logs aren't showing really anything.

**Comment by pickinanameainteasy** [comment]
@rogerfar yes i have restarted the service and it is still doing nothing on red-client when sending the download but shows the red cloud on sonarr

**Comment by pickinanameainteasy** [comment]
@rogerfar sorry for blowing you up here. I read the wrong logs, it was still getting the failed to connect to real debrid error. After upping timeout to 60 it seems to be working but i will continue to test. Thanks

**Comment by cubbieblue16** [comment]
Guys the fix to this since the response here is "I cant replicate the error" is to downgrade to 2.0.46 and the download links thing is gone.  Problem solved.
