### ISSUE TITLE
[BUG] Parameters for external program arguments are incorrect

### ISSUE THREAD

**Issue by vanchaxy** [rogerfar/rdt-client#369]
**What version are you using?**
v2.0.49

The rdt-client uses different formatting of external program argument parameters compared to qBittorrent. For a single-file torrent named "hello" with file "world.txt" and download path "C:\Downloads":

In rdt-client:
%F - C:\Downloads\hello;
%R - C:\Downloads;
%D - C:\Downloads\hello;

while in qBittorrent:
%F - C:\Downloads\hello\world.txt; (or the same as %R for a multiple-file torrent)
%R - C:\Downloads\hello;
%D - C:\Downloads;

**Comment by rogerfar** [comment]
This should be fixed now and returns the content path when there is only 1 file in the resulting directory.
