### ISSUE TITLE
Invalid torrent causes sickchill to silently fail

### ISSUE THREAD

**Issue by phirestalker** [rogerfar/rdt-client#37]
When a torrent is immediately recognized as invalid, SickChill says "qBittorrent: Unable to send Torrent".
Is there any way with the qBittorrent api to signal a failure that allows it to try again as it would for a failed download? If not can an option be added to send back sucess code even on invalid bittorrent? Or should SickChill be handling it different?

**Comment by rogerfar** [comment]
I don't use sickchill, but if it implements the qBittorrent API then it should be able to recognize errors.

**Comment by phirestalker** [comment]
From my research, it seems that the qBittorrent 4.1 API only sends one kind of error, an HTTP code 415. I am going to contact sickchill and see what they recommend.

**Comment by rogerfar** [comment]
When it says "qBittorrent: Unable to send Torrent" what does the log show in RDT? Is it an actual invalid torrent?

**Comment by phirestalker** [comment]
I don't know about log, but in the main interface it does say invalid torrent.

**Comment by rogerfar** [comment]
I'm going to close this, if this is still and issue that needs to addressed, feel free to open it again.
