### ISSUE TITLE
Download speed  display not working since 2.0.49

### ISSUE THREAD

**Issue by sylvaindd** [rogerfar/rdt-client#370]
**What version are you using?**
2.0.49

**Wat OS are you running?**
Debian

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
AllDebrid

Download speed is not displayed anymore on "Downloading file" (it stays at 0 B/s) although it is downloading (progress in % is increasing).
It does work on "Torrent downloading"
![image](https://github.com/rogerfar/rdt-client/assets/5629405/8fb41de3-ea42-44b4-9628-4ac6514ae82d)

**Comment by rogerfar** [comment]
This should be good in the next version.
