### ISSUE TITLE
Question:  How to update when running as windows service?

### ISSUE THREAD

**Issue by Mahava** [rogerfar/rdt-client#374]
Hi Roger,

I'd like to update from .40 to .49
I've always unzipped the update to my install folder overwriting everything except the settings files.  Then restart the service.
This time it didn't work and the service wouldn't start.

I also tried running the powershell update script, but it didn't update.

What's the proper way to update?

-thanks

**Comment by rogerfar** [comment]
You will have to either download the package from here by hand or use the Update.ps1 powershell yes. If it doesn't work, please be more specific what doesn't work.

**Comment by litLizard69** [comment]
Instructions on how to update rdt-client via Update.ps1:

1. Navigate to the rdt-client directory
2. Right click to open the context menu and open terminal/powershell while holding Ctrl and Alt (this will open Powershell as administrator)
3. Execute ".\Update.ps1"
4. The Update.ps1-Script will run and update rdt-client
Done.
