### ISSUE TITLE
Error on startup in Docker: "s6-applyuidgid: fatal: unable to exec dotnet: Exec format error"

### ISSUE THREAD

**Issue by jackkerouac** [rogerfar/rdt-client#375]
**What version are you using?**
Latest

**Wat OS are you running?**
Ubuntu 22.04

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Real-Debrid

Setting permissions
Changing to /app folder
Starting rtdclient
s6-applyuidgid: fatal: unable to exec dotnet: Exec format error
Setting permissions
Changing to /app folder
Starting rtdclient
s6-applyuidgid: fatal: unable to exec dotnet: Exec format error
Setting permissions
Changing to /app folder
Starting rtdclient
s6-applyuidgid: fatal: unable to exec dotnet: Exec format error

... and it repeats. It never actually starts. I have automatic updates on, so I am assuming something updated and made me sad. Any help would be appreciated.

**Comment by Rodmodrtf** [comment]
I had the same issue on arm64 while the container is running do the following:
docker exec -it /bin/bash (this will take you into the containers bash)
While inside the container run this:
wget https://download.visualstudio.microsoft.com/download/pr/c3bf3103-efdb-42e0-af55-bbf861a4215b/dc22eda8877933b8c6569e3823f18d21/aspnetcore-runtime-8.0.0-linux-musl-arm64.tar.gz && wget https://download.visualstudio.microsoft.com/download/pr/88a7d8f6-e27b-4a43-91a4-233cd40daed5/350c9d253971d0ac527f016e145323dd/dotnet-sdk-8.0.100-linux-musl-arm64.tar.gz && tar zxf aspnetcore-runtime-8.0.0-linux-musl-arm64.tar.gz -C  /usr/share/dotnet && tar zxf dotnet-sdk-8.0.100-linux-musl-arm64.tar.gz -C /usr/share/dotnet

exit (to exit the container)

docker restart rdtclient

**Comment by jbonadiman** [comment]
Just had this error and the solution worked for me too.

**Comment by rogerfar** [comment]
This is now fixed with the newest docker version as it had the wrong arm packages.
