### ISSUE TITLE
Possibility to use rsync or cp ?

### ISSUE THREAD

**Issue by billouetaudrey** [rogerfar/rdt-client#376]
Hey, my alldebrid folder is mount on /mnt/alldebrid/magnets

Is it possible to use cp or rsync to my download folder ?

Like

cp /mnt/alldebrid/magnets/tadam.mkv /mnt/Medias/Show/Tada/

Maybe more fast as download client ?

Thanks

**Comment by rogerfar** [comment]
You will have to use a post download script, or maybe the symlink downloader.
