### ISSUE TITLE
Not downloading files

### ISSUE THREAD

**Issue by sflix** [rogerfar/rdt-client#377]
What version are you using? 
Latest (2.0.49)

Wat OS are you running?
Synology

Are you using Docker or as a service?
Docker

Which debrid provider are you using?
RealDebrid

Problem 

Torrents  get stuck either in Torrent waiting for file selection or Torrent finished, waiting for download links.

**Please attach a log file here with the log setting set to debug**
[log.txt](https://github.com/rogerfar/rdt-client/files/13625444/log.txt)

**Comment by beljim** [comment]
Did you find a solution. I have the same issue. Torrent finished, waiting for download links from RD

**Comment by dinjojo** [comment]
> Did you find a solution. I have the same issue. Torrent finished, waiting for download links from RD

Use the 2.39 version the latest version seems to be not working

**Comment by dinjojo** [comment]
Just to be sure I'm using symlink not internal downloader and it seems to have broken post 2.39

**Comment by bsadecki** [comment]
@sflix: If you enable debug logging, do you see the following?

`Completed: -2147483648%`

**Comment by rogerfar** [comment]
I updated the internal downloader to a new version, it should be more stable now.
