### ISSUE TITLE
The connection to RealDebrid has failed: Resource temporarily unavailable (api.real-debrid.com:443)

### ISSUE THREAD

**Issue by jaymcalli** [rogerfar/rdt-client#378]
It worked for days, then all of a sudden I get the following error.

**What version are you using?**

2.0.49

**Wat OS are you running?**

Debian 12

**Are you using Docker or as a service?**

Docker

**Which debrid provider are you using?**

Real Debrid

**Please attach a log file here with the log setting set to debug**

System.AggregateException: One or more errors occurred. (Resource temporarily unavailable (api.real-debrid.com:443))

**Comment by rogerfar** [comment]
Sometime RD isn't available.
