### ISSUE TITLE
Login Credentials

### ISSUE THREAD

**Issue by this-is-eric** [rogerfar/rdt-client#379]
**What version are you using?**
2.0.49
**Wat OS are you running?**
Windows 10
**Are you using Docker or as a service?**
Service
**Which debrid provider are you using?**
Real Debrid
**Please attach a log file here with the log setting set to debug**

Is there a way to view or reset login credentials? I can't attach sonarr unless the authentication type is set to "no authentication." I do not recall entering credentials during setup other than my real-debrid login and pass (and api key), these do not work when entered into the qbittorrent in sonarr.

**Comment by this-is-eric** [comment]
Edit: deleting the db file and restarting the service seemed to have no effect

**Comment by rogerfar** [comment]
They are your login username password. If you delete the database file you can re-setup your password.
