### ISSUE TITLE
s6-applyuidgid: fatal: unable to exec dotnet: Exec format error

### ISSUE THREAD

**Issue by Reen68** [rogerfar/rdt-client#380]
**What version are you using?**
2.0.49
**Wat OS are you running?**
OMV
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
RD
**Please attach a log file here with the log setting set to debug**
Can't attach as none is created.

Since pulling the latest image (has been a while now, but im running a compose with all radarr, sonarr, VPN etc. together - if it stops for whatever reason and I restart i usually use that moment to pull the newest containers) it's not launching rdtclient anymore.

At the start process it says:

Changing to /app folder
Starting rtdclient
s6-applyuidgid: fatal: unable to exec dotnet: Exec format error

and will do this forever until i force stop.

**Comment by Rodmodrtf** [comment]
I had the same issue on arm64 while the container is running do the following:
docker exec -it rdtclient /bin/bash (this will take you into the containers bash)
While inside the container run this:
wget https://download.visualstudio.microsoft.com/download/pr/c3bf3103-efdb-42e0-af55-bbf861a4215b/dc22eda8877933b8c6569e3823f18d21/aspnetcore-runtime-8.0.0-linux-musl-arm64.tar.gz && wget https://download.visualstudio.microsoft.com/download/pr/88a7d8f6-e27b-4a43-91a4-233cd40daed5/350c9d253971d0ac527f016e145323dd/dotnet-sdk-8.0.100-linux-musl-arm64.tar.gz && tar zxf aspnetcore-runtime-8.0.0-linux-musl-arm64.tar.gz -C /usr/share/dotnet && tar zxf dotnet-sdk-8.0.100-linux-musl-arm64.tar.gz -C /usr/share/dotnet

exit (to exit the container)

docker restart rdtclient

**Comment by Reen68** [comment]
Thank you very much, that worked.
