### ISSUE TITLE
Add TorBox.app as part of services

### ISSUE THREAD

**Issue by Wamy-Dev** [rogerfar/rdt-client#383]
TorBox is very similar to Real-Debrid, Alldebrid and Premiumize and has a full API located at https://api-docs.torbox.app.

The website is https://torbox.app

**Comment by TEALC82** [comment]
+1

**Comment by Pukabyte** [comment]
Another +1 on this.
Would love to see an implementation of it.

The API is similar to realdebrid and documentation can be found here:
[https://api.torbox.app/docs](https://www.postman.com/wamy-dev/workspace/torbox/collection/29572726-4244cdaf-ece6-4b6d-a2ca-463a3af48f54)

There's also a realdebrid translation guide here:
[https://www.postman.com/wamy-dev/workspace/torbox/collection/29572726-4244cdaf-ece6-4b6d-a2ca-463a3af48f54](https://www.postman.com/wamy-dev/workspace/torbox/collection/29572726-4244cdaf-ece6-4b6d-a2ca-463a3af48f54)

**Comment by Source-Kod** [comment]
+1
