### ISSUE TITLE
Download speed dropping to 0B/s and halting download continuously.

### ISSUE THREAD

**Issue by sxpekez** [rogerfar/rdt-client#384]
**What version are you using?**
Latest 2.0.49

**Wat OS are you running?**
TrueNAS Scale

**Are you using Docker or as a service?**
Tried both - Currently as Docker TrueCharts app. 

**Which debrid provider are you using?**
Real-Debrid

**Issue**
Download goes to 0B/s and halts every few seconds, then starts up again. It is making the download take 5-10x longer than usual. This is only happening on newer versions. I have set up rdtclient on docker using version 2.0.39 and not had any issues with the download speed. I can see other people have noted issues where the speed shows 0B/s, but looks to be a different issue as theirs continues to download while showing 0B/s, mine is halted until the speed ramps up again. 
I do not have a log file, but have a video of what is happening.
https://streamable.com/jm2dzd

**Comment by rogerfar** [comment]
I updated the internal downloader to a new version, it should be more stable now.
