### ISSUE TITLE
Feature Request: blocklist errored torrents in Arrs

### ISSUE THREAD

**Issue by Pukabyte** [rogerfar/rdt-client#386]
Upon a failed download or error of a torrent or even a manual deletion, is there a way that it can communicate with the arrs to blocklist that torrent and trigger a search again?

This feature is built into sabnzbd and found it really helpful instead of having to go in manually, delete the torrent and then do a manual research of the failed torrent or a torrent that got deleted in rdtclient whether manually or automatic.

Thanks again for this project! Amazing work!

**Comment by rogerfar** [comment]
Doesn't it do this right now? It should at least as the torrent reports back as an error.

**Comment by Pukabyte** [comment]
At the moment it doesn't, it reports an error, but doesn't blocklist the torrent in arrs.

**Comment by colt45rpm** [comment]
From the *arr wiki - https://wiki.servarr.com/sonarr/settings#Failed_Download_Handling

Failed Download Handling is only compatible with SABnzbd and NZBGet.

Failed Downloading Handling does not apply to Torrents nor are there plans to add such functionality.
