### ISSUE TITLE
401/402/403 when trying to navigate

### ISSUE THREAD

**Issue by hobsie** [rogerfar/rdt-client#388]
**What version are you using?**
2.0.53.0

**Wat OS are you running?**
Ubuntu 23.10 Server (as Virtualbox guest, Windows 10 Host)

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Real-Debrid

**Please attach a log file here with the log setting set to debug**

> 2024-01-06 21:54:32.920 +00:00 [WRN] : Starting host on version 2.0.53.0
> 2024-01-06 21:54:47.601 +00:00 [WRN] : 402: /Api/Authentication/IsLoggedIn
> 2024-01-06 21:55:00.425 +00:00 [WRN] : 403: /Api/Authentication/IsLoggedIn
> 2024-01-06 21:55:05.401 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 21:55:45.677 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 22:06:45.643 +00:00 [WRN] : Starting host on version 2.0.53.0
> 2024-01-06 22:07:40.092 +00:00 [WRN] : 403: /Api/Authentication/IsLoggedIn
> 2024-01-06 22:07:44.115 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 22:07:48.009 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 22:07:51.827 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 22:07:56.310 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 22:08:00.130 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 22:08:13.951 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 22:08:18.072 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 22:08:26.309 +00:00 [WRN] : 401: /Api/Settings
> 2024-01-06 22:08:31.459 +00:00 [WRN] : 101: /hub
> 2024-01-06 22:08:39.790 +00:00 [WRN] : 403: /Api/Authentication/IsLoggedIn
> 2024-01-06 22:08:43.771 +00:00 [WRN] : 401: /Api/Settings

First time install. Once the container is up and running I can access the register page, add an API key and then login, but 9 times out of 10 it kicks me back to the login page when trying to navigate in the web interface leaving these warnings in the log. Have added '- logger.level=DEBUG' to the compose .yaml but just seem to be getting warnings. (I've tried a few clean setups, destroying the container and deleting the rdtclient.db each time)

**Comment by hobsie** [comment]
Left the container running over night and it seemed to be more stable for a few minutes before going back to the same behavior. Managed to turn on Debug in the options page before that happened but nothing useful coming from that it seems (I mustn't have turned on debug logging correctly in the docker script, could you confirm what that should look like? Couldn't find it in the documentation):

> [12:42:57 INF] ProviderUpdater started.
[12:42:58 DBG] Found 0 not completed torrents
[12:42:58 DBG] TorrentRunner Initialized
[12:42:58 INF] UpdateChecker started, currently on version v2.0.53.
[12:42:58 INF] WatchFolderChecker started.
[12:43:01 DBG] Method: GET, Path: /Api/Torrents
[12:43:04 WRN] 401: /Api/Settings
[12:43:07 DBG] Method: GET, Path: /Api/Torrents
[12:43:51 WRN] 401: /Api/Settings
[12:43:58 DBG] Method: GET, Path: /Api/Torrents
[12:44:02 WRN] 401: /Api/Settings
[12:44:06 DBG] Method: GET, Path: /Api/Torrents

**Comment by rogerfar** [comment]
Are you using a reverse proxy or a baseHref?

**Comment by hobsie** [comment]
Not that I'm aware of - the VM is currently running in bridged mode so i'm accessing directly from my windows host workstation as ipaddress:6500 in chrome

**Comment by hobsie** [comment]
Closing this out as it seems to be working fine without me changing anything from other machines on the same network so I'm going to chalk this one down to my workstation setup being the issue
