### ISSUE TITLE
Possible Memory Leak in 2.0.35

### ISSUE THREAD

**Issue by RemmyLee** [rogerfar/rdt-client#389]
**What version are you using?**
2.0.35

**Wat OS are you running?**
Arch Linux

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
RealDebrid

**Please attach a log file here with the log setting set to debug**
![image](https://github.com/rogerfar/rdt-client/assets/2806556/6eddb05d-a13e-4851-8ea4-415ce5f60518)

![image](https://github.com/rogerfar/rdt-client/assets/2806556/9a6734dd-a39c-4747-ac99-771eca4bc7e8)

Looks like memory is not freeing in the latest version. This system has 96GB of RAM and it's consuming the entire things before completely locking up.

**Comment by n1nj444** [comment]
Hi, 

same for me. If you could find an workaround please 🙏

**Comment by rogerfar** [comment]
I'm assuming you are using the internal downloader?

**Comment by n1nj444** [comment]
What do you mean by internal downloader?

Yes, the problem increases as the download progresses (so once the torrent is available, once it has been unbridled by AllDebrid).

I had to manually reboot my Synology because I couldn't access anything anymore. I rolled back to version v2.0.49 and everything is working normally again.

**Comment by RemmyLee** [comment]
Yes. Using internal. It seems to be slowly increasing over time, even when idle.
![image](https://github.com/rogerfar/rdt-client/assets/2806556/06241fcd-7a49-4eee-85e5-efbbe0918ef4)

Started a download and then stopped it.
Not releasing the memory:
![image](https://github.com/rogerfar/rdt-client/assets/2806556/80e4a878-b651-445a-9367-ef09cb4bfee4)

**Comment by EulogioGallo** [comment]
Same issue happening to me. Also using internal downloader.

**Comment by rogerfar** [comment]
I tweaked the downloader a bit, can you check again if it's an issue? I tried downloading 6x 12GB files in parallel, with a chunkcount of 20, and so far it doesn't go above 1GB.

If you're shy for memory I do recommend using aria2 as the .NET implementations will never be as good.

**Comment by RemmyLee** [comment]
Apologies for the delay. Just saw this. Testing now.

**Comment by n1nj444** [comment]
Hello, did someone tested the last update ?

**Comment by poulay007** [comment]
i still have issues about memory with my docker

**Comment by Carlosjrlu** [comment]
I have issues with memory on my docker instance too, I downloaded a few episodes with radarr a few hours ago. The memory usage is still high.
![image](https://github.com/user-attachments/assets/7fd24b1a-f994-4c06-b1bb-a5218a8802d9)
