### ISSUE TITLE
Downloads stuck at 100%

### ISSUE THREAD

**Issue by bientavu** [rogerfar/rdt-client#390]
**What version are you using?**
v2.0.54

**Wat OS are you running?**
Ubuntu 22.04

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Alldebrid

**Which downloader are you using?**
Internal Downloader

**Please attach a log file here with the log setting set to debug**
No log file, or is there a specific folder where I can find ? (docker container logs doesn't give anything)

**Description**
Hello I tried the last v2.0.54 version and at first I was really happy because it fixed some issues I had with the v2.0.49 version: download speed was inconsistent, it went sometimes from 20.00 MB/s to 0 MB/s, then back to 20.00 MB/s. It worked but wasn't really ideal because sometimes it stays at 0 MB/s for quite a long time. Anyway v2.0.54 fixed that so that's good.

But unfortunately now there is a more problematic issue: downloads are stuck are 100% when finished and that's it. I can see the file but it's broken and of course it is not automatically moved to the correct Media folder. Here is a screenshot:

![image](https://github.com/rogerfar/rdt-client/assets/72080798/e542d980-a1f5-42e7-bb5f-2513a371f3cd)

EDIT: check the log file as DEBUG, nothing in particular, I can see the API calls but that's it. Also after a looong time I can see that the download continued for another episode and then it's re-stuck at 100%. In this screenshot you can see that it's at 4/12, so it's going on but it is stuck way too much time at 100% before going to the next episode (downloads is the first screenshot were completed by switching back to v2.0.49):

![image](https://github.com/rogerfar/rdt-client/assets/72080798/97658d14-e002-4f5e-80aa-b114b20d8d9f)

Do you know what could be the issue ?

Thanks a lot!

**Comment by rogerfar** [comment]
See https://github.com/rogerfar/rdt-client/issues/344

**Comment by bientavu** [comment]
@rogerfar if i'm not mistaken, #344 is related when the download is finished on the provider side no? In my case this step doesn't come with any errors, it's after when the download is finished at 100% on the client side. Or I'm missing something ?

**Comment by rogerfar** [comment]
Sorry you are right,

**Comment by bientavu** [comment]
@rogerfar that's weird because with v2.0.49 I had no problem with unpacking and moving the files are done instantely and the other downloads can start (I have 2 download max at the same time). It's with v2.0.54 that the problem came.

Btw I tried v2.0.57 and it's even worse in terms of download speed, it's very very slow.

[rdtclient.log for v2.0.54](https://github.com/rogerfar/rdt-client/files/13890671/rdtclient.log)

**Comment by Bulletbling** [comment]
> @rogerfar that's weird because with v2.0.49 I had no problem with unpacking and moving the files, it was done instantely and the other downloads could start right away after the finished ones (I have 2 download max at the same time). It's with v2.0.54 that the problem came.
> 
> Btw I tried v2.0.57 and it's even worse in terms of download speed, it's very very slow.
> 
> [rdtclient.log for v2.0.54](https://github.com/rogerfar/rdt-client/files/13890671/rdtclient.log)

I can agree. I am on 2.0.40 because later versions have either a slow download speed, or downloads continue going past 100% and never end.

**Comment by rogerfar** [comment]
@bientavu what am I looking for in the logs?
