### ISSUE TITLE
Only downloading 1 file out of 9 and then erroring

### ISSUE THREAD

**Issue by doobersn** [rogerfar/rdt-client#391]
**What version are you using?**
Newest version 
**Wat OS are you running?**
unraid 
**Are you using Docker or as a service?**
yes
**Which debrid provider are you using?**
real debrid
**Which downloader are you using?**
internal downloader 
**Please attach a log file here with the log setting set to debug**

I’ve only ran into this a couple times but I tried downloading a cached file several times the other night and it will only download (sometimes not even fully download) 1 out of 9 episodes. It will then error out.

**Comment by rogerfar** [comment]
Please post a log.

**Comment by blackice1580** [comment]
I think i'm having a similar issue as well on unraid docker. Downloading 3 files, 1 completed and the other 2 failed with this error in the docker log "Download reported an error: The SSL connection could not be established, see inner exception.". They are 100% downloaded to real-debrid. When downloading it will get to about 3-6% then drop back to 0% and log the error shown above.

**Comment by iamsaleeb** [comment]
I am having the exact same issue, and also experiencing the same error message as @blackice1580. Running the latest version.

**Comment by janaxhell** [comment]
I have never touched those settings, always had 0 (unlimited) I have now tried with both 6 and 0 and got a rather slow speed, an average of 18Mb/s out of possible 116 Mb/s reached with JDownloader. Download didn't fail, but speed was very low. It usually went faster than that.
