### ISSUE TITLE
download reset

### ISSUE THREAD

**Issue by ozkansoyturk** [rogerfar/rdt-client#392]
**What version are you using?**
Latest docker image, v2.0.57
**Wat OS are you running?**
Fedora
**Are you using Docker or as a service?**
yes
**Which debrid provider are you using?**
alldebrid
**Which downloader are you using?**
internal downloader
**Please attach a log file here with the log setting set to debug**
[rdtclient_340.log](https://github.com/rogerfar/rdt-client/files/13889304/rdtclient_340.log)

Since the latest updates, it no longer works for me. Whether it’s for movies or series, during the download, randomly, the download resets and starts again at 0%. You can see it in the log file, there are many errors :

[ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: The remote server returned an error: (429) Too Many Requests. for download Echo.2024.S01E02.MULTi.1080p.WEB.H264-FW.mkv. Completed: -2147483648%, avg speed: 0bytes/s (a7d71136-dd8d-4207-86f4-cc798135496c) for torrent Echo.2024.S01.MULTi.1080p.WEB.H264-FW (218143633 - Ready 100%) (591a1760-f494-4a77-8a8d-17fb2e0c6230)

Another thing, the Test Real-Debrid download speed is no longer working (it was working even if I used alldebrid before) :
![Capture d’écran 2024-01-10 160301](https://github.com/rogerfar/rdt-client/assets/63678951/4103dae2-88b7-4fa4-b972-6bc9018a41c8)

**Comment by Drknz056** [comment]
Same issue for me here running latest version on a Docker container

**Comment by imadhy** [comment]
I have the same issue here.
@ozkansoyturk you closed the issue, I guess you resolved the problem. What was the problem please ? Thank you 🙏
