### ISSUE TITLE
Issue with "Run external program on torrent completion

### ISSUE THREAD

**Issue by iamsaleeb** [rogerfar/rdt-client#394]
**What version are you using?**
2.0.54

**Wat OS are you running?**
Linux Debian

**Are you using Docker or as a service?**
Service

**Which debrid provider are you using?**
Realdebrid

**Which downloader are you using?**
Internal

**Please attach a log file here with the log setting set to debug**

This may possibly just be me using the setting incorrectly. I am trying to set the group to read and write permissions after the torrent has completed, and have used the command "chmod -R 770 %F/" in the "Run external program on torrent completion" setting. This doesn't appear to be making any changes, but if I try this on qbittorrent, the same setting does work. Am I typing this wrong?

**Comment by iamsaleeb** [comment]
Sorry also to make a point, this is currently how it looks:
![Screenshot_20240113_195620_Samsung Internet](https://github.com/rogerfar/rdt-client/assets/45580709/252ac0f6-011a-4323-a2bc-c0107e32f2c4)

**Comment by rogerfar** [comment]
Check the logs, it should say what command it runs.
