### ISSUE TITLE
Getting "An unexpected error occurred unpacking XXXX for torrent XXXXX: file crc mismatch" error for all torrents

### ISSUE THREAD

**Issue by gnownairb95** [rogerfar/rdt-client#397]
**What version are you using?**
2.0.58

**Wat OS are you running?**
Edition	Windows 11 Home
Version	22H2
Installed on	‎02/‎10/‎2022
OS build	22621.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Are you using Docker or as a service?**
Docker via Docker Desktop

**Which debrid provider are you using?**
Real Debrid

**Which downloader are you using?**
Internal downloader

**Please attach a log file here with the log setting set to debug**
Log here: https://pastebin.com/X7QY88TW

**Comment by TOomaAh** [comment]
I have the same problem with docker. Nothing downloads anymore.

**Comment by rogerfar** [comment]
Closing this, don't think this is an issue anymore.
