### ISSUE TITLE
Permissions in Docker Container

### ISSUE THREAD

**Issue by thomazio** [rogerfar/rdt-client#40]
I keep having permission troubles after re-starting the container. Anyone else?

```
Error: An unexpected error occurred preparing download https://20.download.real-debrid.com/d/U5MEZSFWVQCCY/%5BHorribleSubs%5D%20Steins%20Gate%200%20-%2001%20%5B1080p%5D.mkv for torrent [HorribleSubs] Steins;Gate 0 [1080p] (Unofficial Batch): Access to the path '/data/downloads/sonarr/[HorribleSubs] Steins;Gate 0 [1080p] (Unofficial Batch)' is denied. 
```

It's fixable by running a shell inside container and setting correct permissions.
Downloads dir is 2775, and owned by 1000:1001 (DOTNET/UNKNOWN)
Sonarr / Radarr dir and children keep going back to 2775, and owned by 973:1001 (UNKNOWN/UNKNOWN).
It's really annoying because automatic process needs still manual intervention.

I'm running this on a linux system.

**Comment by rogerfar** [comment]
See https://github.com/rogerfar/rdt-client/issues/41
