### ISSUE TITLE
Feature request: Multiple torrent uploads at same time

### ISSUE THREAD

**Issue by dceldran** [rogerfar/rdt-client#400]
Hi!

Thanks for your job with this client, is amazing!.

When you go to "Add new torrent" section, you can only choose one torrent at same time, it would be good if you can choose a lot of torrents. 

Sometimes i want to add some tv show/anime series and i have one torrent per episode, so i need a little time to add all the season episode per episode.

Thanks!

**Comment by rogerfar** [comment]
I think it's easier to use Sonarr or use the import by folder feature perhaps?

**Comment by dceldran** [comment]
Import by folder feature? where are this feature? i can only see the add torrent button.

thanks!

**Comment by dceldran** [comment]
Thanks for the answers, i will use sonarr for this feature.
