### ISSUE TITLE
2.0.59 appears to have broken symbolic link downloading

### ISSUE THREAD

**Issue by djsecrist** [rogerfar/rdt-client#404]
**What version are you using?**
2.0.59

**Wat OS are you running?**
Docker 24.0.7 on Ubuntu

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Real

**Which downloader are you using?**
Sybolic

Files just sit in "Queued for downloading" status forever.  Downgraded to 2.0.58 and files immediately starting finishing.

**Comment by rogerfar** [comment]
This seems to be a bug that's been in there for a while, should be fixed in the next version.

**Comment by cchance27** [comment]
any news on this seems to be completely broken 

Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Processing 1 torrents
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Processing to download for download big-bunny-h264.mkv. Completed: -2147483648%, >
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Unrestricting links for download big-bunny-h264.mkv. Completed: -2147483648%, avg>
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Unrestricting link for download big-bunny-h264.mkv. Completed: -2147483648%, avg >
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Setting download path to /data/downloads/sonarr for download big-bunny-h264.mkv. >
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Starting download for download big-bunny-h264.mkv. Completed: -2147483648%, avg s>
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Starting symlink resolving of https://nyk6.download.real-debrid.com/d/ASDASD/big-bunny-h264.>
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Searching /data/realdebrid/torrents for big-bunny-h264.mkv
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Cancelling download https://nyk6.download.real-debrid.com/d/ASDASD/big-bunny-h264.DDP5.1.H.2>
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] No ID received for download big-bunny-h264.mkv. Completed: -2147483648%, avg spee>
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Processing for torrent big-bunny-h264.mkv (YYYYYYYY - downloaded 100%) (85f9>
Feb 02 04:05:15 SecureDL RdtClient[484]: [04:05:15 DBG] Waiting for downloads to complete. 0/1 complete (0%) for torrent big-bunny-h264.m>


Files complete in the torrents rclone directory, but the symlink never gets created and dl never completes

**Comment by cchance27** [comment]
Did some troubleshooting to try to help and something weird is going on not sure why... but for some directories it seems like Directory.GetFiles is returning an empty array... for instance
```
using System.IO;
var path = “/data/realdebrid/torrents/“;
DirectoryInfo dir = new DirectoryInfo(path);
var directories = dir.EnumerateDirectories();     // has the directories
var files = dir.EnumerateFiles();                           // has the files

var files2 = Directory.GetFiles(path);                     // returns empty array!??!?!```

**Comment by cchance27** [comment]
I managed to fix this on mine, what it was for me seems to have been that my rclone instance was running as a different user than my rdt-client, so the mount was owned by the owner even though i had --allow-others it was super weird about what it was allowing to see in the directory, i started rclone with the same user as all the other apps i'm running and it instantly finished the pending download.
