### ISSUE TITLE
symbolic link downloader downloading full files (not just linking) when files aren't already cached?

### ISSUE THREAD

**Issue by djsecrist** [rogerfar/rdt-client#405]
As far as I can tell, when I download something using the symbolic link downloader that isn't already cached on RD, I end up with the actual file on my local storage instead of a link pointing to RD.  I don't know how RD processes new downloads and how long it takes for them to show up in the cache.  When I search for the same movie using Debrid Media Manager, I don't (at least not yet) see the version that corresponds to my newly downloaded torrent.  Will it eventually be added to the cached content on RD?  Shouldn't rdt-client wait until the unrarred file to become available and then link to it instead of downloading the fully extracted file to my local storage?

**Comment by djsecrist** [comment]
Is anyone else experiencing this?  run "find /media/shows/ -type f" on your media directories and see if there are lots of files that are not symbolic links.  For me, when *arrs do the search, I mostly end up with proper symbolic links when rdt-client is done with the downloads, but somehow I end up with a lot of actually downloaded files, too.  I think it's when the files aren't already cached in Real-Debrid.  It's like the internal downloader takes over when rdt-client sees a RAR file on the other end of the download link instead of either failing the download (which should trigger radarr/sonarr to auto search again but this isn't working either for some reason; everything just stays in failed state in both rdt-client and the sonarr/radarr queue) or requesting real-debrid to extract the actual files and provide separate download links (if that's possible with RD).

**Comment by rogerfar** [comment]
The Symlink downloader doesn't actually have functionality to download files, only to symlink. Are you sure you didn't use a different downloader?

**Comment by djsecrist** [comment]
I have only ever used the symbolic link downloader.  So, unless I mistakenly changed the drop down, I can't explain it.  I will try to reproduce and capture a log.

**Comment by ehschneller** [comment]
I am experiencing this as well. Rar files are being downloaded rather than waiting.
