### ISSUE TITLE
Empty Directories Being made in RealDebridClient Directory

### ISSUE THREAD

**Issue by asuppa180** [rogerfar/rdt-client#409]
I have everything being deleted after sonarr/radarr moves the file and files are not even downloaded to the main directory. For some reason Empty directories (Never files in it) are being created in the RealDebridClient main directory, these empty directories have the same name as the downloaded file.

**What version are you using?**
2.0.59

**Wat OS are you running?**
Windows 11

**Are you using Docker or as a service?**
As a service on windows

**Which debrid provider are you using?**
Real-Debrid

**Which downloader are you using?**
Internal

**Please attach a log file here with the log setting set to debug**

**Comment by rogerfar** [comment]
Please post a log.

**Comment by pythongod** [comment]
jack@rdtclient:/opt/rdtc$ ls
 AllDebridNET.dll                                                                                      RdtClient.Web.exe
 Aria2NET.dll                                                                                          RdtClient.Web.pdb
 Barbie.2023.1080p.BluRay.x264-PiGNUS                                                                  RdtClient.Web.runtimeconfig.json
 Blade.Runner.2049.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT                          ReusableTasks.dll
 Downloader.dll                                                                                       'Road House (2024) [1080p] [WEBRip] [5.1] [YTS.MX]'
 DownloaderNET.dll                                                                                    'Road House (2024) [720p] [WEBRip] [YTS.MX]'
'Fast and Furious X (2023) [Bluray 720p][Esp](wolfmax4k.com)'                                         'Road House 2024 AMZN WEBRip SDR 10Bit 1440p DDP5.1 HEVC-3Li'
'Harry Potter And The Chamber Of Secrets (2002) [EXTENDED] [REPACK] [1080p] [BluRay] [5.1] [YTS.MX]'  'Road.House.2024.1080p.AMZN.WEBRip.1400MB.DD5.1.x264-GalaxyRG[TGx]'
'Harry Potter And The Prisoner Of Azkaban (2004) [REPACK] [1080p] [BluRay] [5.1] [YTS.MX]'             SQLitePCLRaw.batteries_v2.dll
'Harry Potter And The Sorcerers Stone (2001) [EXTENDED] [REPACK] [1080p] [BluRay] [5.1] [YTS.MX]'      SQLitePCLRaw.core.dll
'Mad Max Fury Road (2015) [1080p]'                                                                     SQLitePCLRaw.provider.e_sqlite3.dll
 Microsoft.AspNetCore.Cryptography.Internal.dll                                                        Serilog.AspNetCore.dll
 Microsoft.AspNetCore.Cryptography.KeyDerivation.dll                                                   Serilog.Extensions.Hosting.dll
 Microsoft.AspNetCore.Identity.EntityFrameworkCore.dll                                                 Serilog.Extensions.Logging.dll
 Microsoft.AspNetCore.SpaServices.Extensions.dll                                                       Serilog.Formatting.Compact.dll
 Microsoft.Data.Sqlite.dll                                                                             Serilog.Settings.Configuration.dll
 Microsoft.EntityFrameworkCore.Abstractions.dll                                                        Serilog.Sinks.Console.dll
 Microsoft.EntityFrameworkCore.Relational.dll                                                          Serilog.Sinks.Debug.dll
 Microsoft.EntityFrameworkCore.Sqlite.dll                                                              Serilog.Sinks.File.dll
 Microsoft.EntityFrameworkCore.dll                                                                     Serilog.dll
 Microsoft.Extensions.Caching.Abstractions.dll                                                         SharpCompress.dll
 Microsoft.Extensions.Caching.Memory.dll                                                              'Succession S02E04 Safe Room 1080p AMZN WEB-DL DDP5 1 H 264-NTb[TGx]'
 Microsoft.Extensions.Configuration.Abstractions.dll                                                  'Succession S02E05 Tern Haven 1080p AMZN WEB-DL DDP5 1 H 264-NTb[TGx]'
 Microsoft.Extensions.DependencyInjection.Abstractions.dll                                            'Succession S02E09 DC 1080p AMZN WEB-DL DDP5 1 H 264-NTb[TGx]'
 Microsoft.Extensions.DependencyInjection.dll                                                          Succession.S01.1080p.BluRay.x265-RARBG
 Microsoft.Extensions.DependencyModel.dll                                                              System.ServiceProcess.ServiceController.dll
 Microsoft.Extensions.Hosting.WindowsServices.dll                                                     'The Beekeeper 2024 1080p BluRay REMUX AVC Atmos-TRiToN'
 Microsoft.Extensions.Identity.Core.dll                                                               'The Dark Knight (2008) 1080p H264 AC-3.mkv'
 Microsoft.Extensions.Identity.Stores.dll                                                             'The.White.Lotus.S01E01.1080p.WEB.H264-GGEZ[TGx]'
 Microsoft.Extensions.Logging.Abstractions.dll                                                        'The.White.Lotus.S01E02.1080p.WEB.H264-GGWP[TGx]'
 Microsoft.Extensions.Logging.dll                                                                     'The.White.Lotus.S01E03.REPACK.1080p.WEB.H264-GGEZ[TGx]'
 Microsoft.Extensions.Options.dll                                                                     'The.White.Lotus.S01E04.Recentering.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[TGx]'
 Microsoft.Extensions.Primitives.dll                                                                  'The.White.Lotus.S01E05.1080p.WEB.H264-GLHF[TGx]'
 Mono.Nat.dll                                                                                         'The.White.Lotus.S01E06.1080p.WEB.H264-GLHF[TGx]'
 MonoTorrent.dll                                                                                       The.Wolf.Of.Wall.Street.2013.1080p.BluRay.REMUX.DTS-HD.MA.5.1-PublicHD
 Newtonsoft.Json.dll                                                                                   Update.ps1
 PremiumizeNET.dll                                                                                    'Wonka (2023) [BLURAY] [1080p] [BluRay] [5.1] [YTS.MX]'
 RDNET.dll                                                                                             ZstdSharp.dll
 RdtClient.Data.deps.json                                                                              appsettings.Development.json
 RdtClient.Data.dll                                                                                    appsettings.json
 RdtClient.Data.pdb                                                                                    data
 RdtClient.Data.runtimeconfig.json                                                                     runtimes
 RdtClient.Service.deps.json                                                                           service-install.bat
 RdtClient.Service.dll                                                                                 service-remove.bat
 RdtClient.Service.pdb                                                                                 web.config
 RdtClient.Web.deps.json                                                                               wwwroot
 RdtClient.Web.dll


This is with LXC https://tteck.github.io/Proxmox/  https://github.com/tteck/Proxmox/raw/main/ct/rdtclient.sh

**Comment by rogerfar** [comment]
Probably better to check in those repositories, because this is not configured right.
