### ISSUE TITLE
Feature Request: Symbolic Link downloader setting to automatically fail downloads that aren't already cached by Debrid

### ISSUE THREAD

**Issue by djsecrist** [rogerfar/rdt-client#412]
Since there isn't a good way for the *arrs to only search for torrents that are already cached on real-debrid, I would like a setting in the Symbolic Link downloader to automatically mark the download as Failed *if* rdt-client determines that Real-Debrid needs to download the torrent.  Then, Sonarr/Radarr should see the failed status and automatically clear the download after searching for another release.  

Side note/issue: Failures aren't automatically being retried by Sonarr/Radarr right now.  They just show as yellow warnings in Sonarr/Radarr right now and don't trigger a re-search as long as the "Redownload Failed" settings are enabled in Radarr/Sonarr.  Seems like that is "as designed" for Torrent handling in the *arrs. I'll have to do some extra scripting for this to work, but I think the idea is still solid until someone comes up with a cached torrent search plugin/service for Prowlarr and Real-Debrid. https://www.reddit.com/r/radarr/comments/q0he3i/failed_download_handling_doesnt_work_feature/

**Comment by djsecrist** [comment]
One more thing...  The Remove torrent action would likely need to be tweaked in rdt-client as well.  When Sonarr/Radarr request the removal of a torrent from rdt-client:
If torrent_status = "Finished" then remove torrent from client only,
else torrent_status = anything other than "Finished" then remove torrent from client, provider, and local.

In fact, I'd like to see this implemented as a feature regardless of the rest of my request. 
 That should allow for cleaning things up properly, I think...  Right now, I get left with a mess of partial torrents in real-debrid if I remove the download from Radarr/Sonarr.  This is because I have rdt-client configured to only delete from client for Post Download qBittorrent action.  When Radarr/Sonarr finish processing a successful download, this is correct thing to do, but failures or delete from queue for any other reason leaves things downloading on the provider side.

**Comment by rogerfar** [comment]
I do like the feature, but I'm afraid this is a bit out of scope. It would be cool to have a Prowlarr addon that can search Real-Debrid.

As to your 2nd comment, it should already do this.
