### ISSUE TITLE
Serilog file is disposed at service start

### ISSUE THREAD

**Issue by jawshr26** [rogerfar/rdt-client#414]
**What version are you using?**
2.0.59
**Wat OS are you running?**
Debian 12 ARM64
**Are you using Docker or as a service?**
Service
**Which debrid provider are you using?**
na 
**Which downloader are you using?**
na
**Please attach a log file here with the log setting set to debug**
 RdtClient[6759]:    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
 RdtClient[6759]:    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
 RdtClient[6759]: [15:47:18 ERR] Unexpected error occurred in ProviderUpdater: A task was canceled.
 RdtClient[6759]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
 RdtClient[6759]:    at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in C:\Projects\rdt-client\server\RdtClient.Service\BackgroundServices\WatchFolderChecker.cs:line 40
 RdtClient[6759]: 2024-01-31T05:47:18.5712146Z Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.ObjectDisposedException: Cannot access a disposed object.
 RdtClient[6759]: Object name: 'The log file has been disposed.'.

**Comment by rogerfar** [comment]
I haven't seen that before, I might found 1 place where it could be an issue, but I doubt it.

If Serilog crashes it prints to the console, as it can't log properly anymore. Does anything show on the console?

**Comment by rogerfar** [comment]
If it still happens feel free to post.
