### ISSUE TITLE
Aria2 download does not confirm

### ISSUE THREAD

**Issue by sswinson** [rogerfar/rdt-client#415]
**What version are you using?**
2.0.59
**What OS are you running?**
Windows
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
Real-debrid
**Which downloader are you using?**
aria2

I am having an issue with the rdtclient's interaction with aria2 downloader. 
I start a file in radarr, rdtclient starts the download in aria2, aria2 finishes, and then rdtclient says Download reported an error: File not found, and then restarts the download (creating an infinite loop).
I think that my permissions are set correctly, and that the docker container can see this file, but is not recognizing it.
![image](https://github.com/rogerfar/rdt-client/assets/158589824/eddd16d8-d079-442a-bd1c-cc85283e1322)
![image](https://github.com/rogerfar/rdt-client/assets/158589824/ca2c30c9-9674-4ce2-8d88-e451c943c661)
![image](https://github.com/rogerfar/rdt-client/assets/158589824/65bc15f5-c892-48f9-963c-6c9e5ecfba0e)

Any help would be greatly appreciated!

**Please attach a log file here with the log setting set to debug**
[rdtclient issue log.txt](https://github.com/rogerfar/rdt-client/files/14141847/rdtclient.issue.log.txt)

**Comment by sswinson** [comment]
I was able to resolve this issue by setting all the paths to the drive that docker is installed on. It does not quite work as I intended, but good enough.

**Comment by rogerfar** [comment]
This is expected yes, Aria2c needs be closely matched to your paths otherwise it'll get all confused.
