### ISSUE TITLE
Unselect certain file types before sending to RD

### ISSUE THREAD

**Issue by davedash** [rogerfar/rdt-client#416]
**What version are you using?**

Latest via docker

**Wat OS are you running?**

Ubuntu + Docker

**Are you using Docker or as a service?**

Docker

**Which debrid provider are you using?**

Real-Debrid

**Which downloader are you using?**
n/a

**Please attach a log file here with the log setting set to debug**

I'm noticing when files are submitted to RD they have text files attached.  So for example a torrent may include:

* info.txt
* movie.mp4

Real-debrid will RAR the whole torrent (and I am not using the downloaded, so I want to stream them from Real Debrid).  

I notice if you submit the Torrent and uncheck the txt file everything works correctly.  Is there a way to specify this?

**Comment by cchance27** [comment]
I believe right now the only way is setting a minimum size to download, so set it to 100 for 100mbit minimum that way it'll only grab videos or whatever, hell even setting it to 1 means it'll download anything not super small... that said a filter for file types would be nice

**Comment by rogerfar** [comment]
Correct, for now you can only do it by specifying a minimum file size.
