### ISSUE TITLE
Download Client is unavailable (Unraid,Sonarr,Radar) 

### ISSUE THREAD

**Issue by Super-6-1** [rogerfar/rdt-client#417]
**What version are you using?** 
2.0.59

**Wat OS are you running?**
Unraid
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
Real-debrid
**Which downloader are you using?**
Bezzed and internal Downloader
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/14157684/rdtclient.log)

Inside both radarr and sonarr I get this issue. All tested and it seems to all be connected but yet this issue occurs, I am using prowlarr for the indexer, Any reason why?

**Comment by cchance27** [comment]
whatever username/password you have setup in sonarr/radarr is incorrect it looks like to me in the logs, either that or something weird with your settings for the connection to rdt... 

403 Error means it's not logged in to RDT
2024-02-04 07:44:48.615 -08:00 [WRN] : 403: /Api/Authentication/IsLoggedIn

This 400 error means something went wrong with the login
2024-02-04 07:44:57.542 -08:00 [WRN] : 400: /Api/Authentication/Login 

and your torrent info checks are all giving 401's so seems to me like a credential issue :S

**Comment by Super-6-1** [comment]
> whatever username/password you have setup in sonarr/radarr is incorrect it looks like to me in the logs, either that or something weird with your settings for the connection to rdt...
> 
> 403 Error means it's not logged in to RDT 2024-02-04 07:44:48.615 -08:00 [WRN] : 403: /Api/Authentication/IsLoggedIn
> 
> This 400 error means something went wrong with the login 2024-02-04 07:44:57.542 -08:00 [WRN] : 400: /Api/Authentication/Login
> 
> and your torrent info checks are all giving 401's so seems to me like a credential issue :S

Thanks! I did figure it out, ill go ahead and close this now.
