### ISSUE TITLE
Can't add torrents - Resource temporarily unavailable (api.real-debrid.com:443))

### ISSUE THREAD

**Issue by palradu** [rogerfar/rdt-client#418]
**What version are you using?**
2.0.60

**What OS are you running?**
Docker container on Synology NAS

**Are you using Docker or as a service?**
Yes

**Which debrid provider are you using?**
Real Debrid

**Which downloader are you using?**
Internal Downloader

**Please attach a log file here with the log setting set to debug**
[rdtclient (1).log](https://github.com/rogerfar/rdt-client/files/14195458/rdtclient.1.log)

I was using v2.0.49 until today and I decided I should update to the latest version. I deleted the container, deleted the image and set up the container again using the same information as before.

The container creation process worked perfectly, it started up and was able to set up the app.

However, I can't add any torrents through the web GUI (log attached). Whenever I try to add a torrent, be it via magnet link or torrent file, I get the same error: One or more errors occurred. (Resource temporarily unavailable (api.real-debrid.com:443)).

Same thing happens when attempting to add a torrent through Sonarr and Radarr, even though the connection between Sonarr/Radarr and the Docker container is active (I get a green checkmark whenever I "test" the connection).

I have checked and after running the command `curl api.real-debrid.com:443` from both the NAS and my PC, I get the error below. Not mentioning the port number in the command provided the right server response:

![putty_bdSZzUWWr0](https://github.com/rogerfar/rdt-client/assets/9775016/aa4abd83-2486-4a6a-82f8-e3f412dfd97b)

Can you please assist?

**Comment by rogerfar** [comment]
Do you have proxy or something? Because that's a network error.

**Comment by palradu** [comment]
I don't have any proxy servers running, the only proxy running is the reverse ngnix proxy for my NAS.

**Comment by cchance27** [comment]
Stop trying to use HTTP to Call an HTTPS server, just providing a port doesn't tell curl to use https. literally the errors telling you whats wrong.

![image](https://github.com/rogerfar/rdt-client/assets/13766359/2028eaeb-a4ca-47be-8a42-6db0e3ae68b2)

**Comment by palradu** [comment]
OK, I get that, but I am not doing anything. The only thing I did was just download the image and run the container. I am not making those requests, rdtclient is...

**Comment by rogerfar** [comment]
So it's good now?

**Comment by evil512-dom** [comment]
Hi, got the same error for alldebrid.
Don't use an reverseproxy.


What version are you using?
2.0.61

What OS are you running?
Docker container on QNAP NAS

Are you using Docker or as a service?
Docker

Which debrid provider are you using?
Alldebrid

Which downloader are you using?
Internal Downloader

log
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/14302390/rdtclient.log)

**Comment by palradu** [comment]
> So it's good now?

I apologize for the late reply. Nope, same error appears. It's not something local, I don't have any proxies running or anything within my network that would generate this error.

**Comment by evil512-dom** [comment]
from my serveur it's working 
Server:         127.0.1.1
Address:        127.0.1.1#53

Non-authoritative answer:
Name:   api.alldebrid.com
Address: 104.23.132.78
Name:   api.alldebrid.com
Address: 104.23.128.79


but not from my container

[]$ docker exec -it c4336a13952c nslookup api.alldebrid.com
;; connection timed out; no servers could be reached
