### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by CaddyV** [rogerfar/rdt-client#419]
Hi! 

Just got RDT - Client setup yesterday, and have been seeing extremely high CPU usage - is this expected? 

1. i5-9th Gen
2. Windows 11
3. 16GB of RAM
4. Internal Downloader
5. 256gb SSD for the OS/Docker
6. NAS Drive for Storage
7. Installed on Docker
8. Currently set to 1 Chunk and 4 Parallel downloads, tried 8 Chunks and 8 Parallel
9. Usage fluctuates between 75% ~ 300%, and my desktop sounds like a rocket and gets very slow. I don't see any other posts about this, so I presume it's an issue on my side?
11. Download speeds fluctuate from 0 to 50MBps throughout

<img width="806" alt="image" src="https://github.com/rogerfar/rdt-client/assets/49270573/e3850416-9ff4-4a02-a4f8-5a96b5d69f5d">

Thank you!

**Comment by rogerfar** [comment]
Can you post a log? Maybe it's unpacking?

**Comment by LemonsAndOranges** [comment]
I've got the same issue, running within docker on Windows 11.  Xeon W-2145, 64 GB RAM, Internal Downloader, SSD for boot and docker. 

As soon as a download is started, it eats up CPU for the entire machine. It doesn't appear to be an unpacking issue, as it starts as soon as a download is initiated.

**Comment by mrman486** [comment]
Seeing a CPU issue with docker. I can just have it running with no downloads etc happening and it’s pushing my RPi4 hard.

What logs etc would be helpful to sort this one out?

**Comment by rogerfar** [comment]
Would be hard to debug, even with logs. What happens if you reduce the `Check Interval`? 

Because when you're not on the web interface and you have no downloads it should be very idle.

**Comment by CaddyV** [comment]
Sorry for getting back so late, will try switching to the Windows Service like LemonsAndOranges did!

**Comment by CaddyV** [comment]
@LemonsAndOranges, @rogerfar  - How did you get the Service working? I just get 'Stopped' when I check services. Don't see anything on my logs folder either

This is my appsettings.json. I tried without the double quotes as well. I'm using Windows, and installed ASP.NET as well. 

{
  "Logging": {
    "File": {
      "Path": "C:\\Users\\"User Name"\\Documents\\"RDT Client"\\"RDT Logs"\\rdtclient.log",
      "FileSizeLimitBytes": 5242880,
      "MaxRollingFiles": 5
    }
  },
  "Database": {
    "Path": "C:\\Users\\"User Name"\\Documents\\"RDT Client"\\"RDT Database"\\rdtclient.db"
  },
  "Port": "6500",
  "BasePath": null
}

**Comment by CaddyV** [comment]
Switched to a shorter path which didn't have spaces, and got it working. 

However, my system crashes near instantly when a download starts - I've got about 6 out of 16GB of RAM free but see this on the logs - 

`2024-04-10 13:45:40.024 +08:00 [ERR] RdtClient.Service.Services.Downloaders.InternalDownloader: Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.SharedArrayPool`1.Rent(Int32 minimumLength)
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
2024-04-10 13:45:40.192 +08:00 [ERR] RdtClient.Service.Services.Downloaders.InternalDownloader: Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.SharedArrayPool`1.Rent(Int32 minimumLength)
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
2024-04-10 13:45:40.192 +08:00 [ERR] RdtClient.Service.Services.Downloaders.InternalDownloader: Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.SharedArrayPool`1.Rent(Int32 minimumLength)
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
2024-04-10 13:45:40.192 +08:00 [ERR] RdtClient.Service.Services.Downloaders.InternalDownloader: Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.SharedArrayPool`1.Rent(Int32 minimumLength)
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
2024-04-10 13:45:40.291 +08:00 [ERR] RdtClient.Service.Services.Downloaders.InternalDownloader: Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.SharedArrayPool`1.Rent(Int32 minimumLength)
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)`

Guess my desktop needs more RAM, will go back to Docker until I can add some.

**Comment by rogerfar** [comment]
It really shouldn't use that much memory, can you show a screenshot of your settings, specifically the download client page.

**Comment by CaddyV** [comment]
Strangely, all I see is one tab on the settings page.

I also noticed the following before my system crashed this time -

- Download speeds while using the Windows version go up to 100MBps, whereas the Docker version stays around 5-10MBps, occasionally shooting upto 40MBps
- Task Manager still showed about 5gb of RAM left, but my Chrome Tabs & Docker crashed, followed by the system crashing

![Crash](https://github.com/rogerfar/rdt-client/assets/49270573/9bc9e2e6-8ca2-4890-8cc9-f8efb6d3c42c)
![Settings](https://github.com/rogerfar/rdt-client/assets/49270573/daadfbd8-0c6f-4f88-8110-704762292edf)

**Comment by rogerfar** [comment]
Honestly I'm not sure at all, I don't think I've seen anyone else with this issue yet. But you're saying you see the same problem when running from Docker right? I assume that's on the same physical machine?

And you have no torrents loaded at all?

**Comment by CaddyV** [comment]
I haven't faced this issue while using the Docker version. I tried both versions on the same physical machine.

Docker Version - Slower Downloads, was causing high CPU usage while downloading (No longer the case after restricting WSL resources)

Windows Version - 100MBps for the first minute or so until apps start getting killed and the desktop eventually crashes

**Comment by itinerantmarshmallow** [comment]
I had this issue while running the Windows version. I managed to resolve it however. 

I just did a reinstall of .NET and deleted and reinstalled the RDC directory. 

The only major differences I can think of is I changed the directory name to just RDC (from RealDebridClient) and where I stored the logs and DB file which are now:

"C:\\RDC\\db\\ ..."

Finally I used Bezzad instead of the Internal downloader. I will re check tonight if the issue is replicable with the internal downloader. 

Unfortunately I completely deleted everything from the first attempt so I haven't got the old logs to help you out Caddy (or you Roger) but I absolutely got the System.OutofMemoryException.

Specs:
i5-9500T
8GB RAM (2666Mhz)

**Comment by CaddyV** [comment]
I'll retry with the same steps as well, although my install of .NET was new. 

I used C:\RDTClient - I had some issues when using a longer path / with a space (C:\RDT Client\...) if I remember correctly. On my install, my settings page was blank so I couldn't switch to a different downloader. 

My Docker version is working reliably, albeit with slow download speeds - but I'll give this a try again

**Comment by rogerfar** [comment]
Try using the Aria2c downloader as a test, that really should keep the memory and CPU down of RDT.

**Comment by CaddyV** [comment]
> Try using the Aria2c downloader as a test, that really should keep the memory and CPU down of RDT.

Sure, will give that a shot as well. Also, thank you for RDT Client - really is epic. :)

**Comment by mattdillon100** [comment]
Still having this problem. I've tried limiting the CPUs in the docker compose file but it's still running very hot

**Comment by itinerantmarshmallow** [comment]
All I can say is try Aria as Roger suggested.

It's a very good downloader. I was having issues with the internal downloader files playback anyway, hasn't happened since I switched to Aria.

**Comment by KUSH43** [comment]
Hello same issue with me, download start en cpu go 100% immediatly and impact the download speed variting with 100/mbps and 30-50mpbs

here the docker logs i try Aria2c same thing

[12:47:52 ERR] The operation has timed out.
System.TimeoutException: The operation has timed out.
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
[12:47:52 ERR] The operation has timed out.
System.TimeoutException: The operation has timed out.
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
[12:47:52 ERR] The operation has timed out.
System.TimeoutException: The operation has timed out.
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
[12:47:57 ERR] The operation has timed out.
System.TimeoutException: The operation has timed out.
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
[12:47:57 ERR] The operation has timed out.
System.TimeoutException: The operation has timed out.
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
[12:47:57 WRN] 101: /hub
[12:47:57 ERR] The operation has timed out.
System.TimeoutException: The operation has timed out.
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
[12:47:57 ERR] The operation has timed out.
System.TimeoutException: The operation has timed out.
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
[12:49:23 WRN] 101: /hub

**Comment by itinerantmarshmallow** [comment]
You should compare to downloading a file directly from RD.

No clue on Bezzad myself, as I said Aria fixed this issue for me.

**Comment by rogerfar** [comment]
I suggest for now switch to Aria2 or Bezzad and play with the parameters.

**Comment by bhugh** [comment]
I am having this issue as well using a docker installation.  Since installing rdtclient, the machine has randomly locked up hard after running for several hours - usually 12-24 hours, requiring a reboot.

Today I caught rdtclient using all available cpu and a lot of memory.  As soon as I was able to kill the rdtclient container, the system returned to normal.

I will try implementing some of the solutions mentioned upthread and see how it goes.  First will be to add some cpu & memory limits along these lines, in the compose file:

`    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M`

I'm not sure what reasonable limits would be, but that's likely to be my starting point.

Thanks for creating a very helpful tool!

**Comment by Enilv74** [comment]
HI @rogerfar 

How you parameterize aria2c with RDT client 
I have some error 
I install aria2 pro docker and put url in rdtclient, test connection is ok but when I launch DSI it failed with connection error

**Comment by mattdillon100** [comment]
> I am having this issue as well using a docker installation. Since installing rdtclient, the machine has randomly locked up hard after running for several hours - usually 12-24 hours, requiring a reboot.
> 
> Today I caught rdtclient using all available cpu and a lot of memory. As soon as I was able to kill the rdtclient container, the system returned to normal.
> 
> I will try implementing some of the solutions mentioned upthread and see how it goes. First will be to add some cpu & memory limits along these lines, in the compose file:
> 
> ` deploy:` ` resources:` ` limits:` ` cpus: '0.50'` ` memory: 500M`
> 
> I'm not sure what reasonable limits would be, but that's likely to be my starting point.
> 
> Thanks for creating a very helpful tool!

I tried this with no luck. Switched to Aria2c and it has been working great for a few hours (using the internal downloader it would crash when one download was added).
