### ISSUE TITLE
Unable to deserialize AllDebrid API response to MagnetUploadResponse

### ISSUE THREAD

**Issue by Rouckmoutpower** [rogerfar/rdt-client#421]
**What version are you using?**
2.0.62
**Wat OS are you running?**
Synology docker
**Are you using Docker or as a service?**
yes
**Which debrid provider are you using?**
Alldebrid
**Which downloader are you using?**
internal
**Please attach a log file here with the log setting set to debug**
error when add torrent

Unable to deserialize AllDebrid API response to MagnetUploadResponse. Response was: { "status": "error", "error": { "code": "MAGNET_TOO_MANY", "message": "Magnets limit reached (1000 accross all tabs)" } }

[rogerfar.csv](https://github.com/rogerfar/rdt-client/files/14323516/rogerfar.csv)

**Comment by Elrau** [comment]
Did you verify on your Alldebrid account how many torrent you have ? Perhaps you just need to purge them.

**Comment by Rouckmoutpower** [comment]
Good evening,

Indeed, that was indeed it.
I didn't know this limit.
Sorry for the inconvenience.

**Comment by hulkito-nol** [comment]
hello, same here...
