### ISSUE TITLE
Stuck queued for downloading

### ISSUE THREAD

**Issue by eoghan2t9** [rogerfar/rdt-client#423]
**What version are you using?**
2.0.62

**Wat OS are you running?**

Ubuntu Server 22.04

**Are you using Docker or as a service?**

Yes

**Which debrid provider are you using?**

Real debrid

**Which downloader are you using?**

Symlink

**Please attach a log file here with the log setting set to debug**

Where can I pull that log file from?

Hi guys my downloads seem to be getting stuck saying queued for downloading however when I click into one of the torrents stating this it's already finished and has got the unrestricted link from real debrid. Some downloads do end up going through and fully completing but a high volume is getting stuck for some reason. Has anyone else got this issue and how to resolve it?

![Screenshot_20240220-082606.png](https://github.com/rogerfar/rdt-client/assets/911750/152402c4-a8c0-4f36-b4ef-7841dd32d3fe)

![Screenshot_20240220-082504.png](https://github.com/rogerfar/rdt-client/assets/911750/5c70e1f5-9e3e-4ae6-9bb0-0d519ea0c1a5)

**Comment by rogerfar** [comment]
Please post logs.

**Comment by screamjojo** [comment]
Same problem, here my logs : https://pastebin.com/Tfn3Q8YH
