### ISSUE TITLE
Real-debrid wont start torrent

### ISSUE THREAD

**Issue by MrMookdog** [rogerfar/rdt-client#432]
Hi

I am using the windows version of rdt-client and for some reason when using radarr and sonarr it will not start my torrent automatically. I have to go into real debrid and click start torrent for it to work. Dont know if there is a setting or something I need to do. Can anyone please help

Thanks
Sean

**Comment by CutePityOwl** [comment]
Same with Debian 11 Base / Real Debrid, happens when torrent contains more than 1 file

**Comment by rogerfar** [comment]
Please post some logs
