### ISSUE TITLE
symlink downloader issue 

### ISSUE THREAD

**Issue by ArrJayyy** [rogerfar/rdt-client#438]
**What version are you using?**
latest version
**Wat OS are you running?**
windows
**Are you using Docker or as a service?**
the exe
**Which debrid provider are you using?**
real debrid
**Which downloader are you using?**
symlink
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/14646945/rdtclient.log)

so the torrent gets added through radarr, but it gets stuck on queued for download. I have seen the other posts with the same issue but I don't see what the fix is. I feel like i have something configured incorrectly, idk how this works really, just following the steps.

why is it looking for the .rar file in the log? is that supposed to be downloaded, as far as i understand its not. And it doesnt get downloaded only the mkv file is in the rclone+zurg so idk whats happening here.

UPDATE: Idk what i did but it started working for a short time than broke again. The same thing happens (q'd for download) but in the log something different is the issue, now it says No ID received, idk what the issue is. I would have attached the log but this time for some reason the logs not being updated either. 
got a log:  [rdtclient.log](https://github.com/rogerfar/rdt-client/files/14716928/rdtclient.log)

Also, why does it create an additional empty folder of the movie in my install directory of the RDT client? Is that supposed to happen?
![image](https://github.com/rogerfar/rdt-client/assets/89042752/9323ea4a-2e9d-459b-880e-7a4f1c5a32ee)

UPDATE 2: So somehow the symlink downloader started working but it only works sometimes. There are basically two things that happen when it fails. It either doesn't receive an ID (as in my previous update) or it looks for some other file like an .rar file or even a .iso file, which it doesn't ever find because only the mkv gets added to the mount. 

The additional folders that it used to create has been fixed, i just changed the location of the rdtclient.db file in the appsettings.json and that seems to resolve that issue. 

UPDATE 3: New build was released with changes to the symlink downloader. Testing it out and it seems that it is also getting stuck. It seems to now get stuck on q'd for unpacking vs q'd for download. As before though, it does seem like it depends on which torrent gets grabbed because I can manually select a different one in the arr's using the interactive search feature and i usually find one that works. I also find that it seems to work more reliably when it comes to downloading movies vs shows. 

Log file (v2.0.65): 
[rdtclient_039.log](https://github.com/rogerfar/rdt-client/files/14897787/rdtclient_039.log)

Snippet from where it gets stuck:
```
2024-04-07 11:17:38.390 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
2024-04-07 11:17:38.390 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 5/11 complete (0%) for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
2024-04-07 11:17:39.394 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2024-04-07 11:17:39.394 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
2024-04-07 11:17:39.394 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
2024-04-07 11:17:39.394 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 5/11 complete (0%) for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
2024-04-07 11:17:39.516 -04:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Updating torrent info from debrid provider
2024-04-07 11:17:40.411 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2024-04-07 11:17:40.411 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
2024-04-07 11:17:40.411 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
2024-04-07 11:17:40.411 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 5/11 complete (0%) for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)

```

**Comment by erix** [comment]
I have the same issue. I use Zurg and rclone to mount the RD downloads. I set the path the rdt-client as` /mnt/zurg/__all__` 
When a torrent is added to rdt-client it succesfully adds it to RD and it appears in the rclone mounted directory. The problem is when rdt-client unrestricts the torrent link and gets the rar file as a result and searches for the rar file in the rclone folder instead of the mkv file. I do not know how to configure the rdt-client to not use the unrestricted link for symlink download but instead use the files in the torrent itself.

**Comment by ArrJayyy** [comment]
> I have a similar issue. I use Zurg and rclone to mount the RD downloads. I set the path the rdt-client as` /mnt/zurg/__all__` When a torrent is added to rdt-client it succesfully adds it to RD and it appears in the rclone mounted directory. The problem is when rdt-client unrestricts the torrent link and gets the rar file as a result and searches for the rar file in the rclone folder instead of the mkv file. I do not know how to configure the rdt-client to not use the unrestricted link for symlink download but instead use the files in the torrent itself.

Yeah, that is basically the same issue i am having, it works sometimes but other times it just looks for the .rar or even an .iso file and just gets stuck at q'd for download in the client.

**Comment by erix** [comment]
After digging a while I have found a patch for the symlink downloader:
https://github.com/rogerfar/rdt-client/compare/master...Pukabyte:rdtclient:master

I will try it once I can create an ARM build of the container, the one available is only amd64:
https://hub.docker.com/r/pukabyte/rdtclient/tags

**Comment by ArrJayyy** [comment]
> After digging a while I have found a patch for the symlink downloader: [master...Pukabyte:rdtclient:master](https://github.com/rogerfar/rdt-client/compare/master...Pukabyte:rdtclient:master)
> 
> I will try it once I can create an ARM build of the container, the one available is only amd64: https://hub.docker.com/r/pukabyte/rdtclient/tags

I tried it on ubuntu using docker, it does work, but honestly i think both versions occasionally bug out. I went back to windows, somehow its now working for the most part.

**Comment by erix** [comment]
I created a patch with suppose to handle the rar downloads. I'm planning to make it work with zurg, it already creates the symlinks for the unpacked files. I have still some problem with it, Radarr is not able to import the download yet. I need to investigate it more. The code is here: https://github.com/rogerfar/rdt-client/compare/master...erix:rdt-client:master
The image is here to test (so far only for arm64): https://hub.docker.com/repository/docker/erix12/rdt-client/general

**Comment by rogerfar** [comment]
@erix can you try the latest version and see if it's still an issue? 

If so, can you post the magnet in a pastebin so I can reproduce?

**Comment by MrJoshGit** [comment]
> **What version are you using?** latest version **Wat OS are you running?** windows **Are you using Docker or as a service?** the exe **Which debrid provider are you using?** real debrid **Which downloader are you using?** symlink **Please attach a log file here with the log setting set to debug** [rdtclient.log](https://github.com/rogerfar/rdt-client/files/14646945/rdtclient.log)
> 
> so the torrent gets added through radarr, but it gets stuck on queued for download. I have seen the other posts with the same issue but I don't see what the fix is. I feel like i have something configured incorrectly, idk how this works really, just following the steps.
> 
> why is it looking for the .rar file in the log? is that supposed to be downloaded, as far as i understand its not. And it doesnt get downloaded only the mkv file is in the rclone+zurg so idk whats happening here.
> 
> UPDATE: Idk what i did but it started working for a short time than broke again. The same thing happens (q'd for download) but in the log something different is the issue, now it says No ID received, idk what the issue is. I would have attached the log but this time for some reason the logs not being updated either. got a log: [rdtclient.log](https://github.com/rogerfar/rdt-client/files/14716928/rdtclient.log)
> 
> Also, why does it create an additional empty folder of the movie in my install directory of the RDT client? Is that supposed to happen? ![image](https://private-user-images.githubusercontent.com/89042752/315853225-9323ea4a-2e9d-459b-880e-7a4f1c5a32ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjA4NTgsIm5iZiI6MTcxNDA2MDU1OCwicGF0aCI6Ii84OTA0Mjc1Mi8zMTU4NTMyMjUtOTMyM2VhNGEtMmU5ZC00NTliLTg4MGUtN2E0ZjFjNWEzMmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1NTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMGIyNzAxYWQwNzVlMzg1ZmM1NzkxNTBiMTczZWFjYmUxOThlYTZmNTc5N2E4YTg2ZTA2YTAxMjlhODczMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BGvY76_CfSgOPEKRW8Zq8ZaTX566ooe0gsK050ICtPo)
> 
> UPDATE 2: So somehow the symlink downloader started working but it only works sometimes. There are basically two things that happen when it fails. It either doesn't receive an ID (as in my previous update) or it looks for some other file like an .rar file or even a .iso file, which it doesn't ever find because only the mkv gets added to the mount.
> 
> The additional folders that it used to create has been fixed, i just changed the location of the rdtclient.db file in the appsettings.json and that seems to resolve that issue.
> 
> UPDATE 3: New build was released with changes to the symlink downloader. Testing it out and it seems that it is also getting stuck. It seems to now get stuck on q'd for unpacking vs q'd for download. As before though, it does seem like it depends on which torrent gets grabbed because I can manually select a different one in the arr's using the interactive search feature and i usually find one that works. I also find that it seems to work more reliably when it comes to downloading movies vs shows.
> 
> Log file (v2.0.65): [rdtclient_039.log](https://github.com/rogerfar/rdt-client/files/14897787/rdtclient_039.log)
> 
> Snippet from where it gets stuck:
> 
> ```
> 2024-04-07 11:17:38.390 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
> 2024-04-07 11:17:38.390 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 5/11 complete (0%) for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
> 2024-04-07 11:17:39.394 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
> 2024-04-07 11:17:39.394 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
> 2024-04-07 11:17:39.394 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
> 2024-04-07 11:17:39.394 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 5/11 complete (0%) for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
> 2024-04-07 11:17:39.516 -04:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Updating torrent info from debrid provider
> 2024-04-07 11:17:40.411 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
> 2024-04-07 11:17:40.411 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
> 2024-04-07 11:17:40.411 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
> 2024-04-07 11:17:40.411 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 5/11 complete (0%) for torrent KonoSuba.God's.Blessing.On.This.Wonderful.World.S01.1080p.BluRay.10-Bit.Dual-Audio.FLAC2.0.x265-YURASUKA (3HESAPRLKIWG2 - downloaded 100%) (80a1b755-d9b0-4727-8216-0ac3d6a0e5d7)
> ```

To the OP, you mentioned the duplicae folders in the insall directory and to fix you changed the location of the .DB file? Where did you change the location to?  Can you share your appsettings .JSON file with me? I am encountering same issue and unable to resolve.

**Comment by rogerfar** [comment]
Is this issue good now? Are there still occasions where it can't find the file on the symlinked drive?

**Comment by ArrJayyy** [comment]
> Is this issue good now? Are there still occasions where it can't find the file on the symlinked drive?

I stopped using Real Debrid few weeks ago, but im guessing since the other post closed that its basically fixed now, so I will close this issue. 

Thanks for the updates.

**Comment by pvbhanuteja** [comment]
Currently facing this issue again.
