### ISSUE TITLE
Real Debrid Client .rar files

### ISSUE THREAD

**Issue by halfloaf123** [rogerfar/rdt-client#444]
**What version are you using?**
Latest
**Wat OS are you running?**
Windows 11
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
Real Debrid
**Which downloader are you using?**
Real Debrid Client

I have setup Sonarr and Radarr with Real Debrid Client but I am having an issue where Real Debrid client is merging the torrent files into a .rar file when it picks up content from Sonarr and Radarr, please can someone assist me on how can Real Debrid client unrar/extract the content after completion.

![Screenshot 2024-03-28 152842](https://github.com/rogerfar/rdt-client/assets/20166391/24bea487-dd34-4da7-a5d3-2a6d072218c1)

**Comment by grogcw** [comment]
Same issue as [#354](https://github.com/rogerfar/rdt-client/issues/354).

**Comment by rogerfar** [comment]
Please post a full log next time including the magnet so I can reproduce it.

**Comment by dinjojo** [comment]
I thinks it's to do with real debrid and not rdtclient not sure how real debrid decides to rar the contents of a file
