### ISSUE TITLE
Torrent getting stuck on "Queued for downloading"

### ISSUE THREAD

**Issue by Schmops8** [rogerfar/rdt-client#448]
**What version are you using?**
Latest, 2.0.63
**Wat OS are you running?**
Windows 10
**Are you using Docker or as a service?**
As a service
**Which debrid provider are you using?**
RealDebrid
**Which downloader are you using?**
Internal Downloader
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/14825469/rdtclient.log)

Tried several different files over Radarr, also tried direct import. Worked fine yesterday and today it just gets stuck on "Queued for downloading". Tried deleting database and rdtclient and

**Comment by Drknz056** [comment]
Yep, I have the same issue also running in Docker.

Files are either queued for download or are downloading when they are already completed in Real Debrid.

Radarr/Sonarr never import the files, just perpetually says downloading in the queue.

**Comment by rogerfar** [comment]
The logs keep stating `No ID received for download`. That's odd, it looks like you're using the internal downloader.

Is there maybe a permission issue that it cannot download to your download path?

**Comment by Shabbypenguin** [comment]
Also having this issue, some files work fine, some dont. logs says it cant find the downloaded file and just cycles searching for it.
[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/14893873/_rdtclient_logs.txt)

**Comment by Schmops8** [comment]
> The logs keep stating `No ID received for download`. That's odd, it looks like you're using the internal downloader.
> 
> Is there maybe a permission issue that it cannot download to your download path?

So I tried around with permissions, they should work. In the "Speed Test" tab it also says "Your download path looks good" and write speed test was also fine. The odd thing is the "Test Real-Debrid download speed" doesnt work.

**Comment by rogerfar** [comment]
This seems to be the same issue as here:
https://github.com/rogerfar/rdt-client/issues/449

Please try the latest version, it should've fixed a few symlink issues.
