### ISSUE TITLE
Prowlarr cannot connect to rdtclient on same host

### ISSUE THREAD

**Issue by raoulvanoosten** [rogerfar/rdt-client#450]
I run Prowlarr on a QNAP NAS with docker compose, and can connect to a normal qBittorrent instance (which uses port 6363). However, when I follow the steps and try to connect to port 6500 for rdt-client, testing takes a very long time and finally gives the error under host "Unable to connect to qBittorrent". The IP-adress is the same as with port 6363. What is going on and how can I fix this?

I use 192.168.1.2, which is the IP-adress of the NAS. Each container also has it's own adress, 172.29.4.2 for rdtclient, but that doesn't work either.

**Comment by rogerfar** [comment]
There's something wrong in either your firewall or your not using the correct port. RDT runs on 6500 by default, so you have to use that port unless you changed it.

**Comment by raoulvanoosten** [comment]
I got it working. It turns out the images had to be in the same compose file.
