### ISSUE TITLE
Error in refreshing page in :6500/setting

### ISSUE THREAD

**Issue by FreeWoRLD83** [rogerfar/rdt-client#454]
**What version are you using?**
2.0.66
**Wat OS are you running?**
Debian 12
**Are you using Docker or as a service?**
Service
**Which debrid provider are you using?**
Real-debrid
**Which downloader are you using?**
Internal

Refreshing web page when in ":6500/settings/" ends up in blank page.

**Comment by rogerfar** [comment]
This was a thing I should've fixed a long time ago, should be good in the next release.
