### ISSUE TITLE
Download path setting seems to not register

### ISSUE THREAD

**Issue by j-cray** [rogerfar/rdt-client#455]
I'm encountering errors that seem to be related to the download path setting. The first error shows its face while attempting a speed test in the settings panel:

`Could not test your download speed
An unexpected error occurred preparing download https://34.download.real-debrid.com/speedtest/testDefault.rar for torrent : The value cannot be an empty string. (Parameter 'path') `

It's strange that it is reporting an empty string for path, as I do have a download path set. Both the permissions check and the folder write speed tests pass with flying colours.

The second error is that all downloads are failing as the program is attempting to download to read-only paths:

`2024-04-09 15:59:56.602 -07:00 [ERR] RdtClient.Service.Services.TorrentRunner: Unable to start download: An unexpected error occurred preparing download https://sea1.download.real-debrid.com/d/4T4F6KGPLD6XM89/A.Fistful.of.Dollars.1964.4K.SDR.2160p.BDRemux%20Ita%20Eng%20x265-NAHOM.mkv for torrent A.Fistful.of.Dollars.1964.4K.SDR.2160p.BDRemux Ita Eng x265-NAHOM: Read-only file system : '/nix/store/zvr6m2pzpy31admcll9clcfk7bnhm54n-rdtClient-v2.0.66/opt/rdtClient/A.Fistful.of.Dollars.1964.4K.SDR.2160p.BDRemux Ita Eng x265-NAHOM' for download A.Fistful.of.Dollars.1964.4K.SDR.2160p.BDRemux Ita Eng x265-NAHOM.mkv. Completed: 0%, avg speed: 0bytes/s (9146f76b-308f-41bd-94fb-fc8efd461f90) remoteID:  for torrent A.Fistful.of.Dollars.1964.4K.SDR.2160p.BDRemux Ita Eng x265-NAHOM (26ANRKLKJAC5U - downloaded 100%) (9dbc239e-6dc0-46cf-994e-17b7c1d740f3)`

It is trying to download to the /nix/store path which is certainly read-only. However, I have set both the download path and the mapped path to `/library/downloads/rdt`, which is not read-only. Empty folders of the given torrent name do appear in `/library/downloads/rdt`, so the program is aware of the path I set, yet it is still trying to download to the nix store path. The `/nix/store` path is the path where rdtclient is installed, so it seems like the program is not reading the download path I set and is instead attempting to download to a default location (`${installpath}/opt/${packagename}`).

I tested both the errors above with both aria2 and the internal downloader. Apologies if the two errors are not connected, but they do seem to be! I've packaged rdtclient for NixOS so I acknowledge I'm blazing a trail here and some of this may be due to errors in my configuration (e.g. the second error may be due to me misunderstanding how  the download paths are implemented.). Full log posted at the pastebin link below. 

**What version are you using?**

v.2.0.66

**Wat OS are you running?**

Linux - NixOS

**Are you using Docker or as a service?**

service

**Which debrid provider are you using?**

real-debrid

**Which downloader are you using?**

aria2c, internal

**Please attach a log file here with the log setting set to debug**

https://pastebin.com/M6txdsNb

**Comment by rogerfar** [comment]
It's hard to say what's going on here, the app is crashing as soon its starting:

```
2024-04-09 14:23:49.628 -07:00 [WRN] RdtClient.Service.BackgroundServices.Startup: Starting host on version 2.0.66.0
2024-04-09 14:24:08.568 -07:00 [ERR] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Writing to the response body is invalid for responses with status code 304.
```
So it's not even loading in the settings looks like.

Are you using the BasePath setting in either appsetting or the BASE_PATH env variable?

**Comment by j-cray** [comment]
oh that's bizarre. I had set the basepath in appsettings.json earlier today, so that might be why that is appearing in the logs. I did however switch it back to null quite quickly and the errors described here persist. (Just double-checked appsettings.json and the basebath value is indeed null).

**Comment by rogerfar** [comment]
I added a fix to the next build to handle 304 responses better.

Can you post a fresh log?

**Comment by j-cray** [comment]
Absolutely.  I logged out/in, ran the download speed test and then tried restarting the two downloads in queue.

[rdtclient.log](https://pastebin.com/kp9qeXdk)

**Comment by rogerfar** [comment]
Looks like your pastebin doesn't work.

**Comment by j-cray** [comment]
argh, that's frusting. [reupload](https://pastebin.com/qqaq9MsP)

**Comment by j-cray** [comment]
nope that didn't work either. pastebin doesn't like my log apparently. will find another paste service, one moment

**Comment by j-cray** [comment]
[github gist](https://gist.github.com/j-cray/782ee1c01efd878db361dccd579f90a1)

**Comment by rogerfar** [comment]
Could you post full logs because I also need to see the startup sequence, and which settings it's trying to use.

**Comment by j-cray** [comment]
oh sure thing! [here you go](https://gist.github.com/j-cray/3ea0a4789d97c4c02b683b5e996adac6)

**Comment by rogerfar** [comment]
Should be good in .72 now.

I believe the issue only occurs because you have the symlink downloader selected and you're trying to do a speedtest, which doesn't jive very well together. For now I'm forcing the downloader to be the Internal downloader with your default downloader is set to symlink.

**Comment by j-cray** [comment]
Absolutely, that fixed the first error with the download test. However I am still facing issues with the program creating empty folders rather than downloading all the files. Please note that I am (or ought to be) using aria2c for downloads, not the symlink downloader. Let me know if you'd like me to close this issue and start a separate one. Thanks for your help getting to the bottom of this!

In case not, here are my [latest logs](https://gist.github.com/j-cray/9345d8b9c87668cb0aa8e0a627e62d21)

**Comment by rogerfar** [comment]
Which torrent in your logs wasn't working? Because it shows it's working as expected. It downloaded it and unpacked it.

**Comment by j-cray** [comment]
All of them fail, that's the thing! rdt-client _thinks_ it correctly downloaded the torrents, but it actually did not. It just creates empty folders with the torrents names, but no files are inside. Let's take A Fistful of Dollars as our example. That's a ~60GB file but it gets downloaded and marked as complete in an instant. No files are inside, packed or unpacked. I've tried to eliminate other causes, so I have tried varying the way I add downloads (prowlarr, manually), I've tried a number of different downloads from various sources, and I have tried using both aria2c and the internal downloader.

I think what has changed is the logging, rather than the actual success of the downloads. The snippet I shared in my first post is the clue, I think.  This line `unexpected error occurred preparing download https://sea1.download.real-debrid.com/d/4T4F6KGPLD6XM89/A.Fistful.of.Dollars.1964.4K.SDR.2160p.BDRemux%20Ita%20Eng%20x265-NAHOM.mkv for torrent A.Fistful.of.Dollars.1964.4K.SDR.2160p.BDRemux Ita Eng x265-NAHOM: Read-only file system : '/nix/store/zvr6m2pzpy31admcll9clcfk7bnhm54n-rdtClient-`.

The path `/nix/store/zvr6m2pzpy31admcll9clcfk7bnhm54n-rdtClient` is not my target download path -- it's the install location of rdt-client. So presumably the program is attempting to do a write operation internally within its install path prior to actually downloading the file to my set download path (`/library/downloads/rdt`) as part of preparing the download.

As I type this out, it occurs to me that rdt-client really is working as intended, but its function isn't entirely compatible with NixOS. If you or anyone reading this is unfamiliar with how NixOS works, it doesn't have a normal file system hierarchy. All programs are installed at the read-only `/nix/store/${hash}/${program}' location. Every time the program changes, say an update occurs, a new hash is created and a new generation of the program now exists. The `/nix/store` is always a read-only filesystem only amendable by the OS itself.

Further evidence of this comes from the download speed test, which is much clearer in its logging now (thank you!). It also tries to download its file to the `/nix/store` path install location of rdt-client, and also fails with a read-only filesystem error.

I am going to close this issue as I don't think there is a bug with rdt-client. I do hope it's possible (and simple/convenient) to amend the program so that this internal download preparation could be done at another path that would be accessible for NixOS (say `/var/rdt-client`), but this is an incredibly niche request, not worth sweating over, especially because NixOS users always have the option to deploy a Docker container. I will open a feature request, but please consider it low-priority. Thanks for your patience and help in puzzling this out!
