### ISSUE TITLE
Constant drive usage

### ISSUE THREAD

**Issue by Reen68** [rogerfar/rdt-client#46]
I'm using rdtclient and as soon as its running (like the container is running) it is constantly accessing my hard drive

21759 be/4 1000        0.00 B/s    0.00 B/s  0.00 %  0.00 % dotnet RdtClient.Web.dll [.NET ThreadPool]

I think its actually that process right there but I'm not sure. (iotop shows me this sometimes while running it)

**EDIT:**

 435 be/4 root       63.27 K/s   75.32 K/s  0.00 %  2.93 % mount.ntfs /dev/sda2 /srv/dev-disk-by-uuid-282A873D2A870752 -o rw,big_writes
24661 be/4 1000        0.00 B/s    9.04 K/s  0.00 %  0.00 % dotnet RdtClient.Web.dll [.NET ThreadPool]

Those two are always writing at the same time.

As soon as I stop the rdtclient docker container it stops.

**Comment by timcoop3r** [comment]
Are you using the JSON logging options in the docker examples? I don't have these and I don't think I see this same behaviour. If you are using the docker logging options maybe try removing them and see if it still does it? (for those processes anyway)

**Comment by Reen68** [comment]
So, just changed the logging option to none and redeployed, afterwards I actually first tried to get some logs which are then unable to retrieve which makes me believe its not logging.

I still see the LED of my drive blinking the whole time as soon as I start the container and it stops as soon as I stop the container.

**Comment by rogerfar** [comment]
It is reading the database every few seconds, so you probably see that?

**Comment by Reen68** [comment]
Could be yes, I restarted logging and checked the cpu/memory usage and everytime I hear the harddrive and See the harddrive led blinking CPU usage of the container goes up.

Is that expected behaviour? 

I actually tried getting the container to run with setting up the db folder on my rootsd (raspbi) and the downloads folder on the external harddrive but It wont.

**Comment by timcoop3r** [comment]
> So, just changed the logging option to none and redeployed, afterwards I actually first tried to get some logs which are then unable to retrieve which makes me believe its not logging.

Thats weird, even without the logging options from the guide which generates external log files to the disk, I still get the logs through the docker command as normal?

**Comment by Reen68** [comment]
I'm still newto that so I dont really know.

Nonetheless, whatever logging options I choose I have those drive reads. I might be moving the db to the OSsd to help out myself with the noise from the drive.

**Comment by Reen68** [comment]
> It is reading the database every few seconds, so you probably see that?

As I could compose the container again today I tried a bit more. I couldn't let the database run on my root or any other folder than my hdd. I actually don't know why as I don't have those problems with other containers (Is it maybe because other containers have a user defined, which would be one with root access?).

Other than that I still see my HDD working every 2 or 3 seconds as soon as the container starts (I tried using a new db so that there's no old settings) and it's preventing my hdd to spindown. 

Im sorry if this is a dumb question but what is the reason to call the db every few seconds? I thought it might be to check if there is a new torrent file in some kind of watchfolder but sabnzbd does the same, although for nzbs and isn't showing this or a similar behaviour (as well as other programs that use watchfolders). Just curious what the reason is as I'm willing to learn.

**Comment by rogerfar** [comment]
I see what you mean yes, it does ping the database every 10 seconds, even if there are no active torrents.

I'll for the next version to improve that behavior a bit by keeping a counter in memory and only read the database whenever there are active torrents.

**Comment by rogerfar** [comment]
I have added caching to not ping the settings table and torrents table when nothing is going on.

Every time the system does an add or update or the Settings, Torrents or Downloads table this cache gets refreshed. 

This should reduce the read/writes significantly.
