### ISSUE TITLE
Making Symlink Downloader faster

### ISSUE THREAD

**Issue by maulik9898** [rogerfar/rdt-client#466]
While reviewing the `DownloadClient.cs` file, I noticed a 1-second delay being added after each symlink download completion:

https://github.com/rogerfar/rdt-client/blob/0bfb4974d8fa1bb276e22962ce87c7e1a773809e/server/RdtClient.Service/Services/DownloadClient.cs#L70

This delay seems to have a significant impact on the overall performance of the download process. In my testing, I observed that symlink resolution tasks typically complete within 0.2 seconds, and the additional 1-second delay is causing unnecessary waiting time.

To quantify the performance impact, I conducted a test using a torrent with 554 files. Here are the results:

```
With delay:
5:51:34.630 START
6:03:00.534 END
11:25.904 Total

Without delay:
6.18.37.536 START no delay
6.20.38.601 END no delay
00:02:01.065 Total no delay
```

As evident from the results, removing the delay led to a significant performance boost, reducing the total download time from approximately 11 minutes to just 2 minutes.

> The testing and observations mentioned above are specific to the symlink downloader. Further investigation may be needed to assess the impact of removing the delay on other downloaders available in the project.

**Comment by rogerfar** [comment]
I took this over from another fork, I left it in because I wasn't sure if it causes issues, because if you do 500 files in a torrent, even with the symlink downloader it will still unrestrict the files.

So it might be worth to investigate if we can skip unrestricting links if we're using the symlink downloader, I don't think it add value.

**Comment by maulik9898** [comment]
Yes for Symlink downloader we can skip this. Btw I am running an instance of RDT with this delay removed for the symlink downloader and it's working amazing. Without delay it's much faster.

**Comment by cchance27** [comment]
I mean realistically you could make the delay an optional value of the symlink downloader, just incase anyone has an issue with it, just leave it disabled by default

**Comment by Rodmodrtf** [comment]
> I took this over from another fork, I left it in because I wasn't sure if it causes issues, because if you do 500 files in a torrent, even with the symlink downloader it will still unrestrict the files.
> 
> So it might be worth to investigate if we can skip unrestricting links if we're using the symlink downloader, I don't think it add value.

+1 for skipping unrestricting links

**Comment by rogerfar** [comment]
I pushed an update that removes the delay. 

The part where it doesn't unrestrict is a bit more complicated, the unrestrict API call gives the filename back of what RD will use to put it, so RDT uses that filename to find the mounted file. I have to check if it's reliable to use the list of selected files to do that instead.

**Comment by Rodmodrtf** [comment]
> I pushed an update that removes the delay.
> 
> The part where it doesn't unrestrict is a bit more complicated, the unrestrict API call gives the filename back of what RD will use to put it, so RDT uses that filename to find the mounted file. I have to check if it's reliable to use the list of selected files to do that instead.

Btw, thank you for this great app
