### ISSUE TITLE
How to process ONLY files existing in personal RD library

### ISSUE THREAD

**Issue by ashipaek0** [rogerfar/rdt-client#472]
How does one process ONLY files in ones RD library (with sonarr/radarr) managing the symlinks?

The toggle  

_Automatically import and process torrents added to provider
When selected, import downloads that are not added through RealDebridClient but have been directly added to your debrid provider._

does not appear to do that.  what does it actually do?

TLDR, i've an existing library in RD curated with Sonarr.  Somehow the symlinks got broken so i have to start afresh, but it seems to be downloading duplicates into RD  and not processing them

**Comment by rogerfar** [comment]
That's what its supposed to do yes. If you have torrents in Real-Debrid, it will import them into RDT. Not sure why you would want to do that though because RDT wouldn't offer any real benefits though. If RDT is setup as the symlink downloader, it symlinks them to your download folders.

**Comment by ashipaek0** [comment]
> That's what its supposed to do yes. If you have torrents in Real-Debrid, it will import them into RDT. Not sure why you would want to do that though because RDT wouldn't offer any real benefits though. If RDT is setup as the symlink downloader, it symlinks them to your download folders.

If i understand this correctly, it means RDT symlink downloader should process my existing RD library, and generate the symlinks to my download folders.

Then i could process my download folders with Sonarr and regenerate my library?

**Comment by Pukabyte** [comment]
@ashipaek0 
Yes, depending on your setup.
If you have multiple instances of sonarr for instance, sonarrHD, sonarr4K and sonarr anime and radarrHD et.
This will not work since you can only set one category on the import. rdtclient won't know which torrent belongs to which category or arr. it will only import to the folder you specify and nothing else.

**Comment by ashipaek0** [comment]
Thanks.

Need to ask, is it compulsory to tick 'download files to host' when using symlink downloader?
will the symlinks setup work without downloading to host'?

my setup is on a VPS with limited bandwidth and it seems to be using up huge bandwidth even without streaming.

**Comment by rogerfar** [comment]
No that setting doesn't actually do anything.
