### ISSUE TITLE
Bug in SymlinkDownloader with subdirectory search enabled

### ISSUE THREAD

**Issue by pettytreebroker** [rogerfar/rdt-client#476]
`file` is never set in this loop:

https://github.com/rogerfar/rdt-client/blob/5cf73e97af473040efe923bbc821b4e9811e7dde/server/RdtClient.Service/Services/Downloaders/SymlinkDownloader.cs#L99-L102

Should be something like:
```
foreach (var subDirectory in subDirectories)
{
    file = FindFile(Path.Combine(rcloneMountPath, subDirectory), potentialFilePaths, fileName);
    if (file != null) {
        break;
    }
}
```

**Comment by rogerfar** [comment]
Well that would sure help yes!

**Comment by rogerfar** [comment]
Fixed in .75
