### ISSUE TITLE
Symlink Downloader and Rar Files

### ISSUE THREAD

**Issue by fregapple** [rogerfar/rdt-client#478]
Latest

Linux / Docker

Real-Debrid

Symlink

Error:
Can't handle compressed files with symlink downloader

Trying to use the symlink downloader with zurg rclone mount. However I am not sure if I am doing something wrong or that is isn't possible.

Files that aren't compressed in .rar will work fine. But otherwise it won't create the symlink. Is is because the file it wants to symlink is within a .rar?

**Comment by rogerfar** [comment]
You can symlink the rar, but what's the point, because you want whatever is in it, so you would still need to unpack it, basically downloading it.

If you don't want the rar, select on the files inside the rar, minus readme's, samples etc.
