### ISSUE TITLE
Downloaded files have root permissions with docker

### ISSUE THREAD

**Issue by phirestalker** [rogerfar/rdt-client#48]
Everything downloaded seems to be saved with root as the owner. This prevents radaar from moving them into the movie folder. I have PUID and PGID set to 1000 in my docker-compose file, which is for my first user on the host system. I do not see any options in settings about changing ownership of files, so I am unsure what else to try.

My image is updated every night automatically, so it should be the latest available.

**Comment by timcoop3r** [comment]
I use the 'user: 1000:1000' config line in docker-compose and runs the container as the correct users on the system resolving file permission problems.

**Comment by phirestalker** [comment]
Ya, I made the mistake of installing the snap version of docker on Ubuntu, which causes the containers to run under root I believe. I wish I could easily migrate to the package version.
I will try the user line and see what happens.

**Comment by phirestalker** [comment]
The user config option fixed it, thank you.
