### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by jackkerouac** [rogerfar/rdt-client#482]
**What version are you using?**
2.0.75.0

**What OS are you running?**
Ubuntu 22.04

**Are you using Docker or as a service?**
Yes

**Which debrid provider are you using?**
Real-Debrid

**Which downloader are you using?**
Aria2

**Please attach a log file here with the log setting set to debug**
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 
  Based on images from linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
Setting permissions
[custom-init] No custom files found, skipping...
Setting permissions
[ls.io-init] done.
Changing to /app folder
Starting rtdclient
[19:49:31 WRN] Starting host on version 2.0.75.0

I cannot login to rdt-client. I get an Invalid Credentials error. I am using the same credentials that I use for Real-Debrid and the same ones I use to connect to rdt-client throught sonarr (both work).

Is there a way to reset the password or something?

**Comment by rogerfar** [comment]
You login with the credential you give in when you first setup rdt. If you forget your password, delete your container and data and start over.

**Comment by billettg** [comment]
Had the same issue, recreating the container and data is not a good solution. Passwords should be changed regularly and the user shouldn't be expected to rebuild each time for a simple password change on RD side.
