### ISSUE TITLE
No GUI  on 2.0.76

### ISSUE THREAD

**Issue by Zuluuk** [rogerfar/rdt-client#483]
**What version are you using?**
2.0.76

**Wat OS are you running?**
Unraid

**Are you using Docker or as a service?**
Yes

**Which debrid provider are you using?**
Real Debrid

**Which downloader are you using?**
Internal

**Please attach a log file here with the log setting set to debug**
Cant get into login screen to get logs, I went back to 2.0.75

**Comment by rogerfar** [comment]
Seems to work fine here.
