### ISSUE TITLE
Blank download entries

### ISSUE THREAD

**Issue by sylvaindd** [rogerfar/rdt-client#488]
**What version are you using?**
2.0.78

**Wat OS are you running?**
Debian

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
AllDebrid

**Which downloader are you using?**
Internal Downloader

**Please attach a log file here with the log setting set to debug**
I keep having blank entries after downloads.
![image](https://github.com/rogerfar/rdt-client/assets/5629405/aa38288a-1200-49f6-8f29-2cc93369aaf3)
![image](https://github.com/rogerfar/rdt-client/assets/5629405/e7fa1faa-7a4d-4570-9ab4-729486d133e2)

**Comment by rogerfar** [comment]
Do you have logs?

**Comment by rogerfar** [comment]
Yeah that's not good, it means that the call to AllDebrid is timing out, you might want to increase the setting `Connection Timeout` on the `Provider` setting tab to something higher.
