### ISSUE TITLE
sonarr:failed to connect to qbitorrent please check your settings

### ISSUE THREAD

**Issue by ananias47** [rogerfar/rdt-client#489]
**What version are you using?** 
2.0.78

**Wat OS are you running?**
Windows 10

**Are you using Docker or as a service?**
service

**Which debrid provider are you using?**
RD

**Which downloader are you using?**
Bezzad

**Please attach a log file here with the log setting set to debug**
[rdtclient_002.log](https://github.com/rogerfar/rdt-client/files/15226697/rdtclient_002.log)

![Screenshot 2024-05-06 232920](https://github.com/rogerfar/rdt-client/assets/6560173/7e3a9e18-6a4e-4853-b562-965ad8105d31)
when i am trying to dl some torrents with sonarr it gives me this error on photo.At the same time other torrent of the same search results works well

**Comment by Jayrayme** [comment]
Same issue, internal downloader.

If i'm going to the alldebrid chrome extension with a right click it's the same, nothing happen. so it's maybe debrid side

**Comment by ananias47** [comment]
yes you are right i try it to convert manualy and it says something about tos violetion from rd side

**Comment by Jayrayme** [comment]
I asked alldebrid and they said they are on this issue but they don't know when it will be fixed
