### ISSUE TITLE
Program crashes & creates temp folder in system32 folder when using Sonarr

### ISSUE THREAD

**Issue by starkayc** [rogerfar/rdt-client#490]
**What version are you using?**
v2.0.65
**Wat OS are you running?**
Windows 10 Pro
**Are you using Docker or as a service?**
Service
**Which debrid provider are you using?**
RD
**Which downloader are you using?**
Internal Downloader
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/15253548/rdtclient.log)

When using v2.0.65 and above the program crashes with no fix other than to downgrade to v2.0.64. I have ASP.NET Core Runtime 8 installed via winget. I also noticed that the program creates temp folder in system32 folder which I'm not sure is intentional or not as I have my download/map path set to "G:\Torrents\Downloads".

Here's a video of it: https://streamable.com/3flwsf

Event Viewer Logs:

> Application: RdtClient.Web.exe
CoreCLR Version: 8.0.424.16909
.NET Version: 8.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FF853CCFE14

> Faulting application name: RdtClient.Web.exe, version: 2.0.71.0, time stamp: 0x65cd0000
Faulting module name: coreclr.dll, version: 8.0.424.16909, time stamp: 0x65f9e938
Exception code: 0xc0000005
Fault offset: 0x000000000013fe14
Faulting process id: 0x910
Faulting application start time: 0x01daa173c3db867e
Faulting application path: E:\RealDebridClient\RdtClient.Web.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\coreclr.dll
Report Id: cfb833ba-27cd-410c-866c-1980d94620f5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by rogerfar** [comment]
How are you starting rdt? Service or manually? Try running `dotnet RdtClient.Web.dll`.

**Comment by starkayc** [comment]
> How are you starting rdt? Service or manually? Try running `dotnet RdtClient.Web.dll`.

I'm running it as a service and used the bat file to install as service. It seems like it only crashes when it's downloading something as when I ran the command it crashed at 60%. Though when I ran it with `dotnet RdtClient.Web.dll` it created the folder where RDT is at compared to in System32. Thanks!

Crash Pic:
![image](https://github.com/rogerfar/rdt-client/assets/5252904/5696a2f0-50be-406c-9c8c-fc185a40ab9c)

Video of problem(crashes at 2:20): https://www.youtube.com/watch?v=WW8x7KsqjDM

**Comment by rogerfar** [comment]
Super odd, never seen that before. Some quick googling suggests that coreclr maybe corrupt? Could you try removing .NET 8 and re-installing it again?

**Comment by starkayc** [comment]
> Super odd, never seen that before. Some quick googling suggests that coreclr maybe corrupt? Could you try removing .NET 8 and re-installing it again?

I removed .NET 8 then rebooted and installed it again via `winget install dotnet-runtime-8 dotnet-sdk-8` then rebooted and the results were the same. Everything works on v2.0.64 & below though. 

Video: https://www.youtube.com/watch?v=-c0zwRxAxDM

**Comment by rogerfar** [comment]
Do you get the same result with the Bezzad downloader?

**Comment by starkayc** [comment]
> Do you get the same result with the Bezzad downloader?

Using Bezzad option resulted in no crash and been working fine for a day without any issues other than creating folders in system32. Though if it's a result of running as service then its fine. Thanks!

**Comment by rogerfar** [comment]
That's good to know, the internal downloader clearly still has issues unfortunately.
