### ISSUE TITLE
Windows Service Stops, Wont stay started.

### ISSUE THREAD

**Issue by asislife20** [rogerfar/rdt-client#492]
**What version are you using?**
2.0.78
**Wat OS are you running?**
Windows 11
**Are you using Docker or as a service?**
Service
**Which debrid provider are you using?**
Real-debrid 
**Which downloader are you using?**
Internal Downloader 
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/15280306/rdtclient.log)

**Comment by rogerfar** [comment]
There's nothing in the logs that stand out, did you check the event logs?
