### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Suric4t3** [rogerfar/rdt-client#5]
Hi ! 
Do you have a docker on this app to run it on a linux server?
Congratulations for this job !

**Comment by lordbeavis** [comment]
i would like to do the same, i think the jackett docker runs the windows binaries, so maybe we can get it to build with that?

**Comment by rogerfar** [comment]
I think that's a good idea, shouldn't be too difficult, I just have to check if I'm using any Windows specific stuff.

**Comment by lordbeavis** [comment]
i think this is what is needed. 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-5.0

**Comment by rogerfar** [comment]
I have added Docker support for now, check the Readme for instructions.

I will drop support for services as it's easier to maintain just 1 deployment type, you can still build it yourself pretty easily if needed.
