### ISSUE TITLE
Feature req: support for debrid-link.com

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [rogerfar/rdt-client#505]
Hello, I use another debrid provider called debrid-link.com. I like the project and I would like to if it would support debrid-link.com too?

**Comment by GumballHelmet** [comment]
I use it too, it could be very nice to add it. API: https://debrid-link.com/api_doc/v2/introduction

**Comment by Kayn2106** [comment]
Yeah that'd be great ;)

**Comment by megatwig** [comment]
There's an existing FR [here](https://github.com/rogerfar/rdt-client/issues/249)

**Comment by rogerfar** [comment]
Love how people make forks instead of PR's so everyone can benefit.
