### ISSUE TITLE
Remove Torrent On Completion Does Not Work

### ISSUE THREAD

**Issue by pavichokche** [rogerfar/rdt-client#517]
**What version are you using?**
2.0.78
**Wat OS are you running?**
Windows 11 Pro, up to date
**Are you using Docker or as a service?**
Service
**Which debrid provider are you using?**
Real-debrid
**Which downloader are you using?**
Bezzad
**Please attach a log file here with the log setting set to debug**
[rdtclient - Copy (2).log](https://github.com/user-attachments/files/15514077/rdtclient.-.Copy.2.log)

All the Post Download Action options are set to "remove download from client and provider" and yet after completion the log just says:
2024-05-31 07:09:16.233 -04:00 [DBG] RdtClient.Service.Services.TorrentRunner: Not removing torrents or files for torrent www.SceneTime.com   -    Station 19 S07E10 1080p HEVC x265-MeGusta (TEZHWNCZK2RTU - downloaded 100%) (425bc816-6f6a-429d-a509-f0b2a52bbff3)

![image](https://github.com/rogerfar/rdt-client/assets/14185621/91c4ed02-080e-409e-ab54-263901ebf79a)

**Comment by fungos** [comment]
Similar here with 2.0.80

**Comment by rogerfar** [comment]
That's working as expected. Radarr / Sonarr are responsible for sending a delete command. So that setting is ignored when it comes from those 2.
