### ISSUE TITLE
Cannot add torrent: { "error": "wrong_parameter", "error_code": 2 }

### ISSUE THREAD

**Issue by phirestalker** [rogerfar/rdt-client#52]
All torrents seem to be giving me this error as of today. I have tried with the torrent file and with a magnet link pasted in. I am able to add the torrent to real-debrid directly without issue.

EDIT:
forgot to mention that the download test inside rdt-client succeeds, so the API key should still be good.

**Comment by phirestalker** [comment]
Yep, it was the API key. DOH!!
On a side note, it does not seem capable of getting the status of torrents that are added directly to the site. Is that feature planned?

**Comment by rogerfar** [comment]
I have recently also out that the API rotates itself without warning, very useful feature... But it's impossible to detect if the API key is invalid or changed.

It originally pulled in torrents from RDClient but I decided to keep them separate, maybe in the future if there is more demand for it.

**Comment by phirestalker** [comment]
What happens if I also add the torrent to rdt-client? Will it sync up then?

**Comment by rogerfar** [comment]
I'm not sure really what happens on the RD end, it might just give an error that the torrent already exist? Try it :)

**Comment by phirestalker** [comment]
It picks it up just fine. Thanks for the help. Since this works so well there really is no need for a new feature.
