### ISSUE TITLE
Download speed dropping to 0B/s and halting download continuously

### ISSUE THREAD

**Issue by ajama-1984** [rogerfar/rdt-client#528]
Download speed keeps dropping to 0B/s, which means that downloads are taking longer than usual. I reinstalled RDT-Client with a fresh folder for app data to exclude config issues. Tried on two separate docker/server instances 

**What version are you using?**
2.0.79

**What OS are you running?**
Ubuntu OS with RDT-Client running in docker

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Real Debrid

**Which downloader are you using?**
Internal Downloader

**Please attach a log file here with the log setting set to debug**
[rdtclient_018.log](https://github.com/user-attachments/files/15927534/rdtclient_018.log)

**Comment by ajama-1984** [comment]
Is the internal downloader the best option in this case? or do is it recommended to use Aria2c?

**Comment by adiberk** [comment]
I am having the same issue.  Also it is eating up all the CPU

**Comment by ajama-1984** [comment]
@rogerfar Is there anything else I can provide to help you investigate this?

**Comment by zosobao5150** [comment]
I also have this issue.

**Comment by adiberk** [comment]
I believe I found solution. If I set a max download speed to  15 mb (I am sure you can do more).  I stop seeing drops to 0

**Comment by ajama-1984** [comment]
> I believe I found solution. If I set a max download speed to 15 mb (I am sure you can do more). I stop seeing drops to 0

Doesnt work at all. @rogerfar are you able to replicate this with the internal downloader?

**Comment by rogerfar** [comment]
Try using the bezzad downloader or aria2, it will greatly improve.

**Comment by KUSH43** [comment]
with bezzad downloader i'm limited to 130 mb/s and with internal downloaders speed up to 250mb/s idont understand why bezzad was limited
