### ISSUE TITLE
Unable to download files in the new RDT version (v2.0.80)

### ISSUE THREAD

**Issue by sureshfizzy** [rogerfar/rdt-client#538]
**What version are you using?**
v2.0.80

**Wat OS are you running?**
Ubuntu 22.04.4 LTS aarch64

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Real-Debrid

**Which downloader are you using?**
Symlink Downloader

**Please attach a log file here with the log setting set to debug**
[_rdtclient-Sonarr_logs.txt](https://github.com/user-attachments/files/16216541/_rdtclient-Sonarr_logs.txt)

With the current RDT package, the torrent remains stalled, and I am unable to download files. It runs in an infinite loop.

**Comment by sureshfizzy** [comment]
@rogerfar Just adding few more details here, During the period while rdt tries to donwload the shows, I can see some rate limits are being hit on the other software (I use zurg). 

2024-07-14T10:38:10.107Z    DEBUG    api_client    API rate limit reached, attempt #1, retrying in 1 seconds

I guess rdt client is still hitting with a high amount of api which makes other apps unusable.

**Comment by joshk6656** [comment]
API limits are shared between all apps on the API key. I doubt it is rdt-client that is causing the limit, more likely it is how you are mounting your RD content.

**Comment by rogerfar** [comment]
I'm not sure what Zurg is, but what @joshk6656 says, you are sharing API limits. RDT implements a retry mechanism now, otherwise adjust your back off time in `Settings -> Check Internal` and set it to something like 1 minute.
