### ISSUE TITLE
Torrent error: magnet_error

### ISSUE THREAD

**Issue by jctennis** [rogerfar/rdt-client#54]
I am getting a LOT of torrents failing with this error when using rdt-client with Sonarr and Jackett. Any idea how I can troubleshoot this?

**Comment by rogerfar** [comment]
Did you try adding those magnets manually in RealDebrid? Does that work?

**Comment by jctennis** [comment]
I did not, because Sonarr added them automatically and I'm not sure if
there is a way to pull the magnet link to try it. I'll have to dig around
and figure out how to do that.

**Comment by jctennis** [comment]
The problem was with the torrents. Not RDT-client. I'll close this. Thanks!
