### ISSUE TITLE
Rared files and music support

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [rogerfar/rdt-client#541]
Hi @rogerfar (sorry for ping), I use zurg nightly that have extract option to extract rar files in rclone dir so how to tell RDT Client to look for extracted files and use symlink downloader to download the extracted mp3 files?

**Comment by rogerfar** [comment]
Can you give an example torrent.

**Comment by EsmailELBoBDev2** [comment]
https://1337x.to/torrent/2090829/Ed-Sheeran-Divide-Deluxe-2017/
