### ISSUE TITLE
[Feature] Pause downloads

### ISSUE THREAD

**Issue by Matssa56** [rogerfar/rdt-client#543]
Hi,

Is there a way to pause the active downloads (for example pause in order to save bandwidth)?

I know you can reduce the speed but not under 1Mbps.

Thanks!

**What version are you using?**
Lastest version

**Wat OS are you running?**
Debian 12

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Alldebrid

**Which downloader are you using?**
Internal / Bezzad

**Comment by rogerfar** [comment]
Try using the Aria2c downloader, that has built in pause support.
