### ISSUE TITLE
Real Debrid API Response Changes for Uncached Torrents

### ISSUE THREAD

**Issue by naby-dev** [rogerfar/rdt-client#545]
It seems as though Real Debrid has changed the way the handle uncached torrents when using the instant availability endpoint. 
Before the hash would still be returned with an empty body. Now they return a empty list instead. This cause a deserialization issue,

![image](https://github.com/user-attachments/assets/f8d18ef9-9c65-40bb-9468-e4c7bc793d0b)
![image](https://github.com/user-attachments/assets/7e8e0aea-734d-478e-b85a-251963fd386f)

**Infohash to test with:**
137e55f28e395400393dd7f68f7ff5ed4d41000e

**URL:**
https://app.real-debrid.com/rest/1.0/torrents/instantAvailability/137e55f28e395400393dd7f68f7ff5ed4d41000e

**What version are you using?**
2.0.80

**What OS are you running?**
Linux 

**Are you using Docker or as a service?**
Docker 

**Which debrid provider are you using?**
Real Debrid 

**Which downloader are you using?**
Bezzad

**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/user-attachments/files/16286638/rdtclient.log)

**Comment by rogerfar** [comment]
Thanks! Managed to reproduce it, updated the RDNET library and will publish a new release of RDT.
