### ISSUE TITLE
Feature request:  Have a filter bar and select/select all action to be able to quickly delete items.

### ISSUE THREAD

**Issue by vamichael** [rogerfar/rdt-client#546]
**What version are you using?**

**Wat OS are you running?**

**Are you using Docker or as a service?**

**Which debrid provider are you using?**

**Which downloader are you using?**

**Please attach a log file here with the log setting set to debug**

**Comment by rogerfar** [comment]
![image](https://github.com/user-attachments/assets/b7b7dfc1-4636-427a-bead-5b7691701e4f)

**Comment by vamichael** [comment]
How can you enter a search item?  e.g.

> Forrest Gump
