### ISSUE TITLE
Some Movie path issue

### ISSUE THREAD

**Issue by Rodmodrtf** [rogerfar/rdt-client#547]
**What version are you using?**
2.0.80
**Wat OS are you running?**
Ubuntu
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
RD
**Which downloader are you using?**
Symlink Downloader
**Please attach a log file here with the log setting set to debug**

**Comment by Rodmodrtf** [comment]
folder and .mkv naming mismatch and unable to import using radarr, example Movie.2024.[GB]/Movie.2024.mkv
renaming the folder to Movie.2024.mkv fixed the issue, guessing rdtclient is reporting the wrong folder name to radarr

**Comment by rogerfar** [comment]
Please add logs.
