### ISSUE TITLE
Progress not showing on sonarr

### ISSUE THREAD

**Issue by gibahjoe** [rogerfar/rdt-client#567]
Sonarr doesnt show progress at all and time left is always 00:00:00  so I have to check RDT Client for the progress (it shows on rdt client).

**What version are you using?**
2.0.81

**Wat OS are you running?**
Windows 11

**Are you using Docker or as a service?**
Service

**Which debrid provider are you using?**
Real-debrid

**Which downloader are you using?**
Internal downloader

**Please attach a log file here with the log setting set to debug**

**Comment by BlueBull010** [comment]
Yup, I have this issue as well, with Radarr too. It used to work in the past and it didn't stop working right after an RDT update, so I suspect an update on the Sonarr side could have caused this. Not a major issue as long as downloads still work though, just a small inconvenience

**Comment by jamauai** [comment]
Same issue. Also v2.0.81 in docker.

**Comment by rogerfar** [comment]
This is fixed in the next version.
