### ISSUE TITLE
Running Service on Win11 constantly eats all storage space on computer until service is disabled

### ISSUE THREAD

**Issue by Starslayer74** [rogerfar/rdt-client#570]
**What version are you using?**
20.8.1
**Wat OS are you running?**
Windows 11
**Are you using Docker or as a service?**
Service
**Which debrid provider are you using?**
Real-debrid
**Which downloader are you using?**
Internal
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/user-attachments/files/16786907/rdtclient.log)

**Comment by rogerfar** [comment]
I'm assuming you mean memory instead of HDD space right?

The error I'm seeing is `Not enough memory is available to complete this request`. How much memory does your PC have? Try using the Bezad downloader and see if that helps.

**Comment by Starslayer74** [comment]
No, it's actually using up space on my SSD. My PC has 16gb of RAM but admittedly not a lot of space free on the SSD (currently around 15 gigs free) - I can actually start the service and open file explorer, and watch my C drive space start going down immediately. Is it just that I don't actually have enough free space to run the service?

I'll try the Bezad downloader like you suggested.

**Comment by rogerfar** [comment]
Is it downloading anything at that point? Do you know which file is eating up all the space? Try maybe something like Spacesniffer or windirstat to see where it is going to.

**Comment by Starslayer74** [comment]
Nope, not downloading anything, I can just start the service, nothing is queued to download, and it just starts growing. I can't find a file that is taking up the space

**Comment by Starslayer74** [comment]
I used spacesniffer and found some other huge files that I was not aware of, and freed up a lot more space, and now the service seems to be stablized, It looks like that might have been the culprit. I'm going to let it run today and see what it looks like tomorrow morning, there are a few downloads that should start overnight
