### ISSUE TITLE
[BUG] Internal Downloader Speed Limiting Glitchy / Not as Intended

### ISSUE THREAD

**Issue by Reasonable-Grape2698** [rogerfar/rdt-client#579]
**What version are you using?**
Latest

**Wat OS are you running?**
Ubuntu

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Realdebrid

**Which downloader are you using?**
Internal

**Please attach a log file here with the log setting set to debug**
N/A

Speed limiting not functioning. Set to 6, though continues downloading a 6.5+ / maxing connection.
Set to 1, downloads at exactly 2.29
Set to 2, downloads at exactly 4.38/4.39

Edit: parallel downloads... Plus overheads. So 2 * 2 + overheads = 4.38. This may be as intended, so maybe this is a feature request to optimise it and/or allow fractional amounts (ie 2.5) to get the exact desired download speed. Currently if I set it as 2.5 it reverts after saving and refreshing page.

**Comment by Reasonable-Grape2698** [comment]
Did further testing, it's setting the limit PER download and seems not to include overheads. 

For example, 2MB/s * 2 downloads + overheads = ~4.38MB/s.

Needs to just be updated to divide it by the number of parallel downloads, unless this is as intended?

**Comment by Reasonable-Grape2698** [comment]
Feature request: Enable fractions of download speed, ie 2.2? This way I can configure it to get exactly ~5 after overheads.

3 is too much, 2 isn't enough.

**Comment by GabbeHags** [comment]
I have looked through the code and it looks like you are correct. The "Maximum parallel downloads" in General settings sets each of the parallell downloads to the value in "Download speed (in MB/s) (only used for the Internal Downloader)" in Download Client settings.

So for example if i have set "Maximum parallel downloads" to 1 and "Download speed" to 10 then the max speed i will be using is 10. But if i would set "Maximum parallel downloads" to 4 then each of the parallell downloads will be limited to 10 but in total we can use 40.

So one solution would be to make the download speed for each download take in to consideration all active download and change the download speed corresponding to that.

I will create a PR that will make the active parallel download be taken in to consideration when deciding the current download speed.

**Comment by Reasonable-Grape2698** [comment]
> I have looked through the code and it looks like you are correct. The "Maximum parallel downloads" in General settings sets each of the parallell downloads to the value in "Download speed (in MB/s) (only used for the Internal Downloader)" in Download Client settings.
> 
> So for example if i have set "Maximum parallel downloads" to 1 and "Download speed" to 10 then the max speed i will be using is 10. But if i would set "Maximum parallel downloads" to 4 then each of the parallell downloads will be limited to 10 but in total we can use 40.
> 
> So one solution would be to make the download speed for each download take in to consideration all active download and change the download speed corresponding to that.
> 
> I will create a PR that will make the active parallel download be taken in to consideration when deciding the current download speed.

Would it also be possible to make 'maximum download speed' a fraction? Currently if I set a fraction, save it, then go back to the page it's reverted back to what it was.

Due to overheads ~5MB/s becomes ~5.3MB/s so it's hard to tune to exact amounts. Alternatively if it could include overheads / etc but that would be harder to code
