### ISSUE TITLE
All parameters lost when updating (docker)

### ISSUE THREAD

**Issue by zukato** [rogerfar/rdt-client#581]
### Discussed in https://github.com/rogerfar/rdt-client/discussions/580

<div type='discussions-op-text'>

<sup>Originally posted by **zukato** September  5, 2024</sup>
As per the title, when I update the image, all my settings are lost, even the login and password. When going into the folder /data/db folder, it is empty.

Please excuse me if I posted in the wrong place.

What am I doing wrong?

Here is the docker compose (Portainer stack):
```
rdtclient:
    image: rogerfar/rdtclient:latest
    container_name: rdtclient
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - /mnt/data/torrents:/data/downloads
      - /home/myuser/docker-configs/rdtclient:/data/db'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Europe/Paris"
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 6500:6500
```</div>

**Comment by Reasonable-Grape2698** [comment]
Why's there a ' at the end of /data/db?

Not sure that would be why but it shouldn't be there should it?

**Comment by zukato** [comment]
It shouldn't, you are absolutely right. Thank you very much for spotting it!
