### ISSUE TITLE
How to update? (Linux Service)

### ISSUE THREAD

**Issue by tundrablasen** [rogerfar/rdt-client#592]
How do I update rdtc when installed as a Linux service

**Comment by XeonNAS** [comment]
@tundrablasen  you closed this, did you find a solution?

**Comment by tundrablasen** [comment]
> [@tundrablasen](https://github.com/tundrablasen) you closed this, did you find a solution?

Yes. 

1) stopp the service (if you have it configured)
2) download the new zip and just unpack it in the same installation folder
3) restart the service 

The new version is then running

**Comment by XeonNAS** [comment]
I added a Linux script to one of the other discussions and reading through the windows script. My bash is less than perfect.
