### ISSUE TITLE
Files aren't being renamed when downloaded from Torbox

### ISSUE THREAD

**Issue by Masamune3210** [rogerfar/rdt-client#616]
**What version are you using?**
2.0.87
**Wat OS are you running?**
Unraid
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
Torbox
**Which downloader are you using?**
Bezzed
**Please attach a log file here with the log setting set to debug**
Would rather not attach log to public issue as it contains private information

**Comment by asylumexp** [comment]
can you give example of your files not being renamed?

**Comment by asylumexp** [comment]
Think this might have to do with current torbox issues, will have to see if it changes on Monday with the new servers.

**Comment by asylumexp** [comment]
Did some checks. Torbox has disabled the HEAD method used to check the file name and file size before download. Checking with them now about this.

**Comment by asylumexp** [comment]
Following up on this, @rogerfar removed the code that renames the files correctly so it won't work even if the HEAD method is enabled for zip downloads (or if the code is changed to download files individually).

**Comment by rogerfar** [comment]
That's true I removed those calls, I will make some time this week to have a look at this API in more detail.

**Comment by Koomongous** [comment]
Servers have improved somewhat, any progress on this boss?

**Comment by jordan-dalby** [comment]
@asylumexp @rogerfar any updates on this?

**Comment by asylumexp** [comment]
> @asylumexp @rogerfar any updates on this?

I’ll be able to work on this next week.

**Comment by brockbreacher** [comment]
> I was trying with the latest update, the downloads were already done normally, but the renaming problem persists, it even changes the extension, in order to be recognized by sonarr or radarr I had to change the name manually.
> 
> The download creates a folder with the correct name, but the files inside do not.

to be fair it was only to fix it downloading at all, the renaming problem hasn't been looked at yet, @asylumexp

**Comment by awp0** [comment]
I'm also impacted by this. Any idea if we could use the "run external program on torrent completion" to work around this? Not sure if there would be timing implications or added complexity with multi-part files.

**Comment by asylumexp** [comment]
It hasn’t been fixed yet, I’ll start working on it later today.

**Comment by Koomongous** [comment]
Hey, so it seems files are still occasionally being named incorrectly, seems fairly random at this point. Anyone else experiencing this?
