### ISSUE TITLE
Disabled Endpoint Error

### ISSUE THREAD

**Issue by thinhlegolas** [rogerfar/rdt-client#617]
So is this the end of rdtclient after RD announcement?

**Comment by Cap10Canuck** [comment]
> So is this the end of rdtclient after RD announcement?

It would appear so, but only for Real Debrid.  The client uses the API which is no longer functioning.  Remember that rdtclient also supports other hosters (Premiumize, etc.), so it's not dead yet.  My Real Debrid use case hinged on the the use of rdtclient.  Usenet here I come...

**Comment by andygruber** [comment]
Do not really know the technical background behind it, but since 1 hour or so, at least torrentio works again with RD. So I guess there are some possibilities.

**Comment by danhcheung** [comment]
The technical reason is that realdebrid removed the API endpoint for checking if a file is available in the cache or if realdebrid needs to download the torrent first. So there's no way to see if the file is available.

What torrentio is doing their own caching of what is available on their own, but it's also not reliable since Rd cleans up the cache occasionally

https://github.com/TheBeastLT/torrentio-scraper/issues/305

If you use rdtclient with zurg mounts, the zurg mounts are still fine, you can still download/stream the media. Its just that you can't send realdebrid your torrents and/or you can't see the availability of the media in Rd's cache

**Comment by ziomek64** [comment]
Is alldebrid good guys? Premiumrize is a lot more expensive.

**Comment by drizzt09** [comment]
> Is alldebrid good guys? Premiumrize is a lot more expensive.

Torbox is also an option

**Comment by Amcro** [comment]
For people looking for an alternative, i've got myself alldebrid for month today. Downloaded one torrent with rdt client and one mega link converted to alldebrid link with jdownloader API. Both worked perfect. I guess the only difference is Real Debrid has huge cache already compared to alldebrid but both will probably work same if users switch to alldebrid.

**Comment by cchance27** [comment]
why not just bypass the availabilty check, this isn't a streaming app if it has to get it from a torrent or other service who cares, let RD download it ... i mean sure you lose the "already available check" but ... just let it grab it

**Comment by danhcheung** [comment]
> why not just bypass the availabilty check, this isn't a streaming app if it has to get it from a torrent or other service who cares, let RD download it ... i mean sure you lose the "already available check" but ... just let it grab it

This makes a lot of sense, but the current implementation requires the check. From the behavior, I think rdtclient sends realdebrid the torrent/magnet link, and then checks for availability, and then chooses your files, and then it's made available to your account. Since it doesnt pass checking for availability, the files to download never gets chosen, and you never get to download your files.

There's also the fact that they purged a ton movies/shows and may have blacklisted them

**Comment by Scope666** [comment]
This workaround works with one of the popular add-ons ... wondering if can provide a possible alternate workflow:    (this works)

![image](https://github.com/user-attachments/assets/0ab1898c-8005-4c20-852c-e67c6809e5b4)

**Comment by drizzt09** [comment]
Blackhole and torrentio have workarounds in place. Hopefully RDtclient can use similar option.

**Comment by ziomek64** [comment]
Hopefully there will be some workaround because I have a plan bought to august XD

**Comment by halfloaf123** [comment]
@GabbeHags when will this be available and will this fix the disabled endpoint error?

**Comment by dataprolet** [comment]
Have you read the PR, @halfloaf123? And it's up to @rogerfar to accept the PR. @GabbeHags probably can't answer this.

**Comment by halfloaf123** [comment]
> Have you read the PR, @halfloaf123? And it's up to @rogerfar to accept the PR. @GabbeHags probably can't answer this.

I never read the PR sorry

**Comment by GabbeHags** [comment]
> @GabbeHags when will this be available and will this fix the disabled endpoint error?

This fix will make RDT think that nothing is cached and then try to start the download. After i made this change i have not seen the  disabled endpoint error.

So now we just need to wait for @rogerfar to look through my changes.

**Comment by ziomek64** [comment]
> @halfloaf123 
> > @GabbeHags when will this be available and will this fix the disabled endpoint error?
> 
> This fix will make RDT-Client think that nothing is cached and then try to start the download, i made this change because RD removed the functionality to check if something is cached. After i made this change i have not seen the  disabled endpoint error.
> 
> So now we just need to wait for @rogerfar to look through my changes.

Is this all that is needed? I'm also getting an infringing link error but that's on hostings. I wonder if it can happen on torrents in rd client

**Comment by GabbeHags** [comment]
@ziomek64 
This probably won't fix that.

This is what Real-Debrid mentions on there [help page](https://real-debrid.com/support):
> **I'm getting "infringing_torrent" error when I add a magnet / torrent**
> Our service received a DMCA letter about the magnet / torrent you are trying to add, this torrent can't be downloaded anymore and all copies you may have must be deleted for copyright compliance.

**Comment by elmerfds** [comment]
@GabbeHags do you have a docker image built with your fixes that we can use in the mean time until your PR is merged?

**Comment by halfloaf123** [comment]
> @GabbeHags do you have a docker image built with your fixes that we can use in the mean time until your PR is merged?

Will be interested in the docker image as well if you can share it @GabbeHags

**Comment by ziomek64** [comment]
> @ziomek64 This probably won't fix that.
> 
> This is what Real-Debrid mentions on there [help page](https://real-debrid.com/support):
> 
> > **I'm getting "infringing_torrent" error when I add a magnet / torrent**
> > Our service received a DMCA letter about the magnet / torrent you are trying to add, this torrent can't be downloaded anymore and all copies you may have must be deleted for copyright compliance.

That might be the deal breaker for many. I'll have to test out alldebrid and torbox

**Comment by godwin42sh** [comment]
Hey, just published an image on dockerhub based on @GabbeHags here godwin42sh/rdtclient, I would advise to build one for yoursel (you souldn't trust me and it's really easy to do, just look at the changes on my fork and set the correct repo secrets)

Everything works like a charm, all credits goes to @GabbeHags for the fix !

**Comment by Scope666** [comment]
> Hey, just published an image on dockerhub, based on @GabbeHags PR, here godwin42sh/rdtclient. I would advise to build one for yoursel (you souldn't trust me and it's really easy to do, just look at the changes on my fork and set the correct repo secrets)
> 
> Everything works like a charm, all credits goes to @GabbeHags for the fix !

Pulled your image, I had an existing download that was stuck, clicked restart, boom, immediately started working ... nice job!!!

**Comment by halfloaf123** [comment]
> Hey, just published an image on dockerhub, based on @GabbeHags PR, here godwin42sh/rdtclient. I would advise to build one for yoursel (you souldn't trust me and it's really easy to do, just look at the changes on my fork and set the correct repo secrets)
> 
> Everything works like a charm, all credits goes to @GabbeHags for the fix !

You guys are true legends thanks a million @GabbeHags @godwin42sh

**Comment by thinhlegolas** [comment]
@GabbeHags hi, it seems your workaround ignores the minimum filesize setting hence the symlink downloader is failing due to compressed file.

**Comment by sarthakps** [comment]
@godwin42sh @GabbeHags Absolute saviours. So grateful for your work.

**Comment by jake8923948** [comment]
![Screenshot_20241124_012804_Chrome](https://github.com/user-attachments/assets/51f83b69-b31f-4b14-8261-70bf6be794f4)

This has fixed RDT for me. 
Sonarr/radarr searches are working as expected

API has disabled "instantly available" status, so I thought disabling this (which would use the instantly available function) would work, and it has! Happy days.
Only going to be buying 1 month of real debrid at a time now

**Comment by jake8923948** [comment]
Further, 
![Screenshot_20241124_013406_Chrome](https://github.com/user-attachments/assets/75b930ef-b17e-4e1b-b3ba-99d7f4b31049)
![Screenshot_20241124_013416_Chrome](https://github.com/user-attachments/assets/7fc26831-d5ea-4a00-948d-d5956abbadc8)

**Comment by thinhlegolas** [comment]
> ![Screenshot_20241124_012804_Chrome](https://private-user-images.githubusercontent.com/25887548/389240425-51f83b69-b31f-4b14-8261-70bf6be794f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MTM5MDMsIm5iZiI6MTczMjQxMzYwMywicGF0aCI6Ii8yNTg4NzU0OC8zODkyNDA0MjUtNTFmODNiNjktYjMxZi00YjE0LTgyNjEtNzBiZjZiZTc5NGY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDAyMDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMjhiOWNkMTg1N2U2NWVkODc0MDMzMjQ0Njc2ZWVmZTI5YWI0MzQyYjdlMjkyMzBiZDk5OWQyZjUyMDM5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aiwOFqb5fuePhfmJ72wrC6FTTSPwcl51RTTr3oxevxE)
> 
> This has fixed RDT for me. Sonarr/radarr searches are working as expected
> 
> API has disabled "instantly available" status, so I thought disabling this (which would use the instantly available function) would work, and it has! Happy days. Only going to be buying 1 month of real debrid at a time now

This works for me!!!

**Comment by tduong-cloud** [comment]
> @GabbeHags hi, it seems your workaround ignores the minimum filesize setting hence the symlink downloader is failing due to compressed file.

I second this.
I used to set up the mimimum filesize in order to download only the video file, and not any text or sample video in the torrent, and then avoid having to unpack. It was smoother that way. I don't know if, knowing the current issues, we can still benefit of that setting?

Thanks a lot

**Comment by jake8923948** [comment]
> > !
> This works for me!!!

Glad to hear it!

**Comment by thinhlegolas** [comment]
> > @GabbeHags hi, it seems your workaround ignores the minimum filesize setting hence the symlink downloader is failing due to compressed file.
> 
> I second this. I used to set up the mimimum filesize in order to download only the video file, and not any text or sample video in the torrent, and then avoid having to unpack. It was smoother that way. I don't know if, knowing the current issues, we can still benefit of that setting?
> 
> Thanks a lot

Please follow the setting as mentioned by @jake8923948

**Comment by tduong-cloud** [comment]
> > > @GabbeHags hi, it seems your workaround ignores the minimum filesize setting hence the symlink downloader is failing due to compressed file.
> > 
> > 
> > I second this. I used to set up the mimimum filesize in order to download only the video file, and not any text or sample video in the torrent, and then avoid having to unpack. It was smoother that way. I don't know if, knowing the current issues, we can still benefit of that setting?
> > Thanks a lot
> 
> Please follow the setting as mentioned by @jake8923948

Hey thanks for answering :). So I have tried, at least I think :D. I have pulled godwin42sh/rdtclient image and disable the setting as @jake8923948 suggested, but still same behavior

**Comment by jake8923948** [comment]
> > > > @GabbeHags hi, it seems your workaround ignores the minimum filesize setting hence the symlink downloader is failing due to compressed file.
> > > 
> > > 
> > > I second this. I used to set up the mimimum filesize in order to download only the video file, and not any text or sample video in the torrent, and then avoid having to unpack. It was smoother that way. I don't know if, knowing the current issues, we can still benefit of that setting?
> > > Thanks a lot
> > 
> > 
> > Please follow the setting as mentioned by @jake8923948
> 
> Hey thanks for answering :). So I have tried, at least I think :D. I have pulled godwin42sh/rdtclient image and disable the setting as @jake8923948 suggested, but still same behavior

Use default image and just disable this setting and it'll work exactly as before RDs 'update'

If RDC worked and your only issue was disabled_endpoint, this checkbox is the solution

**Comment by tduong-cloud** [comment]
> Sorry, I should also have mentionned that I am not utilizing the symlink downloader but aria2c



> > > > > @GabbeHags hi, it seems your workaround ignores the minimum filesize setting hence the symlink downloader is failing due to compressed file.
> > > > 
> > > > 
> > > > I second this. I used to set up the mimimum filesize in order to download only the video file, and not any text or sample video in the torrent, and then avoid having to unpack. It was smoother that way. I don't know if, knowing the current issues, we can still benefit of that setting?
> > > > Thanks a lot
> > > 
> > > 
> > > Please follow the setting as mentioned by @jake8923948
> > 
> > 
> > Hey thanks for answering :). So I have tried, at least I think :D. I have pulled godwin42sh/rdtclient image and disable the setting as @jake8923948 suggested, but still same behavior
> 
> Use default image and just disable this setting and it'll work exactly as before RDs 'update'
> 
> If RDC worked and your only issue was disabled_endpoint, this checkbox is the solution

Sorry, I should also have mentionned that I am not utilizing the symlink downloader but aria2c

I actually have tried your workaround with both images. No luck

**Comment by thinhlegolas** [comment]
> workaround

You should use the rogerfar image and disable the setting under both "Provider" and "qbittorrent"

**Comment by tduong-cloud** [comment]
Ok, now not all files are selected when imported into RD, but they are not downloaded on my server :(.

Sorry, I feel like a noob asking

**Comment by jake8923948** [comment]
![Screenshot_20241124_024010_Chrome](https://github.com/user-attachments/assets/a1c758f8-93b9-43aa-81d4-50a143c81618)
![Screenshot_20241124_023915_Chrome](https://github.com/user-attachments/assets/a6013023-8e57-4490-9824-1a7b78122a7e)
These are my settings

3 days ago it was working. Tonight it stopped, saying "disabled_endpoint"
I changed that 1 checkbox, and it's performing exactly how it did 3 days ago

**Comment by tduong-cloud** [comment]
> 3 days ago it was working. Tonight it stopped, saying "disabled_endpoint" I changed that 1 checkbox, and it's performing exactly how it did 3 days ago

Thanks for the support. I have configured as you suggested. what downloader are you using ? I am using aria2c, I guess that may be the difference ?

**Comment by jake8923948** [comment]
> > 3 days ago it was working. Tonight it stopped, saying "disabled_endpoint" I changed that 1 checkbox, and it's performing exactly how it did 3 days ago
> 
> Thanks for the support. I have configured as you suggested. what downloader are you using ? I am using aria2c, I guess that may be the difference ?
> 
> The status of the file end with "finished" but nothing got downloaded
> 
> ![image](https://private-user-images.githubusercontent.com/73973593/389244288-9bf45f72-3add-4245-b565-9238c597fbd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MTcwNzcsIm5iZiI6MTczMjQxNjc3NywicGF0aCI6Ii83Mzk3MzU5My8zODkyNDQyODgtOWJmNDVmNzItM2FkZC00MjQ1LWI1NjUtOTIzOGM1OTdmYmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDAyNTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMzRkNDgzODVmNTRlMWVkNmUyZWMzNjRkZDMzYTI3NjIyMjgyYjIxZjQ2ZjkyMTdjOWQwNzE4MmIxMjU4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ObxpscLfY02ptUQ3qwwgw1srviL5oLvkCX8Qk-my9XI)

I'm using the standard one, internal I believe??

**Comment by tduong-cloud** [comment]
> I'm using the standard one, internal I believe??

I can see the link generated, but it's just like it is not transferred to Aria2c. I have tried with the internal downloader as well, same.

**Comment by tduong-cloud** [comment]
> > > 3 days ago it was working. Tonight it stopped, saying "disabled_endpoint" I changed that 1 checkbox, and it's performing exactly how it did 3 days ago
> > 
> > 
> > Thanks for the support. I have configured as you suggested. what downloader are you using ? I am using aria2c, I guess that may be the difference ?
> > The status of the file end with "finished" but nothing got downloaded
> > ![image](https://private-user-images.githubusercontent.com/73973593/389244288-9bf45f72-3add-4245-b565-9238c597fbd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MTcwNzcsIm5iZiI6MTczMjQxNjc3NywicGF0aCI6Ii83Mzk3MzU5My8zODkyNDQyODgtOWJmNDVmNzItM2FkZC00MjQ1LWI1NjUtOTIzOGM1OTdmYmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDAyNTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMzRkNDgzODVmNTRlMWVkNmUyZWMzNjRkZDMzYTI3NjIyMjgyYjIxZjQ2ZjkyMTdjOWQwNzE4MmIxMjU4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ObxpscLfY02ptUQ3qwwgw1srviL5oLvkCX8Qk-my9XI)
> 
> I'm using the standard one, internal I believe??

Ok, nevermind, I am just dumb as fuck. My container was corrupted, had to restart it and now it is working.
Thanks !!!

**Comment by Killj0y1** [comment]
I changed the settings that others mentioned and running a native install not docker. Still getting the error even after restarting the service and confirming the changes were made.

**Comment by Ameenota** [comment]
Same as @Killj0y1  but on docker. Unchecked the box in the 2 places mentioned above, restarted by container, but I still get disabled_endpoint

**Comment by Killj0y1** [comment]
> Same as @Killj0y1 but on docker. Unchecked the box in the 2 places mentioned above, restarted by container, but I still get disabled_endpoint

I got it working. I had to readd all pending torrents now they are downloading. Anything that was already there will fail. So I removed all pending jobs and readded them and it's working now.

**Comment by halfloaf123** [comment]
> ![Screenshot_20241124_012804_Chrome](https://private-user-images.githubusercontent.com/25887548/389240425-51f83b69-b31f-4b14-8261-70bf6be794f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NDY4MjksIm5iZiI6MTczMjQ0NjUyOSwicGF0aCI6Ii8yNTg4NzU0OC8zODkyNDA0MjUtNTFmODNiNjktYjMxZi00YjE0LTgyNjEtNzBiZjZiZTc5NGY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDExMDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzBlMmY2NTFhMjczNmRmZmQxMGJhZTMzNTFlYjAxYzAyY2M0M2Y3M2ZlZWM4MWM2ZDI5YjZhOGUzY2YyZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B1g0E3imO8axXcH8sltF4MVWoXfnTsudHqlRvJvGjKo)
> 
> This has fixed RDT for me. Sonarr/radarr searches are working as expected
> 
> API has disabled "instantly available" status, so I thought disabling this (which would use the instantly available function) would work, and it has! Happy days. Only going to be buying 1 month of real debrid at a time now

This works beautifully thanks a million mate , this community are true legends @jake8923948

**Comment by thinhlegolas** [comment]
> ![Screenshot_20241124_024010_Chrome](https://github.com/user-attachments/assets/a1c758f8-93b9-43aa-81d4-50a143c81618)
> 
> ![Screenshot_20241124_023915_Chrome](https://github.com/user-attachments/assets/a6013023-8e57-4490-9824-1a7b78122a7e)
> 
> These are my settings
> 
> 
> 
> 3 days ago it was working. Tonight it stopped, saying "disabled_endpoint"
> 
> I changed that 1 checkbox, and it's performing exactly how it did 3 days ago 

@rogerfar this has solved the problem it seems.

**Comment by rogerfar** [comment]
I added a simple check to see if RealDebrid has disabled the instant availability endpoint (just in case they decide to turn it on again eventually).

But this does mean that the `Only download available files` will be broken for now.

**Comment by Scope666** [comment]
> Only download available files

So just to confirm, "Only download available files" should be UNCHECKED for both "Provider" and "qBittorrent" correct?    (if using *arr apps)

**Comment by rogerfar** [comment]
I'm pushing 89 where the setting doesn't work anymore for Real-Debrid.

Only AllDebrid supports it, but doesn't support cherry picking files.

**Comment by jake8923948** [comment]
> > I added a simple check to see if RealDebrid has disabled the instant availability endpoint (just in case they decide to turn it on again eventually).
> 
> > But this does mean that the Only download available files will be broken for now.
> 
> So just to confirm, "Only download available files" should be UNCHECKED for both "Provider" and "qBittorrent" correct? (if using *arr apps)

Refer to my screenshots. Provider wasn't disabled, but *arr is and it works fine and as expected

**Comment by jake8923948** [comment]
> I'm pushing 89 where the setting doesn't work anymore for Real-Debrid.
> 
> Only AllDebrid supports it, but doesn't support cherry picking files.

Thanks Roger, for all your continued hard work and development on this

**Comment by Scope666** [comment]
> > I'm pushing 89 where the setting doesn't work anymore for Real-Debrid.
> > Only AllDebrid supports it, but doesn't support cherry picking files.
> 
> Thanks Roger, for all your continued hard work and development on this

I'll 2nd that...  RDT has been a game changer for me.   <3

**Comment by Scope666** [comment]
So I just updated to 89, and it seems to have broken communication to Sonarr ... Sonarr is not showing the download under Queue, and after the DL is finished, it's not taking action on the file... just leaving it in place.
