### ISSUE TITLE
APIKEY error for Alldebrid

### ISSUE THREAD

**Issue by Jeck1198** [rogerfar/rdt-client#620]
**What version are you using?**
v2.0.87

**What OS are you running?**
Windows 11

**Are you using Docker or as a service?**
Service

**Which debrid provider are you using?**
Alldebrid

**Which downloader are you using?**
Internal

I was successfully using v2.0.86. I ran the update powershell script and now the service won't start. Looking at the logs it shows that the apikey is invalid. This key was working in 86 though. I just created a new key in Alldebrid but how do I enter the new key into RDT Client with the service down?

2024-11-23 07:51:02.817 -05:00 [ERR] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
System.Exception: Unable to deserialize AllDebrid API response to UserResponse. Response was: {"status":"error","error":{"code":"AUTH_BAD_APIKEY","message":"The auth apikey is invalid"}}
 ---> AllDebridNET.AllDebridException: The auth apikey is invalid (AUTH_BAD_APIKEY)

**Comment by rogerfar** [comment]
What do you mean the service is down?

**Comment by shulymn** [comment]
The service is perfectly fine, they must have misconfigured their API key
I am using all-debrid since real-debrid stopped working, no issues at all.

**Comment by Jeck1198** [comment]
Hi @rogerfar - The service wouldn't start due to the misconfiguration of the alldebrid apikey. I was looking for a way to update the apikey now that the service wouldn't start. I decided it would be easier to just reinstall rdt-client, so I will close this issue now. Thanks for responding though.
