### ISSUE TITLE
v2.0.89 requires ASP.net core 9.0.0 on windows else service does not start

### ISSUE THREAD

**Issue by gibahjoe** [rogerfar/rdt-client#623]
**What version are you using?**

[v2.0.89](https://github.com/rogerfar/rdt-client/releases/tag/v2.0.89)

**Wat OS are you running?**
Windows 11

**Are you using Docker or as a service?**
As a service

**Which debrid provider are you using?**
Real Debrid

**Which downloader are you using?**
Not sure

**Please attach a log file here with the log setting set to debug**

NO logs. Just A PSA and possibly an update to the ReadMe to mention that the last 3 versions or so require ASP.Net core 9.0.0 to run or else the service won't start.

I had to check event viewer logs to see why the service was not starting and also followed the recommendation in the logs which was to update to 9.0.0

**Comment by rogerfar** [comment]
Thanks, I thought it was just the runtime, I will update the README.
