### ISSUE TITLE
Failed to load /app/libhostpolicy.so

### ISSUE THREAD

**Issue by quentinzil** [rogerfar/rdt-client#65]
Hello,

Thank you so much for this amazing project.

Since I pulled the latest image, I run into the following issue:

`Changing to /app folder`
`Starting rtdclient`
`Failed to load /app/libhostpolicy.so, error: /app/libhostpolicy.so: wrong ELF class: ELFCLASS32`
`An error occurred while loading required library libhostpolicy.so from [/app/]`

Any thoughts or ideas?

**Comment by rogerfar** [comment]
I think this is the same issue as https://github.com/rogerfar/rdt-client/issues/47
