### ISSUE TITLE
In client, account > version still says 1.7.4, verified downloaded 1.7.6

### ISSUE THREAD

**Issue by minus1kelvin** [rogerfar/rdt-client#66]
I manually selected 1.7.6 in the Docker version pull down selection, but in the client GUI it still says 1.7.4. In my Docker image section and in the Container section, both also say 1.7.6.

**Comment by rjhclem** [comment]
Same here. Manually pulled the 1.7.6 Docker image, client still says 1.7.4 under "Account"

**Comment by rogerfar** [comment]
Did you do a hard refresh Ctrl+F5, does it update?

**Comment by rjhclem** [comment]
I did, still says 1.7.4

**Comment by rogerfar** [comment]
I rebuild the image from scratch, I think there was some caching going on, should be good now.

**Comment by rjhclem** [comment]
Looks like that did the trick, showing 1.7.6 for me now
