### ISSUE TITLE
RSS Reader

### ISSUE THREAD

**Issue by popeye2468** [rogerfar/rdt-client#69]
any way of adding an RSS reader funtion? Please

**Comment by timcoop3r** [comment]
I’d suggest using something dedicated to this functionality, like FlexGet, to read RSS and then use the qbitorrent plugin to interface with rdt-client for downloads?

**Comment by rogerfar** [comment]
I think @timcoop3r has a good point. This project is purely intended to be a proxy between RealDebrid and your download apps through the qBittorrent API.

If you have issues hooking those up, please re-open this ticket so I can take a look.
