### ISSUE TITLE
is not a valid local path. You may need a Remote Path Mapping

### ISSUE THREAD

**Issue by lordbeavis** [rogerfar/rdt-client#7]
Sonarr is looking for 
[C:\Users\realdebrid\Desktop\RealDebridClient\Downloads\[Ohys-Raws] Shingeki no Kyojin The Final Season - 01 (NHKG 1280x720 x264 AAC).mp4]

but Real Debrid Client created name & path
C:\Users\realdebrid\Desktop\RealDebridClient\Downloads\[Ohys-Raws] Shingeki no Kyojin The Final Season - 01 (NHKG 1280x720 x264 AAC).mp4\%5BOhys-Raws%5D%20Shingeki%20no%20Kyojin%20The%20Final%20Season%20-%2001%20%28NHKG%201280x720%20x264%20AAC%29.mp4

i have Remote Path Mappings set to
RealDebridClient         Remote:C:\Users\realdebrid\Desktop\RealDebridClient\Downloads\              Local:/data/completed/

rdt-client is running on a win 10 vm with a symlink to a mapped network drive and sonar is running in docker

**Comment by rogerfar** [comment]
That's an odd one, did this file automatically get extracted?

**Comment by lordbeavis** [comment]
yes, its happening to all the files. if i use the manual import it finds the files no problem

**Comment by rogerfar** [comment]
@lordbeavis are you using the windows service or Docker container? If the first, could you try with Docker?

**Comment by rogerfar** [comment]
I have added simple remote mapping in the latest version.
