### ISSUE TITLE
Failing to add Categories / Labels

### ISSUE THREAD

**Issue by IrealiTY** [rogerfar/rdt-client#70]
I'm using 2 Sonarr setups to split between 2 types of content.
Setting up the first, client in Sonarr 1 worked flawlessly, just used "sonarr" as a category.

In the 2nd one, I'm trying to set it to something else to make it easier to split, but I always get:

```
[Warn] SonarrErrorPipeline: Invalid request Validation failed: 
  -- TvCategory: Configuration of label failed 
```
in the sonarr log, the rdt-client doesn't seem to write anything to the log file related to that (even when set to verbose logging)

Setting up Radarr with "radarr" category also worked flawlessly. I don't think the categories are hard-coded, are they?

**Comment by timcoop3r** [comment]
The categories are indeed currently hard coded

**Comment by IrealiTY** [comment]
Sad :D For now I've setup 2 instances for rdt-client which works but it's obviously not the perfect solution

**Comment by rogerfar** [comment]
The current solution didn't work very well no, I added a small fix to store categories in the settings table now.

**Comment by rogerfar** [comment]
This has been deployed now.
