### ISSUE TITLE
Client disconnecting from radarr & sonarr

### ISSUE THREAD

**Issue by Muneer91** [rogerfar/rdt-client#74]
Hi, 
updated to 1.8.2, and the client disconnects from sonarr and radarr after 1 successful download.
doesn't matter what the torrent is, it downloads fine, then second download starts and then both sonarr and radarr report the communication failed to the download client.

I'm using docker and the logs show bunch of error messages like below:

[ERR] Unexpected error occurred in TorrentDownloadManager.Tick
System.NullReferenceException: Object reference not set to an instance of an object.

also, when this error appears, downloads that normally run at 20-30MB/sec slow down to a few hundred KB/sec.

i have reverted back to 1.7.6 and there are no issues.
i still have the db files i can pm you if you want.

**Comment by rogerfar** [comment]
Could you send the full log? Especially where it shows the line number of that exception.

**Comment by Muneer91** [comment]
Thanks for the quick response. 
This is the bit of code that comes up repeatedly. If you need more let me know we can arrange some way of sending you the full log file. 

2021-08-04 09:28:33.291 +01:00 [WRN] 304: /index.html
2021-08-04 09:28:33.312 +01:00 [WRN] 101: /hub
2021-08-04 09:28:34.720 +01:00 [WRN] 304: /index.html
2021-08-04 09:28:34.731 +01:00 [WRN] 101: /hub
2021-08-04 09:28:47.770 +01:00 [ERR] Unexpected error occurred in TorrentDownloadManager.Tick
System.NullReferenceException: Object reference not set to an instance of an object.
   at RdtClient.Data.Data.DownloadData.UpdateUnpackingQueued(Guid downloadId, Nullable`1 dateTime) in /appserver/server/RdtClient.Data/Data/DownloadData.cs:line 105
   at RdtClient.Service.Services.Downloads.UpdateUnpackingQueued(Guid downloadId, Nullable`1 dateTime) in /appserver/server/RdtClient.Service/Services/Downloads.cs:line 50
   at RdtClient.Service.Services.Torrents.Download(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 319
   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 443
   at RdtClient.Service.Services.TaskRunner.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/Services/TaskRunner.cs:line 38
2021-08-04 09:29:16.354 +01:00 [WRN] 101: /hub

**Comment by rogerfar** [comment]
And this is for the latest version? Because the line numbers don't seem to match up to the code very well.

If you want to PM me the DB file that would be very useful, you send it to me at roger@versluis.ca
.

**Comment by Muneer91** [comment]
Yes it was for 1.8.2
At this point I downgraded to 1.7.8 and I found I had the same issue. 

After downgrading again to 1.7.6 it started working fine. Although I still can see a different error in the log for 1.7.6 but the front end and functionality works fine. 

I have emailed you the db and full log file. 

Thanks

**Comment by rogerfar** [comment]
@Muneer91 the DB file you sent doesn't have any torrents in it. Can you send me the torrent where this happens with?

**Comment by Muneer91** [comment]
It happens with any torrent I download, the first one works fine, then subsequent ones have issues. 

I can recreate on docker tonight and add a torrent to send you. 

Thanks

**Comment by rogerfar** [comment]
I do see a lot of errors about categories, I made a small fix in there, that might have caused the issue.

Can you try tonight with 1.8.3?

**Comment by Muneer91** [comment]
Definitely I will do that. 

I will disable my current container and create a fresh one with 1.8.3 and let you know the results. 

Thanks

**Comment by Muneer91** [comment]
@rogerfar I can see 1.8.3 on git but on docker it shows 1.8.2 as latest. 

Do you know how long it usually takes to show the new version on the docker side?

**Comment by rogerfar** [comment]
Takes about 10 minutes, should be there now.

**Comment by Muneer91** [comment]
@rogerfar I installed a fresh image of 1.8.3 and I didn't have the issue with download speed. 
However, there are still errors in the logs and the web ui keeps crashing and I get a blank page every now and again. 

I have sent you the log and db via email which should have some torrent files included if you need them.

**Comment by rogerfar** [comment]
This is what I see in the logs:
```
Unexpected error occurred in TorrentDownloadManager.Tick
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
```
And
```
Unexpected error occurred in TorrentDownloadManager.Tick
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
```

I'm not sure what country you're trying to connect to Real-Debrid from but it looks like their API keeps breaking on you.

Because this process locks most other processes, sonarr and radarr could time out yes.

I will push 1.8.4 where the timeout is set to 10 seconds, this will hopefully alleviate the timeout pain a bit.

**Comment by Muneer91** [comment]
Thanks @rogerfar 

I connect to realdebrid using my own connection from UK. I don't use vpn because it tends to slow down the download speeds. 

Do you think I should be using a vpn?

**Comment by Muneer91** [comment]
Hi @rogerfar 
I've since re-imaged my device and started from scratch. After setting everything up from new and also forcing the rdtclient to go through a vpn, I can report everything is working as expected. 

Thanks for all your help!
