### ISSUE TITLE
[Bug] Radarr can't connect : "An item with the same key has already been added. Key: movies"

### ISSUE THREAD

**Issue by DaisyF8** [rogerfar/rdt-client#77]
So suddenly radarr, lidarr, sonarr lost connection to rdt-client (all with docker).  I can't get a good test, and can't save after the test failed.  No connections possible anymore.

In logs for radarr I also get "key has allready been added". I use movies for radarr, tv for sonarr, and music for lidarr.

Here is the log. I can send you the db private if you tell me how.

[rdtclient.log](https://github.com/rogerfar/rdt-client/files/6994850/rdtclient.log)

**Comment by rogerfar** [comment]
an you upgrade to the latest version, that has been fixed in there.

**Comment by DaisyF8** [comment]
Woops, I hadn't noticed you updated.

Yes Fixed :+1:
