### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by handshake87** [rogerfar/rdt-client#8]
Attempting to run startup.bat and immediately get opens a window and closes again. I then right click and run as admin and a window appears quickly and closes. No console remains open. Confirmed it is not running. Upon installing the service I get console window confirming service was installed. Service is showing in panel as "Automatic." When selecting to start the service i get error: "Windows could not start the RealDebridClient service on Local Computer. Error 1053: The service did not respond to the start or control request in a timely fashion."

Running on windows 10 fully updated and user is admin.

**Comment by rogerfar** [comment]
Make sure you have the .NET Core runtime installed:
https://dotnet.microsoft.com/download 
I recommend 5.0 as I will be upgrading it to that version soon.

I'll also release a Docker container soon.

**Comment by handshake87** [comment]
I have installed .NET 5.0.1 and still is crashing when I start the startup.bat

**Comment by rogerfar** [comment]
Can you run it in a console window so you can see the output? That will give a better understanding of what the actual error is.

**Comment by handshake87** [comment]
`It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64`

What is wierd is i have 5.0.1 installed. I followed the link and also installed the 3.0 and still is not working.

**Comment by rogerfar** [comment]
Try installing 3.1 LTS, that should work.

**Comment by handshake87** [comment]
Yup that resolved it! Thank you so much!!
