### ISSUE TITLE
Add Template in Unraid Community Applications

### ISSUE THREAD

**Issue by vonwerderc** [rogerfar/rdt-client#81]
**What version are you using?**
n/a
**Wat OS are you running?**
Unraid
**Are you using Docker or as a service?**
Docker

Hello, I think it would help a lot of people out if you could add this as a template on the Community Applications tab for Unraid.

**Comment by janitory** [comment]
You can already add it through the dockerhub search inside the CA tab in Unraid.

If you go that route, I'd recommend to add a PUID and a PGID variable to the template and set those to the same IDs as your sonarr container.

**Comment by Today223** [comment]
I hope you can make this install simple. I have been struggling to install this all day on Unraid.

**Comment by janitory** [comment]
> I hope you can make this install simple. I have been struggling to install this all day on Unraid.

In Unraid, go to Apps. Type `rdtclient` into the search bar, enter and then click on `Click Here To Get More Results From DockerHub` on the top right.
Select the result that has rogerfar underneath the name, hit install and then press No on the prompt.
When setting up the template, make sure you have the following set (you might need to manually add them through the options on the bottom):

Name: DB Path
Host Path: /mnt/user/appdata/rdtclient/ (you can adjust this to your liking, but this is default for Unraid)
Container Path: /data/db

Name: Download Path
Host Path: /mnt/user/media/downloads (just point this to your downloads folder)
Container Path: /data/downloads

And the following port:
Name: Host Port
And enter 6500

That's it.

**Comment by rogerfar** [comment]
I believe this is already is an app in unraid for RDT, it's just not mine.
