### ISSUE TITLE
Feature Request: Mark torrent as failed if seeders or download speed falls below threshold

### ISSUE THREAD

**Issue by MVethana** [rogerfar/rdt-client#85]
Create an option for rdt to a torrent as failed to sonarr/radarr/etc and find a new one if:

- \# of seeders fall below a threshold set within settings / # of seeders is 0
- RD download speed is below a set speed (seeders are too slow for user preference) / download speed is 0
- Torrent reaches a maximum time specified to be fully downloaded to Real Debrid

Using sonarr/radarr + jackett, even filtering for torrents with >= 1 seeder, due to seeders leaving/etc. a torrent can be sent to rd that has no seeders and will never finish. Create an option to mark these as failed/bad so that a different torrent can be downloaded instead

**Comment by timcoop3r** [comment]
Not directly related to your specific feature request, but a general tip none the less, you may be able to use this information to help Sonarr/Radar select a better download in the first place, thats more likely to already be downloaded and cached on RD even with low seeders: https://trash-guides.info/
Virtually nothing for me ever needs a torrent to download as its already cached.

**Comment by rogerfar** [comment]
Continued in https://github.com/rogerfar/rdt-client/issues/97
