### ISSUE TITLE
Issue with recursive unpacking

### ISSUE THREAD

**Issue by jvvilar** [rogerfar/rdt-client#86]
If a particular download contains rar files, the program marks the download as failed with the following error:

An unexpected error occurred unpacking https://34.download.real-debrid.com/d/3AZADL4ZHHPAS/ _FILE NAME_ .rar for torrent 
 _SAME NAME_ : Directory does not exist to extract to: _PATH TO RADARR_ \ _SAME NAME_ \Temp\

Error is technically correct. The path ends with the folder named after the rar file, but obviously there is no Temp subfolder here.

**Comment by rogerfar** [comment]
Can you send me a torrent link through pastebin so I can check?

**Comment by jvvilar** [comment]
[https://pastebin.com/5BPqjpVE](url)

That torrent is completely unrelated, but they all cause the same issue (being a multi-part rar that gets compressed into a single one by RealDebrid).

After the download is complete, you will easily spot what's happening in UnpackClient.cs

Note that I fixed this in my running version, by actually creating the TEMP sub folder the code looks for, keeping a secondary variable with the internal rar info, decompressing the rars into the TEMP folder and then decompressing those into to the actual destination folder. It works just fine for me and my use, but I didn't take the time to go actually go through much of your code, so it's not done elegantly and I wouldn't want it if I was in your shoes.

**Comment by FrankTheTank908** [comment]
I am also getting an error with multiple part downloads that real debris zips. It unpacks first zip and fails on unpacking the multiple compressed files inside for the videos in question

**Comment by rogerfar** [comment]
If anyone can send me an example magnet then I can do testing.

**Comment by popeye2468** [comment]
magnet:?xt=urn:btih:9a3705ac7494527c53610a30a233affb29692c2b&dn=&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2Ftracker.ccc.de%3A80&tr=udp%3A%2F%2Ftracker.blackunicorn.xyz%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969

**Comment by FrankTheTank908** [comment]
Here is a tv torrent file 12 compressed files for the episode.
Unfortunately these release groups compress them a lot.


magnet:?xt=urn:btih:QF6GBB6QXWXSB2CZVQGSBCB4HUOEDFDF&dn=Rick.and.Morty.S06E08.1080p.WEB.H264-GLHF&tr=https%3A%2F%2Frouting.bgp.technology%2F79051663fedbd99c7fc8fdfb2c84a62a%2Fannounce



Frank

**Comment by FrankTheTank908** [comment]
If you can give me a throwaway email I can email you the magnet link because it’s a private tracker.

**Comment by FrankTheTank908** [comment]
Or the torrent file.

**Comment by cinderblockgames** [comment]
Obviously not the best solution, but this at least makes the Temp folder.  Haven't seen it in action yet to see if it addresses the issue.

```
#!/bin/sh

inotifywait -m /path/to/downloads/* -e create |
  while read dir action file; do
    directory="$dir$file"
    if [ -d "${directory}" ]; then
      mkdir "$directory/Temp"
    fi
  done
```

Install in crontab:

```
@reboot /path/to/make-temp-folder
```

**Comment by FrankTheTank908** [comment]
Just a theory but adding another check for .rar or .r01 etc… after the first unpack before showing completed in UnpackClient.cs  fix the issue but I don’t know programming to try it out.

**Comment by rogerfar** [comment]
I have some development in the works that handles this now, but I have to spend some time on testing before I want to roll it out, I'll make some time for it soon.

**Comment by rogerfar** [comment]
This should be fixed now in the new version.

**Comment by cinderblockgames** [comment]
Looks like the container in .20 isn't set up correctly:

```
Changing to /app folder
Starting rtdclient
You must install or update .NET to run this application.
App: /app/RdtClient.Web.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet/
The following frameworks were found:
  7.0.3 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.20.04-x64
```

**Comment by FrankTheTank908** [comment]
.21 is working great. I tested it with torrent that had unpacking issues. I’ll test it I’ve the days and report back if anything come up. Thank you so much for fixing the issue. ❤️

**Comment by MrAlucardDante** [comment]
Latest version (currently .30) still struggles with multi-part rar (.part0X.rar). RDTClient tries to unpacks every part as soon as it’s downloaded, even though the other parts aren’t done yet. It should wait for all parts before unpacking. @
![IMG_1420](https://user-images.githubusercontent.com/20476382/232247213-232d6d71-db8a-457d-a094-a3fcb9a2da1b.png)

**Comment by rogerfar** [comment]
There were some fixed implemented for this, please open a new issue if this still is a problem.
