### ISSUE TITLE
Feature Request : Need ability to configure base URL / app context 

### ISSUE THREAD

**Issue by carponoid** [rogerfar/rdt-client#87]
Presently the web app is using the root context (\) and it would be nice to have a mechansim to configure app context / base URL, this is particularly useful when running the app behind reverse proxy. Tried adding context path to the "HostURL" property but it throws error 

System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase()

**Comment by rogerfar** [comment]
I'm not sure exactly what you mean, are you trying to setup a reverse proxy and access rdt as a subdirectory, like http://domain.com/rdt ?

**Comment by carponoid** [comment]
Hi, Yes that's right, trying to access /rdt as a subdirectory but not sure if there is way to do it already?

**Comment by rogerfar** [comment]
No that's pure reverse proxy config. The HostURL can only be the IP address, almost always you will just leave this as 0.0.0.0
