### ISSUE TITLE
Torrents are not automatically being detected or downloaded

### ISSUE THREAD

**Issue by profucius** [rogerfar/rdt-client#88]
Version: 1.9.8.0

OS: Windows, Service

Issue:

I have everything installed and setup properly, tested connection to Real-Debrid successfully, ran the test download to a directory successfully. However, when I add a torrent to RD from another app that I use (wako) RD has the file showing as ready, but RDC web interface page does not show anything. I do not think RDC is detecting that any torrents are available to be downloaded.

I dug through the settings, but cannot find anything that fixes this. Am I missing something, can I try doing something to fix this?

EDIT: I tried switching from Real-Debrid (paid) to AllDebrid (paid) and the same issue persists.

**Comment by rogerfar** [comment]
Unfortunately that's not the intent of this app. It only works by adding torrents to its interface and using the qBittorrent API proxy. 

I'll leave this one open, maybe in the future we can add a button to import existing torrents.

**Comment by rogerfar** [comment]
I added an option in version 2.0 under the Provider settings. You can now specify if you want to automatically import torrents when they are added to RealDebrid.

Just a note though, it will only import them if the files have been selected already.

**Comment by profucius** [comment]
Thank you for this. Admittedly I was still wrapping my brain around how your software works, and now that I've had more time exploring the Sonarr settings too, I see that it is working as expected. Brilliant idea and software execution! Many thanks
