### ISSUE TITLE
Controlling from outside local network and Radarr

### ISSUE THREAD

**Issue by krusion** [rogerfar/rdt-client#9]
I'm not really tech savvy, but I recently stumbled onto this and was hoping I could ask if this does what I'm trying to do. 

Can this be controlled outside my local network? If so, how? 

Also, what's the point of linking it to Radarr? Can it pull requests from Radarr and automatically download them through real debrid? 

I've looked at Radarr before and it seems interesting, but I don't use usenet and usually use real debrid for torrent downloads instead of a VPN. Would this work in such a scenario?

**Comment by rogerfar** [comment]
RDT is a proxy between Sonarr/Radarr and RealDebrid, it pretents it's a Torrent client by mimicking the qBittorrent protocol. It basically accepts new torrent files and forwards them to RealDebrid, who then downloads them. When the download is finished RDT will download the file from RealDebrid and offer Sonarr/Radarr the result, who then process it further.

If you want to access it outside your network you will need to setup a reverse proxy or do port forwarding.
