### ISSUE TITLE
Torrent unable to be removed after being stuck processing

### ISSUE THREAD

**Issue by janitory** [rogerfar/rdt-client#91]
**What version are you using?**
2.0

**Wat OS are you running?**
Unraid

**Are you using Docker or as a service?**
Docker

**Please attach a log file here with the log setting set to debug**
https://pastebin.com/VKmZtbx7

Full log attached, however DBG mode was only set after 16:35 CET
[rdtclient_257.log](https://github.com/rogerfar/rdt-client/files/7597031/rdtclient_257.log)

Had a torrent that was stuck on processing. It was added by Sonarr (08:26 CET). Sometimes magnet-links don't start torrenting on RD. Uploading the .torrent file is a workaround, however this time the torrent was still stuck on processing. Trying to view the torrent in the rdt-client resulted in permanent loading. Removing the torrent on RD didn't help, neither has removing it through sonarr.

**Comment by janitory** [comment]
Wow... While writing this ticket, it finally got removed after being stuck for hours. However, there's still an underlying issue that can be looked at.

**Comment by rogerfar** [comment]
This is most likely due to the issue that was fixed in the latest version now.
