### ISSUE TITLE
Torrent waiting for file selection: Select files of a torrent automatically

### ISSUE THREAD

**Issue by HashaRock** [rogerfar/rdt-client#92]
Not completely sure if this is technically a feature request or just something I'm missing out on but when Sonarr is running with RDT and it feeds a magnet link to it, it requires files to be selected. I know this is a feature of RD where when you go to the downloads page you can choose what files it downloads (file directory with folders, subtitles, .txt files, etc). 

Is there any way to bypass this since it practically makes Sonarr useless unless you handpick every file yourself?

I think it might have something to do with this which shows up manually but still prompts for file selection on the RD website:
![image](https://user-images.githubusercontent.com/63619145/143473716-8af42094-5fca-4086-80d0-724fb42e5908.png)

**Comment by rogerfar** [comment]
I'm not sure what you mean exactly. If you use Radarr/Sonarr it won't ask anything but assume the default setting from the Settings page.

**Comment by HashaRock** [comment]
I mean that when a torrent is entered to the system, it does not automatically start downloading for some reason. That photo is an example. It basically asks what files I want to download from the torrent instead of automatically downloading the movie or file. 

![image](https://user-images.githubusercontent.com/63619145/143500467-ab84f1a1-80a6-40f8-86b3-d0b2ba6dac3f.png)

**Comment by rogerfar** [comment]
I see, can you set the logs to Debug and upload them?

**Comment by HashaRock** [comment]
I think this is RD issue since file selection is on RD's website. 

![image](https://user-images.githubusercontent.com/63619145/143500554-d6646b0d-8a83-4aaf-9048-f20c461c6583.png)

**Comment by HashaRock** [comment]
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/7605257/rdtclient.log)

There's the log! Hope that helps! Also tried with another torrent but same thing, definitely a RD API issue. 

![image](https://user-images.githubusercontent.com/63619145/143500899-e4becac2-5c5a-4bf1-86de-dc5816e6b2ec.png)

**Comment by rogerfar** [comment]
Please update to the latest version.

**Comment by HashaRock** [comment]
Will try once i'm home thanks!

**Comment by rogerfar** [comment]
I'm going to close this issue. If it's still a problem feel free to comment here again.

**Comment by drmikecrowe** [comment]
I'm suffering from this as well
