### ISSUE TITLE
Add exclusion so that subtitle files are downloaded

### ISSUE THREAD

**Issue by nihilist77** [rogerfar/rdt-client#93]
Hi,

Very nice tool! Appreciate the work done! I installed this in a Synology NAS and working flawlessly. There were some permission issues at first. But as the base image is from `linuxserver.io`, I could just provide `PUID`, `GID` and `UMASK_SET` and all the permission issues were gone.

Now on to a feature request. I think the idea behind "Minimum file size to download" is neat. But is it possible to add an exclusion to subtitle files? Sonarr or radarr have an option to import subtitle files if available. That helps when it comes to subtitles. These subtitles files are usually less than a MB. So these have a chance to get deleted due to the minimum file size setting. I tried to set the minimum file size to less than a MB, but that didn't work.

Below is a setting example from radarr.
<img width="682" alt="Screen Shot 2021-11-27 at 8 31 07 AM" src="https://user-images.githubusercontent.com/59402317/143689369-cf509231-57e0-4541-98e2-cc9954376971.png">

**Comment by rogerfar** [comment]
You can now use regex to exclude or include certain files. Have a look if that will work for you.
