### ISSUE TITLE
Externally added torrent - Category not allowed to be set

### ISSUE THREAD

**Issue by profucius** [rogerfar/rdt-client#94]
I opened the ticket previously requesting that RDT-client is able to detect externally added torrents. I do like this feature, as sometimes I add torrents from an external app (Wako) for Sonarr or Radarr to detect.

However, it seems that Sonarr and Radarr require a category to be set, but RDT-client does not set a category automatically on external torrents (understandable). I am requesting that RDT-client allows a category to be set.

When you click on a torrent in the dashboard, and see all of it's details (with the tabs General, Torrent Files, and Downloads). On the General tab, under Category it current states "(no category set)" I am requesting that, at the very least, this be a choice box or input box that allows for setting a category manually. Preferably however, there would be a default category that external torrents are automatically, assigned, and then if the user later decides to change the category, they can do so as stated above, so that Sonarr/Radarr will be able to detect and import.

Screenshot of Sonarr detecting the torrent in RDT-client, but cannot import due to lack of category:
![image](https://user-images.githubusercontent.com/18254607/143780250-c28e4221-e998-48a5-8e8b-07d9caf2930a.png)

**Comment by profucius** [comment]
Nevermind, I just ran a test by removing categories in the download client within sonarr, and it still produced the error. I think the issue is on the sonarr side. I'll close this ticket now.

**Comment by profucius** [comment]
If you have anything to add, like a setting to allow import regardless of the error above, please let me know.

**Comment by profucius** [comment]
Reopening, found this link stating that Sonarr is able to auto import external downloads, but they require a category to do so:

https://github.com/Sonarr/Sonarr/issues/2676#issuecomment-407115922

**Comment by rogerfar** [comment]
This should work in the latest versions now.
