### ISSUE TITLE
Please add premiumize support

### ISSUE THREAD

**Issue by nihilist77** [rogerfar/rdt-client#96]
Hi,

It would be really great to have premiumize support. And I can help if needed. I can code a bit with python and looked into how this can be implemented.

Initially it looked like updating and adding a file for premiumize in `rdt-client/server/RdtClient.Service/Services/TorrentClients/` will do. But after digging some more I found out you have written two backends for real-debrid and alldebrid. Which is pretty neat and the code quality is very high. But that's where I am kind of lost. I am not very familiar with `nuget` and it will take some time for me to figure out.

On the bright side, the features needed to implement using the premiumize [API](https://app.swaggerhub.com/apis-docs/premiumize.me/api) is already done in both of the backend nuget packages. So the implementation might be simpler than writing something from scratch.

From my side, I can help test the features if needed.

**Comment by airtonix** [comment]
Why? 

this is a real debrid client, not a premiumise client.

**Comment by nihilist77** [comment]
> this is a real debrid client, not a premiumise client.

Remind me, why does `rdt-client` support AllDebrid again?

**Comment by neilj1983** [comment]
You should take a look at - https://github.com/piejanssens/premiumizer

When I used it before the docker worked perfectly for me

**Comment by GOvEy1nw** [comment]
@rogerfar I second this, I'd gladly donate a years premiumize to you in return. I used Premiumizer before, but it's very buggy and way less responsive than rdt-client.

**Comment by rogerfar** [comment]
I have added support in 2.0.22. I found when you add a torrent and then download it, it will reduce your point balance: https://www.premiumize.me/fairuse

Not sure if that's normal when using it through the webbrowser or other tools.

I have done some initial testing, as their API's is the most limited, you can't select which files you want to download, and it will zip the files after the torrent is complete and download the complete zip. The zip is then extracted, but I haven't tested it with *arr to see if that is picked up correctly.

**Comment by nihilist77** [comment]
Thanks, appreciate it! 

Yes, the point system is normal. The points go down regardless of a browser or other method. They get reloaded every 24 hours so usually it's not a problem.

Also agreed about the API. I have set up a docker container with Premiumize. I tried 2 downloads. One failed after 3 retries. Another went fine all the way. Let me know if I can treat you with a coffee.

**Comment by GOvEy1nw** [comment]
@rogerfar this is fantastic thank you!

I'm not a coder, but I think that [Premiumizer](https://github.com/piejanssens/premiumizer) handled downloads well in regards to compatibility with the *arrs, so the code there may shed some light? [Premiumizearr](https://github.com/JackDallas/Premiumizearr) seems to handle it in a good way too.

Please let me know how I can get a years subscription to premiumize (or just the equivalent monetary wise!) over to you!

**Comment by GOvEy1nw** [comment]
@rogerfar also, what would be the recommended way to run 2x rdt-client containers at the same time? I tried by just setting a different local port for one (and different config setups/locations of course) which kind of works, but I was only able to log into one at a time (it'd log me out of container 1 when I logged into container 2 for example), which I think was causing other issues with grabbing files etc.

**Comment by rogerfar** [comment]
If you run them both on localhost for example, cookies will probably cross contaminate. 

Maybe setting up a reverse proxy so you have different subdomains?

What is the end goal here? You want to use multiple providers for different categories?

**Comment by GOvEy1nw** [comment]
I use Premiumizer, Real-Debrid & OffCloud interchangeably, because they each have a different set of pre-cached files and capabilities etc.

For example, Real-Debrid is my general go to for torrents as has a great cache of torrents already, but sometimes it comes across one that it says is 'invalid' or something, but I put that same torrent into Premiumizer and it's all good.

Premiumizer & OffCloud have Usenet support too, which comes in handy if the file I'm trying to get isn't available via torrent.

So an ideal (albeit might not be possible) solution would be to have multiple accounts linked to the same container, and set up with priority (RD = 1, Pr = 2, OC = 3, for example) and then if the file fails or isn't available via the first priority account, the app will send the same file to the second priority account etc.f

**Comment by berot3** [comment]
Just wondering. Are there any other debrid multihoster besides premiumize which also offer Usenet?

**Comment by GOvEy1nw** [comment]
> Just wondering. Are there any other debrid multihoster besides premiumize which also offer Usenet?
> 
> Just now I stumbled across high-way.me. Does anyone think there could be support for it too? I think having a bit of choice/variety would be awesome!
> 
> * I'd like to add one more reason for those 2 (or at least 1) to be added:
>   **_Seeding_**: I didn't collect all the facts yet, but premiumize seeds 3 days and highway even more. Real and All are probably seeding, but I don't think it's enough.
>   There is also debrid-link.fr which is torrent only, but also advertises as seedbox.

I use Offcloud, which also has Usenet support. Managed to grab a lifetime licence for that too. I'm sure there are plenty of others, but they're the 3 I use now, Real-Debrid, Premiumize, Offcloud.
