### ISSUE TITLE
Add setting to "fail" a torrent if it has no seeders, or takes X time to download

### ISSUE THREAD

**Issue by profucius** [rogerfar/rdt-client#97]
Sonarr & Radarr have settings built-in that if the torrent downloading reports "failed" that it will skip that torrent and automatically find another release to download.

![image](https://user-images.githubusercontent.com/18254607/144121906-de81058d-8001-4256-a72f-aa84621d992a.png)

Sometimes when searching for a torrent through Sonarr or Radarr using the built-in search, the indexer will show the torrent having seeders, but when added to RDT, will show as no seeders (or will be very slow to download). This can cause a download to stall out, and Sonarr/Radarr to not react within a reasonable amount of time for an alternative to be found.

![image](https://user-images.githubusercontent.com/18254607/144125282-74b76251-6323-4ea6-8dab-fc82c6c57505.png)

**I propose that RDT has some settings that will assist in this type of scenario:**

- Setting: If the torrent has less than or equal to X seeders after Y minutes, automatically report download as failed.
- Setting: If downloading speed is slower than X kbps after Y minutes, automatically report downloaded as failed.

These settings would give Sonarr and Radarr the ability to react to slow and impossible downloads quicker, so that they can automatically search for another torrent to download instead.

**Comment by nihilist77** [comment]
Sonarr and radarr already have options to pick torrents that have a preset number of seeders. You can find it within indexer settings. So rather than rdt failing, you can just not select that.

<img width="666" alt="Screen Shot 2021-11-30 at 5 05 43 PM" src="https://user-images.githubusercontent.com/59402317/144153045-5014bf3a-8ee1-42a6-8824-908a5b6525de.png">

As for the downloading speed, don't think the API provides that.

**Comment by profucius** [comment]
I'm aware of the setting for a preset number of seeders. The issue is that many times, an indexer will show plenty of seeders available on a torrent, but once it gets added to RDT it claims no seeders, and the speed is very slow. Not always, and it seems to be certain indexers that are bigger offenders. An RDT setting would handle this.

About the API, I'm not asking for anything that RDT doesn't already do. See my second screenshot, it shows how fast AllDebrid is downloading the torrent to its servers. Going to the AllDebrid website shows the same information.

**Comment by bastardsandcheats** [comment]
> Sonarr and radarr already have options to pick torrents that have a preset number of seeders. You can find it within indexer settings. So rather than rdt failing, you can just not select that.

Yes but because RD can cache torrents, the number of seeds can be irrelevant. You could have a torrent with 1 seeds, cached on RD that you miss if you set number of seeds higher. 

I think this feature would be useful, and as @profucius says, rdt already knows the speed.

**Comment by rogerfar** [comment]
For now I added a setting called `lifetime`, I experimented a little with older torrents but it's flaky. When it's busy it can take quite a bit of time for RealDebrid to actually start downloading the torrent, which could generate false positives.

Also seeder/leecher counts don't work when the torrent is cached looks like.
