### ISSUE TITLE
Unable to intall..

### ISSUE THREAD

**Issue by 3PCInc** [rogerfar/rdt-client#98]
**What version are you using?**
I am using the latest docker version on dockerhub.
**Wat OS are you running?**
Ubuntu.
**Are you using Docker or as a service?**
Docker.
**Please attach a log file here with the log setti
[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/7655946/_rdtclient_logs.txt)
ng set to debug**

My container does not want to start, I use the docker compose provided by the developer but it does not want to start and I get the logs that this attached. 

I specify that the container worked for several weeks and that it is during a reinstallation that the problem occurred. 
 I have emptied the directories containing the database. 
I checked that the permissions were correct.
Can you help me?

**Comment by rogerfar** [comment]
The logs state ` SQLite Error 10: 'disk I/O error'.`. You might want to just remove the whole container and re-instatiate it.
